INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(71, 'multiple_choice', 'We _____ appreciate your patience during this process.', '["are","do","have","really"]', 'do', 'do appreciate 強調確實感謝，反駁不耐煩的印象。'),
(71, 'multiple_choice', 'She _____ submit the report — I saw her send it myself.', '["does","did","was","has"]', 'did', 'did submit 強調她確實提交了（過去式強調）。'),
(71, 'multiple_choice', 'He _____ try his best, even if the results weren''t perfect.', '["is","has","would","does"]', 'does', 'does try 強調他確實努力了（三單現在式）。'),
(71, 'fill_blank', 'I _____ (emphatic) believe this is the right decision for the company.', NULL, 'do', 'do believe 強調肯定信念。'),
(71, 'multiple_choice', 'We _____ value our relationship with your company.', '["do","would","have","are"]', 'do', 'do value 強調確實重視關係。'),
(71, 'multiple_choice', 'They _____ complete their projects on time, contrary to what you might think.', '["have","were","do","are"]', 'do', 'do complete 反駁認為他們不能按時完成的看法。'),
(71, 'multiple_choice', 'She _____ work extremely hard — she just doesn''t show it.', '["is","has","does","would"]', 'does', 'does work 強調她確實努力（三單）。'),
(71, 'transform', 'We really care about quality. (Use emphatic do)', NULL, 'We do care about maintaining the highest quality standards.', 'do care 強調確實在乎。'),
(71, 'fill_blank', 'The team _____ (emphatic) meet their deadlines, despite the challenges.', NULL, 'does', 'does meet 強調三單事實。'),
(71, 'multiple_choice', 'He _____ send the invoice, but it may have gone to your spam folder.', '["did","was","had","has"]', 'did', 'did send 強調他確實寄了（過去式）。'),
(71, 'multiple_choice', 'We _____ understand the urgency of this matter.', '["are","do","have","would"]', 'do', 'do understand 強調理解的語氣。'),
(71, 'multiple_choice', 'I _____ apologize for any inconvenience this may have caused.', '["do","have","am","would"]', 'do', 'do apologize 強調真誠道歉。'),
(71, 'transform', 'She took all the necessary precautions. (Use emphatic did)', NULL, 'She did take all the necessary precautions before the launch.', 'did take 強調過去確實採取措施。'),
(71, 'fill_blank', 'They _____ (emphatic) try to resolve the issue before escalating.', NULL, 'did', 'did try 強調過去確實嘗試解決。'),
(71, 'multiple_choice', 'The results _____ show improvement compared to last quarter.', '["have","are","would","do"]', 'do', 'do show 強調結果確實顯示改善。'),
(71, 'multiple_choice', 'We _____ meet our obligations under the contract.', '["are","have","do","would"]', 'do', 'do meet 強調確實履行合約義務。'),
(71, 'multiple_choice', 'She _____ receive the email, but she was too busy to respond.', '["has","did","was","had"]', 'did', 'did receive 強調她確實收到了（過去式）。'),
(71, 'transform', 'The new policy has had a positive impact. (Use emphatic does)', NULL, 'The new policy does have a positive impact on employee morale.', 'does have 強調政策確實有效。'),
(71, 'fill_blank', 'I _____ (emphatic) think we should reconsider our approach.', NULL, 'do', 'do think 強調肯定意見。'),
(71, 'multiple_choice', 'He _____ handle pressure very well — that''s why he leads the team.', '["would","is","does","has"]', 'does', 'does handle 強調能力（三單）。'),
(72, 'multiple_choice', 'We recommend that the board _____ the proposal immediately.', '["approves","approved","approve","approving"]', 'approve', 'recommend that + 原形動詞（虛擬語氣）。'),
(72, 'multiple_choice', 'The committee insists that all documents _____ in English.', '["were submitted","be submitted","should submitted","are submitted"]', 'be submitted', 'insist that + 原形被動（be + p.p.）。'),
(72, 'multiple_choice', 'It is essential that every employee _____ the training.', '["attends","is attending","attend","attended"]', 'attend', 'It is essential that + 原形動詞。'),
(72, 'fill_blank', 'The director suggested that the team _____ (reconsider) its approach.', NULL, 'reconsider', 'suggest that + 原形動詞，虛擬語氣。'),
(72, 'multiple_choice', 'The policy requires that all contractors _____ background checks.', '["are undergoing","undergo","underwent","undergoes"]', 'undergo', 'require that + 原形動詞。'),
(72, 'multiple_choice', 'It is important that the report _____ before Friday.', '["should completed","was completed","is completed","be completed"]', 'be completed', 'It is important that + 原形（被動）。'),
(72, 'multiple_choice', 'She demands that the error _____ immediately.', '["is corrected","was corrected","be corrected","should corrected"]', 'be corrected', 'demand that + 原形（被動）。'),
(72, 'transform', 'The management says all staff must attend. (Use: requires that)', NULL, 'Management requires that all staff attend the mandatory briefing.', 'require that + 原形動詞。'),
(72, 'fill_blank', 'The legal team recommended that the contract _____ (revise) before signing.', NULL, 'be revised', 'recommend that + 原形被動，虛擬語氣。'),
(72, 'multiple_choice', 'It is vital that the team _____ aware of the new regulations.', '["was","should be","be","is"]', 'be', 'It is vital that + be（原形）。'),
(72, 'multiple_choice', 'The auditor suggested that the company _____ its accounting practices.', '["reviewed","review","reviews","should review"]', 'review', 'suggest that + 原形動詞。'),
(72, 'multiple_choice', 'We insist that the supplier _____ a replacement within 48 hours.', '["is providing","provide","provides","should provide"]', 'provide', 'insist that + 原形動詞。'),
(72, 'transform', 'It is necessary for all managers to complete the form. (Use subjunctive)', NULL, 'It is necessary that all managers complete the certification form.', 'It is necessary that + 原形動詞。'),
(72, 'fill_blank', 'The board proposed that a new committee _____ (form) to investigate the issue.', NULL, 'be formed', 'propose that + 原形（被動），虛擬語氣。'),
(72, 'multiple_choice', 'It is crucial that the strategy _____ before the board meeting.', '["was finalized","is finalized","be finalized","should finalize"]', 'be finalized', 'It is crucial that + 原形（被動）。'),
(72, 'multiple_choice', 'The manager recommended that she _____ leadership training.', '["undergo","undergoes","underwent","is undergoing"]', 'undergo', 'recommend that + 原形，虛擬語氣。'),
(72, 'multiple_choice', 'The protocol demands that all visitors _____ security badges.', '["should wear","wear","wears","wore"]', 'wear', 'demand that + 原形動詞。'),
(72, 'transform', 'We advise that all stakeholders attend. (Use: suggest that)', NULL, 'We suggest that all stakeholders attend the annual general meeting.', 'suggest that + 原形動詞。'),
(72, 'fill_blank', 'It is imperative that the deadline _____ (meet).', NULL, 'be met', 'be met 原形被動，虛擬語氣。'),
(72, 'multiple_choice', 'She proposed that the salary review _____ every year.', '["be conducted","should conducted","is conducted","was conducted"]', 'be conducted', 'propose that + 原形被動。'),
(73, 'multiple_choice', 'I wish I _____ more time to review the proposal.', '["had","have","will have","would have"]', 'had', 'wish + 過去式表對現在的願望。'),
(73, 'multiple_choice', 'She wishes she _____ taken that promotion years ago.', '["had","will have","have","would have"]', 'had', 'wish + 過去完成式表對過去的遺憾。'),
(73, 'multiple_choice', 'If only we _____ better market research before the launch.', '["do","would do","did","had done"]', 'had done', 'if only + 過去完成式表過去的遺憾，語氣更強。'),
(73, 'fill_blank', 'He wishes the client _____ (respond) faster to our emails.', NULL, 'would respond', 'wish + would + 原形表對他人行為的期望。'),
(73, 'multiple_choice', 'We wish we _____ the contract before the price increase.', '["had signed","signed","have signed","would sign"]', 'had signed', 'wish + 過去完成式表後悔沒有及早簽約。'),
(73, 'multiple_choice', 'If only she _____ more confident during the presentation.', '["had been","were","was","would be"]', 'were', 'if only + were（正式英語）表對現在的願望。'),
(73, 'multiple_choice', 'I wish our team _____ more efficiently.', '["has worked","worked","would work","works"]', 'worked', 'wish + 過去式表對現在的願望。'),
(73, 'transform', 'I regret that we did not hire more staff. (Use: If only)', NULL, 'If only we had hired more staff, we could have met the demand.', 'if only + 過去完成式表過去遺憾。'),
(73, 'fill_blank', 'He wishes the new system _____ (work) as well as the old one.', NULL, 'worked', 'wish + 過去式表對現在的願望。'),
(73, 'multiple_choice', 'If only I _____ about the deal before it fell through.', '["would know","have known","had known","knew"]', 'had known', 'if only + 過去完成式表遺憾。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(73, 'multiple_choice', 'She wishes she _____ have a better work-life balance.', '["can","would","should","could"]', 'could', 'wish + could 表希望能夠（可能性的願望）。'),
(73, 'multiple_choice', 'We wish the client _____ give us more detailed feedback.', '["should","would","could","will"]', 'would', 'wish + would 表期望他人行為改變。'),
(73, 'transform', 'We regret that we lost that account. (Use: We wish we hadn''t)', NULL, 'We wish we hadn''t lost that valuable account.', 'wish + 過去完成否定表遺憾。'),
(73, 'fill_blank', 'If only the budget _____ (be) larger, we could have achieved more.', NULL, 'had been', 'if only + 過去完成式表過去遺憾。'),
(73, 'multiple_choice', 'He wishes he _____ asked for more details before signing.', '["have","had","would have","will have"]', 'had', 'wish + 過去完成式表遺憾。'),
(73, 'multiple_choice', 'If only we _____ the opportunity sooner.', '["recognized","have recognized","would recognize","had recognized"]', 'had recognized', 'if only + 過去完成式。'),
(73, 'multiple_choice', 'She wishes her presentation _____ gone better.', '["had","have","would have","will have"]', 'had', 'wish + 過去完成式表遺憾。'),
(73, 'transform', 'I regret that I didn''t network more at the conference. (Use: I wish I had)', NULL, 'I wish I had networked more at the conference.', 'wish + 過去完成式表遺憾。'),
(73, 'fill_blank', 'If only the team _____ (follow) the original plan, we would be on track.', NULL, 'had followed', 'if only + 過去完成式表後悔。'),
(73, 'multiple_choice', 'We wish the supplier _____ more transparent about delivery times.', '["is","were","was","would be"]', 'were', 'wish + were（過去式）表對現在狀況的願望。'),
(74, 'multiple_choice', '_____ the contract carefully, she noticed a significant error.', '["Read","Having read","Reading","To read"]', 'Reading', 'Reading 現在分詞子句表示同時進行的動作。'),
(74, 'multiple_choice', '_____ in the industry for ten years, she has built an impressive network.', '["To work","Having worked","Worked","Working"]', 'Having worked', 'Having worked = 完成分詞子句，表在主句動作前已完成。'),
(74, 'multiple_choice', '_____ a cost-effective solution, the team adopted the new software.', '["Sought","Having sought","To seek","Seeking"]', 'Seeking', 'Seeking a solution 分詞子句表目的或同時進行。'),
(74, 'fill_blank', '_____ (walk) into the meeting room, he noticed the client looked concerned.', NULL, 'Walking', 'Walking into 現在分詞子句。'),
(74, 'multiple_choice', '_____ that the client was unsatisfied, the manager personally called.', '["Known","Knowing","Having known","To know"]', 'Knowing', 'Knowing that 現在分詞子句表示因為知道。'),
(74, 'multiple_choice', 'She sat at her desk, _____ through the annual report.', '["having flipped","flipped","to flip","flipping"]', 'flipping', 'flipping through 伴隨動作的現在分詞子句。'),
(74, 'multiple_choice', '_____ all stakeholders, the manager made a balanced decision.', '["Consulted","To consult","Consulting","Having consulted"]', 'Consulting', 'Consulting all stakeholders 分詞子句（因此/同時）。'),
(74, 'transform', 'Because she had reviewed all the data, she was confident in her recommendation. (Use -ing clause)', NULL, 'Having reviewed all the data, she was confident in her recommendation.', 'Having reviewed 完成分詞子句。'),
(74, 'fill_blank', '_____ (understand) the risks, the board approved the merger cautiously.', NULL, 'Understanding', 'Understanding the risks 現在分詞子句表因為了解風險。'),
(74, 'multiple_choice', 'He answered all the client''s questions, _____ his expertise.', '["to demonstrate","demonstrated","demonstrating","having demonstrated"]', 'demonstrating', 'demonstrating 伴隨動作的分詞子句。'),
(74, 'multiple_choice', '_____ a thorough analysis, the consultants recommended restructuring.', '["Having conducted","To conduct","Conducting","Conducted"]', 'Having conducted', 'Having conducted 表在主句動作前已完成分析。'),
(74, 'multiple_choice', 'The CEO gave the speech, _____ to the achievements of the entire team.', '["referring","having referred","referred","to refer"]', 'referring', 'referring to 分詞子句，伴隨動作。'),
(74, 'transform', 'Because she worked efficiently, she finished ahead of schedule. (Use -ing clause)', NULL, 'Working efficiently, she finished the project well ahead of schedule.', 'Working efficiently 現在分詞子句表原因。'),
(74, 'fill_blank', '_____ (not / realize) the severity, he underestimated the challenge.', NULL, 'Not realizing', 'Not realizing 否定分詞子句。'),
(74, 'multiple_choice', '_____ the proposal three times, she finally submitted it.', '["Revising","Having revised","Revised","To revise"]', 'Having revised', 'Having revised 表完成後提交。'),
(74, 'multiple_choice', 'She reported the issue, _____ full documentation to support her claims.', '["to provide","having provided","provided","providing"]', 'providing', 'providing 伴隨動作。'),
(74, 'multiple_choice', '_____ late, he missed the beginning of the presentation.', '["To arrive","Having arrived","Arriving","Arrived"]', 'Arriving', 'Arriving late 現在分詞子句（因為晚到）。'),
(74, 'transform', 'After she read the brief, she prepared detailed questions. (Use -ing clause)', NULL, 'Having read the brief, she prepared detailed and insightful questions.', 'Having read 完成分詞子句。'),
(74, 'fill_blank', '_____ (consider) all options, the team chose the most cost-effective approach.', NULL, 'Having considered', 'Having considered 完成分詞子句。'),
(74, 'multiple_choice', 'The director walked out, _____ nothing further to add.', '["saying","said","to say","having said"]', 'saying', 'saying 伴隨動作的分詞子句。'),
(75, 'multiple_choice', '_____ by the legal team, the contract was ready to sign.', '["Reviewing","Having reviewed","To review","Reviewed"]', 'Reviewed', 'Reviewed by 被動過去分詞子句，表完成審查後。'),
(75, 'multiple_choice', '_____ clearly, the instructions were easy to follow.', '["Having written","Written","To write","Writing"]', 'Written', 'Written clearly 被動過去分詞子句。'),
(75, 'multiple_choice', 'The report, _____ overnight, impressed everyone the next morning.', '["completing","having completed","completed","to complete"]', 'completed', 'completed overnight 被動分詞子句。'),
(75, 'fill_blank', '_____ (train) by industry experts, the staff are highly competent.', NULL, 'Trained', 'Trained by 被動過去分詞子句。'),
(75, 'multiple_choice', '_____ thoroughly, the proposal was approved without objection.', '["Having prepared","To prepare","Prepared","Preparing"]', 'Prepared', 'Prepared thoroughly 被動過去分詞子句。'),
(75, 'multiple_choice', 'The data, _____ three times, was finally accepted as accurate.', '["verifying","to verify","verified","having verified"]', 'verified', 'verified three times 被動分詞子句（非限定）。'),
(75, 'multiple_choice', '_____ in Seoul, the new branch quickly became profitable.', '["Establishing","Established","To establish","Having established"]', 'Established', 'Established in Seoul 被動過去分詞子句。'),
(75, 'transform', 'Because the design was approved, production could begin. (Use past participle clause)', NULL, 'Approved by the design committee, the product went into production.', 'Approved 被動過去分詞子句。'),
(75, 'fill_blank', '_____ (submit) on time, the report received positive feedback from the board.', NULL, 'Submitted', 'Submitted on time 被動分詞子句。'),
(75, 'multiple_choice', 'The proposal, _____ by senior leadership, was distributed to all managers.', '["to endorse","endorsed","endorsing","having endorsed"]', 'endorsed', 'endorsed by senior leadership 被動分詞修飾 proposal。'),
(75, 'multiple_choice', '_____ on the market for ten years, the brand is widely trusted.', '["To establish","Having established","Establishing","Established"]', 'Established', 'Established on the market 被動過去分詞子句。'),
(75, 'multiple_choice', 'Once _____, the product will be available in all major retail stores.', '["to launch","launched","having launched","launching"]', 'launched', 'Once launched 被動過去分詞子句。'),
(75, 'transform', 'After the issue was identified, the team worked on a solution. (Use past participle clause)', NULL, 'Identified early, the issue was resolved before it escalated.', 'Identified 被動過去分詞子句。'),
(75, 'fill_blank', '_____ (analyse) carefully, the results showed a clear trend.', NULL, 'Analysed', 'Analysed carefully 被動過去分詞子句。'),
(75, 'multiple_choice', 'If _____ correctly, this strategy should yield significant returns.', '["having implemented","implementing","implemented","to implement"]', 'implemented', 'If implemented correctly 條件被動分詞子句。'),
(75, 'multiple_choice', 'The system, _____ in 2020, is due for an upgrade.', '["having installed","installing","installed","to install"]', 'installed', 'installed in 2020 被動分詞修飾 system。'),
(75, 'multiple_choice', '_____ in three languages, the annual report reaches a global audience.', '["To publish","Published","Publishing","Having published"]', 'Published', 'Published in three languages 被動過去分詞子句。'),
(75, 'transform', 'Once we finalize the agreement, we will make an announcement. (Use past participle clause)', NULL, 'Once finalized, the agreement will be publicly announced.', 'Once finalized 被動過去分詞子句。'),
(75, 'fill_blank', '_____ (overwhelm) with requests, the support team needed more staff.', NULL, 'Overwhelmed', 'Overwhelmed 被動過去分詞子句，表被淹沒在請求中。'),
(75, 'multiple_choice', '_____ by the client, the revised proposal was immediately accepted.', '["Having requested","Requesting","Requested","To request"]', 'Requested', 'Requested by the client 被動過去分詞子句。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(76, 'multiple_choice', 'The employee _____ the project is very experienced.', '["managed","managing","who managing","to manage"]', 'managing', 'managing 現在分詞縮減關係子句（= who manages）。'),
(76, 'multiple_choice', 'The report _____ last week has been approved.', '["submitted","that submitted","to submit","submitting"]', 'submitted', 'submitted 過去分詞縮減被動關係子句（= that was submitted）。'),
(76, 'multiple_choice', 'The candidates _____ for the position all have relevant experience.', '["to apply","applied","who applying","applying"]', 'applying', 'applying 現在分詞縮減主動關係子句。'),
(76, 'fill_blank', 'The system _____ (install) last year needs an upgrade.', NULL, 'installed', 'installed 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'The clients _____ at the trade fair placed large orders.', '["contacting","contacted","who contacting","to contact"]', 'contacted', 'contacted 過去分詞縮減被動關係子句（= who were contacted）。'),
(76, 'multiple_choice', 'The team _____ the analysis made several key recommendations.', '["conducted","who conducting","to conduct","conducting"]', 'conducting', 'conducting 現在分詞縮減主動關係子句（= that is conducting）。'),
(76, 'multiple_choice', 'The software _____ by our IT team is highly efficient.', '["that developing","developed","developing","to develop"]', 'developed', 'developed 過去分詞縮減被動關係子句。'),
(76, 'transform', 'The employee who was selected for the promotion has ten years of experience. (Reduce)', NULL, 'The employee selected for the promotion has ten years of experience.', 'selected 過去分詞縮減被動關係子句。'),
(76, 'fill_blank', 'The proposal _____ (consider) by the board will be announced next week.', NULL, 'being considered', 'being considered 表正在進行中的被動分詞子句。'),
(76, 'multiple_choice', 'Any employee _____ in misconduct will face disciplinary action.', '["to engage","engaged","who engaging","engaging"]', 'engaging', 'engaging in 現在分詞縮減主動關係子句。'),
(76, 'multiple_choice', 'The documents _____ to all parties must be signed.', '["to send","sent","sending","that sending"]', 'sent', 'sent to all parties 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'The companies _____ to participate in the pilot program will be contacted.', '["to select","selected","selecting","that selecting"]', 'selected', 'selected 過去分詞縮減被動關係子句。'),
(76, 'transform', 'The manager who is leading the restructuring is highly experienced. (Reduce)', NULL, 'The manager leading the restructuring is highly experienced.', 'leading 現在分詞縮減主動關係子句。'),
(76, 'fill_blank', 'The data _____ (collect) over three years will be analysed this quarter.', NULL, 'collected', 'collected 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'All orders _____ before Friday will be processed by next week.', '["that placing","to place","placing","placed"]', 'placed', 'placed before Friday 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'The team _____ on the new platform faces some technical challenges.', '["worked","that working","working","to work"]', 'working', 'working on 現在分詞縮減主動關係子句。'),
(76, 'multiple_choice', 'The contract _____ by both parties takes effect immediately.', '["signing","signed","that signing","to sign"]', 'signed', 'signed by both parties 過去分詞縮減被動關係子句。'),
(76, 'transform', 'The client who complained about the delay was given a discount. (Reduce)', NULL, 'The client complaining about the delay was given a discount.', 'complaining 現在分詞縮減主動關係子句。'),
(76, 'fill_blank', 'The staff _____ (recruit) through the agency will start next month.', NULL, 'recruited', 'recruited 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'The strategy _____ last year has proven very effective.', '["adopting","that adopting","adopted","to adopt"]', 'adopted', 'adopted last year 過去分詞縮減被動關係子句。'),
(77, 'multiple_choice', 'Which is more formal?', '["Hey, want to know about your services?","I''m writing to ask about your services.","I am writing to enquire about your services.","Got questions about your services."]', 'I am writing to enquire about your services.', '完整形式、正式詞彙 enquire，更書面正式。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''buy''?', '["get","pick up","grab","purchase"]', 'purchase', 'purchase 比 buy 更正式。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''use''?', '["make use","use out","utilise","use up"]', 'utilise', 'utilise 是 use 的正式書面表達。'),
(77, 'fill_blank', 'Please _____ (tell) us if you require further assistance. (formal)', NULL, 'inform', 'inform 比 tell 更正式。'),
(77, 'multiple_choice', 'Which is more appropriate for a formal business letter?', '["Sorry, but you didn''t get the job.","We regret to inform you that your application has been unsuccessful.","We''re sad to say you failed.","Your application didn''t make it."]', 'We regret to inform you that your application has been unsuccessful.', '正式：regret to inform，完整形式，禮貌措辭。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''help''?', '["chip in","assist","lend a hand","pitch in"]', 'assist', 'assist 比 help 更正式。'),
(77, 'multiple_choice', 'Which is more formal?', '["Just give us a call anytime.","Feel free to contact us.","Please do not hesitate to contact us.","Ring us whenever."]', 'Please do not hesitate to contact us.', 'Please do not hesitate to 是正式商業英語的標準用語。'),
(77, 'transform', 'The meeting is going to start at 2 p.m. (Make more formal)', NULL, 'The meeting is scheduled to commence at 2:00 p.m.', 'is scheduled to commence 更正式；2:00 p.m. 更正式。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''end''?', '["finish up","stop","terminate","quit"]', 'terminate', 'terminate 比 end 更正式（尤指合約）。'),
(77, 'fill_blank', 'We would like to _____ (send) you a copy of our latest brochure. (formal)', NULL, 'forward', 'forward 比 send 更正式。'),
(77, 'multiple_choice', 'Which is NOT appropriate in a formal business email?', '["That sounds great! I''ll get back to you ASAP.","Please find attached the requested document.","We look forward to your response.","We would be delighted to proceed."]', 'That sounds great! I''ll get back to you ASAP.', '口語縮寫 ASAP 和感嘆號不適合正式商業郵件。'),
(77, 'multiple_choice', 'Which sentence uses formal register?', '["Just confirming I got your message.","We wish to confirm receipt of your correspondence.","Thanks for writing to us.","We got your email."]', 'We wish to confirm receipt of your correspondence.', '正式：confirm receipt of your correspondence，無縮寫，正式詞彙。'),
(77, 'transform', 'We want to know if you''re interested. (Make more formal)', NULL, 'We would like to know whether you would be interested in this proposal.', 'would like to + whether 更正式。'),
(77, 'fill_blank', 'I _____ (write) to follow up on our discussion last week. (formal)', NULL, 'am writing to', 'am writing to 正式信件開頭。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''start''?', '["get going","kick off","commence","start up"]', 'commence', 'commence 比 start 更正式。'),
(77, 'multiple_choice', 'Which sentence is most appropriate for a formal email closing?', '["Hope to hear from you.","We look forward to hearing from you at your earliest convenience.","Talk soon!","Get back to me when you can."]', 'We look forward to hearing from you at your earliest convenience.', '正式結尾語，完整表達，無縮寫。'),
(77, 'multiple_choice', 'Which is the formal way to say ''find out''?', '["look into","figure out","ascertain","dig up"]', 'ascertain', 'ascertain 是 find out 的正式書面表達。'),
(77, 'transform', 'Thanks for your help. (Make more formal)', NULL, 'We would like to express our sincere gratitude for your assistance.', 'express gratitude 正式感謝用語。'),
(77, 'fill_blank', 'We are _____ (look/for) suitable candidates for this position. (formal)', NULL, 'seeking', 'seeking 比 looking for 更正式。'),
(77, 'multiple_choice', 'Which is the formal way to say ''talk about''?', '["talk through","discuss","go over","chat about"]', 'discuss', 'discuss 比 talk about 更正式書面。'),
(78, 'multiple_choice', 'This _____ indicate that sales are beginning to recover.', '["certainly","may","always","definitely"]', 'may', 'may 表謹慎的可能性，是典型的模糊限制語。'),
(78, 'multiple_choice', 'It _____ that there has been a misunderstanding.', '["seems","proves","clearly is","is"]', 'seems', 'it seems that 表猜測/外交委婉。'),
(78, 'multiple_choice', 'The results _____ suggest that the strategy is working.', '["always","definitely","would appear to","certainly"]', 'would appear to', 'would appear to 是高度模糊限制語。'),
(78, 'fill_blank', 'Sales have _____ (possible) declined due to seasonal factors.', NULL, 'possibly', 'possibly 表猜測性副詞，模糊限制語。'),
(78, 'multiple_choice', 'This is _____ due to increased competition.', '["definitely","certainly","arguably","clearly"]', 'arguably', 'arguably 表可以爭論，軟化斷言。'),
(78, 'multiple_choice', 'There _____ be some resistance to the new policy.', '["must","might","shall","will"]', 'might', 'might 表猜測可能性，模糊限制語。'),
(78, 'multiple_choice', 'It _____ that costs will continue to rise.', '["is clear","is likely","is certain","is definite"]', 'is likely', 'is likely 表可能但不確定。'),
(78, 'transform', 'The data shows that profits will fall. (Soften with hedging)', NULL, 'The data suggests that profits may fall slightly next quarter.', 'suggests 和 may 模糊限制語。'),
(78, 'multiple_choice', 'The decline _____ be attributed to external factors.', '["can probably","always","definitely","certainly can"]', 'can probably', 'can probably 是模糊限制語組合。'),
(78, 'fill_blank', 'This _____ (tend) to indicate that there is room for improvement.', NULL, 'tends to', 'tends to indicate 是模糊限制語搭配。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(78, 'multiple_choice', 'It _____ fair to say that progress has been made.', '["would be","is definitely","is certainly","is clearly"]', 'would be', 'it would be fair to say 是典型模糊限制語。'),
(78, 'multiple_choice', 'The evidence _____ suggest a causal relationship.', '["does not","does not necessarily","never","cannot"]', 'does not necessarily', 'does not necessarily 是模糊限制的否定表達。'),
(78, 'multiple_choice', 'There is _____ a connection between the two events.', '["certainly","clearly","possibly","definitely"]', 'possibly', 'possibly 表謹慎猜測。'),
(78, 'transform', 'We are sure that the market will improve. (Add hedging)', NULL, 'We believe that the market may improve over the coming months.', 'believe that...may 模糊限制語。'),
(78, 'fill_blank', 'The report _____ (indicate) that further research is needed.', NULL, 'indicates / suggests', 'indicates 比 proves 更謹慎；suggests 更是模糊限制語。'),
(78, 'multiple_choice', 'This _____ be seen as a positive development.', '["could","shall","will","must"]', 'could', 'could be seen as 模糊限制語。'),
(78, 'multiple_choice', 'It _____ that some stakeholders may have concerns.', '["is certain","is conceivable","is definite","is obvious"]', 'is conceivable', 'it is conceivable that 是正式模糊限制語。'),
(78, 'transform', 'The new regulation will affect all businesses. (Soften with hedging)', NULL, 'The new regulation is likely to affect most businesses to some extent.', 'is likely to 和 to some extent 模糊限制語。'),
(78, 'fill_blank', 'This _____ (appear) to be a viable long-term solution.', NULL, 'appears', 'appears to be 是模糊限制語。'),
(78, 'multiple_choice', 'The figures _____ point to a slight improvement.', '["certainly","definitely","clearly","seem to"]', 'seem to', 'seem to 表謹慎推斷，模糊限制語。'),
(79, 'multiple_choice', 'Which sentence uses nominalization?', '["We''re putting off the launch.","We decided to postpone the launch.","We postponed it.","A decision was made to postpone the launch."]', 'A decision was made to postpone the launch.', 'A decision was made 將動詞 decide 名詞化。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''improve''?', '["improvement","improved","improving","to improve"]', 'improvement', 'improvement 是 improve 的名詞化形式。'),
(79, 'multiple_choice', 'Which sentence uses nominalization?', '["More people want it.","Demand has increased.","People are buying more.","An increase in demand has been observed."]', 'An increase in demand has been observed.', 'An increase in demand 名詞化 demand increased。'),
(79, 'fill_blank', 'Which noun is the nominalization of ''reduce''? → _____.', NULL, 'reduction', 'reduction 是 reduce 的名詞化。'),
(79, 'multiple_choice', 'We need to _____ our strategy. (Make it more formal using nominalization)', '["check","review","look at","conduct a review of"]', 'conduct a review of', 'conduct a review of 是 review 的名詞化形式，更正式。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''analyse''?', '["to analyse","analysing","analysis","analysed"]', 'analysis', 'analysis 是 analyse 的名詞化。'),
(79, 'multiple_choice', 'Which sentence uses nominalization?', '["We finished setting up the system.","We implemented the new system on schedule.","The new system was set up on time.","The implementation of the new system was completed on schedule."]', 'The implementation of the new system was completed on schedule.', 'The implementation 名詞化 implement。'),
(79, 'transform', 'We agreed to proceed with the merger. (Nominalize)', NULL, 'Agreement was reached to proceed with the merger.', 'agreement 是 agree 的名詞化。'),
(79, 'fill_blank', 'The _____ (discuss) of the proposal took two hours.', NULL, 'discussion', 'discussion 是 discuss 的名詞化。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''fail''?', '["to fail","failure","failed","failing"]', 'failure', 'failure 是 fail 的名詞化。'),
(79, 'multiple_choice', 'Which sentence is more formal through nominalization?', '["We''ve grown a lot.","Significant growth has been achieved.","Growth happened significantly.","We grew significantly."]', 'Significant growth has been achieved.', 'significant growth has been achieved 名詞化 grew。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''solve''?', '["solved","solving","to solve","solution"]', 'solution', 'solution 是 solve 的名詞化。'),
(79, 'fill_blank', 'The _____ (acquire) of the company was completed last year.', NULL, 'acquisition', 'acquisition 是 acquire 的名詞化。'),
(79, 'multiple_choice', 'Which sentence uses nominalization correctly?', '["We were negotiating for three weeks.","Negotiating took three weeks.","The negotiation of terms took three weeks.","We negotiated terms for three weeks."]', 'The negotiation of terms took three weeks.', 'The negotiation of terms 名詞化 negotiated。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''decide''?', '["to decide","decision","deciding","decided"]', 'decision', 'decision 是 decide 的名詞化。'),
(79, 'transform', 'We evaluated the risks carefully. (Nominalize)', NULL, 'A thorough evaluation of the risks was conducted.', 'evaluation 是 evaluate 的名詞化。'),
(79, 'fill_blank', 'We conducted a _____ (investigate) into the issue.', NULL, 'investigation', 'investigation 是 investigate 的名詞化。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''recommend''?', '["recommended","recommending","to recommend","recommendation"]', 'recommendation', 'recommendation 是 recommend 的名詞化。'),
(79, 'multiple_choice', 'Which sentence demonstrates nominalization?', '["We expanded successfully into Asia.","We went into Asia successfully.","The expansion of our operations into Asia has been successful.","Expanding into Asia worked out."]', 'The expansion of our operations into Asia has been successful.', 'The expansion of our operations 名詞化 expanded。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''approve''?', '["approving","approval","to approve","approved"]', 'approval', 'approval 是 approve 的名詞化。'),
(80, 'multiple_choice', 'Which is the more formal, impersonal version?', '["I''ve decided to postpone it.","We decided to postpone the launch.","It has been decided to postpone the launch.","Let''s postpone the launch."]', 'It has been decided to postpone the launch.', 'It has been decided 非人稱被動式，最正式。'),
(80, 'multiple_choice', 'Which sentence uses impersonal structure?', '["Note that the results are preliminary.","It is important to note that the results are preliminary.","You should note the preliminary results.","I want you to note the preliminary results."]', 'It is important to note that the results are preliminary.', 'It is important to note that 非人稱結構。'),
(80, 'multiple_choice', 'Which is the most formal way to start a recommendation?', '["You should implement these measures.","Implement these measures.","It is recommended that the following measures be implemented.","We recommend implementing these measures."]', 'It is recommended that the following measures be implemented.', 'It is recommended that + 虛擬語氣，非人稱被動，最正式。'),
(80, 'fill_blank', 'It _____ (note) that the data has certain limitations.', NULL, 'should be noted', 'it should be noted that 非人稱被動式。'),
(80, 'multiple_choice', 'Which uses passive voice appropriately?', '["We rejected the proposal.","They rejected the proposal because of budget.","The proposal was rejected due to budget constraints.","Budget constraints made us reject it."]', 'The proposal was rejected due to budget constraints.', 'The proposal was rejected 被動語態，不強調行為者。'),
(80, 'multiple_choice', 'Which is the most formal impersonal structure?', '["It would appear that further investigation is required.","Apparently, we need to investigate more.","It seems we need to look into this more.","We think further investigation is needed."]', 'It would appear that further investigation is required.', 'It would appear that 最高度正式非人稱結構。'),
(80, 'multiple_choice', 'Which sentence demonstrates formal passive writing?', '["We got the board to review the findings.","The findings have been reviewed and approved by the board.","The board reviewed and approved the findings.","The board has reviewed and approved everything."]', 'The findings have been reviewed and approved by the board.', 'The findings have been reviewed...被動語態，無人稱強調。'),
(80, 'transform', 'We will announce the results at the AGM. (Make impersonal/passive)', NULL, 'It has been decided that the results will be announced at the AGM.', '被動+非人稱結構。'),
(80, 'fill_blank', 'It _____ (establish) that the new policy will take effect in Q2.', NULL, 'has been established', 'it has been established that 非人稱被動式。'),
(80, 'multiple_choice', 'Which is the most appropriate sentence for a formal report conclusion?', '["Obviously the strategy worked.","The strategy was effective, we think.","It can therefore be concluded that the strategy has been effective.","So we can say the strategy worked."]', 'It can therefore be concluded that the strategy has been effective.', 'It can be concluded that 正式非人稱被動推論。'),
(80, 'multiple_choice', 'Which impersonal structure is correct?', '["It is believed that the market will recover by year end.","People believe the market will recover.","We believe the market will recover.","I believe the market will recover."]', 'It is believed that the market will recover by year end.', 'It is believed that 非人稱被動，報告中常用。'),
(80, 'multiple_choice', 'Which is the most formal?', '["We are taking steps to address the issue.","We''re working on fixing the issue.","Steps are being taken to address the issue.","We''re on it."]', 'Steps are being taken to address the issue.', 'Steps are being taken 被動進行式，非人稱。'),
(80, 'transform', 'We need to ensure all employees understand the policy. (Make formal/impersonal)', NULL, 'It is essential that all employees are made aware of the new policy.', 'It is essential that + 被動，非人稱。'),
(80, 'fill_blank', 'It _____ (report) that the merger negotiations are ongoing.', NULL, 'has been reported', 'it has been reported that 非人稱被動式。'),
(80, 'multiple_choice', 'Which is the most appropriate for a formal notice?', '["All staff must attend the briefing.","You all have to attend.","All staff are required to attend the mandatory briefing.","Everyone needs to come to the briefing."]', 'All staff are required to attend the mandatory briefing.', 'All staff are required to 被動非人稱，最正式。'),
(80, 'multiple_choice', 'Which is a correct impersonal structure?', '["Note that sales improved.","We should note that sales improved.","Don''t forget sales improved.","It is worth noting that sales have improved significantly."]', 'It is worth noting that sales have improved significantly.', 'It is worth noting that 非人稱結構。'),
(80, 'multiple_choice', 'Which sentence best exemplifies formal passive in reports?', '["We spent six months collecting data.","Data collection took six months.","The data was collected over a period of six months.","We collected data for six months."]', 'The data was collected over a period of six months.', 'The data was collected 標準學術/報告被動式。'),
(80, 'transform', 'We have identified several key issues. (Make formal/impersonal)', NULL, 'Several key issues have been identified in the course of this review.', 'Several key issues have been identified 非人稱被動式。'),
(80, 'fill_blank', 'It is _____ (expect) that the new system will reduce errors by 30%.', NULL, 'expected', 'it is expected that 非人稱被動預測。'),
(80, 'multiple_choice', 'Which is the most formal way to express an obligation?', '["It is mandatory that all contractors comply with safety regulations.","Make sure all contractors follow safety rules.","All contractors must comply with safety regulations.","Every contractor needs to follow safety rules."]', 'It is mandatory that all contractors comply with safety regulations.', 'It is mandatory that + 虛擬語氣，非人稱被動，最正式。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(81, 'multiple_choice', 'Which sentence correctly uses a colon?', '["The proposal covers three areas, budget: timeline and resources.","The proposal covers three areas: budget, timeline, and resources.","The proposal covers three areas; budget, timeline, and resources.","The proposal covers: three areas budget timeline resources."]', 'The proposal covers three areas: budget, timeline, and resources.', '冒號引出列表正確用法。'),
(81, 'multiple_choice', 'Which sentence correctly uses a semicolon?', '["The project is behind schedule: we need more resources.","The project is behind schedule; we need to allocate more resources.","The project is behind schedule, we need more resources.","The project is behind schedule but we need more resources."]', 'The project is behind schedule; we need to allocate more resources.', '分號連接兩個獨立但相關的子句。'),
(81, 'fill_blank', 'The meeting covered the following topics_____ budget allocation, staffing, and the Q4 strategy.', NULL, '：（colon）', '冒號引出列表。'),
(81, 'multiple_choice', 'Which correctly uses a colon?', '["Please bring the following, documents: your passport CV and references.","Please bring the following documents; your passport, CV, and references.","Please bring: the following documents your passport CV and references.","Please bring the following documents: your passport, CV, and references."]', 'Please bring the following documents: your passport, CV, and references.', '冒號引出列表。'),
(81, 'multiple_choice', 'Which correctly uses a semicolon?', '["Sales increased in Asia, however they declined in Europe.","Sales increased in Asia: however, they declined in Europe.","Sales increased in Asia; however, they declined in Europe.","Sales increased in Asia - however they declined in Europe."]', 'Sales increased in Asia; however, they declined in Europe.', '分號 + 連接副詞 however 正確用法。'),
(81, 'multiple_choice', 'Where should a colon go in this sentence? ''We offer three payment options _____ monthly, quarterly, or annually.''', '["，",":","；","—"]', ':', '冒號引出選項列表。'),
(81, 'fill_blank', 'She has one goal_____ to become the regional director within five years.', NULL, '：（colon）', '冒號強調唯一目標。'),
(81, 'multiple_choice', 'Which is correct?', '["The budget was approved consequently the project began.","The budget was approved: consequently the project began.","The budget was approved; consequently, the project began.","The budget was approved, consequently the project began."]', 'The budget was approved; consequently, the project began.', '分號 + 連接副詞 consequently 正確。'),
(81, 'multiple_choice', 'Which sentence uses a semicolon correctly?', '["The report is comprehensive, it covers all KPIs.","The report is comprehensive; it covers all key performance indicators.","The report is comprehensive: it covers all KPIs.","The report is comprehensive. It covers all KPIs."]', 'The report is comprehensive; it covers all key performance indicators.', '分號連接兩個緊密相關的獨立子句。'),
(81, 'transform', 'The company has three priorities. These are: growth, innovation, and sustainability. (Combine using colon)', NULL, 'The company has three priorities: growth, innovation, and sustainability.', '冒號合併為一個句子列舉。'),
(81, 'multiple_choice', 'Which correctly uses a colon?', '["The conclusion: is clear we must cut costs immediately.","The conclusion is clear, we must cut costs immediately.","The conclusion is clear; we must cut costs immediately.","The conclusion is clear: we must cut costs immediately."]', 'The conclusion is clear: we must cut costs immediately.', '冒號強調後面的重要陳述。'),
(81, 'fill_blank', 'We have identified two issues_____ the timeline is too tight, and the budget is insufficient.', NULL, '：（colon）', '冒號引出後面的說明。'),
(81, 'multiple_choice', 'Which sentence uses punctuation correctly?', '["She is qualified; she has an MBA and ten years of experience.","She is qualified - she has an MBA and ten years of experience.","She is qualified, she has an MBA and ten years of experience.","She is qualified: she has an MBA and ten years of experience."]', 'She is qualified; she has an MBA and ten years of experience.', '分號連接兩個獨立子句正確（冒號也可，但分號表更對等關係）。'),
(81, 'multiple_choice', 'Choose the correctly punctuated sentence:', '["There are four steps, research plan execute and review.","There are four steps; research, plan, execute, and review.","There are four, steps: research plan execute and review.","There are four steps: research, plan, execute, and review."]', 'There are four steps: research, plan, execute, and review.', '冒號引出四個步驟的列表。'),
(81, 'transform', 'Sales are falling. Furthermore, costs are rising. (Join with semicolon)', NULL, 'Sales are falling; furthermore, costs are rising.', '分號 + 連接副詞 furthermore。'),
(81, 'fill_blank', 'The agenda includes the following items_____ Q3 review, budget proposal, and staffing update.', NULL, '：（colon）', '冒號引出會議議程列表。'),
(81, 'multiple_choice', 'Which is correct?', '["The deadline is Friday. Please ensure all reports are submitted.","The deadline is Friday: please ensure all reports are submitted.","The deadline is Friday; please ensure all reports are submitted.","The deadline is Friday, please ensure all reports are submitted."]', 'The deadline is Friday; please ensure all reports are submitted.', '分號連接兩個緊密相關子句，命令強調。'),
(81, 'multiple_choice', 'Choose the correct sentence:', '["The audit revealed one major concern, insufficient documentation.","The audit revealed: one major concern insufficient documentation.","The audit revealed one major concern; insufficient documentation.","The audit revealed one major concern: insufficient documentation."]', 'The audit revealed one major concern: insufficient documentation.', '冒號強調唯一的重大問題。'),
(81, 'fill_blank', 'We have three options_____ negotiate, compromise, or walk away.', NULL, '：（colon）', '冒號引出選項。'),
(81, 'multiple_choice', 'Which correctly uses a semicolon?', '["He is an expert in finance, she specializes in operations.","He is an expert in finance: she specializes in operations.","He is an expert in finance; she specializes in operations.","He is an expert in finance. she specializes in operations."]', 'He is an expert in finance; she specializes in operations.', '分號連接對比的兩個獨立子句。'),
(82, 'multiple_choice', 'Which is correct?', '["The companies'' annual report was released today.","The companies annual report was released today.","The company''s annual report was released today.","The companys'' annual report was released today."]', 'The company''s annual report was released today.', 'company''s 單數所有格。'),
(82, 'multiple_choice', 'Which is correct?', '["It is''s important to review the contract carefully.","Its important to review the contract carefully.","It''s important to review the contract carefully.","Its'' important to review the contract carefully."]', 'It''s important to review the contract carefully.', 'It''s = it is，縮寫用撇號。'),
(82, 'multiple_choice', 'Which is correct?', '["The managers report''s are due on Friday.","The manager''s reports are due on Friday.","The managers'' reports are due on Friday.","The managers reports are due on Friday."]', 'The managers'' reports are due on Friday.', 'managers'' 複數所有格（多個管理者的報告）。'),
(82, 'fill_blank', 'The product has its _____ (own) unique features. (its or it''s?)', NULL, 'its', '其 own = its，所有格，不加撇號。'),
(82, 'multiple_choice', 'Which is correct?', '["The teams'' performance exceeded all expectations.","The teams performance exceeded all expectations.","The team''s performance exceeded all expectations.","The team''s performance exceeded all expectations."]', 'The team''s performance exceeded all expectations.', 'team''s 單數所有格正確。'),
(82, 'multiple_choice', 'Which sentence uses the apostrophe correctly?', '["Were pleased to announce the launch of our new product.","We are''s pleased to announce our new product.","We''re pleased to announce the launch of our new product.","Were'' pleased to announce the launch."]', 'We''re pleased to announce the launch of our new product.', 'We''re = we are，縮寫正確。'),
(82, 'multiple_choice', 'Which is correct?', '["The CEOs'' decision was final.","The CEOs decision was final.","The CEO''s decision was final.","The CEO''s decision was final."]', 'The CEO''s decision was final.', 'CEO''s 單數所有格正確。'),
(82, 'fill_blank', 'The company revised _____ pricing strategy. (its or it''s?)', NULL, 'its', 'its 所有格，不加撇號。'),
(82, 'multiple_choice', 'Which is correct for multiple employees?', '["The employees contract''s were all renewed.","The employees contracts were all renewed.","The employees'' contracts were all renewed.","The employee''s contracts were all renewed."]', 'The employees'' contracts were all renewed.', 'employees'' 複數所有格。'),
(82, 'multiple_choice', 'Which is correct?', '["They''s already submitted their proposals.","Their''ve already submitted their proposals.","They''ve already submitted their proposals.","They have''s already submitted their proposals."]', 'They''ve already submitted their proposals.', 'They''ve = they have，縮寫正確。'),
(82, 'multiple_choice', 'Which sentence is correct?', '["The shareholder''s meeting is scheduled for next Tuesday.","The shareholders'' meeting is scheduled for next Tuesday.","The shareholder''s'' meeting is scheduled for next Tuesday.","The shareholders meeting is scheduled for next Tuesday."]', 'The shareholders'' meeting is scheduled for next Tuesday.', 'shareholders'' 複數所有格（多個股東的會議）。'),
(82, 'fill_blank', '_____ (It is) been three months since the merger was announced.', NULL, 'It''s', 'It''s = it has，縮寫用撇號。'),
(82, 'multiple_choice', 'Which is correct?', '["The two companies''s merger was announced yesterday.","The two company''s merger was announced yesterday.","The two companies'' merger was announced yesterday.","The two companies merger was announced yesterday."]', 'The two companies'' merger was announced yesterday.', 'companies'' 複數所有格。'),
(82, 'multiple_choice', 'Which is correct?', '["He responsible for client relations.","His responsible for client relations.","He''s responsible for client relations.","He is''s responsible for client relations."]', 'He''s responsible for client relations.', 'He''s = he is，縮寫正確。'),
(82, 'multiple_choice', 'Which apostrophe usage is correct?', '["The department''s budget was increased.","The departments budget was increased.","The department''s budget was increased.","The departments'' budget was increased."]', 'The department''s budget was increased.', 'department''s 單數所有格。'),
(82, 'transform', 'The office of the director is on the 10th floor. (Use possessive apostrophe)', NULL, 'The director''s office is on the 10th floor.', 'director''s 單數所有格代替 of 結構。'),
(82, 'fill_blank', 'The company _____ known for its innovative products. (it''s or its)', NULL, 'It''s', 'It''s = it is，作謂語動詞。'),
(82, 'multiple_choice', 'Which is correct?', '["Don''t share the clients'' personal data.","Do not share the clients personal data.","Don''t share the client''s personal data.","Dont share the client''s personal data."]', 'Don''t share the client''s personal data.', 'Don''t 縮寫；client''s 單數所有格正確。'),
(82, 'multiple_choice', 'Which is correct for a company owned by multiple owners?', '["The directors decision was unanimous.","The director''s decision was unanimous.","The directors'' decision was unanimous.","The directors''s decision was unanimous."]', 'The directors'' decision was unanimous.', 'directors'' 複數所有格正確。'),
(82, 'multiple_choice', 'Which sentence has NO apostrophe error?', '["We''ve received confirmation from all our supplier''s.","Weve received confirmation from all our suppliers.","We have''s received confirmation from all our suppliers.","We''ve received confirmation from all our suppliers."]', 'We''ve received confirmation from all our suppliers.', 'We''ve 縮寫正確；suppliers 複數名詞，不需要撇號。'),
(83, 'multiple_choice', 'The new software will greatly _____ our workflow efficiency.', '["extend","enhance","enlarge","expand"]', 'enhance', 'enhance 提升（品質/效率），最適合 workflow efficiency 的搭配。'),
(83, 'multiple_choice', 'All employees are required to _____ with the new data protection regulations.', '["follow","obey","agree","comply"]', 'comply', 'comply with regulations 固定搭配，表遵守法規。'),
(83, 'multiple_choice', 'The company plans to _____ its operations to Southeast Asia next year.', '["increase","develop","expand","enhance"]', 'expand', 'expand operations 擴大業務規模，固定搭配。'),
(83, 'fill_blank', 'The director will _____ the team through the restructuring process.', NULL, 'guide / lead', 'guide/lead someone through a process 指引通過。'),
(83, 'multiple_choice', 'The quarterly results _____ a significant improvement in profit margins.', '["reveal out","demonstrate","indicate to","show up"]', 'demonstrate', 'demonstrate 正式表達，展示結果；demonstrate a improvement 正確搭配。'),
(83, 'multiple_choice', 'We need to _____ additional funding to complete the project.', '["get","earn","find","secure"]', 'secure', 'secure funding 取得資金，商業英語固定搭配。'),
(83, 'multiple_choice', 'The board has _____ the new marketing strategy.', '["accepted","confirmed","endorsed","agreed"]', 'endorsed', 'endorse 正式核可/背書，比 agree 更強烈。'),
(83, 'fill_blank', 'The company _____ a significant market share within its first year.', NULL, 'captured / gained', 'capture/gain market share 取得市場份額。'),
(83, 'multiple_choice', 'Please _____ receipt of this document by signing the enclosed form.', '["verify","acknowledge","confirm","accept"]', 'acknowledge', 'acknowledge receipt of 確認收到，正式書面搭配。'),
(83, 'multiple_choice', 'The new policy will _____ in effect from the first of next month.', '["make","come","go","take"]', 'come', 'come into effect 生效，固定搭配。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(83, 'multiple_choice', 'She was _____ as the most innovative employee of the year.', '["appreciated","rewarded","recognized","known"]', 'recognized', 'recognized as 被認可為，正式表彰搭配。'),
(83, 'fill_blank', 'The merger was _____ by the relevant regulatory authorities.', NULL, 'approved / sanctioned', 'approve/sanction the merger 批准合併。'),
(83, 'multiple_choice', 'The team needs to _____ a solution before the client meeting tomorrow.', '["devise","develop up","find out","think"]', 'devise', 'devise a solution 設計/制定解決方案，正式搭配。'),
(83, 'multiple_choice', 'Our products are _____ to customers in over 50 countries.', '["available","obtainable","possible","accessible"]', 'available', 'available to customers 對客戶可取得，常用搭配。'),
(83, 'multiple_choice', 'The company has _____ significant progress in reducing its carbon footprint.', '["achieved","done","accomplished","made"]', 'made', 'make progress 固定搭配。'),
(83, 'fill_blank', 'She _____ an important role in the company''s expansion into Asia.', NULL, 'played', 'play a role 扮演角色，固定搭配。'),
(83, 'multiple_choice', 'The new branch will be _____ in the financial district.', '["situated","placed","positioned","located"]', 'located', 'located in 位於，商業英語常見。'),
(83, 'multiple_choice', 'The proposal was _____ on several grounds, including cost and timing.', '["refused","denied","rejected","declined"]', 'rejected', 'rejected on grounds 以...為由被拒絕。'),
(83, 'fill_blank', 'The CEO _____ a speech about the company''s vision at the annual meeting.', NULL, 'delivered / gave', 'deliver/give a speech 發表演講。'),
(83, 'multiple_choice', 'All team members are expected to _____ their best effort in this project.', '["offer","provide","give","contribute"]', 'contribute', 'contribute one''s best effort 貢獻最大努力，正式商業表達。'),
(84, 'multiple_choice', 'The committee _____ a final decision until all the data has been reviewed.', '["has not made","does not make","will not make","did not make"]', 'will not make', 'will not make...until 表未來的條件：直到資料審查完才做決定。'),
(84, 'multiple_choice', 'Please ensure the report is submitted _____ Friday at the latest.', '["until","before","on","by"]', 'by', 'by Friday 截止日期用 by（at the latest 確認是截止）。'),
(84, 'multiple_choice', 'All staff who _____ the meeting will receive the minutes by email.', '["will not attend","are not attending","have not attended","do not attend"]', 'do not attend', 'do not attend 泛指所有不出席者（零條件句式）。'),
(84, 'fill_blank', 'The software _____ (install) on all company computers by the end of the week.', NULL, 'will have been installed', '未來完成被動式。'),
(84, 'multiple_choice', 'Neither the CEO nor the directors _____ available for comment.', '["has been","is","was","were"]', 'were', 'neither...nor 就近原則，directors 複數，were。'),
(84, 'multiple_choice', 'The proposal, _____ was submitted last week, has been approved.', '["what","who","which","that"]', 'which', '非限定性關係子句（逗號隔開），用 which。'),
(84, 'multiple_choice', 'She has been working for the company _____ she graduated.', '["as","from","for","since"]', 'since', 'since + 時間點，現在完成進行式。'),
(84, 'fill_blank', 'The meeting _____ (reschedule) to 3 p.m. due to a scheduling conflict.', NULL, 'has been rescheduled', '現在完成被動式，說明已完成的重新安排。'),
(84, 'multiple_choice', 'He was promoted _____ his outstanding performance.', '["because of","even though","although","despite"]', 'because of', 'because of + 名詞短語表原因。'),
(84, 'multiple_choice', 'The report must _____ before the board meeting begins.', '["be to review","review","be reviewed","be reviewing"]', 'be reviewed', 'must be reviewed 情態動詞被動式。'),
(84, 'multiple_choice', 'Applicants _____ relevant experience are encouraged to apply.', '["having","with","of","who have"]', 'with', 'with relevant experience 介系詞短語修飾 applicants（也可用 having 或 who have）。'),
(84, 'fill_blank', 'By the time the new branch opens, we _____ (expand) into five new markets.', NULL, 'will have expanded', 'by the time 未來完成式。'),
(84, 'multiple_choice', 'The results were _____ better than anticipated.', '["considerably","considering","considerable","considerate"]', 'considerably', 'considerably 副詞修飾 better（比較級）。'),
(84, 'multiple_choice', '_____ the price increase, demand remains strong.', '["Because of","Even though","Despite","Although"]', 'Despite', 'Despite + 名詞短語（price increase），讓步。'),
(84, 'multiple_choice', 'She is the _____ experienced candidate for this position.', '["most","very","much","more"]', 'most', 'the most + 形容詞最高級。'),
(84, 'transform', 'Active: The HR team reviewed all applications. (Passive)', NULL, 'All applications were reviewed by the HR team.', 'were reviewed by 被動語態。'),
(84, 'fill_blank', 'The client _____ (not / respond) to our emails for two weeks.', NULL, 'has not responded', '現在完成式否定，for two weeks 持續。'),
(84, 'multiple_choice', 'We recommend that all participants _____ the pre-reading materials.', '["are reviewing","reviewed","review","reviews"]', 'review', 'recommend that + 原形動詞（虛擬語氣）。'),
(84, 'multiple_choice', 'The survey results indicate _____ customer satisfaction has improved.', '["that","how","which","what"]', 'that', 'indicate + that 名詞子句受語。'),
(84, 'multiple_choice', 'All shipments _____ before they are dispatched.', '["must be inspected","are must inspected","must have inspected","must inspect"]', 'must be inspected', 'must be inspected 情態動詞被動。'),
(85, 'multiple_choice', 'Thank you for your email of March 15th. We are _____ to inform you that...', '["happy","delighted","glad","pleased"]', 'pleased', 'pleased 最常見的正式商業郵件開頭表達（delighted 也正式但 pleased 更標準）。'),
(85, 'multiple_choice', 'We _____ your order and it will be dispatched within two working days.', '["will receive","have received","received","are receiving"]', 'have received', 'have received 現在完成式，說明已收到訂單。'),
(85, 'multiple_choice', 'Should you have any questions, please do not _____ to contact us.', '["hesitate","try","want","wait"]', 'hesitate', 'do not hesitate to contact us 正式商業套語。'),
(85, 'fill_blank', 'We are writing to _____ you that your application has been successful.', NULL, 'inform', 'inform someone that 正式商業通知。'),
(85, 'multiple_choice', 'Further to our conversation _____ Friday, I am sending you the revised proposal.', '["in","by","on","at"]', 'on', 'on Friday 特定日期用 on。'),
(85, 'multiple_choice', 'Please find _____ the document you requested.', '["attached","inside","below","enclosed"]', 'attached', 'Please find attached 電子郵件附件的標準用語。'),
(85, 'multiple_choice', 'We would like to take this _____ to thank you for your continued support.', '["chance","opportunity","time","occasion"]', 'opportunity', 'take this opportunity to 正式感謝套語。'),
(85, 'transform', 'Write the standard phrase to open an email politely enquiring about an order status.', NULL, 'I am writing to enquire about the current status of our order placed on March 10th.', 'enquire about 正式詢問。'),
(85, 'fill_blank', 'I am _____ to confirm that the meeting has been rescheduled to 10 a.m.', NULL, 'writing', 'I am writing to confirm 正式郵件開頭。'),
(85, 'multiple_choice', 'We _____ any inconvenience this may have caused.', '["apologise for","apologise of","are sorry to","apologise about"]', 'apologise for', 'apologise for 正式道歉，固定搭配。'),
(85, 'multiple_choice', 'Please _____ receipt of this email by clicking the confirmation link below.', '["acknowledge","confirm","accept","verify"]', 'acknowledge', 'acknowledge receipt 確認收到，正式書面用語。'),
(85, 'multiple_choice', 'We are _____ to announce the appointment of Ms. Chen as our new CFO.', '["happy","pleased","glad","delighted"]', 'delighted', 'delighted to announce 正式公告用語，最正式。'),
(85, 'fill_blank', 'If you _____ any further queries, please do not hesitate to get in touch.', NULL, 'have / should have', 'If you have / should you have 正式條件句。'),
(85, 'multiple_choice', 'This is to _____ you that your account has been successfully created.', '["notify","inform","say","tell"]', 'notify', 'notify someone that 正式通知。'),
(85, 'multiple_choice', 'We _____ to your email within one business day.', '["responded","will respond","respond","are responding"]', 'will respond', 'will respond 承諾未來動作。'),
(85, 'multiple_choice', 'As per our _____ agreement, payment is due within 30 days of the invoice date.', '["mutual","common","collective","shared"]', 'mutual', 'mutual agreement 雙方協議，固定搭配。'),
(85, 'fill_blank', 'We wish to _____ your attention to the changes outlined in this document.', NULL, 'draw / bring', 'draw/bring someone''s attention to 引起注意。'),
(85, 'multiple_choice', 'We look _____ to receiving your response.', '["ahead","onward","towards","forward"]', 'forward', 'look forward to + V-ing 固定期待用語。'),
(85, 'multiple_choice', 'Please _____ that any expenses must be pre-approved by your line manager.', '["understand","remember","note","know"]', 'note', 'Please note that 正式提醒用語。'),
(85, 'multiple_choice', 'In _____ to your query, please find the requested information below.', '["response","reaction","answer","reply"]', 'response', 'in response to 正式回覆套語。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(86, 'multiple_choice', 'Please find the _____ for your recent order attached to this email.', '["invoice","account","receipt","bill"]', 'invoice', 'invoice 發票（向客戶請款的帳單），receipt 收據（已付款證明）。'),
(86, 'multiple_choice', 'The company sent out a _____ to inform employees about the new policy.', '["memo","bulletin","notice","announcement"]', 'memo', 'memo（備忘錄）通常指公司內部通知。'),
(86, 'multiple_choice', 'We need to finalize the _____ before the deal can go through.', '["deal","paper","contract","agreement"]', 'contract', 'finalize the contract 最終確定合約，最準確。'),
(86, 'fill_blank', 'The goods will be _____ within three business days of receiving payment.', NULL, 'dispatched / shipped', 'dispatched/shipped 出貨，商業英語常用。'),
(86, 'multiple_choice', 'She is responsible for _____ new talent for the organization.', '["employing to","staffing up","hiring out","recruiting"]', 'recruiting', 'recruiting new talent 招募新人才，固定搭配。'),
(86, 'multiple_choice', 'The _____ terms state that payment is due within 30 days.', '["financial","billing","payment","invoice"]', 'payment', 'payment terms 付款條件，固定搭配。'),
(86, 'multiple_choice', 'We need to review the _____ before signing to ensure all terms are acceptable.', '["criteria and standards","policies and procedures","rules and regulations","terms and conditions"]', 'terms and conditions', 'terms and conditions 條款細則，合約必備。'),
(86, 'fill_blank', 'Could you provide us with a _____ for the services you will provide?', NULL, 'quotation / quote', 'quotation/quote 報價單，正式商業文件。'),
(86, 'multiple_choice', 'The _____ meeting gave employees a chance to raise concerns about the restructuring.', '["staff","town hall","company","group"]', 'town hall', 'town hall meeting 全員大會，商業英語術語。'),
(86, 'multiple_choice', 'She was given a _____ for her outstanding contribution to the project.', '["reward","raise","bonus","promotion"]', 'bonus', 'bonus 獎金（非加薪 raise，非晉升 promotion）。'),
(86, 'multiple_choice', 'Please submit your _____ form for the expenses incurred during your business trip.', '["invoice","payment","reimbursement","claim"]', 'reimbursement', 'reimbursement form 費用報銷表格，最準確。'),
(86, 'fill_blank', 'The client requested a _____ on the price for placing a large order.', NULL, 'discount / reduction', 'discount 折扣，commercial 英語常見。'),
(86, 'multiple_choice', 'The new marketing _____ increased brand awareness significantly.', '["program","project","initiative","campaign"]', 'campaign', 'marketing campaign 行銷活動，最常見搭配。'),
(86, 'multiple_choice', 'She was asked to prepare a _____ of the meeting for distribution.', '["notes","transcript","minutes","record"]', 'minutes', 'minutes of a meeting 會議記錄，固定搭配。'),
(86, 'multiple_choice', 'We would like to place an _____ for 500 units of your product.', '["application","request","inquiry","order"]', 'order', 'place an order 下訂單，固定搭配。'),
(86, 'fill_blank', 'The company''s annual _____ showed strong revenue growth.', NULL, 'report / financial results', 'annual report 年度報告，常見商業文件。'),
(86, 'multiple_choice', 'The _____ department handles all compensation and benefits issues.', '["Personnel","Staffing","Human Resources","Employee"]', 'Human Resources', 'Human Resources（HR）人力資源部門，最通用。'),
(86, 'multiple_choice', 'We are currently _____ a new software development partner.', '["searching","finding","seeking","looking"]', 'seeking', 'seeking a partner 尋求合作夥伴，正式動詞。'),
(86, 'fill_blank', 'Please _____ the attached document and return it signed.', NULL, 'review / sign', 'review and sign 審閱並簽署。'),
(86, 'multiple_choice', 'The _____ for the new CEO position attracted over 200 applicants.', '["bulletin","announcement","advertisement","job posting"]', 'job posting', 'job posting 職位公告，數位時代最常用。'),
(87, 'multiple_choice', 'The company reported a _____ of $2 million due to unexpected costs.', '["deficit","deficiency","loss","shortage"]', 'deficit', 'deficit 赤字/虧損，財務術語。'),
(87, 'multiple_choice', 'Our top priority this year is _____ — keeping our existing clients happy.', '["customer service","client management","customer retention","account handling"]', 'customer retention', 'customer retention 客戶保留率，商業策略關鍵詞。'),
(87, 'multiple_choice', 'The _____ year runs from April to March in our company.', '["fiscal","annual","financial","accounting"]', 'fiscal', 'fiscal year 財政年度，正式財務術語。'),
(87, 'multiple_choice', 'The two companies announced a _____ that will create the largest firm in the sector.', '["merger","alliance","acquisition","partnership"]', 'merger', 'merger 合併（兩公司合為一）；acquisition 收購（一方買下另一方）。'),
(87, 'fill_blank', 'The company''s _____ grew by 15% compared to the same period last year.', NULL, 'revenue / turnover', 'revenue 收入，financial 核心指標。'),
(87, 'multiple_choice', 'She has a strong _____ record — she has never missed a deadline.', '["job","performance","track","work"]', 'track', 'track record 業績記錄，固定搭配。'),
(87, 'multiple_choice', 'We need to improve our _____ process to attract better candidates.', '["recruitment","staffing","hiring","employment"]', 'recruitment', 'recruitment process 招募流程，正式 HR 術語。'),
(87, 'fill_blank', 'The board approved a major _____ to streamline operations and reduce headcount.', NULL, 'restructuring', 'restructuring 重組，商業策略術語。'),
(87, 'multiple_choice', 'She serves as a _____ between the client and the technical team.', '["go-between","bridge","liaison","contact"]', 'liaison', 'liaison 聯絡員/中間人，正式商業術語。'),
(87, 'multiple_choice', 'The company filed for _____ after failing to repay its debts.', '["bankruptcy","closure","insolvency","liquidation"]', 'bankruptcy', 'bankruptcy 破產，法律商業術語。'),
(87, 'multiple_choice', 'We need to allocate more resources to _____ development.', '["goods","product","item","merchandise"]', 'product', 'product development 產品開發，固定搭配。'),
(87, 'fill_blank', 'The new acquisition will _____ our market position significantly.', NULL, 'strengthen / enhance', 'strengthen/enhance our position 鞏固/提升市場地位。'),
(87, 'multiple_choice', 'She was given _____ to negotiate directly with the supplier.', '["allowance","ability","permission","authorization"]', 'authorization', 'authorization 授權，正式商業術語。'),
(87, 'multiple_choice', 'The _____ of the company''s shares fell sharply following the announcement.', '["rate","worth","price","value"]', 'value', 'value of shares 股票價值，financial 術語。'),
(87, 'multiple_choice', 'We need to reduce our _____ costs to improve profit margins.', '["fixed","running","operational","overhead"]', 'overhead', 'overhead costs 間接成本/管理費用，financial 術語。'),
(87, 'fill_blank', 'The client submitted a formal _____ about the quality of our service.', NULL, 'complaint', 'complaint 正式投訴，商業英語。'),
(87, 'multiple_choice', 'The company set an _____ target of 20% revenue growth next year.', '["optimistic","realistic","ambitious","aggressive"]', 'ambitious', 'ambitious target 雄心勃勃的目標，正面語境。'),
(87, 'multiple_choice', 'She is in charge of _____ with key industry partners.', '["networking","communicating","collaborating","liaising"]', 'liaising', 'liaising with partners 與合作夥伴保持聯繫，正式動詞。'),
(87, 'fill_blank', 'All employees must sign a _____ (non-disclosure agreement) before starting.', NULL, 'non-disclosure agreement / NDA', 'NDA 保密協議，商業英語縮寫。'),
(87, 'multiple_choice', 'The company signed a _____ with a major retailer to distribute its products.', '["retail deal","trade contract","sales contract","distribution agreement"]', 'distribution agreement', 'distribution agreement 分銷協議，正式商業術語。'),
(88, 'multiple_choice', 'The two sides reached a _____ after weeks of difficult talks.', '["agreement","compromise","settlement","deal"]', 'compromise', 'reach a compromise 達成妥協，談判術語。'),
(88, 'multiple_choice', 'He _____ the task to his assistant to free up time for strategic work.', '["transferred","gave","delegated","assigned"]', 'delegated', 'delegate a task 委派任務，管理術語。'),
(88, 'multiple_choice', 'The company''s _____ revenue grew by 30% thanks to its new app.', '["digital","internet","online","tech"]', 'digital', 'digital revenue 數位收入，現代商業術語。'),
(88, 'fill_blank', 'The startup''s _____ model is designed to serve millions of users without extra costs.', NULL, 'scalable / scalability', 'scalable business model 可擴展商業模式。'),
(88, 'multiple_choice', 'Her _____ of industry trends allowed her to anticipate market shifts.', '["awareness","knowledge","grasp","understanding"]', 'knowledge', 'knowledge of 對...的瞭解，knowledge of industry trends 最自然。'),
(88, 'multiple_choice', 'The company is trying to _____ its brand in the competitive market.', '["differentiate","separate","distinguish","isolate"]', 'differentiate', 'differentiate a brand 讓品牌差異化，商業策略術語。'),
(88, 'multiple_choice', 'We need to assess the _____ of opening a new branch in that market.', '["possibility","probability","feasibility","viability"]', 'feasibility', 'feasibility 可行性，assess the feasibility 評估可行性。'),
(88, 'fill_blank', 'The new product was a _____ technology that changed how people communicate.', NULL, 'disruptive', 'disruptive technology 顛覆性科技，現代商業術語。'),
(88, 'multiple_choice', 'She has a strong _____ and is known for meeting her targets consistently.', '["values","morals","standards","work ethic"]', 'work ethic', 'work ethic 工作道德/勤勉，固定搭配。'),
(88, 'multiple_choice', 'The company offered a _____ to the client to make up for the delivery delay.', '["concession","compensation","discount","benefit"]', 'concession', 'concession 讓步/優惠，談判術語。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(88, 'multiple_choice', 'The annual _____ with external auditors is a regulatory requirement.', '["inspection","audit","review","check"]', 'audit', 'audit 審計，formal financial inspection。'),
(88, 'fill_blank', 'She _____ successfully between the two competing factions to reach an agreement.', NULL, 'mediated / negotiated', 'mediate/negotiate between parties 調解/談判。'),
(88, 'multiple_choice', 'He presented a _____ case for investing in the new technology.', '["good","strong","convincing","compelling"]', 'compelling', 'compelling case 有說服力的論點，商業提案術語。'),
(88, 'multiple_choice', 'The company''s _____ structure was simplified to improve decision-making speed.', '["corporate","organizational","management","company"]', 'organizational', 'organizational structure 組織架構，管理術語。'),
(88, 'multiple_choice', 'All parties must _____ to the confidentiality clause in the contract.', '["hold","adhere","stick","follow"]', 'adhere', 'adhere to 遵守，正式法律/商業術語。'),
(88, 'fill_blank', 'The firm announced it would _____ its non-core assets to focus on its main business.', NULL, 'divest / sell off', 'divest 出售非核心資產，商業策略術語。'),
(88, 'multiple_choice', 'She presented a _____ plan with three phases covering the next five years.', '["management","strategic","operational","business"]', 'strategic', 'strategic plan 策略計劃，固定搭配。'),
(88, 'multiple_choice', 'The _____ of the deal fell through at the last minute.', '["ending","closing","completion","finalization"]', 'finalization', 'finalization of a deal 最終確定交易，名詞化形式。'),
(88, 'fill_blank', 'The company''s _____ (market capitalization) exceeded $10 billion last year.', NULL, 'market capitalization / market cap', 'market cap 市值，重要財務術語。'),
(88, 'multiple_choice', 'His _____ approach to management earned him a reputation as a great leader.', '["collaborative","cooperative","joint","team"]', 'collaborative', 'collaborative approach 協作方式，管理術語。'),
(89, 'multiple_choice', 'In a business email, ''Please find attached...'' means:', '["Please look for the attachment.","Please attach a document.","The attachment is included with the email.","The document will be sent later."]', 'The attachment is included with the email.', 'Please find attached 表附件已附上。'),
(89, 'multiple_choice', 'What does ''As per our previous discussion'' indicate in an email?', '["The writer is referring back to an earlier conversation.","The writer is disagreeing.","The writer is starting a new topic.","The writer is apologising."]', 'The writer is referring back to an earlier conversation.', 'as per 表依照，referring to earlier discussion。'),
(89, 'multiple_choice', 'In a job posting, ''competitive salary'' most likely means:', '["A salary that involves competition.","A salary that compares well with industry standards.","A salary that is the highest available.","A salary that is challenging to earn."]', 'A salary that compares well with industry standards.', 'competitive salary 有競爭力的薪資，與業界相當。'),
(89, 'fill_blank', 'In a business letter, ''We regret to inform you...'' is used to deliver _____  news.', NULL, 'negative / bad', 'regret to inform 表遺憾地通知，傳遞壞消息。'),
(89, 'multiple_choice', 'What does ''cc:'' mean in an email header?', '["The email is from the CEO.","The email has been copied to additional recipients.","The email needs confirmation.","The email content is confidential."]', 'The email has been copied to additional recipients.', 'cc = carbon copy，副本收件人。'),
(89, 'multiple_choice', 'In a memo, ''effective immediately'' means:', '["The change has been effective for a while.","The change or instruction starts right away.","The change may be effective in the future.","The change will be effective eventually."]', 'The change or instruction starts right away.', 'effective immediately 立即生效。'),
(89, 'multiple_choice', 'A ''cover letter'' in a job application is:', '["A letter introducing yourself and explaining your interest in the position.","A summary of your work experience.","A reference from a previous employer.","A list of your qualifications."]', 'A letter introducing yourself and explaining your interest in the position.', 'cover letter 求職信，介紹自己與申請原因。'),
(89, 'transform', 'What does ''Subject to change without notice'' mean in a price list? (Explain in English)', NULL, 'It means prices may change at any time and the company does not have to inform customers in advance.', 'subject to change without notice 隨時可能改變，不另行通知。'),
(89, 'multiple_choice', 'In a notice, ''This supersedes all previous versions'' means:', '["This is the most current version and replaces all older ones.","This is the first version.","This has been approved by all departments.","This corrects errors in the last version."]', 'This is the most current version and replaces all older ones.', 'supersede 取代，表此版本為最新官方版本。'),
(89, 'multiple_choice', 'What does ''please RSVP by Friday'' mean?', '["Please arrive no later than Friday.","Please respond to survey questions by Friday.","Please read and review the invitation by Friday.","Please confirm whether you will attend by Friday."]', 'Please confirm whether you will attend by Friday.', 'RSVP = Répondez s''il vous plaît（法文），請回覆確認出席。'),
(89, 'multiple_choice', 'In a business report, ''Q3'' refers to:', '["The third question in a survey.","The third goal of the project.","The third item on the agenda.","The third quarter of the financial year."]', 'The third quarter of the financial year.', 'Q3 = Quarter 3，第三季。'),
(89, 'fill_blank', '''The meeting has been postponed until further notice'' means it has been _____.', NULL, 'cancelled / delayed indefinitely', 'postponed until further notice 暫時延期，無新日期。'),
(89, 'multiple_choice', 'What is an ''agenda'' in the context of a meeting?', '["The minutes of the previous meeting.","A list of attendees.","A summary of decisions made.","A list of topics to be discussed during the meeting."]', 'A list of topics to be discussed during the meeting.', 'agenda 會議議程，討論事項清單。'),
(89, 'multiple_choice', 'In a business context, ''ROI'' stands for:', '["Rate of Inflation","Return on Investment","Revenue over Income","Results of Implementation"]', 'Return on Investment', 'ROI = Return on Investment 投資報酬率。'),
(89, 'multiple_choice', 'If a contract is ''null and void'', it means:', '["The contract is valid and enforceable.","The contract has expired.","The contract has no legal force.","The contract needs revision."]', 'The contract has no legal force.', 'null and void 無效，不具法律效力。'),
(89, 'transform', 'What does ''The figures are subject to revision'' mean in a report?', NULL, 'It means the figures may be updated or changed later, and the current figures are not final.', 'subject to revision 可能修訂，非最終數字。'),
(89, 'fill_blank', 'In a job advertisement, ''competitive benefits package'' refers to salary, _____, and other perks.', NULL, 'healthcare / bonuses / paid leave', 'benefits package 福利套餐，包含薪資外的各種福利。'),
(89, 'multiple_choice', '''FYI'' in an email subject line means:', '["For Your Immediate response","From Your Inbox","For Your Information — no action required.","Follow Up Instructions"]', 'For Your Information — no action required.', 'FYI = For Your Information 供您參考。'),
(89, 'multiple_choice', 'A ''bottom line'' in business refers to:', '["The net profit or loss of a company.","The final sentence of a report.","The last point in a presentation.","The baseline budget."]', 'The net profit or loss of a company.', 'bottom line 最終損益，常引申為最重要的結果。'),
(89, 'multiple_choice', 'In business correspondence, ''enclosed please find'' means:', '["Please prepare the enclosed document.","Please search for the enclosed document.","The document will be sent separately.","The mentioned document is included with the letter."]', 'The mentioned document is included with the letter.', 'enclosed please find = please find enclosed 信中附上文件。'),
(90, 'multiple_choice', 'The number of employees in this branch _____ increased.', '["have","were","are","has"]', 'has', 'the number of 作主語，動詞用單數 has。'),
(90, 'multiple_choice', 'A number of issues _____ been identified.', '["have","is","was","has"]', 'have', 'a number of 作主語，動詞用複數 have。'),
(90, 'multiple_choice', 'Each of the candidates _____ required to submit a portfolio.', '["are","is","have been","were"]', 'is', 'each of + 複數名詞，動詞用單數 is。'),
(90, 'fill_blank', 'Neither the CEO nor the managers _____ available for comment.', NULL, 'were', 'neither...nor 就近原則，managers 複數，were。'),
(90, 'multiple_choice', 'Not only the sales team but also the director _____ attending the summit.', '["have been","were","is","are"]', 'is', 'not only...but also 就近原則，director 單數，is。'),
(90, 'multiple_choice', 'The staff _____ notified about the policy change.', '["were","is","has been","was"]', 'were', 'staff 通常視為複數（集合名詞），were。'),
(90, 'multiple_choice', 'All of the information _____ been verified.', '["has","have","are","were"]', 'has', 'all of + 不可數名詞 information，動詞單數 has。'),
(90, 'multiple_choice', 'Either the manager or the assistants _____ responsible.', '["is","are","have been","were"]', 'are', 'either...or 就近原則，assistants 複數，are。'),
(90, 'fill_blank', 'The board of directors _____ a meeting next Tuesday.', NULL, 'is holding', 'board of directors 集合名詞（正式英語多用單數）is holding。'),
(90, 'multiple_choice', 'There _____ several problems with the proposal.', '["were","is","are","has been"]', 'are', 'there are + 複數名詞 problems。'),
(90, 'multiple_choice', 'The team''s performance _____ improved significantly.', '["were","have","has","are"]', 'has', 'team''s performance 主語單數，has improved。'),
(90, 'multiple_choice', 'None of the applications _____ complete.', '["was","are","has been","is"]', 'are', 'none of + 複數名詞，可接複數（informal: none are）。'),
(90, 'multiple_choice', 'The data _____ clearly showing an upward trend.', '["is","have been","were","are"]', 'is', 'data 作不可數名詞時，is（現代用法）。'),
(90, 'fill_blank', 'A series of workshops _____ scheduled for the new hires.', NULL, 'has been / is', 'a series of 集合名詞，單數動詞。'),
(90, 'multiple_choice', 'Both the quality and the cost _____ need to be considered.', '["of the product","product''s","products''","of product"]', 'of the product', 'both...and 後，動詞複數（need），of the product 修飾兩者。'),
(90, 'multiple_choice', 'Each department _____ submit its report by the end of the month.', '["must their own","must they","must","must their"]', 'must', 'each department 單數，must + 原形動詞。'),
(90, 'multiple_choice', 'More than one application _____ been disqualified.', '["were","are","has","have"]', 'has', 'more than one + 單數名詞，動詞用單數 has。'),
(90, 'fill_blank', 'The committee _____ (decide) on the final candidate last week.', NULL, 'decided', 'committee 集合名詞（正式英語單數），decided。'),
(90, 'multiple_choice', 'Economics _____ the study of how resources are allocated.', '["is","have been","are","were"]', 'is', 'Economics 學科名稱用單數 is。'),
(90, 'multiple_choice', 'Ten years _____ a long time to commit to any project.', '["is","were","are","have been"]', 'is', 'ten years as a concept of duration = single unit，is。');