INSERT INTO grammar_topics (id, title, category, level, explanation_md) VALUES
(51, 'Coordinating Conjunctions: FANBOYS', 'conjunction', 2, 'FANBOYS（for、and、nor、but、or、yet、so）連接對等成分。商業英語常用 and（增加）、but（對比）、so（結果）、or（選擇）。'),
(52, 'Subordinating Conjunctions', 'conjunction', 3, '從屬連接詞引導從屬子句，包括時間（when）、原因（because）、條件（if/unless）、對比（although）等，建立複雜的邏輯關係。'),
(53, 'Correlative Conjunctions: either...or / neither...nor', 'conjunction', 3, '相關連接詞成對使用：either...or（兩者之一）；neither...nor（兩者都不）；both...and（兩者都）；not only...but also（不只...而且）。主謂一致依就近原則。'),
(54, 'Basic Sentence Structure (SVO)', 'word order', 1, '英語基本結構是主語-動詞-受語（SVO）。時間和地點副詞通常置句尾。修飾語放被修飾詞附近。這是所有英語寫作的基礎。'),
(55, 'Adverb Placement', 'word order', 3, '頻率副詞（always/often/never）置 be 後、主要動詞前；程度副詞（very/quite）置形容詞/副詞前；時間/地點副詞通常句尾。'),
(56, 'Inversion after Negative Adverbials', 'word order', 5, '否定副詞位於句首時需主謂倒裝：Never have we seen...；Not only did we...；Rarely does...；Hardly had...。常見於正式商業演講和高品質寫作。'),
(57, 'Quantifiers: some / any / no', 'determiner', 2, 'some 用於肯定句和期望肯定答案的疑問句；any 用於否定句和一般疑問句；no = not any（語氣更強）。'),
(58, 'Quantifiers: much / many / a lot of', 'determiner', 2, 'much + 不可數名詞（much time）；many + 可數名詞（many clients）；a lot of 兩者皆可，口語化。正式書面英語偏好 much/many。'),
(59, 'Quantifiers: few / little / a few / a little', 'determiner', 3, 'few/little 表幾乎沒有（消極）；a few/a little 表有一些（積極）。few/a few 用於可數名詞；little/a little 用於不可數名詞。'),
(60, 'Each / Every / All', 'determiner', 3, 'each 強調個別性（each employee）；every 強調整體的每一個（every department）；all 表全體（all staff）。each/every 接單數動詞，all 接複數動詞。'),
(61, 'Reflexive Pronouns', 'pronoun', 2, '反身代名詞（myself、yourself、himself、herself、itself、ourselves、yourselves、themselves）用於反身動作或強調（親自）。'),
(62, 'Indefinite Pronouns: someone/anyone/no one', 'pronoun', 2, 'someone/somebody 肯定句；anyone/anybody 疑問/否定句；no one/nobody 否定意義。對應 something/anything/nothing；somewhere/anywhere/nowhere。'),
(63, 'Countable and Uncountable Nouns', 'noun', 2, '可數名詞有複數（report→reports）；不可數名詞無複數（information、advice、equipment、furniture、progress、research、knowledge、news）。'),
(64, 'Compound Nouns', 'noun', 3, '複合名詞由兩個或更多詞組成，如 market research、software update、customer service。重音通常在第一個詞。書寫形式有分開、連字號或合一詞等。'),
(65, 'Order of Adjectives', 'adjective', 3, '形容詞排列順序：數量→意見→尺寸→年齡→形狀→顏色→來源→材質→目的。如 a small modern Japanese conference room。'),
(66, 'Participial Adjectives: -ed vs -ing', 'adjective', 3, '-ed 形容詞描述人的感受（I''m satisfied）；-ing 形容詞描述造成感受的事物（The results are satisfying）。混用是常見錯誤。'),
(67, 'Adverbs of Frequency', 'adverb', 2, '頻率副詞依次：always→usually/generally→often/frequently→sometimes/occasionally→rarely/seldom→never。置 be 後、主要動詞前。'),
(68, 'Adverbs of Degree', 'adverb', 3, '程度副詞強化或弱化程度：very/extremely/highly（非常）、quite/fairly/rather（相當）、somewhat/slightly（稍微）、barely/hardly（幾乎不）。'),
(69, 'Connecting Adverbs', 'adverb', 3, '連接副詞（conjunctive adverbs）連接兩個獨立子句，通常前有分號或句號後有逗號：however、therefore、moreover、furthermore、nevertheless、consequently、meanwhile。'),
(70, 'Cleft Sentences: It is...that', 'emphasis', 4, '分裂句 It is/was...that 強調句中特定成分。如 It was the CEO who approved it（強調主語）；It is the price that concerns us（強調受語）。'),
(71, 'Emphatic Do', 'emphasis', 4, '強調助動詞 do/does/did 用於強調肯定動詞，反駁懷疑或加強肯定語氣，如 We do appreciate your feedback。'),
(72, 'Subjunctive Mood', 'subjunctive', 5, '虛擬語氣用於建議/要求動詞（suggest/recommend/insist/require/demand）後的 that 子句，動詞用原形。It is essential/important/necessary + that + 原形。'),
(73, 'Wishes and Regrets: wish / if only', 'subjunctive', 4, 'wish + 過去式表現在的願望；wish + 過去完成式表過去的遺憾；wish + would 表對他人行為的期望；if only 語氣更強。'),
(74, 'Present Participle Clauses', 'participle clause', 4, '現在分詞子句（-ing 子句）表示同時進行或原因，取代副詞子句使文章更簡潔。如 Knowing the deadline, she worked overtime。'),
(75, 'Past Participle Clauses', 'participle clause', 4, '過去分詞子句（-ed 子句）通常表被動的完成動作，取代 when/after/because + passive。如 Reviewed by the team, the report was approved。'),
(76, 'Reduced Relative Clauses', 'participle clause', 4, '關係子句縮減：主動 → 現在分詞（the employee who manages = the employee managing）；被動 → 過去分詞（the report that was submitted = the report submitted）。'),
(77, 'Formal vs Informal Register', 'register', 3, '正式英語：完整形式（I am writing）、正式詞彙（assist/commence/enquire）、被動語態、避免縮寫。非正式：縮寫、口語詞彙。根據語境調整語體。'),
(78, 'Hedging Language', 'register', 4, '模糊限制語軟化陳述，表達不確定性或保持禮貌：It seems/appears that、This might/may、It would appear that、Apparently、Somewhat。廣泛用於商業分析和外交溝通。'),
(79, 'Nominalization', 'register', 4, '名詞化將動詞/形容詞轉為名詞，使文體更正式客觀。decide→decision、improve→improvement、analyze→analysis、discuss→discussion。'),
(80, 'Formal Writing: Passive and Impersonal', 'register', 4, '正式商業寫作使用被動語態（It has been decided）和非人稱結構（It is important to note that）保持客觀性，廣泛用於商業報告、提案和官方通知。'),
(81, 'Colons and Semicolons', 'punctuation', 3, '冒號（:）引出列表、解釋或強調；分號（;）連接兩個獨立但緊密相關的子句，代替句號。正確使用展現書面語言精確性。'),
(82, 'Apostrophes', 'punctuation', 2, '撇號用於縮寫（it''s = it is；we''re = we are）和所有格（the company''s policy；the managers'' reports）。注意 its（所有格）vs it''s（it is）。'),
(83, 'TOEIC: Part 5 Vocabulary in Context', 'TOEIC', 3, 'TOEIC Part 5 根據上下文選擇正確詞彙。策略：先讀完整句子，注意關鍵詞和搭配，用消去法。廣泛閱讀商業文章是提升詞彙的最佳方法。'),
(84, 'TOEIC: Part 5 Grammar Focus', 'TOEIC', 3, 'TOEIC Part 5 語法題涵蓋時態、詞類、介系詞等，需快速準確判斷。考試策略：識別空格的詞性，排除明顯錯誤，注意主謂一致。'),
(85, 'TOEIC: Part 6 Text Completion', 'TOEIC', 3, 'TOEIC Part 6 需根據整段上下文選擇正確詞彙、時態或句子。理解篇章邏輯和連貫性是關鍵，要看前後文選擇最合適的填空。'),
(86, 'TOEIC: Business Vocabulary I', 'TOEIC', 2, 'TOEIC 商業核心詞彙：合約（contract/agreement）、付款（invoice/receipt）、出貨（shipment/dispatch）、人資（recruitment/candidate）等。'),
(87, 'TOEIC: Business Vocabulary II', 'TOEIC', 2, 'TOEIC 商業詞彙進階：財務（fiscal/revenue/deficit）、策略（merger/acquisition/restructuring）、客戶關係（retention/satisfaction/complaint）等。'),
(88, 'TOEIC: Business Vocabulary III', 'TOEIC', 3, 'TOEIC 進階商業詞彙：談判（negotiate/concession）、組織（hierarchy/delegate）、數位商業（platform/scalable/disruptive）等。'),
(89, 'TOEIC: Part 7 Reading Comprehension Strategies', 'TOEIC', 3, 'TOEIC Part 7 需快速掌握文章主旨、推斷資訊及理解細節。常見題型：主旨題、細節題、詞義題、推斷題。本主題練習商業文件閱讀理解。'),
(90, 'TOEIC: Subject-Verb Agreement', 'TOEIC', 2, '主謂一致是 TOEIC 高頻考點：集合名詞、either/neither、not only...but also、there is/are、每一/all of。'),
(91, 'TOEIC: Preposition and Phrasal Verb Collocations', 'TOEIC', 3, 'TOEIC 常考介系詞固定搭配和片語動詞，如 look forward to、in charge of、deal with、carry out、put off。'),
(92, 'TOEIC: Word Forms', 'TOEIC', 3, 'TOEIC 詞形變化題考驗能否識別空格需要的詞性（名詞/動詞/形容詞/副詞），需熟悉常見詞尾：-tion、-ment、-al、-ous、-ly、-ize 等。'),
(93, 'TOEIC: Sentence Structure Errors', 'TOEIC', 3, '辨識常見語法錯誤：主謂不一致、時態錯誤、多餘詞、遺漏詞等。TOEIC Part 5 需快速識別並選出正確選項。'),
(94, 'Tag Questions', 'grammar', 3, '附加問句（疑問附加語）：陳述句用正附加，疑問句用負附加（She is here, isn''t she? / He isn''t coming, is he?）。情態動詞、完成式、被動式均有對應附加問句。'),
(95, 'Conditionals: unless / provided that / as long as', 'conditional', 3, 'unless = if not（除非）；provided (that) = on condition that（前提是）；as long as = if（只要）。這三個詞都引導條件子句，是 if 的重要替代表達。'),
(96, 'Present Perfect Continuous', 'tense', 4, '現在完成進行式（have/has been + V-ing）強調從過去持續到現在的動作，常與 for/since/all day/recently 連用，強調動作的持續性。'),
(97, 'Reported Speech: No Backshift Exceptions', 'reported speech', 4, '當報告的是普遍事實、科學真理、仍為真的情況，或報告者認為時態不需後移時，時態不必後移。正式學術和新聞英語中常見此現象。'),
(98, 'Sentence Connectors: Listing and Addition', 'conjunction', 3, '列舉和補充連接詞：firstly/secondly/finally（列舉順序）；in addition/furthermore/moreover（補充）；as well as/also/too（也）；what is more（更重要的是）。'),
(99, 'Sentence Connectors: Contrast and Concession', 'conjunction', 3, '對比讓步連接詞：however/nevertheless（然而）；on the other hand（另一方面）；by contrast（相比之下）；in spite of this（儘管如此）；even so（即便如此）。'),
(100, 'Question Forms', 'grammar', 2, '疑問句種類：Yes/No 問句（使用助動詞倒裝）；Wh- 問句（疑問詞 + 助動詞倒裝）；間接問句（陳述語序）；主語問句（疑問詞作主語，無倒裝）。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(1, 'multiple_choice', 'She _____ in the marketing department.', '["is working","work","working","works"]', 'works', 'works 用現在簡單式描述固定職責。'),
(1, 'multiple_choice', 'They _____ on a new product right now.', '["worked","works","are working","work"]', 'are working', 'right now 需用現在進行式 are working。'),
(1, 'multiple_choice', 'He usually _____ to the office by 9 a.m.', '["has arrived","is arriving","arrive","arrives"]', 'arrives', 'usually 搭配現在簡單式 arrives。'),
(1, 'multiple_choice', 'We _____ our quarterly report this week.', '["prepared","are preparing","prepare","prepares"]', 'are preparing', 'this week 暫時性，are preparing 正確。'),
(1, 'multiple_choice', 'The CEO _____ a speech at the conference tomorrow.', '["gave","give","is giving","gives"]', 'is giving', '已安排的未來，is giving 正確。'),
(1, 'multiple_choice', 'Our team _____ five days a week.', '["are working","work","works","is working"]', 'works', 'five days a week 頻率，works 三單正確。'),
(1, 'fill_blank', 'Listen! The manager _____ (speak) to the client right now.', NULL, 'is speaking', 'Listen! 表當下進行，is speaking。'),
(1, 'fill_blank', 'She always _____ (check) her emails before the meeting.', NULL, 'checks', 'always 搭配簡單式，checks 三單。'),
(1, 'multiple_choice', 'I _____ the new software is very efficient.', '["thinks","think","am thinking","thought"]', 'think', 'think 靜態動詞，不用進行式。'),
(1, 'multiple_choice', 'The sales figures _____ every quarter.', '["increases","increase","increased","are increasing"]', 'increase', 'every quarter 固定規律，簡單式 increase。'),
(1, 'fill_blank', 'Sales _____ (rise) steadily this quarter.', NULL, 'are rising', 'this quarter 當下趨勢，are rising。'),
(1, 'transform', 'The company reviews budgets quarterly. (Rewrite using: reviews)', NULL, 'The company reviews its annual budget every quarter.', '現在簡單式 reviews 表定期政策。'),
(1, 'multiple_choice', 'She _____ at three different locations this month.', '["works","worked","work","is working"]', 'is working', 'this month 暫時性，is working 正確。'),
(1, 'multiple_choice', 'We _____ international clients on a regular basis.', '["served","serve","are serving","serves"]', 'serve', 'on a regular basis 固定習慣，serve 複數主詞。'),
(1, 'fill_blank', 'Please be quiet. I _____ (concentrate) on this report.', NULL, 'am concentrating', '當下正在進行，am concentrating。'),
(1, 'multiple_choice', 'The training program _____ for new hires every six months.', '["run","runs","ran","is running"]', 'runs', 'every six months 固定週期，runs 三單。'),
(1, 'multiple_choice', 'Look at those clouds — it _____ to rain.', '["went","go","is going","goes"]', 'is going', '根據眼前跡象，is going to rain。'),
(1, 'fill_blank', 'Profits _____ (grow) faster than expected this year.', NULL, 'are growing', 'this year 當前進行趨勢，are growing。'),
(1, 'multiple_choice', 'She _____ in charge of client relations.', '["be","was","are","is"]', 'is', 'is 現在式三單，描述當前職責。'),
(1, 'multiple_choice', 'The board _____ three times a year.', '["is meeting","meets","met","meet"]', 'meets', 'three times a year 頻率，簡單式 meets。'),
(2, 'multiple_choice', 'She _____ a presentation when the power went out.', '["was giving","gives","had given","gave"]', 'was giving', '過去進行式描述背景動作 was giving；when 引入插入動作。'),
(2, 'multiple_choice', 'The team _____ the project last Friday.', '["completes","was completing","has completed","completed"]', 'completed', 'last Friday 明確時間點，過去簡單式 completed。'),
(2, 'multiple_choice', 'While I _____ the contract, my boss called.', '["had reviewed","reviewed","was reviewing","review"]', 'was reviewing', 'while 引導背景進行式 was reviewing。'),
(2, 'multiple_choice', 'He _____ the report at 10 a.m. yesterday.', '["wrote","had written","was writing","writes"]', 'was writing', 'at 10 a.m. yesterday 指過去時刻進行中，was writing。'),
(2, 'multiple_choice', 'We _____ the deal in 2022.', '["were finalizing","finalized","finalize","had finalized"]', 'finalized', 'in 2022 完成時間點，過去簡單式 finalized。'),
(2, 'fill_blank', 'When the CEO entered, everyone _____ (stand) up.', NULL, 'stood', 'stand up 是即時反應，過去簡單式 stood。'),
(2, 'fill_blank', 'They _____ (negotiate) for two hours when the client left.', NULL, 'were negotiating', '背景動作用過去進行式 were negotiating。'),
(2, 'multiple_choice', 'I _____ in Tokyo when I received the news.', '["have attended","attend","was attending","attended"]', 'was attending', '背景進行式 was attending，插入 received。'),
(2, 'multiple_choice', 'The system _____ down three times last week.', '["went","was going","goes","had gone"]', 'went', 'last week 加次數，過去簡單式 went。'),
(2, 'transform', 'She talked to the client. At the same time she reviewed the doc. (Use: while)', NULL, 'While she was talking to the client, she reviewed the document.', 'while 引導背景進行式，主句過去簡單式。'),
(2, 'fill_blank', 'He _____ (travel) to Singapore when his flight got delayed.', NULL, 'was travelling', '背景動作用過去進行式 was travelling。'),
(2, 'multiple_choice', 'The review _____ three hours.', '["was lasting","has lasted","lasted","lasts"]', 'lasted', '過去簡單式 lasted 描述完整持續時間。'),
(2, 'multiple_choice', 'What _____ you _____ at 3 p.m. Thursday?', '["did / do","have / done","do / doing","were / doing"]', 'were / doing', 'at 3 p.m. 過去時刻，過去進行式疑問句。'),
(2, 'fill_blank', 'As I _____ (prepare) the slides, I noticed an error.', NULL, 'was preparing', 'As 引導背景動作，過去進行式 was preparing。'),
(2, 'multiple_choice', 'The new policy _____ effect in January last year.', '["was taking","takes","took","had taken"]', 'took', '明確時間，過去簡單式 took effect。'),
(2, 'multiple_choice', 'She _____ the file when her computer crashed.', '["updates","had updated","updated","was updating"]', 'was updating', '背景 was updating，插入 crashed。'),
(2, 'fill_blank', 'The team _____ (celebrate) when they heard the news.', NULL, 'was celebrating', '背景動作用過去進行式 was celebrating。'),
(2, 'multiple_choice', 'The conference _____ for three days.', '["lasts","lasted","was lasting","has lasted"]', 'lasted', '過去簡單式 lasted 描述完成持續。'),
(2, 'transform', 'He worked at the office. Then his phone rang. (Use: was working when)', NULL, 'He was working at the office when his phone rang.', 'was working 背景進行式，when 引入插入動作。'),
(2, 'multiple_choice', 'I _____ the client when my manager interrupted.', '["have called","was calling","called","call"]', 'was calling', '背景 was calling，插入 interrupted。'),
(3, 'multiple_choice', 'We _____ the new system last month.', '["were implementing","implement","implemented","have implemented"]', 'implemented', 'last month 明確過去，過去簡單式 implemented。'),
(3, 'multiple_choice', 'The company _____ its revenue by 20% this year.', '["increase","increased","has increased","was increasing"]', 'has increased', 'this year 到目前，現在完成式 has increased。'),
(3, 'fill_blank', 'She _____ (work) here for five years.', NULL, 'has worked', 'for five years 持續到現在，has worked。'),
(3, 'multiple_choice', 'Have you _____ the client''s requirements?', '["review","were reviewing","reviewed","reviewing"]', 'reviewed', 'Have you + 過去分詞，現在完成式疑問句。'),
(3, 'fill_blank', 'Profits _____ (rise) steadily since the restructuring.', NULL, 'have risen', 'since 搭配現在完成式 have risen。'),
(3, 'multiple_choice', 'This is the best quarter our company _____.', '["was ever having","ever had","had ever","has ever had"]', 'has ever had', 'ever 搭配最高級使用現在完成式。'),
(3, 'transform', 'We launched the product. It is now in 30 markets. (Use: have launched)', NULL, 'We have launched the product and it is now in 30 markets.', '現在完成式連結過去行動與現在狀態。'),
(3, 'multiple_choice', 'They _____ their headquarters to Singapore.', '["move","were moving","have moved","moved"]', 'have moved', '強調結果，現在完成式 have moved。'),
(3, 'fill_blank', 'The manager _____ just _____ (return) from the trade fair.', NULL, 'has / returned', 'just 搭配現在完成式。'),
(3, 'multiple_choice', 'We _____ this client for over ten years.', '["are serving","served","have served","serve"]', 'have served', 'for over ten years 持續到現在，have served。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(3, 'multiple_choice', 'The report _____ not been submitted yet.', '["have","has","had","was"]', 'has', 'report 單數，has not been submitted yet。'),
(3, 'fill_blank', 'How long _____ you _____ (be) in this role?', NULL, 'have / been', 'How long + have + 主詞 + been 問持續時間。'),
(3, 'multiple_choice', 'Our new policy _____ already _____ results.', '["has / produced","is / producing","have / produced","had / produced"]', 'has / produced', 'already 搭配現在完成式，policy 單數 has。'),
(3, 'multiple_choice', 'She _____ three conferences this year.', '["attends","was attending","has attended","attended"]', 'has attended', 'this year 到目前，現在完成式。'),
(3, 'transform', 'I have never visited Seoul. (Use: first time)', NULL, 'This is the first time I have visited Seoul.', 'first time + 現在完成式表達首次經驗。'),
(3, 'fill_blank', 'The board _____ (approve) the proposal this morning.', NULL, 'has approved', 'this morning 仍在今天，has approved。'),
(3, 'multiple_choice', 'Sales _____ doubled since the campaign launched.', '["have","had","has","are"]', 'have', 'Sales 複數，have doubled。'),
(3, 'multiple_choice', 'I _____ just _____ an email from the client.', '["did / receive","had / received","have / received","was / receiving"]', 'have / received', 'just 搭配現在完成式。'),
(3, 'multiple_choice', 'The team _____ the prototype three times this week.', '["has tested","tested","was testing","test"]', 'has tested', 'this week 到目前，has tested。'),
(3, 'multiple_choice', 'She _____ not yet _____ the draft contract.', '["has / finalized","did / finalize","had / finalized","is / finalizing"]', 'has / finalized', 'not yet 搭配現在完成式 has not finalized。'),
(4, 'multiple_choice', 'I _____ the report an hour ago.', '["have submitted","submit","submitted","was submitting"]', 'submitted', 'an hour ago 過去時間點，過去簡單式 submitted。'),
(4, 'multiple_choice', 'We _____ our target this quarter so far.', '["were exceeding","exceed","exceeded","have exceeded"]', 'have exceeded', 'so far 到現在，現在完成式 have exceeded。'),
(4, 'multiple_choice', 'She _____ the company in 2015.', '["join","joined","had joined","has joined"]', 'joined', 'in 2015 明確過去，過去簡單式 joined。'),
(4, 'fill_blank', 'Have you _____ (send) the invoice yet?', NULL, 'sent', 'yet 搭配現在完成式，sent 是 send 的過去分詞。'),
(4, 'multiple_choice', 'The last product launch _____ very successful.', '["has been","were","was","is"]', 'was', 'last product launch 過去特定事件，was。'),
(4, 'multiple_choice', 'The company _____ three offices since 2010.', '["opens","has opened","opened","was opening"]', 'has opened', 'since 2010 到現在，has opened。'),
(4, 'fill_blank', 'We _____ (not / receive) any feedback yet.', NULL, 'have not received', 'yet 否定句搭配現在完成式。'),
(4, 'multiple_choice', 'Did you _____ the presentation last Tuesday?', '["delivering","delivered","deliver","have delivered"]', 'deliver', 'Did you + 原形動詞，過去式疑問句。'),
(4, 'transform', 'The price dropped and is still low for three months. (Use: has dropped)', NULL, 'The price has dropped and has remained low for three months.', '現在完成式強調持續到現在的結果。'),
(4, 'multiple_choice', 'This is the third time he _____ late this month.', '["is","had been","has been","was"]', 'has been', 'this month 到現在累積，has been。'),
(4, 'multiple_choice', 'The auditors _____ the accounts last week.', '["were checking","have checked","checked","check"]', 'checked', 'last week 明確過去，過去簡單式 checked。'),
(4, 'fill_blank', 'How many deals _____ the team _____ (close) this quarter?', NULL, 'has / closed', 'this quarter 到目前，現在完成式疑問句。'),
(4, 'multiple_choice', 'We _____ a new office in Berlin last year.', '["open","had opened","have opened","opened"]', 'opened', 'last year 明確過去，過去簡單式 opened。'),
(4, 'multiple_choice', 'Our profits _____ significantly since we restructured.', '["have grown","are growing","grew","grow"]', 'have grown', 'since 搭配現在完成式 have grown。'),
(4, 'transform', 'I lost the contract six months ago. (Use: ago)', NULL, 'I lost the contract six months ago.', 'ago 搭配過去簡單式。'),
(4, 'fill_blank', 'The CEO _____ (step down) last Friday.', NULL, 'stepped down', 'last Friday 明確過去，過去簡單式 stepped down。'),
(4, 'multiple_choice', 'They _____ never _____ such strong demand before.', '["did / see","were / seeing","have / seen","had / seen"]', 'have / seen', 'never + 現在完成式表從未有的經驗。'),
(4, 'multiple_choice', 'When _____ the merger _____?', '["had / happened","has / happened","did / happen","was / happening"]', 'did / happen', 'When 問明確時間，過去簡單式疑問句。'),
(4, 'fill_blank', 'We _____ (partner) with three new suppliers since January.', NULL, 'have partnered', 'since January 到現在，現在完成式。'),
(4, 'multiple_choice', 'I _____ him at the trade fair in April.', '["meet","was meeting","met","have met"]', 'met', 'in April 過去時間點，過去簡單式 met。'),
(5, 'multiple_choice', 'By the time the client arrived, we _____ all the documents.', '["have prepared","were preparing","had prepared","prepared"]', 'had prepared', 'by the time 建立先後，had prepared 在到達前完成。'),
(5, 'multiple_choice', 'She realized she _____ the wrong file.', '["was sending","has sent","had sent","sent"]', 'had sent', 'realized 在過去，發送更早，過去完成式 had sent。'),
(5, 'fill_blank', 'Before the meeting started, the team _____ (review) the agenda.', NULL, 'had reviewed', 'before 表先後，更早的動作用過去完成式。'),
(5, 'multiple_choice', 'When I arrived, the presentation _____ already _____.', '["had / started","has / started","did / start","was / starting"]', 'had / started', 'already + 過去完成式；had started。'),
(5, 'multiple_choice', 'He _____ never _____ such a complex contract before.', '["was / negotiating","did / negotiate","had / negotiated","has / negotiated"]', 'had / negotiated', 'never + 過去完成式表從未有的經驗。'),
(5, 'transform', 'First we submitted. Then we received approval. (Use: had submitted)', NULL, 'We had submitted the proposal before we received approval.', 'had submitted 描述更早的動作。'),
(5, 'multiple_choice', 'By the end of Q3, we _____ the annual target.', '["were exceeding","exceeded","had exceeded","have exceeded"]', 'had exceeded', 'by the end of Q3 設定過去時間點，had exceeded。'),
(5, 'fill_blank', 'The client _____ (already / sign) the NDA before the first meeting.', NULL, 'had already signed', 'before 連接兩個過去事件，更早用過去完成式。'),
(5, 'multiple_choice', 'I discovered that my colleague _____ the same research.', '["conducted","was conducting","has conducted","had conducted"]', 'had conducted', 'discovered 過去，研究更早，had conducted。'),
(5, 'multiple_choice', 'They _____ the merger long before it was announced.', '["had planned","were planning","planned","have planned"]', 'had planned', 'long before 強調先後，had planned。'),
(5, 'fill_blank', 'Once the audit _____ (complete), the results were presented.', NULL, 'had been completed', 'once 引導過去完成被動式。'),
(5, 'multiple_choice', 'The product had been on the market two years before it _____ a profit.', '["had made","made","was making","makes"]', 'made', 'made 是後發生的過去事件，簡單過去式。'),
(5, 'multiple_choice', 'We _____ already _____ a similar service before the client asked.', '["did / develop","were / developing","have / developed","had / developed"]', 'had / developed', 'already + 過去完成式 had developed。'),
(5, 'transform', 'The team finished. Then the director reviewed it. (Use: had finished)', NULL, 'By the time the director reviewed it, the team had finished the report.', 'had finished 在 reviewed 之前完成。'),
(5, 'fill_blank', 'I realized I _____ (forget) to include the appendix.', NULL, 'had forgotten', 'realized 在過去，forget 更早，had forgotten。'),
(5, 'multiple_choice', 'All the guests _____ when the CEO made her announcement.', '["have arrived","arrived","were arriving","had arrived"]', 'had arrived', 'when the CEO made 設定過去時間點，had arrived 已到。'),
(5, 'multiple_choice', 'They _____ not _____ the terms before signing.', '["had / understood","did / understand","have / understood","were / understanding"]', 'had / understood', '簽約前的過去完成式否定。'),
(5, 'fill_blank', 'The company _____ (expand) into Asia before the crisis hit.', NULL, 'had expanded', 'before 建立先後，更早用過去完成式。'),
(5, 'multiple_choice', 'By the time I joined, the company _____ its strategy.', '["already revised","has already revised","was already revising","had already revised"]', 'had already revised', 'had already revised 過去完成式。'),
(5, 'multiple_choice', 'She found out that the deal _____ without her approval.', '["had approved","had been approved","has been approved","was approved"]', 'had been approved', '過去完成被動式 had been approved。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(6, 'multiple_choice', 'I _____ send you the contract as soon as it''s ready.', '["am going to","was","would","will"]', 'will', 'will 表即時承諾；am going to 也可，但 will 更常見於即時承諾。'),
(6, 'multiple_choice', 'We _____ launch the new product line next spring. Everything is planned.', '["would","were going to","will","are going to"]', 'are going to', '已計劃好的意圖用 be going to；will 表臨時決定。'),
(6, 'multiple_choice', 'Look at those sales numbers — this _____ be our best year ever!', '["is going to","was going to","would","will"]', 'is going to', '根據眼前證據預測，用 be going to。'),
(6, 'fill_blank', 'I just decided — I _____ (take) the overseas assignment.', NULL, 'will take', 'just decided 表臨時決定，用 will。'),
(6, 'multiple_choice', 'The director _____ give a speech at the annual banquet next month.', '["would","was going to","is going to","will"]', 'is going to', 'next month 已排定計劃，be going to 更合適。'),
(6, 'transform', 'It is planned that the company expands to Europe next year. (Use: going to)', NULL, 'The company is going to expand to Europe next year.', '已計劃的意圖用 be going to。'),
(6, 'multiple_choice', 'Don''t worry, I _____ help you with the report.', '["was going to","would","will","am going to"]', 'will', '即時答應幫忙，will 最自然。'),
(6, 'fill_blank', 'We _____ (hold) the annual conference in Dubai. All arrangements are made.', NULL, 'are going to hold', '已安排好的計劃，be going to 正確。'),
(6, 'multiple_choice', 'It looks like the project _____ be delayed.', '["will","is going to","was going to","would"]', 'is going to', '根據現有跡象預測，be going to。'),
(6, 'multiple_choice', 'She _____ be the new CFO. It was announced yesterday.', '["would be","is going to","was going to","will"]', 'is going to', '已宣布的計劃，be going to。'),
(6, 'fill_blank', 'Someone has to present this. — OK, I _____ (do) it.', NULL, 'will do', '即時決定，will do。'),
(6, 'multiple_choice', 'By this time next year, we _____ have doubled our market share.', '["would","are going to","will","were going to"]', 'will', '未來完成式 will have doubled，預測未來時間點前完成。'),
(6, 'transform', 'The manager has decided to retire in July. (Use: going to retire)', NULL, 'The manager is going to retire in July.', '已決定的計劃，be going to。'),
(6, 'multiple_choice', 'I _____ definitely call you back after the meeting.', '["am going to","would","was going to","will"]', 'will', '即時承諾用 will。'),
(6, 'fill_blank', 'The negotiation _____ (start) at 2 p.m. It''s on the schedule.', NULL, 'is going to start', '已排定計劃，be going to start。'),
(6, 'multiple_choice', 'There''s no way around it — we _____ need more funding.', '["would","are going to","will","were going to"]', 'will', '客觀預測用 will；are going to 也可。'),
(6, 'multiple_choice', 'She promised she _____ send the invoice today.', '["will","would","was going to","is going to"]', 'would', 'promised 後的間接引語用 would。'),
(6, 'fill_blank', 'Watch out! That pile of documents _____ (fall).', NULL, 'is going to fall', '根據眼前情況的即時預測，be going to。'),
(6, 'multiple_choice', 'We _____ restructure the department. We''ve been planning it for months.', '["would","will","are going to","were going to"]', 'are going to', '幾個月的計劃，be going to。'),
(6, 'multiple_choice', 'I think the market _____ recover by Q3.', '["will","would","was going to","is going to"]', 'will', '主觀預測用 will。'),
(7, 'multiple_choice', 'By next Friday, we _____ the audit report.', '["will be submitting","are submitting","will submit","will have submitted"]', 'will have submitted', 'by next Friday 搭配未來完成式 will have submitted。'),
(7, 'multiple_choice', 'This time next week, I _____ the annual conference in London.', '["will attend","will have attended","attend","will be attending"]', 'will be attending', 'this time next week 指未來某時刻進行中，will be attending。'),
(7, 'fill_blank', 'By the end of this year, the company _____ (open) ten new branches.', NULL, 'will have opened', 'by the end of this year 搭配未來完成式。'),
(7, 'multiple_choice', 'Don''t call at 3 p.m. — she _____ her presentation then.', '["gives","will have given","will be giving","will give"]', 'will be giving', 'at 3 p.m. 未來時刻正在進行，will be giving。'),
(7, 'multiple_choice', 'We _____ the new platform for six months by December.', '["will have been using","will use","have been using","will be using"]', 'will have been using', 'by December 強調持續時間完成，未來完成進行式。'),
(7, 'transform', 'The project ends on March 31. (Use: will have completed by)', NULL, 'We will have completed the project by March 31.', 'by + 未來時間點，搭配未來完成式。'),
(7, 'multiple_choice', 'I _____ in this role for ten years next June.', '["have been working","will work","will have been working","will be working"]', 'will have been working', 'next June 到那時累積10年，未來完成進行式。'),
(7, 'fill_blank', 'By the time you read this, the meeting _____ (start) already.', NULL, 'will have already started', 'by the time 搭配未來完成式。'),
(7, 'multiple_choice', 'At this time tomorrow, they _____ final contract terms.', '["negotiate","will have negotiated","will be negotiating","will negotiate"]', 'will be negotiating', 'this time tomorrow 未來某時刻進行中，will be negotiating。'),
(7, 'multiple_choice', 'We _____ 1,000 units by the end of Q2.', '["will ship","will be shipping","will have shipped","are shipping"]', 'will have shipped', 'by the end of Q2 搭配未來完成式 will have shipped。'),
(7, 'fill_blank', 'This time next month, I _____ (work) in our Singapore office.', NULL, 'will be working', 'this time next month 未來時刻正在進行。'),
(7, 'multiple_choice', 'By 2027, the company _____ its expansion into five new markets.', '["will have completed","will be completing","completes","will complete"]', 'will have completed', 'by 2027 搭配未來完成式。'),
(7, 'multiple_choice', 'She _____ in the middle of her vacation when you call.', '["will be relaxing","relaxes","will have relaxed","will relax"]', 'will be relaxing', 'when you call 那個時間點正在休假，will be relaxing。'),
(7, 'transform', 'The renovation ends before the clients arrive. (Use: will have finished)', NULL, 'The renovation will have finished before the clients arrive.', 'before 搭配未來完成式。'),
(7, 'fill_blank', 'By the end of Q4, total revenue _____ (reach) $10 million.', NULL, 'will have reached', 'by the end of Q4 搭配未來完成式。'),
(7, 'multiple_choice', 'Don''t disturb the CEO at 2 p.m. — she _____ an important call.', '["will be having","has","will have had","will have"]', 'will be having', '2 p.m. 未來時刻進行中，will be having。'),
(7, 'multiple_choice', 'We _____ this software for a year by next January.', '["will have been using","have used","will use","will be using"]', 'will have been using', 'by next January 累積一年，未來完成進行式。'),
(7, 'fill_blank', 'By the time the new hire starts, we _____ (complete) the onboarding materials.', NULL, 'will have completed', 'by the time 搭配未來完成式。'),
(7, 'multiple_choice', 'This time next year, the team _____ in a brand new office.', '["works","will be working","will have worked","will work"]', 'will be working', 'this time next year 未來時刻進行。'),
(7, 'multiple_choice', 'By 2030, we _____ 500 employees worldwide.', '["will be hiring","will have hired","are hiring","will hire"]', 'will have hired', 'by 2030 搭配未來完成式 will have hired。'),
(8, 'multiple_choice', 'She _____ the company for three years when she _____ her first promotion.', '["has been working / receives","was working / has received","worked / was receiving","had been working / received"]', 'had been working / received', 'had been working 表在 received 之前持續的動作。'),
(8, 'multiple_choice', 'By the time I _____ tomorrow, the deal _____.', '["will arrive / is signed","arrived / had been signed","arrive / will have been signed","am arriving / will sign"]', 'arrive / will have been signed', 'arrive 時間子句用現在式，主句用未來完成被動式。'),
(8, 'multiple_choice', 'We _____ the market every year, but this year we _____ something different.', '["analyse / tried","have analysed / tried","analyse / are trying","analysed / tried"]', 'analyse / are trying', 'every year 簡單式，this year 進行式（暫時策略）。'),
(8, 'fill_blank', 'The team _____ (just / finish) the report when the client _____ (call).', NULL, 'had just finished / called', 'had just finished 過去完成，called 插入動作。'),
(8, 'multiple_choice', 'She _____ in marketing for ten years before she _____ to management.', '["worked / has moved","had worked / moved","was working / moved","has worked / moves"]', 'had worked / moved', '在 moved 之前的持續，had worked；then moved。'),
(8, 'multiple_choice', 'I _____ a lot of business trips lately, so I _____ quite tired.', '["took / was","had taken / was","have been taking / am","take / am"]', 'have been taking / am', 'lately 現在完成進行式，result 現在狀態。'),
(8, 'multiple_choice', 'As soon as she _____ the budget, she _____ the board.', '["is approving / will inform","approved / informed","will approve / informs","approves / will inform"]', 'approves / will inform', 'as soon as 時間子句用現在式，主句用 will。'),
(8, 'transform', 'The company lost money last year. Now it is profitable. (Use appropriate tenses)', NULL, 'The company lost money last year, but it has become profitable now.', 'lost 過去式；has become 現在完成式表狀態改變。'),
(8, 'multiple_choice', 'When I came into the office, she _____ already _____ all the preparations.', '["did / make","has / made","had / made","was / making"]', 'had / made', 'came 過去，preparations 更早完成，had made。'),
(8, 'fill_blank', 'Sales _____ (increase) every quarter since the new strategy _____ (implement).', NULL, 'have increased / was implemented', 'since 搭配現在完成式；被動過去式 was implemented。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(8, 'multiple_choice', 'He _____ the company before it _____ public.', '["was leaving / had gone","leaves / goes","left / has gone","had left / went"]', 'had left / went', '左邊更早 had left；然後 went public。'),
(8, 'multiple_choice', 'The factory _____ at full capacity when the order _____.', '["was operating / arrived","is operating / will arrive","has been operating / arrives","operated / was arriving"]', 'was operating / arrived', '背景進行式 was operating，插入 arrived。'),
(8, 'multiple_choice', 'By next March, she _____ in management for five years.', '["will have been","was","has been","will be"]', 'will have been', 'by next March 未來時間點，will have been。'),
(8, 'fill_blank', 'I _____ (not / see) her since she _____ (transfer) to the Hong Kong office.', NULL, 'have not seen / was transferred', 'since 搭配現在完成式；transferred 被動過去式。'),
(8, 'multiple_choice', 'While we _____ the presentation, our server _____ down.', '["prepared / was going","prepare / goes","had prepared / went","were preparing / went"]', 'were preparing / went', '背景進行式 were preparing，插入 went down。'),
(8, 'multiple_choice', 'She _____ this role for two years by the time she _____ her MBA.', '["held / finished","will have held / finishes","holds / finishes","has held / finishes"]', 'will have held / finishes', 'by the time 未來完成式 will have held；時間子句用現在式。'),
(8, 'multiple_choice', 'The client _____ before we _____ to respond.', '["had left / had time","has left / have time","was leaving / had time","left / have time"]', 'had left / had time', 'had left 和 had time 兩個過去完成式，強調均在主句時間前。'),
(8, 'transform', 'First the budget was approved. Then the project started. (Use: had been approved)', NULL, 'The project started after the budget had been approved.', 'after 連接：had been approved 更早，started 後來。'),
(8, 'multiple_choice', 'She _____ three proposals this week and _____ two of them.', '["has written / submitted","wrote / has submitted","is writing / submitted","writes / submits"]', 'has written / submitted', 'this week 現在完成式，且已提交也是本週。'),
(8, 'multiple_choice', 'He rarely _____ late, but yesterday he _____ the whole morning.', '["is / missed","is / has missed","has been / missed","was / misses"]', 'is / missed', 'rarely is 習慣；yesterday missed 過去事件。'),
(9, 'multiple_choice', 'Please send me _____ contract you mentioned in your email.', '["a","the","—","an"]', 'the', 'mentioned 已知，雙方都知的特定合約，用 the。'),
(9, 'multiple_choice', 'She is _____ CEO of a Fortune 500 company.', '["—","an","a","the"]', 'the', 'CEO 是獨一無二的職位，且特指某公司，用 the。'),
(9, 'multiple_choice', 'We need to review _____ annual budget before the board meeting.', '["the","—","an","a"]', 'the', 'annual budget 是特定文件，用 the。'),
(9, 'multiple_choice', 'This is _____ most efficient solution we''ve found.', '["a","an","—","the"]', 'the', '最高級前用 the。'),
(9, 'fill_blank', 'I met _____ client you recommended. He was very professional.', NULL, 'the', 'you recommended 使其特定化，用 the。'),
(9, 'multiple_choice', 'She gave _____ speech at _____ conference last week.', '["a / the","a / a","the / a","the / the"]', 'a / the', 'speech 首次提及用 a；conference 已知特定活動用 the。'),
(9, 'multiple_choice', '_____ new product launch was a great success.', '["The","An","—","A"]', 'The', '特定的新產品發表（已知事件），用 The。'),
(9, 'multiple_choice', 'Can you go over _____ proposal one more time?', '["the","an","a","—"]', 'the', '已知特定提案，用 the。'),
(9, 'transform', 'Our company has a headquarters. It is in Tokyo. (Use: the)', NULL, 'Our company''s headquarters is in the heart of Tokyo.', 'headquarters 特指，用 the。'),
(9, 'multiple_choice', 'We discussed _____ merger at _____ last board meeting.', '["the / a","the / the","a / a","a / the"]', 'the / the', '已知的合併案和上次的董事會議，均用 the。'),
(9, 'fill_blank', 'Could you book _____ meeting room on the third floor?', NULL, 'the', '特定的三樓會議室，用 the。'),
(9, 'multiple_choice', 'This is _____ first time we''ve worked with this supplier.', '["the","an","a","—"]', 'the', '第一次（序數概念），用 the first time。'),
(9, 'multiple_choice', '_____ finance team will present _____ results next Tuesday.', '["The / a","The / the","A / the","A / a"]', 'The / the', '已知部門和已知結果，均用 the。'),
(9, 'multiple_choice', 'It''s _____ best deal we''ve ever made.', '["the","an","a","—"]', 'the', '最高級 best 前用 the。'),
(9, 'fill_blank', 'We are aiming for _____ top position in _____ market.', NULL, 'the / the', 'top position 特指，market 已知特定市場，均用 the。'),
(9, 'multiple_choice', 'She is in charge of _____ Asia-Pacific region.', '["the","—","a","an"]', 'the', '地理區域名稱前通常用 the。'),
(9, 'multiple_choice', 'I''ll forward you _____ minutes of today''s meeting.', '["—","a","an","the"]', 'the', '特定的今天會議記錄，用 the。'),
(9, 'multiple_choice', 'We need _____ decision by Friday.', '["—","a","the","an"]', 'a', '首次提及，未特定的某個決定，用 a。'),
(9, 'transform', 'There is only one director of operations. (Use: the)', NULL, 'Please contact the director of operations regarding this issue.', '職稱加上唯一性，用 the。'),
(9, 'multiple_choice', '_____ productivity in our team has improved significantly.', '["An","—","The","A"]', 'The', '特指我們團隊的生產力，用 The。'),
(10, 'multiple_choice', 'She submitted _____ expense report this morning.', '["an","the","a","—"]', 'an', 'expense 以母音音素 /e/ 開頭，用 an。'),
(10, 'multiple_choice', 'We need to hire _____ experienced project manager.', '["the","an","—","a"]', 'an', 'experienced 以母音音素 /e/ 開頭，用 an。'),
(10, 'multiple_choice', 'He has _____ MBA from a top university.', '["an","a","the","—"]', 'an', 'MBA 發音 /em biː eɪ/，M 發母音音素，用 an。'),
(10, 'multiple_choice', 'Can you send _____ update by end of day?', '["—","the","an","a"]', 'an', 'update 以母音音素 /ʌ/ 開頭，用 an。'),
(10, 'multiple_choice', 'She made _____ excellent presentation to the board.', '["a","the","an","—"]', 'an', 'excellent 以母音音素 /e/ 開頭，用 an。'),
(10, 'fill_blank', 'We are looking for _____ office in _____ central location.', NULL, 'an / a', 'office 母音開頭 an；central 輔音開頭 a。'),
(10, 'multiple_choice', 'It was _____ unique opportunity that we couldn''t pass up.', '["—","a","the","an"]', 'a', 'unique 發音 /juːniːk/，以 /j/ 輔音音素開頭，用 a。'),
(10, 'multiple_choice', 'Please prepare _____ agenda for the meeting.', '["—","a","an","the"]', 'an', 'agenda 以母音音素 /æ/ 開頭，用 an。'),
(10, 'multiple_choice', 'He is _____ honest and dedicated employee.', '["—","an","a","the"]', 'an', 'honest 以母音音素 /ɒ/ 開頭（h 不發音），用 an。'),
(10, 'transform', 'Please write one report per week. (Use: a)', NULL, 'Please submit a report every week.', 'a 用於泛指一份報告。'),
(10, 'multiple_choice', 'That was _____ one-time offer.', '["—","the","an","a"]', 'a', 'one-time 發音 /wʌn/，以 /w/ 輔音音素開頭，用 a。'),
(10, 'multiple_choice', 'She gave _____ half-hour presentation.', '["the","—","an","a"]', 'a', 'half-hour 發音 /hɑːf/，以 /h/ 輔音音素開頭，用 a。'),
(10, 'fill_blank', 'It was _____ historic moment for our company.', NULL, 'a', 'historic 發音 /hɪˈstɒrɪk/，以 /h/ 開頭，用 a（英式有人用 an）。'),
(10, 'multiple_choice', 'He is _____ EU representative attending the summit.', '["a","—","an","the"]', 'a', 'EU 發音 /juː/，以 /j/ 輔音音素開頭，用 a。'),
(10, 'multiple_choice', 'We had _____ informal meeting with the client.', '["a","—","the","an"]', 'an', 'informal 以母音音素 /ɪ/ 開頭，用 an。'),
(10, 'multiple_choice', 'She received _____ award for outstanding performance.', '["—","the","a","an"]', 'an', 'award 以母音音素 /ə/ 開頭，用 an。'),
(10, 'fill_blank', 'This is _____ once-in-a-lifetime opportunity.', NULL, 'a', 'once 發音 /wʌns/，以 /w/ 輔音音素開頭，用 a。'),
(10, 'multiple_choice', 'He sent _____ urgent email to the entire team.', '["a","the","—","an"]', 'an', 'urgent 以母音音素 /ʌ/ 開頭，用 an。'),
(10, 'multiple_choice', 'She is _____ account manager at our firm.', '["an","the","a","—"]', 'an', 'account 以母音音素 /ə/ 開頭，用 an。'),
(10, 'multiple_choice', 'They issued _____ official statement this morning.', '["—","a","an","the"]', 'an', 'official 以母音音素 /ə/ 開頭，用 an。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(11, 'multiple_choice', '_____ information you need is on the company website.', '["A","The","—","An"]', 'The', '特定資訊（you need 限定），用 The。'),
(11, 'multiple_choice', 'She travels to _____ Japan every quarter for business.', '["an","—","a","the"]', '—', '國家名通常不加冠詞。'),
(11, 'multiple_choice', 'We communicate mostly by _____ email.', '["the","a","—","an"]', '—', 'by email 固定搭配，零冠詞。'),
(11, 'multiple_choice', '_____ managers are responsible for team performance.', '["The","A","—","An"]', '—', '泛指所有管理者，複數名詞泛稱，零冠詞。'),
(11, 'fill_blank', 'She goes to _____ work by subway every day.', NULL, '—（不加冠詞）', 'go to work 固定搭配，零冠詞。'),
(11, 'multiple_choice', '_____ knowledge is essential in today''s business world.', '["—","An","The","A"]', '—', 'knowledge 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'We had _____ lunch with the new partners.', '["an","the","—","a"]', '—', 'have lunch 固定搭配，零冠詞（也可 a business lunch）。'),
(11, 'multiple_choice', 'The company invested heavily in _____ technology last year.', '["the","a","—","an"]', '—', 'technology 不可數泛稱，零冠詞。'),
(11, 'transform', 'The advice from experts is valuable. (Use zero article for advice)', NULL, 'Advice from experts is always valuable in business.', 'advice 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'He is based in _____ New York.', '["a","the","—","an"]', '—', '城市名一般不加冠詞。'),
(11, 'multiple_choice', '_____ progress has been made on the project.', '["A","An","The","—"]', '—', 'progress 不可數泛稱，零冠詞（如要特指則用 The progress）。'),
(11, 'multiple_choice', 'Could you send the report by _____ post?', '["an","a","the","—"]', '—', 'by post 固定搭配，零冠詞。'),
(11, 'fill_blank', 'We need to improve _____ communication within the team.', NULL, '—（不加冠詞）', 'communication 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'She joined _____ Microsoft after graduating.', '["an","—","a","the"]', '—', '公司名專有名詞通常不加冠詞。'),
(11, 'multiple_choice', 'We are making _____ good progress on the project.', '["—","the","an","a"]', '—', 'make progress 固定搭配中，good progress 零冠詞。'),
(11, 'multiple_choice', 'He was promoted to _____ director last month.', '["—","a","the","an"]', '—', 'become/be appointed + 職稱，零冠詞。'),
(11, 'fill_blank', '_____ teamwork is crucial for project success.', NULL, '—（不加冠詞）', 'teamwork 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'The CEO went to _____ university in the UK.', '["a","—","the","an"]', '—', 'go to university 固定搭配，零冠詞。'),
(11, 'multiple_choice', '_____ automation is transforming the manufacturing industry.', '["An","The","—","A"]', '—', 'automation 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'We need to focus on _____ customer satisfaction.', '["—","an","the","a"]', '—', '泛指顧客滿意度，不可數概念，零冠詞。'),
(12, 'multiple_choice', 'The meeting is scheduled _____ 10 a.m.', '["on","in","at","by"]', 'at', '精確時間點用 at。'),
(12, 'multiple_choice', 'The product was launched _____ 2021.', '["on","by","in","at"]', 'in', '年份用 in。'),
(12, 'multiple_choice', 'We have a client call _____ Tuesday.', '["on","at","by","in"]', 'on', '星期幾用 on。'),
(12, 'multiple_choice', 'I''ll send you the report _____ the morning.', '["at","by","on","in"]', 'in', 'the morning/afternoon/evening 用 in。'),
(12, 'fill_blank', 'The contract expires _____ March 31st.', NULL, 'on', '特定日期用 on。'),
(12, 'multiple_choice', 'She joined the company _____ January.', '["in","at","by","on"]', 'in', '月份用 in。'),
(12, 'multiple_choice', 'The office opens _____ 9 o''clock.', '["at","by","in","on"]', 'at', '精確時間點用 at。'),
(12, 'multiple_choice', 'We should finalize the deal _____ the end of the month.', '["in","at","on","by"]', 'by', 'deadline 截止日期用 by。'),
(12, 'transform', 'The conference happens in the third week of August. (Use: on)', NULL, 'The conference is on August 18th.', '具體日期用 on。'),
(12, 'multiple_choice', 'The project started _____ the summer.', '["at","on","by","in"]', 'in', 'the summer 季節用 in。'),
(12, 'multiple_choice', 'She usually works late _____ Fridays.', '["at","by","on","in"]', 'on', '星期幾用 on。'),
(12, 'fill_blank', 'The team meeting is _____ noon every Wednesday.', NULL, 'at', 'noon 是特定時間點，用 at。'),
(12, 'multiple_choice', 'The deal was signed _____ midnight.', '["at","in","on","by"]', 'at', 'midnight 是精確時間點，用 at。'),
(12, 'multiple_choice', 'Our fiscal year ends _____ December.', '["at","on","in","by"]', 'in', '月份用 in。'),
(12, 'multiple_choice', 'He was promoted _____ 2023.', '["by","on","in","at"]', 'in', '年份用 in。'),
(12, 'fill_blank', 'The workshop is scheduled _____ the afternoon of June 5th.', NULL, 'on the afternoon of', '特定日期的下午用 on the afternoon of。'),
(12, 'multiple_choice', 'She will return from leave _____ Monday morning.', '["in","by","at","on"]', 'on', 'Monday morning 特定時間組合用 on。'),
(12, 'multiple_choice', 'The proposal is due _____ the end of this week.', '["on","in","at","by"]', 'by', 'due 截止用 by。'),
(12, 'multiple_choice', 'We met _____ a conference in Singapore _____ 2022.', '["at / in","in / in","on / in","at / at"]', 'at / in', 'conference 地點 at；year 用 in。'),
(12, 'multiple_choice', 'The company was founded _____ the early 1990s.', '["by","in","at","on"]', 'in', 'decade 用 in the 1990s。'),
(13, 'multiple_choice', 'The manager is _____ her office right now.', '["on","at","in","by"]', 'in', 'office 是封閉空間，用 in。'),
(13, 'multiple_choice', 'Please meet me _____ the reception desk.', '["by","in","at","on"]', 'at', 'reception desk 是功能性地點，用 at。'),
(13, 'multiple_choice', 'The documents are _____ the table.', '["in","at","by","on"]', 'on', 'table 是表面，用 on。'),
(13, 'multiple_choice', 'Our headquarters is _____ London.', '["on","by","in","at"]', 'in', '城市用 in。'),
(13, 'fill_blank', 'The printer is _____ the third floor.', NULL, 'on', 'floor 樓層用 on。'),
(13, 'multiple_choice', 'She is _____ a business trip.', '["by","in","on","at"]', 'on', 'on a business trip 固定搭配。'),
(13, 'multiple_choice', 'I''ll see you _____ the conference center.', '["at","by","on","in"]', 'at', 'conference center 功能性地點，用 at。'),
(13, 'multiple_choice', 'The logo is _____ the top of the page.', '["on","in","by","at"]', 'at', 'at the top 指頂部位置。'),
(13, 'fill_blank', 'Can you post it _____ the notice board?', NULL, 'on', 'notice board 是表面，用 on。'),
(13, 'multiple_choice', 'The product details are listed _____ page 10.', '["in","at","by","on"]', 'on', 'page 頁面用 on。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(13, 'multiple_choice', 'She is waiting _____ the entrance.', '["on","by","in","at"]', 'at', 'entrance 功能性地點，用 at。'),
(13, 'multiple_choice', 'There''s a typo _____ paragraph three.', '["in","at","on","by"]', 'in', 'paragraph 段落用 in。'),
(13, 'multiple_choice', 'He works _____ a large corporation _____ the city centre.', '["for / at","at / at","for / in","at / in"]', 'for / in', 'work for 公司；city centre 地區 in。'),
(13, 'transform', 'The error is located at line 5 of the report. (Use: on)', NULL, 'The error is on line 5 of the report.', 'line 行用 on。'),
(13, 'fill_blank', 'Please put your signature _____ the dotted line.', NULL, 'on', 'dotted line 是線（表面），用 on。'),
(13, 'multiple_choice', 'The annual report is _____ the website.', '["in","by","on","at"]', 'on', 'website 用 on。'),
(13, 'multiple_choice', 'She arrived _____ the airport at 6 a.m.', '["by","in","on","at"]', 'at', 'airport 功能性地點，用 at。'),
(13, 'multiple_choice', 'The branch is located _____ the financial district.', '["on","in","at","by"]', 'in', 'district 地區，用 in。'),
(13, 'fill_blank', 'The meeting notes are _____ the shared drive.', NULL, 'in', 'shared drive 是虛擬空間，用 in。'),
(13, 'multiple_choice', 'He is _____ a meeting and cannot be disturbed.', '["by","at","in","on"]', 'in', 'in a meeting 固定搭配。'),
(14, 'multiple_choice', 'She walked _____ the conference room without knocking.', '["into","onto","in","to"]', 'into', 'into 表從外進入，walked into 進入會議室。'),
(14, 'multiple_choice', 'He traveled _____ Singapore for the trade fair.', '["into","toward","to","onto"]', 'to', 'to 表目的地，traveled to Singapore。'),
(14, 'multiple_choice', 'The new employee walked _____ the office on her first day.', '["through","to","in","into"]', 'into', 'walked into 進入辦公室。'),
(14, 'multiple_choice', 'The CEO walked _____ the building past the reception area.', '["across","into","through","along"]', 'through', 'through 表穿越整個空間，walked through。'),
(14, 'fill_blank', 'She drove _____ the tunnel to get to the airport.', NULL, 'through', 'through 穿越隧道。'),
(14, 'multiple_choice', 'The delivery van drove _____ the warehouse district.', '["across","into","along","through"]', 'through', 'through 穿越區域。'),
(14, 'multiple_choice', 'Please walk _____ the corridor to find the HR office.', '["through","along","past","into"]', 'along', 'along 沿著走廊走。'),
(14, 'multiple_choice', 'The manager moved her desk _____ the window.', '["onto","to","into","toward"]', 'to', 'moved to 移到某地點。'),
(14, 'transform', 'He entered the meeting room. (Use: walked into)', NULL, 'He walked into the meeting room.', 'walked into 表進入的動作。'),
(14, 'multiple_choice', 'She ran _____ the street to catch a taxi.', '["through","across","into","along"]', 'across', 'across 橫越街道。'),
(14, 'multiple_choice', 'The courier went _____ the building to make the delivery.', '["to","through","past","into"]', 'into', 'into 進入建築物。'),
(14, 'fill_blank', 'We drove _____ the new factory on our way to the airport.', NULL, 'past', 'past 表經過某地點。'),
(14, 'multiple_choice', 'The document was passed _____ the table.', '["along","into","through","across"]', 'across', 'passed across 從桌子一端傳到另一端。'),
(14, 'multiple_choice', 'She took the elevator _____ the parking garage.', '["onto","into","to","through"]', 'to', 'to 表目的地樓層或地點。'),
(14, 'multiple_choice', 'The goods were shipped _____ several distribution centers.', '["through","to","into","across"]', 'through', 'through 表中轉經過幾個中心。'),
(14, 'fill_blank', 'Could you bring the files _____ my office?', NULL, 'to', 'bring to 帶到某地。'),
(14, 'multiple_choice', 'He walked _____ the podium to begin his keynote.', '["across","into","to","onto"]', 'to', 'walked to 走向講台（onto 也可用於上台）。'),
(14, 'multiple_choice', 'The intern hurried _____ the corridor to deliver the report.', '["through","along","across","into"]', 'along', 'along 沿走廊快走。'),
(14, 'multiple_choice', 'The new manager was moved _____ the Tokyo branch.', '["to","through","onto","into"]', 'to', 'moved to 調派到東京分部。'),
(14, 'multiple_choice', 'She glanced _____ the street before crossing.', '["through","along","across","into"]', 'across', 'across 橫過，glanced across 朝對面看。'),
(15, 'multiple_choice', 'She is responsible _____ managing the entire supply chain.', '["of","for","to","with"]', 'for', 'responsible for 負責，固定搭配。'),
(15, 'multiple_choice', 'Are you familiar _____ our company''s return policy?', '["of","with","to","about"]', 'with', 'familiar with 熟悉，固定搭配。'),
(15, 'multiple_choice', 'The team was satisfied _____ the outcome of the negotiation.', '["of","by","about","with"]', 'with', 'satisfied with 對...滿意，固定搭配。'),
(15, 'multiple_choice', 'He is interested _____ exploring new markets in Southeast Asia.', '["for","with","about","in"]', 'in', 'interested in 對...感興趣，固定搭配。'),
(15, 'fill_blank', 'She is very good _____ managing difficult clients.', NULL, 'at', 'good at 擅長，固定搭配。'),
(15, 'multiple_choice', 'We are committed _____ delivering the highest quality service.', '["to","with","for","in"]', 'to', 'committed to 致力於，固定搭配。'),
(15, 'multiple_choice', 'He was disappointed _____ the quarterly results.', '["in","with","about","by"]', 'with', 'disappointed with/in 對...失望，均可用。'),
(15, 'multiple_choice', 'The CFO is worried _____ the rising operational costs.', '["with","of","for","about"]', 'about', 'worried about 擔心，固定搭配。'),
(15, 'transform', 'He has awareness of the risks. (Use: aware of)', NULL, 'He is aware of the risks involved in this project.', 'aware of 知道，固定搭配。'),
(15, 'multiple_choice', 'Our company is capable _____ handling large-scale projects.', '["to","of","for","with"]', 'of', 'capable of 有能力，固定搭配。'),
(15, 'multiple_choice', 'The client was impressed _____ our presentation.', '["about","by","with","of"]', 'by', 'impressed by/with 均可，by 更強調感受來源。'),
(15, 'fill_blank', 'She is enthusiastic _____ the new marketing initiative.', NULL, 'about', 'enthusiastic about 對...充滿熱情，固定搭配。'),
(15, 'multiple_choice', 'We are concerned _____ the delay in delivery.', '["about","of","with","for"]', 'about', 'concerned about 擔憂，固定搭配。'),
(15, 'multiple_choice', 'He is not suitable _____ this position.', '["for","of","with","to"]', 'for', 'suitable for 適合，固定搭配。'),
(15, 'multiple_choice', 'The manager was very strict _____ punctuality.', '["with","of","about","for"]', 'about', 'strict about 嚴格要求，固定搭配。'),
(15, 'fill_blank', 'Our team is very proud _____ this achievement.', NULL, 'of', 'proud of 對...感到驕傲，固定搭配。'),
(15, 'multiple_choice', 'She is very skilled _____ data analysis.', '["for","at","with","in"]', 'at', 'skilled at 擅長，固定搭配（skilled in 也可）。'),
(15, 'multiple_choice', 'The company is based _____ Singapore.', '["in","at","on","for"]', 'in', 'based in 總部設於，固定搭配。'),
(15, 'multiple_choice', 'He is tired _____ attending endless meetings.', '["from","with","about","of"]', 'of', 'tired of 厭倦，固定搭配。'),
(15, 'multiple_choice', 'The team is fully dedicated _____ completing this project.', '["with","for","in","to"]', 'to', 'dedicated to 獻身於，固定搭配。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(16, 'multiple_choice', 'We applied _____ a government grant to fund the project.', '["to","for","in","with"]', 'for', 'apply for 申請，固定搭配。'),
(16, 'multiple_choice', 'She deals _____ customer complaints on a daily basis.', '["with","in","for","about"]', 'with', 'deal with 處理，固定搭配。'),
(16, 'multiple_choice', 'Our success relies _____ the dedication of our team members.', '["in","with","on","for"]', 'on', 'rely on 依賴，固定搭配。'),
(16, 'multiple_choice', 'The company is investing _____ renewable energy infrastructure.', '["into","in","for","on"]', 'in', 'invest in 投資於，固定搭配。'),
(16, 'fill_blank', 'He agreed _____ the proposed changes to the contract.', NULL, 'to', 'agree to (proposal/change) 同意某事，固定搭配。'),
(16, 'multiple_choice', 'We need to comply _____ all local safety regulations.', '["for","by","to","with"]', 'with', 'comply with 遵守，固定搭配。'),
(16, 'multiple_choice', 'She specializes _____ international trade law.', '["in","for","with","on"]', 'in', 'specialize in 專門從事，固定搭配。'),
(16, 'multiple_choice', 'The manager apologized _____ the miscommunication.', '["with","to","for","about"]', 'for', 'apologize for 為...道歉，固定搭配。'),
(16, 'transform', 'He contributes money to the charity fund. (Use: contributes to)', NULL, 'He contributes to the company''s success every day.', 'contribute to 貢獻於，固定搭配。'),
(16, 'multiple_choice', 'We are looking _____ a new distribution partner.', '["at","after","into","for"]', 'for', 'look for 尋找，固定搭配。'),
(16, 'multiple_choice', 'She reported _____ the regional director every week.', '["on","for","to","with"]', 'to', 'report to 向...匯報，固定搭配。'),
(16, 'fill_blank', 'The company prides itself _____ excellent customer service.', NULL, 'on', 'pride oneself on 以...自豪，固定搭配。'),
(16, 'multiple_choice', 'He is responsible _____ a team of 15 engineers.', '["for","with","to","of"]', 'for', 'responsible for 負責，固定搭配。'),
(16, 'multiple_choice', 'We should focus _____ improving client retention rates.', '["with","on","in","for"]', 'on', 'focus on 專注於，固定搭配。'),
(16, 'multiple_choice', 'The team succeeded _____ launching the product on schedule.', '["at","with","in","for"]', 'in', 'succeed in 成功地做到，固定搭配。'),
(16, 'fill_blank', 'Could you elaborate _____ the cost-saving measures?', NULL, 'on', 'elaborate on 詳細說明，固定搭配。'),
(16, 'multiple_choice', 'Our policy prohibits us _____ sharing confidential data.', '["for","from","with","of"]', 'from', 'prohibit from 禁止，固定搭配。'),
(16, 'multiple_choice', 'She tends _____ work long hours before major deadlines.', '["to","with","toward","for"]', 'to', 'tend to 傾向於，固定搭配。'),
(16, 'multiple_choice', 'We are considering _____ expanding to new markets.', '["—","on","about","for"]', '—', 'consider + V-ing 直接接動名詞，不需介系詞。'),
(16, 'multiple_choice', 'He objected _____ the proposed budget cuts.', '["to","about","with","for"]', 'to', 'object to 反對，固定搭配。'),
(17, 'multiple_choice', 'If you _____ the invoice, we will process your order immediately.', '["send","sending","will send","sent"]', 'send', 'if 子句用現在式；send 正確。'),
(17, 'multiple_choice', 'If demand increases, prices generally _____.', '["are rising","rose","will rise","rise"]', 'rise', '零條件句：普遍規律，兩個現在式。'),
(17, 'multiple_choice', 'If she _____ the interview, she will get the job.', '["will pass","passes","passed","passing"]', 'passes', 'if 子句現在式 passes，主句 will get。'),
(17, 'fill_blank', 'If we _____ (not / reduce) costs, the project will go over budget.', NULL, 'do not reduce', 'if 子句現在式，否定 do not reduce。'),
(17, 'multiple_choice', 'If you heat water to 100°C, it _____.', '["will boil","boiled","is boiling","boils"]', 'boils', '零條件句：科學事實，兩個現在式。'),
(17, 'multiple_choice', 'We will lose the client if we _____ to respond quickly.', '["are failing","failed","will fail","fail"]', 'fail', 'if 子句現在式 fail，主句 will lose。'),
(17, 'multiple_choice', 'If the team _____ the target, they will receive a bonus.', '["met","will meet","meets","is meeting"]', 'meets', 'if 子句現在式 meets，主句 will receive。'),
(17, 'transform', 'We might expand if we secure funding. (Use: will expand if we secure)', NULL, 'We will expand into new markets if we secure the necessary funding.', '第一條件句：will + if + 現在式。'),
(17, 'multiple_choice', 'If you press this button, the printer _____.', '["started","will start","is starting","starts"]', 'starts', '零條件句：操作指示，兩個現在式。'),
(17, 'fill_blank', 'If the weather _____ (be) good, the outdoor event will go ahead.', NULL, 'is', 'if 子句現在式 is，天氣預測。'),
(17, 'multiple_choice', 'If the client _____ by Friday, we will cancel the order.', '["will not confirm","has not confirmed","did not confirm","does not confirm"]', 'does not confirm', 'if 子句現在式否定 does not confirm。'),
(17, 'multiple_choice', 'Temperatures _____ if greenhouse gas emissions continue to rise.', '["will increase","increased","increase","are increasing"]', 'will increase', '第一條件句主句用 will increase 預測。'),
(17, 'multiple_choice', 'If you _____ your password, you can reset it online.', '["will forget","forgot","are forgetting","forget"]', 'forget', 'if 子句現在式 forget，零條件句操作說明。'),
(17, 'fill_blank', 'If the proposal _____ (approve) this week, work will begin immediately.', NULL, 'is approved', 'if 子句被動現在式 is approved。'),
(17, 'multiple_choice', 'She _____ the project if she gets the approval.', '["is managing","manages","managed","will manage"]', 'will manage', '主句 will manage，第一條件句。'),
(17, 'multiple_choice', 'If you _____ any questions, please contact our helpdesk.', '["have","will have","had","are having"]', 'have', 'if 子句現在式 have。'),
(17, 'transform', 'Assuming we sign the contract, we start next month. (Use: If we sign)', NULL, 'If we sign the contract this week, we will start next month.', '第一條件句：if + 現在式，will + 原形。'),
(17, 'fill_blank', 'If you _____ (not / leave) now, you will miss the train.', NULL, 'do not leave', 'if 子句否定現在式。'),
(17, 'multiple_choice', 'If the market _____ as expected, returns will be strong.', '["performs","performed","will perform","is performing"]', 'performs', 'if 子句現在式 performs。'),
(17, 'multiple_choice', 'Employees receive overtime pay if they _____ more than 40 hours a week.', '["work","worked","are working","will work"]', 'work', '零條件句：公司政策，兩個現在式。'),
(18, 'multiple_choice', 'If I _____ the manager, I would restructure the team.', '["were","am","was","be"]', 'were', '正式英語 if I were 用 were，第二條件句。'),
(18, 'multiple_choice', 'If we _____ more resources, we could finish ahead of schedule.', '["have","will have","had","would have"]', 'had', 'if 子句過去式 had，第二條件句。'),
(18, 'multiple_choice', 'She would apply for the promotion if she _____ more confident.', '["were","would be","was","is"]', 'were', '正式英語 if she were，第二條件句。'),
(18, 'fill_blank', 'If our pricing _____ (be) more competitive, we would win more clients.', NULL, 'were', '第二條件句 if 子句用 were。'),
(18, 'multiple_choice', 'What would you do if you _____ in charge?', '["were","are","would be","will be"]', 'were', 'if you were in charge 第二條件句 were。'),
(18, 'multiple_choice', 'If they _____ the investment, the company would expand faster.', '["increase","will increase","increased","would increase"]', 'increased', 'if 子句過去式 increased，主句 would expand。'),
(18, 'transform', 'We can''t reduce costs without cutting staff. (Use: If we could)', NULL, 'If we could reduce costs without cutting staff, we would do it immediately.', '第二條件句：假設我們有能力做到。'),
(18, 'multiple_choice', 'If the market _____ differently, we would need a new strategy.', '["behaves","would behave","will behave","behaved"]', 'behaved', 'if 子句過去式 behaved，第二條件句假設。'),
(18, 'fill_blank', 'I would attend the conference if I _____ (not / be) so busy.', NULL, 'were not', '第二條件句 if I were not，正式英語。'),
(18, 'multiple_choice', 'If the client _____ more time, we could deliver a better product.', '["would give","will give","gave","gives"]', 'gave', 'if 子句過去式 gave，第二條件句。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(18, 'multiple_choice', 'She would be able to lead the project if she _____ more experience.', '["had","will have","has","would have"]', 'had', 'if 子句過去式 had，第二條件句。'),
(18, 'multiple_choice', 'If we _____ a bigger budget, we could run a global campaign.', '["have","will have","would have","had"]', 'had', 'if 子句 had，第二條件句假設更多預算。'),
(18, 'transform', 'We don''t have time, so we can''t review everything. (Use: If we had)', NULL, 'If we had more time, we would review every aspect of the proposal.', '第二條件句假設有時間的情況。'),
(18, 'fill_blank', 'What would you recommend if you _____ (be) the consultant?', NULL, 'were', '正式第二條件句，if you were。'),
(18, 'multiple_choice', 'If the headquarters _____ in Asia, travel costs would be lower.', '["would be","is","was","were"]', 'were', 'if 子句 were，正式第二條件句。'),
(18, 'multiple_choice', 'He would accept the offer if the salary _____ higher.', '["is","would be","was","were"]', 'were', 'if the salary were 第二條件句正式用法。'),
(18, 'multiple_choice', 'If I _____ you, I would focus on client retention.', '["would be","am","were","was"]', 'were', 'If I were you 建議句型。'),
(18, 'fill_blank', 'If the partnership _____ (be) confirmed, we would announce it immediately.', NULL, 'were', '第二條件句 if 子句用 were。'),
(18, 'multiple_choice', 'The project would take less time if we _____ more staff.', '["hired","will hire","would hire","hire"]', 'hired', 'if 子句過去式 hired。'),
(18, 'multiple_choice', 'If they _____ the deal, it would be a major milestone.', '["secured","secure","would secure","will secure"]', 'secured', 'if 子句過去式 secured，第二條件句。'),
(19, 'multiple_choice', 'If we _____ earlier, we would have captured the market.', '["invested","have invested","had invested","would invest"]', 'had invested', 'if 子句過去完成式 had invested，第三條件句。'),
(19, 'multiple_choice', 'She would have got the promotion if she _____ the project.', '["has completed","would complete","completed","had completed"]', 'had completed', 'if 子句 had completed，第三條件句。'),
(19, 'fill_blank', 'If the team _____ (communicate) better, the misunderstanding would not have occurred.', NULL, 'had communicated', '第三條件句 if 子句 had communicated。'),
(19, 'multiple_choice', 'We would have met the deadline if there _____ no supply chain issues.', '["had been","was","had have","were"]', 'had been', 'if 子句 had been，第三條件句被動條件。'),
(19, 'multiple_choice', 'If I _____ the email earlier, I would have responded in time.', '["had seen","have seen","would see","saw"]', 'had seen', 'if 子句 had seen，第三條件句。'),
(19, 'multiple_choice', 'The project would have succeeded if we _____ a better team.', '["had assembled","have assembled","would assemble","assembled"]', 'had assembled', 'if 子句 had assembled，第三條件句。'),
(19, 'transform', 'We didn''t launch early enough. That''s why we lost market share. (Use: If we had launched)', NULL, 'If we had launched the product earlier, we would have gained more market share.', '第三條件句反思過去決策。'),
(19, 'fill_blank', 'If the budget _____ (approve) earlier, we would have started sooner.', NULL, 'had been approved', '第三條件句被動 had been approved。'),
(19, 'multiple_choice', 'She wouldn''t have resigned if she _____ a pay rise.', '["received","has received","had received","would receive"]', 'had received', 'if 子句 had received，第三條件句。'),
(19, 'multiple_choice', 'If the negotiations _____ longer, we might have reached a better deal.', '["would last","had lasted","have lasted","lasted"]', 'had lasted', 'if 子句 had lasted，第三條件句。'),
(19, 'multiple_choice', 'We _____ more if we had targeted a different demographic.', '["had sold","would have sold","sold","would sell"]', 'would have sold', '主句 would have sold，第三條件句結果。'),
(19, 'fill_blank', 'If they _____ (accept) our initial proposal, the project would have started in Q1.', NULL, 'had accepted', '第三條件句 if 子句 had accepted。'),
(19, 'multiple_choice', 'He would have attended the summit if he _____ been invited.', '["has","had","was","would have"]', 'had', 'if 子句 had been，第三條件句。'),
(19, 'transform', 'The deal fell through because we lacked preparation. (Use: If we had prepared)', NULL, 'If we had prepared more thoroughly, the deal would not have fallen through.', '第三條件句反思準備不足。'),
(19, 'multiple_choice', 'If the system _____ down, we would have lost all the data.', '["would crash","had crashed","has crashed","crashed"]', 'had crashed', 'if 子句 had crashed，第三條件句。'),
(19, 'multiple_choice', 'She would have become CEO if she _____ at the company longer.', '["would stay","has stayed","stayed","had stayed"]', 'had stayed', 'if 子句 had stayed，第三條件句。'),
(19, 'fill_blank', 'If we _____ (hire) more staff, we would not have missed the deadline.', NULL, 'had hired', '第三條件句 if 子句 had hired。'),
(19, 'multiple_choice', 'The launch would have been more successful if we _____ the market properly.', '["researched","had researched","would research","have researched"]', 'had researched', 'if 子句 had researched，第三條件句。'),
(19, 'multiple_choice', 'If I _____ the job offer, I would have moved to London.', '["accepted","would accept","had accepted","have accepted"]', 'had accepted', 'if 子句 had accepted，第三條件句。'),
(19, 'multiple_choice', 'They wouldn''t have run out of stock if they _____ demand correctly.', '["have forecast","had forecast","would forecast","forecast"]', 'had forecast', 'if 子句 had forecast，第三條件句。'),
(20, 'multiple_choice', 'If I _____ that job offer in 2020, I would be in New York now.', '["took","would take","had taken","take"]', 'had taken', 'if 子句 had taken（過去假設），主句 would be（現在結果）。'),
(20, 'multiple_choice', 'She would already be a director if she _____ the promotion.', '["accepts","accepted","had accepted","would accept"]', 'had accepted', '混合條件：had accepted 過去，would be 現在。'),
(20, 'fill_blank', 'If we _____ (invest) in that startup, we would be much wealthier now.', NULL, 'had invested', '混合條件：had invested 過去，would be 現在。'),
(20, 'multiple_choice', 'If the project _____ failed, the company would be in a much worse position today.', '["didn''t","wouldn''t have","had not","hasn''t"]', 'had not', 'had not failed（過去完成式否定），would be（現在）。'),
(20, 'multiple_choice', 'He wouldn''t be so stressed now if he _____ better at delegating.', '["were","would have been","had been","was"]', 'had been', '混合條件：had been 過去，wouldn''t be 現在。'),
(20, 'multiple_choice', 'If I _____ that business partnership, we might be global leaders today.', '["had not turned down","hadn''t turned down","didn''t turn down","won''t turn down"]', 'had not turned down', 'had not turned down 過去完成式否定。'),
(20, 'transform', 'We made a bad decision last year. That''s why we''re struggling now. (Use mixed conditional)', NULL, 'If we had made a better decision last year, we would not be struggling now.', '混合條件反思過去決策的現在影響。'),
(20, 'fill_blank', 'If she _____ (not / resign) last year, she would still be working here.', NULL, 'had not resigned', '混合條件：had not resigned 過去，would be 現在。'),
(20, 'multiple_choice', 'If the market _____ crashed in 2020, our investment would be thriving now.', '["wouldn''t have","didn''t","had not","hasn''t"]', 'had not', 'had not crashed 過去完成否定，would be thriving 現在結果。'),
(20, 'multiple_choice', 'He would be more fluent in English now if he _____ his studies earlier.', '["would start","has started","started","had started"]', 'had started', '混合條件：had started 過去，would be 現在。'),
(20, 'multiple_choice', 'If we _____ diversified earlier, we would be less vulnerable to market changes now.', '["had","have","did","would have"]', 'had', 'had diversified 過去完成，would be 現在結果。'),
(20, 'fill_blank', 'If they _____ (choose) a different supplier, delivery would not be an issue now.', NULL, 'had chosen', '混合條件：had chosen 過去假設，would not be 現在影響。'),
(20, 'multiple_choice', 'She wouldn''t have so many responsibilities now if she _____ every opportunity.', '["won''t seize","hadn''t seized","didn''t seize","hasn''t seized"]', 'hadn''t seized', '混合條件：hadn''t seized 過去，wouldn''t have 現在。'),
(20, 'multiple_choice', 'If the team _____ the right tools from the start, we would be much further along.', '["would use","had used","was using","used"]', 'had used', '混合條件：had used 過去，would be 現在。'),
(20, 'transform', 'He spent too much on advertising. Now the budget is tight. (Use mixed conditional)', NULL, 'If he had not spent so much on advertising, the budget would not be so tight now.', '混合條件：had not spent 過去，would not be 現在。'),
(20, 'fill_blank', 'If we _____ (build) that factory, our capacity would be double what it is today.', NULL, 'had built', '混合條件：had built 過去假設，would be 現在。'),
(20, 'multiple_choice', 'She might be fluent in Japanese now if she _____ the language course.', '["had completed","has completed","completed","would complete"]', 'had completed', '混合條件：had completed 過去，might be 現在。'),
(20, 'multiple_choice', 'If I _____ the networking event, I would already know the key clients.', '["had attended","have attended","attended","would attend"]', 'had attended', '混合條件：had attended 過去，would know 現在。'),
(20, 'fill_blank', 'The company _____ (be) more profitable now if they had controlled costs earlier.', NULL, 'would be', '混合條件主句：would be 現在結果。'),
(20, 'multiple_choice', 'If she _____ taken that scholarship, she would have a much stronger network now.', '["had","would have","has","was"]', 'had', 'had taken 過去，would have 現在。');