INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(3, 'multiple_choice', 'The report _____ not been submitted yet.', '["have","has","had","was"]', 'has', 'report 單數，has not been submitted yet。'),
(3, 'fill_blank', 'How long _____ you _____ (be) in this role?', NULL, 'have / been', 'How long + have + 主詞 + been 問持續時間。'),
(3, 'multiple_choice', 'Our new policy _____ already _____ results.', '["has / produced","is / producing","have / produced","had / produced"]', 'has / produced', 'already 搭配現在完成式，policy 單數 has。'),
(3, 'multiple_choice', 'She _____ three conferences this year.', '["attends","was attending","has attended","attended"]', 'has attended', 'this year 到目前，現在完成式。'),
(3, 'transform', 'I have never visited Seoul. (Use: first time)', NULL, 'This is the first time I have visited Seoul.', 'first time + 現在完成式表達首次經驗。'),
(3, 'fill_blank', 'The board _____ (approve) the proposal this morning.', NULL, 'has approved', 'this morning 仍在今天，has approved。'),
(3, 'multiple_choice', 'Sales _____ doubled since the campaign launched.', '["have","had","has","are"]', 'have', 'Sales 複數，have doubled。'),
(3, 'multiple_choice', 'I _____ just _____ an email from the client.', '["did / receive","had / received","have / received","was / receiving"]', 'have / received', 'just 搭配現在完成式。'),
(3, 'multiple_choice', 'The team _____ the prototype three times this week.', '["has tested","tested","was testing","test"]', 'has tested', 'this week 到目前，has tested。'),
(3, 'multiple_choice', 'She _____ not yet _____ the draft contract.', '["has / finalized","did / finalize","had / finalized","is / finalizing"]', 'has / finalized', 'not yet 搭配現在完成式 has not finalized。'),
(4, 'multiple_choice', 'I _____ the report an hour ago.', '["have submitted","submit","submitted","was submitting"]', 'submitted', 'an hour ago 過去時間點，過去簡單式 submitted。'),
(4, 'multiple_choice', 'We _____ our target this quarter so far.', '["were exceeding","exceed","exceeded","have exceeded"]', 'have exceeded', 'so far 到現在，現在完成式 have exceeded。'),
(4, 'multiple_choice', 'She _____ the company in 2015.', '["join","joined","had joined","has joined"]', 'joined', 'in 2015 明確過去，過去簡單式 joined。'),
(4, 'fill_blank', 'Have you _____ (send) the invoice yet?', NULL, 'sent', 'yet 搭配現在完成式，sent 是 send 的過去分詞。'),
(4, 'multiple_choice', 'The last product launch _____ very successful.', '["has been","were","was","is"]', 'was', 'last product launch 過去特定事件，was。'),
(4, 'multiple_choice', 'The company _____ three offices since 2010.', '["opens","has opened","opened","was opening"]', 'has opened', 'since 2010 到現在，has opened。'),
(4, 'fill_blank', 'We _____ (not / receive) any feedback yet.', NULL, 'have not received', 'yet 否定句搭配現在完成式。'),
(4, 'multiple_choice', 'Did you _____ the presentation last Tuesday?', '["delivering","delivered","deliver","have delivered"]', 'deliver', 'Did you + 原形動詞，過去式疑問句。'),
(4, 'transform', 'The price dropped and is still low for three months. (Use: has dropped)', NULL, 'The price has dropped and has remained low for three months.', '現在完成式強調持續到現在的結果。'),
(4, 'multiple_choice', 'This is the third time he _____ late this month.', '["is","had been","has been","was"]', 'has been', 'this month 到現在累積，has been。'),
(4, 'multiple_choice', 'The auditors _____ the accounts last week.', '["were checking","have checked","checked","check"]', 'checked', 'last week 明確過去，過去簡單式 checked。'),
(4, 'fill_blank', 'How many deals _____ the team _____ (close) this quarter?', NULL, 'has / closed', 'this quarter 到目前，現在完成式疑問句。'),
(4, 'multiple_choice', 'We _____ a new office in Berlin last year.', '["open","had opened","have opened","opened"]', 'opened', 'last year 明確過去，過去簡單式 opened。'),
(4, 'multiple_choice', 'Our profits _____ significantly since we restructured.', '["have grown","are growing","grew","grow"]', 'have grown', 'since 搭配現在完成式 have grown。'),
(4, 'transform', 'I lost the contract six months ago. (Use: ago)', NULL, 'I lost the contract six months ago.', 'ago 搭配過去簡單式。'),
(4, 'fill_blank', 'The CEO _____ (step down) last Friday.', NULL, 'stepped down', 'last Friday 明確過去，過去簡單式 stepped down。'),
(4, 'multiple_choice', 'They _____ never _____ such strong demand before.', '["did / see","were / seeing","have / seen","had / seen"]', 'have / seen', 'never + 現在完成式表從未有的經驗。'),
(4, 'multiple_choice', 'When _____ the merger _____?', '["had / happened","has / happened","did / happen","was / happening"]', 'did / happen', 'When 問明確時間，過去簡單式疑問句。'),
(4, 'fill_blank', 'We _____ (partner) with three new suppliers since January.', NULL, 'have partnered', 'since January 到現在，現在完成式。'),
(4, 'multiple_choice', 'I _____ him at the trade fair in April.', '["meet","was meeting","met","have met"]', 'met', 'in April 過去時間點，過去簡單式 met。'),
(5, 'multiple_choice', 'By the time the client arrived, we _____ all the documents.', '["have prepared","were preparing","had prepared","prepared"]', 'had prepared', 'by the time 建立先後，had prepared 在到達前完成。'),
(5, 'multiple_choice', 'She realized she _____ the wrong file.', '["was sending","has sent","had sent","sent"]', 'had sent', 'realized 在過去，發送更早，過去完成式 had sent。'),
(5, 'fill_blank', 'Before the meeting started, the team _____ (review) the agenda.', NULL, 'had reviewed', 'before 表先後，更早的動作用過去完成式。'),
(5, 'multiple_choice', 'When I arrived, the presentation _____ already _____.', '["had / started","has / started","did / start","was / starting"]', 'had / started', 'already + 過去完成式；had started。'),
(5, 'multiple_choice', 'He _____ never _____ such a complex contract before.', '["was / negotiating","did / negotiate","had / negotiated","has / negotiated"]', 'had / negotiated', 'never + 過去完成式表從未有的經驗。'),
(5, 'transform', 'First we submitted. Then we received approval. (Use: had submitted)', NULL, 'We had submitted the proposal before we received approval.', 'had submitted 描述更早的動作。'),
(5, 'multiple_choice', 'By the end of Q3, we _____ the annual target.', '["were exceeding","exceeded","had exceeded","have exceeded"]', 'had exceeded', 'by the end of Q3 設定過去時間點，had exceeded。'),
(5, 'fill_blank', 'The client _____ (already / sign) the NDA before the first meeting.', NULL, 'had already signed', 'before 連接兩個過去事件，更早用過去完成式。'),
(5, 'multiple_choice', 'I discovered that my colleague _____ the same research.', '["conducted","was conducting","has conducted","had conducted"]', 'had conducted', 'discovered 過去，研究更早，had conducted。'),
(5, 'multiple_choice', 'They _____ the merger long before it was announced.', '["had planned","were planning","planned","have planned"]', 'had planned', 'long before 強調先後，had planned。'),
(5, 'fill_blank', 'Once the audit _____ (complete), the results were presented.', NULL, 'had been completed', 'once 引導過去完成被動式。'),
(5, 'multiple_choice', 'The product had been on the market two years before it _____ a profit.', '["had made","made","was making","makes"]', 'made', 'made 是後發生的過去事件，簡單過去式。'),
(5, 'multiple_choice', 'We _____ already _____ a similar service before the client asked.', '["did / develop","were / developing","have / developed","had / developed"]', 'had / developed', 'already + 過去完成式 had developed。'),
(5, 'transform', 'The team finished. Then the director reviewed it. (Use: had finished)', NULL, 'By the time the director reviewed it, the team had finished the report.', 'had finished 在 reviewed 之前完成。'),
(5, 'fill_blank', 'I realized I _____ (forget) to include the appendix.', NULL, 'had forgotten', 'realized 在過去，forget 更早，had forgotten。'),
(5, 'multiple_choice', 'All the guests _____ when the CEO made her announcement.', '["have arrived","arrived","were arriving","had arrived"]', 'had arrived', 'when the CEO made 設定過去時間點，had arrived 已到。'),
(5, 'multiple_choice', 'They _____ not _____ the terms before signing.', '["had / understood","did / understand","have / understood","were / understanding"]', 'had / understood', '簽約前的過去完成式否定。'),
(5, 'fill_blank', 'The company _____ (expand) into Asia before the crisis hit.', NULL, 'had expanded', 'before 建立先後，更早用過去完成式。'),
(5, 'multiple_choice', 'By the time I joined, the company _____ its strategy.', '["already revised","has already revised","was already revising","had already revised"]', 'had already revised', 'had already revised 過去完成式。'),
(5, 'multiple_choice', 'She found out that the deal _____ without her approval.', '["had approved","had been approved","has been approved","was approved"]', 'had been approved', '過去完成被動式 had been approved。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(6, 'multiple_choice', 'I _____ send you the contract as soon as it''s ready.', '["am going to","was","would","will"]', 'will', 'will 表即時承諾；am going to 也可，但 will 更常見於即時承諾。'),
(6, 'multiple_choice', 'We _____ launch the new product line next spring. Everything is planned.', '["would","were going to","will","are going to"]', 'are going to', '已計劃好的意圖用 be going to；will 表臨時決定。'),
(6, 'multiple_choice', 'Look at those sales numbers — this _____ be our best year ever!', '["is going to","was going to","would","will"]', 'is going to', '根據眼前證據預測，用 be going to。'),
(6, 'fill_blank', 'I just decided — I _____ (take) the overseas assignment.', NULL, 'will take', 'just decided 表臨時決定，用 will。'),
(6, 'multiple_choice', 'The director _____ give a speech at the annual banquet next month.', '["would","was going to","is going to","will"]', 'is going to', 'next month 已排定計劃，be going to 更合適。'),
(6, 'transform', 'It is planned that the company expands to Europe next year. (Use: going to)', NULL, 'The company is going to expand to Europe next year.', '已計劃的意圖用 be going to。'),
(6, 'multiple_choice', 'Don''t worry, I _____ help you with the report.', '["was going to","would","will","am going to"]', 'will', '即時答應幫忙，will 最自然。'),
(6, 'fill_blank', 'We _____ (hold) the annual conference in Dubai. All arrangements are made.', NULL, 'are going to hold', '已安排好的計劃，be going to 正確。'),
(6, 'multiple_choice', 'It looks like the project _____ be delayed.', '["will","is going to","was going to","would"]', 'is going to', '根據現有跡象預測，be going to。'),
(6, 'multiple_choice', 'She _____ be the new CFO. It was announced yesterday.', '["would be","is going to","was going to","will"]', 'is going to', '已宣布的計劃，be going to。'),
(6, 'fill_blank', 'Someone has to present this. — OK, I _____ (do) it.', NULL, 'will do', '即時決定，will do。'),
(6, 'multiple_choice', 'By this time next year, we _____ have doubled our market share.', '["would","are going to","will","were going to"]', 'will', '未來完成式 will have doubled，預測未來時間點前完成。'),
(6, 'transform', 'The manager has decided to retire in July. (Use: going to retire)', NULL, 'The manager is going to retire in July.', '已決定的計劃，be going to。'),
(6, 'multiple_choice', 'I _____ definitely call you back after the meeting.', '["am going to","would","was going to","will"]', 'will', '即時承諾用 will。'),
(6, 'fill_blank', 'The negotiation _____ (start) at 2 p.m. It''s on the schedule.', NULL, 'is going to start', '已排定計劃，be going to start。'),
(6, 'multiple_choice', 'There''s no way around it — we _____ need more funding.', '["would","are going to","will","were going to"]', 'will', '客觀預測用 will；are going to 也可。'),
(6, 'multiple_choice', 'She promised she _____ send the invoice today.', '["will","would","was going to","is going to"]', 'would', 'promised 後的間接引語用 would。'),
(6, 'fill_blank', 'Watch out! That pile of documents _____ (fall).', NULL, 'is going to fall', '根據眼前情況的即時預測，be going to。'),
(6, 'multiple_choice', 'We _____ restructure the department. We''ve been planning it for months.', '["would","will","are going to","were going to"]', 'are going to', '幾個月的計劃，be going to。'),
(6, 'multiple_choice', 'I think the market _____ recover by Q3.', '["will","would","was going to","is going to"]', 'will', '主觀預測用 will。'),
(7, 'multiple_choice', 'By next Friday, we _____ the audit report.', '["will be submitting","are submitting","will submit","will have submitted"]', 'will have submitted', 'by next Friday 搭配未來完成式 will have submitted。'),
(7, 'multiple_choice', 'This time next week, I _____ the annual conference in London.', '["will attend","will have attended","attend","will be attending"]', 'will be attending', 'this time next week 指未來某時刻進行中，will be attending。'),
(7, 'fill_blank', 'By the end of this year, the company _____ (open) ten new branches.', NULL, 'will have opened', 'by the end of this year 搭配未來完成式。'),
(7, 'multiple_choice', 'Don''t call at 3 p.m. — she _____ her presentation then.', '["gives","will have given","will be giving","will give"]', 'will be giving', 'at 3 p.m. 未來時刻正在進行，will be giving。'),
(7, 'multiple_choice', 'We _____ the new platform for six months by December.', '["will have been using","will use","have been using","will be using"]', 'will have been using', 'by December 強調持續時間完成，未來完成進行式。'),
(7, 'transform', 'The project ends on March 31. (Use: will have completed by)', NULL, 'We will have completed the project by March 31.', 'by + 未來時間點，搭配未來完成式。'),
(7, 'multiple_choice', 'I _____ in this role for ten years next June.', '["have been working","will work","will have been working","will be working"]', 'will have been working', 'next June 到那時累積10年，未來完成進行式。'),
(7, 'fill_blank', 'By the time you read this, the meeting _____ (start) already.', NULL, 'will have already started', 'by the time 搭配未來完成式。'),
(7, 'multiple_choice', 'At this time tomorrow, they _____ final contract terms.', '["negotiate","will have negotiated","will be negotiating","will negotiate"]', 'will be negotiating', 'this time tomorrow 未來某時刻進行中，will be negotiating。'),
(7, 'multiple_choice', 'We _____ 1,000 units by the end of Q2.', '["will ship","will be shipping","will have shipped","are shipping"]', 'will have shipped', 'by the end of Q2 搭配未來完成式 will have shipped。'),
(7, 'fill_blank', 'This time next month, I _____ (work) in our Singapore office.', NULL, 'will be working', 'this time next month 未來時刻正在進行。'),
(7, 'multiple_choice', 'By 2027, the company _____ its expansion into five new markets.', '["will have completed","will be completing","completes","will complete"]', 'will have completed', 'by 2027 搭配未來完成式。'),
(7, 'multiple_choice', 'She _____ in the middle of her vacation when you call.', '["will be relaxing","relaxes","will have relaxed","will relax"]', 'will be relaxing', 'when you call 那個時間點正在休假，will be relaxing。'),
(7, 'transform', 'The renovation ends before the clients arrive. (Use: will have finished)', NULL, 'The renovation will have finished before the clients arrive.', 'before 搭配未來完成式。'),
(7, 'fill_blank', 'By the end of Q4, total revenue _____ (reach) $10 million.', NULL, 'will have reached', 'by the end of Q4 搭配未來完成式。'),
(7, 'multiple_choice', 'Don''t disturb the CEO at 2 p.m. — she _____ an important call.', '["will be having","has","will have had","will have"]', 'will be having', '2 p.m. 未來時刻進行中，will be having。'),
(7, 'multiple_choice', 'We _____ this software for a year by next January.', '["will have been using","have used","will use","will be using"]', 'will have been using', 'by next January 累積一年，未來完成進行式。'),
(7, 'fill_blank', 'By the time the new hire starts, we _____ (complete) the onboarding materials.', NULL, 'will have completed', 'by the time 搭配未來完成式。'),
(7, 'multiple_choice', 'This time next year, the team _____ in a brand new office.', '["works","will be working","will have worked","will work"]', 'will be working', 'this time next year 未來時刻進行。'),
(7, 'multiple_choice', 'By 2030, we _____ 500 employees worldwide.', '["will be hiring","will have hired","are hiring","will hire"]', 'will have hired', 'by 2030 搭配未來完成式 will have hired。'),
(8, 'multiple_choice', 'She _____ the company for three years when she _____ her first promotion.', '["has been working / receives","was working / has received","worked / was receiving","had been working / received"]', 'had been working / received', 'had been working 表在 received 之前持續的動作。'),
(8, 'multiple_choice', 'By the time I _____ tomorrow, the deal _____.', '["will arrive / is signed","arrived / had been signed","arrive / will have been signed","am arriving / will sign"]', 'arrive / will have been signed', 'arrive 時間子句用現在式，主句用未來完成被動式。'),
(8, 'multiple_choice', 'We _____ the market every year, but this year we _____ something different.', '["analyse / tried","have analysed / tried","analyse / are trying","analysed / tried"]', 'analyse / are trying', 'every year 簡單式，this year 進行式（暫時策略）。'),
(8, 'fill_blank', 'The team _____ (just / finish) the report when the client _____ (call).', NULL, 'had just finished / called', 'had just finished 過去完成，called 插入動作。'),
(8, 'multiple_choice', 'She _____ in marketing for ten years before she _____ to management.', '["worked / has moved","had worked / moved","was working / moved","has worked / moves"]', 'had worked / moved', '在 moved 之前的持續，had worked；then moved。'),
(8, 'multiple_choice', 'I _____ a lot of business trips lately, so I _____ quite tired.', '["took / was","had taken / was","have been taking / am","take / am"]', 'have been taking / am', 'lately 現在完成進行式，result 現在狀態。'),
(8, 'multiple_choice', 'As soon as she _____ the budget, she _____ the board.', '["is approving / will inform","approved / informed","will approve / informs","approves / will inform"]', 'approves / will inform', 'as soon as 時間子句用現在式，主句用 will。'),
(8, 'transform', 'The company lost money last year. Now it is profitable. (Use appropriate tenses)', NULL, 'The company lost money last year, but it has become profitable now.', 'lost 過去式；has become 現在完成式表狀態改變。'),
(8, 'multiple_choice', 'When I came into the office, she _____ already _____ all the preparations.', '["did / make","has / made","had / made","was / making"]', 'had / made', 'came 過去，preparations 更早完成，had made。'),
(8, 'fill_blank', 'Sales _____ (increase) every quarter since the new strategy _____ (implement).', NULL, 'have increased / was implemented', 'since 搭配現在完成式；被動過去式 was implemented。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(8, 'multiple_choice', 'He _____ the company before it _____ public.', '["was leaving / had gone","leaves / goes","left / has gone","had left / went"]', 'had left / went', '左邊更早 had left；然後 went public。'),
(8, 'multiple_choice', 'The factory _____ at full capacity when the order _____.', '["was operating / arrived","is operating / will arrive","has been operating / arrives","operated / was arriving"]', 'was operating / arrived', '背景進行式 was operating，插入 arrived。'),
(8, 'multiple_choice', 'By next March, she _____ in management for five years.', '["will have been","was","has been","will be"]', 'will have been', 'by next March 未來時間點，will have been。'),
(8, 'fill_blank', 'I _____ (not / see) her since she _____ (transfer) to the Hong Kong office.', NULL, 'have not seen / was transferred', 'since 搭配現在完成式；transferred 被動過去式。'),
(8, 'multiple_choice', 'While we _____ the presentation, our server _____ down.', '["prepared / was going","prepare / goes","had prepared / went","were preparing / went"]', 'were preparing / went', '背景進行式 were preparing，插入 went down。'),
(8, 'multiple_choice', 'She _____ this role for two years by the time she _____ her MBA.', '["held / finished","will have held / finishes","holds / finishes","has held / finishes"]', 'will have held / finishes', 'by the time 未來完成式 will have held；時間子句用現在式。'),
(8, 'multiple_choice', 'The client _____ before we _____ to respond.', '["had left / had time","has left / have time","was leaving / had time","left / have time"]', 'had left / had time', 'had left 和 had time 兩個過去完成式，強調均在主句時間前。'),
(8, 'transform', 'First the budget was approved. Then the project started. (Use: had been approved)', NULL, 'The project started after the budget had been approved.', 'after 連接：had been approved 更早，started 後來。'),
(8, 'multiple_choice', 'She _____ three proposals this week and _____ two of them.', '["has written / submitted","wrote / has submitted","is writing / submitted","writes / submits"]', 'has written / submitted', 'this week 現在完成式，且已提交也是本週。'),
(8, 'multiple_choice', 'He rarely _____ late, but yesterday he _____ the whole morning.', '["is / missed","is / has missed","has been / missed","was / misses"]', 'is / missed', 'rarely is 習慣；yesterday missed 過去事件。'),
(9, 'multiple_choice', 'Please send me _____ contract you mentioned in your email.', '["a","the","—","an"]', 'the', 'mentioned 已知，雙方都知的特定合約，用 the。'),
(9, 'multiple_choice', 'She is _____ CEO of a Fortune 500 company.', '["—","an","a","the"]', 'the', 'CEO 是獨一無二的職位，且特指某公司，用 the。'),
(9, 'multiple_choice', 'We need to review _____ annual budget before the board meeting.', '["the","—","an","a"]', 'the', 'annual budget 是特定文件，用 the。'),
(9, 'multiple_choice', 'This is _____ most efficient solution we''ve found.', '["a","an","—","the"]', 'the', '最高級前用 the。'),
(9, 'fill_blank', 'I met _____ client you recommended. He was very professional.', NULL, 'the', 'you recommended 使其特定化，用 the。'),
(9, 'multiple_choice', 'She gave _____ speech at _____ conference last week.', '["a / the","a / a","the / a","the / the"]', 'a / the', 'speech 首次提及用 a；conference 已知特定活動用 the。'),
(9, 'multiple_choice', '_____ new product launch was a great success.', '["The","An","—","A"]', 'The', '特定的新產品發表（已知事件），用 The。'),
(9, 'multiple_choice', 'Can you go over _____ proposal one more time?', '["the","an","a","—"]', 'the', '已知特定提案，用 the。'),
(9, 'transform', 'Our company has a headquarters. It is in Tokyo. (Use: the)', NULL, 'Our company''s headquarters is in the heart of Tokyo.', 'headquarters 特指，用 the。'),
(9, 'multiple_choice', 'We discussed _____ merger at _____ last board meeting.', '["the / a","the / the","a / a","a / the"]', 'the / the', '已知的合併案和上次的董事會議，均用 the。'),
(9, 'fill_blank', 'Could you book _____ meeting room on the third floor?', NULL, 'the', '特定的三樓會議室，用 the。'),
(9, 'multiple_choice', 'This is _____ first time we''ve worked with this supplier.', '["the","an","a","—"]', 'the', '第一次（序數概念），用 the first time。'),
(9, 'multiple_choice', '_____ finance team will present _____ results next Tuesday.', '["The / a","The / the","A / the","A / a"]', 'The / the', '已知部門和已知結果，均用 the。'),
(9, 'multiple_choice', 'It''s _____ best deal we''ve ever made.', '["the","an","a","—"]', 'the', '最高級 best 前用 the。'),
(9, 'fill_blank', 'We are aiming for _____ top position in _____ market.', NULL, 'the / the', 'top position 特指，market 已知特定市場，均用 the。'),
(9, 'multiple_choice', 'She is in charge of _____ Asia-Pacific region.', '["the","—","a","an"]', 'the', '地理區域名稱前通常用 the。'),
(9, 'multiple_choice', 'I''ll forward you _____ minutes of today''s meeting.', '["—","a","an","the"]', 'the', '特定的今天會議記錄，用 the。'),
(9, 'multiple_choice', 'We need _____ decision by Friday.', '["—","a","the","an"]', 'a', '首次提及，未特定的某個決定，用 a。'),
(9, 'transform', 'There is only one director of operations. (Use: the)', NULL, 'Please contact the director of operations regarding this issue.', '職稱加上唯一性，用 the。'),
(9, 'multiple_choice', '_____ productivity in our team has improved significantly.', '["An","—","The","A"]', 'The', '特指我們團隊的生產力，用 The。'),
(10, 'multiple_choice', 'She submitted _____ expense report this morning.', '["an","the","a","—"]', 'an', 'expense 以母音音素 /e/ 開頭，用 an。'),
(10, 'multiple_choice', 'We need to hire _____ experienced project manager.', '["the","an","—","a"]', 'an', 'experienced 以母音音素 /e/ 開頭，用 an。'),
(10, 'multiple_choice', 'He has _____ MBA from a top university.', '["an","a","the","—"]', 'an', 'MBA 發音 /em biː eɪ/，M 發母音音素，用 an。'),
(10, 'multiple_choice', 'Can you send _____ update by end of day?', '["—","the","an","a"]', 'an', 'update 以母音音素 /ʌ/ 開頭，用 an。'),
(10, 'multiple_choice', 'She made _____ excellent presentation to the board.', '["a","the","an","—"]', 'an', 'excellent 以母音音素 /e/ 開頭，用 an。'),
(10, 'fill_blank', 'We are looking for _____ office in _____ central location.', NULL, 'an / a', 'office 母音開頭 an；central 輔音開頭 a。'),
(10, 'multiple_choice', 'It was _____ unique opportunity that we couldn''t pass up.', '["—","a","the","an"]', 'a', 'unique 發音 /juːniːk/，以 /j/ 輔音音素開頭，用 a。'),
(10, 'multiple_choice', 'Please prepare _____ agenda for the meeting.', '["—","a","an","the"]', 'an', 'agenda 以母音音素 /æ/ 開頭，用 an。'),
(10, 'multiple_choice', 'He is _____ honest and dedicated employee.', '["—","an","a","the"]', 'an', 'honest 以母音音素 /ɒ/ 開頭（h 不發音），用 an。'),
(10, 'transform', 'Please write one report per week. (Use: a)', NULL, 'Please submit a report every week.', 'a 用於泛指一份報告。'),
(10, 'multiple_choice', 'That was _____ one-time offer.', '["—","the","an","a"]', 'a', 'one-time 發音 /wʌn/，以 /w/ 輔音音素開頭，用 a。'),
(10, 'multiple_choice', 'She gave _____ half-hour presentation.', '["the","—","an","a"]', 'a', 'half-hour 發音 /hɑːf/，以 /h/ 輔音音素開頭，用 a。'),
(10, 'fill_blank', 'It was _____ historic moment for our company.', NULL, 'a', 'historic 發音 /hɪˈstɒrɪk/，以 /h/ 開頭，用 a（英式有人用 an）。'),
(10, 'multiple_choice', 'He is _____ EU representative attending the summit.', '["a","—","an","the"]', 'a', 'EU 發音 /juː/，以 /j/ 輔音音素開頭，用 a。'),
(10, 'multiple_choice', 'We had _____ informal meeting with the client.', '["a","—","the","an"]', 'an', 'informal 以母音音素 /ɪ/ 開頭，用 an。'),
(10, 'multiple_choice', 'She received _____ award for outstanding performance.', '["—","the","a","an"]', 'an', 'award 以母音音素 /ə/ 開頭，用 an。'),
(10, 'fill_blank', 'This is _____ once-in-a-lifetime opportunity.', NULL, 'a', 'once 發音 /wʌns/，以 /w/ 輔音音素開頭，用 a。'),
(10, 'multiple_choice', 'He sent _____ urgent email to the entire team.', '["a","the","—","an"]', 'an', 'urgent 以母音音素 /ʌ/ 開頭，用 an。'),
(10, 'multiple_choice', 'She is _____ account manager at our firm.', '["an","the","a","—"]', 'an', 'account 以母音音素 /ə/ 開頭，用 an。'),
(10, 'multiple_choice', 'They issued _____ official statement this morning.', '["—","a","an","the"]', 'an', 'official 以母音音素 /ə/ 開頭，用 an。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(11, 'multiple_choice', '_____ information you need is on the company website.', '["A","The","—","An"]', 'The', '特定資訊（you need 限定），用 The。'),
(11, 'multiple_choice', 'She travels to _____ Japan every quarter for business.', '["an","—","a","the"]', '—', '國家名通常不加冠詞。'),
(11, 'multiple_choice', 'We communicate mostly by _____ email.', '["the","a","—","an"]', '—', 'by email 固定搭配，零冠詞。'),
(11, 'multiple_choice', '_____ managers are responsible for team performance.', '["The","A","—","An"]', '—', '泛指所有管理者，複數名詞泛稱，零冠詞。'),
(11, 'fill_blank', 'She goes to _____ work by subway every day.', NULL, '—（不加冠詞）', 'go to work 固定搭配，零冠詞。'),
(11, 'multiple_choice', '_____ knowledge is essential in today''s business world.', '["—","An","The","A"]', '—', 'knowledge 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'We had _____ lunch with the new partners.', '["an","the","—","a"]', '—', 'have lunch 固定搭配，零冠詞（也可 a business lunch）。'),
(11, 'multiple_choice', 'The company invested heavily in _____ technology last year.', '["the","a","—","an"]', '—', 'technology 不可數泛稱，零冠詞。'),
(11, 'transform', 'The advice from experts is valuable. (Use zero article for advice)', NULL, 'Advice from experts is always valuable in business.', 'advice 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'He is based in _____ New York.', '["a","the","—","an"]', '—', '城市名一般不加冠詞。'),
(11, 'multiple_choice', '_____ progress has been made on the project.', '["A","An","The","—"]', '—', 'progress 不可數泛稱，零冠詞（如要特指則用 The progress）。'),
(11, 'multiple_choice', 'Could you send the report by _____ post?', '["an","a","the","—"]', '—', 'by post 固定搭配，零冠詞。'),
(11, 'fill_blank', 'We need to improve _____ communication within the team.', NULL, '—（不加冠詞）', 'communication 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'She joined _____ Microsoft after graduating.', '["an","—","a","the"]', '—', '公司名專有名詞通常不加冠詞。'),
(11, 'multiple_choice', 'We are making _____ good progress on the project.', '["—","the","an","a"]', '—', 'make progress 固定搭配中，good progress 零冠詞。'),
(11, 'multiple_choice', 'He was promoted to _____ director last month.', '["—","a","the","an"]', '—', 'become/be appointed + 職稱，零冠詞。'),
(11, 'fill_blank', '_____ teamwork is crucial for project success.', NULL, '—（不加冠詞）', 'teamwork 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'The CEO went to _____ university in the UK.', '["a","—","the","an"]', '—', 'go to university 固定搭配，零冠詞。'),
(11, 'multiple_choice', '_____ automation is transforming the manufacturing industry.', '["An","The","—","A"]', '—', 'automation 不可數泛稱，零冠詞。'),
(11, 'multiple_choice', 'We need to focus on _____ customer satisfaction.', '["—","an","the","a"]', '—', '泛指顧客滿意度，不可數概念，零冠詞。'),
(12, 'multiple_choice', 'The meeting is scheduled _____ 10 a.m.', '["on","in","at","by"]', 'at', '精確時間點用 at。'),
(12, 'multiple_choice', 'The product was launched _____ 2021.', '["on","by","in","at"]', 'in', '年份用 in。'),
(12, 'multiple_choice', 'We have a client call _____ Tuesday.', '["on","at","by","in"]', 'on', '星期幾用 on。'),
(12, 'multiple_choice', 'I''ll send you the report _____ the morning.', '["at","by","on","in"]', 'in', 'the morning/afternoon/evening 用 in。'),
(12, 'fill_blank', 'The contract expires _____ March 31st.', NULL, 'on', '特定日期用 on。'),
(12, 'multiple_choice', 'She joined the company _____ January.', '["in","at","by","on"]', 'in', '月份用 in。'),
(12, 'multiple_choice', 'The office opens _____ 9 o''clock.', '["at","by","in","on"]', 'at', '精確時間點用 at。'),
(12, 'multiple_choice', 'We should finalize the deal _____ the end of the month.', '["in","at","on","by"]', 'by', 'deadline 截止日期用 by。'),
(12, 'transform', 'The conference happens in the third week of August. (Use: on)', NULL, 'The conference is on August 18th.', '具體日期用 on。'),
(12, 'multiple_choice', 'The project started _____ the summer.', '["at","on","by","in"]', 'in', 'the summer 季節用 in。'),
(12, 'multiple_choice', 'She usually works late _____ Fridays.', '["at","by","on","in"]', 'on', '星期幾用 on。'),
(12, 'fill_blank', 'The team meeting is _____ noon every Wednesday.', NULL, 'at', 'noon 是特定時間點，用 at。'),
(12, 'multiple_choice', 'The deal was signed _____ midnight.', '["at","in","on","by"]', 'at', 'midnight 是精確時間點，用 at。'),
(12, 'multiple_choice', 'Our fiscal year ends _____ December.', '["at","on","in","by"]', 'in', '月份用 in。'),
(12, 'multiple_choice', 'He was promoted _____ 2023.', '["by","on","in","at"]', 'in', '年份用 in。'),
(12, 'fill_blank', 'The workshop is scheduled _____ the afternoon of June 5th.', NULL, 'on the afternoon of', '特定日期的下午用 on the afternoon of。'),
(12, 'multiple_choice', 'She will return from leave _____ Monday morning.', '["in","by","at","on"]', 'on', 'Monday morning 特定時間組合用 on。'),
(12, 'multiple_choice', 'The proposal is due _____ the end of this week.', '["on","in","at","by"]', 'by', 'due 截止用 by。'),
(12, 'multiple_choice', 'We met _____ a conference in Singapore _____ 2022.', '["at / in","in / in","on / in","at / at"]', 'at / in', 'conference 地點 at；year 用 in。'),
(12, 'multiple_choice', 'The company was founded _____ the early 1990s.', '["by","in","at","on"]', 'in', 'decade 用 in the 1990s。'),
(13, 'multiple_choice', 'The manager is _____ her office right now.', '["on","at","in","by"]', 'in', 'office 是封閉空間，用 in。'),
(13, 'multiple_choice', 'Please meet me _____ the reception desk.', '["by","in","at","on"]', 'at', 'reception desk 是功能性地點，用 at。'),
(13, 'multiple_choice', 'The documents are _____ the table.', '["in","at","by","on"]', 'on', 'table 是表面，用 on。'),
(13, 'multiple_choice', 'Our headquarters is _____ London.', '["on","by","in","at"]', 'in', '城市用 in。'),
(13, 'fill_blank', 'The printer is _____ the third floor.', NULL, 'on', 'floor 樓層用 on。'),
(13, 'multiple_choice', 'She is _____ a business trip.', '["by","in","on","at"]', 'on', 'on a business trip 固定搭配。'),
(13, 'multiple_choice', 'I''ll see you _____ the conference center.', '["at","by","on","in"]', 'at', 'conference center 功能性地點，用 at。'),
(13, 'multiple_choice', 'The logo is _____ the top of the page.', '["on","in","by","at"]', 'at', 'at the top 指頂部位置。'),
(13, 'fill_blank', 'Can you post it _____ the notice board?', NULL, 'on', 'notice board 是表面，用 on。'),
(13, 'multiple_choice', 'The product details are listed _____ page 10.', '["in","at","by","on"]', 'on', 'page 頁面用 on。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(13, 'multiple_choice', 'She is waiting _____ the entrance.', '["on","by","in","at"]', 'at', 'entrance 功能性地點，用 at。'),
(13, 'multiple_choice', 'There''s a typo _____ paragraph three.', '["in","at","on","by"]', 'in', 'paragraph 段落用 in。'),
(13, 'multiple_choice', 'He works _____ a large corporation _____ the city centre.', '["for / at","at / at","for / in","at / in"]', 'for / in', 'work for 公司；city centre 地區 in。'),
(13, 'transform', 'The error is located at line 5 of the report. (Use: on)', NULL, 'The error is on line 5 of the report.', 'line 行用 on。'),
(13, 'fill_blank', 'Please put your signature _____ the dotted line.', NULL, 'on', 'dotted line 是線（表面），用 on。'),
(13, 'multiple_choice', 'The annual report is _____ the website.', '["in","by","on","at"]', 'on', 'website 用 on。'),
(13, 'multiple_choice', 'She arrived _____ the airport at 6 a.m.', '["by","in","on","at"]', 'at', 'airport 功能性地點，用 at。'),
(13, 'multiple_choice', 'The branch is located _____ the financial district.', '["on","in","at","by"]', 'in', 'district 地區，用 in。'),
(13, 'fill_blank', 'The meeting notes are _____ the shared drive.', NULL, 'in', 'shared drive 是虛擬空間，用 in。'),
(13, 'multiple_choice', 'He is _____ a meeting and cannot be disturbed.', '["by","at","in","on"]', 'in', 'in a meeting 固定搭配。'),
(14, 'multiple_choice', 'She walked _____ the conference room without knocking.', '["into","onto","in","to"]', 'into', 'into 表從外進入，walked into 進入會議室。'),
(14, 'multiple_choice', 'He traveled _____ Singapore for the trade fair.', '["into","toward","to","onto"]', 'to', 'to 表目的地，traveled to Singapore。'),
(14, 'multiple_choice', 'The new employee walked _____ the office on her first day.', '["through","to","in","into"]', 'into', 'walked into 進入辦公室。'),
(14, 'multiple_choice', 'The CEO walked _____ the building past the reception area.', '["across","into","through","along"]', 'through', 'through 表穿越整個空間，walked through。'),
(14, 'fill_blank', 'She drove _____ the tunnel to get to the airport.', NULL, 'through', 'through 穿越隧道。'),
(14, 'multiple_choice', 'The delivery van drove _____ the warehouse district.', '["across","into","along","through"]', 'through', 'through 穿越區域。'),
(14, 'multiple_choice', 'Please walk _____ the corridor to find the HR office.', '["through","along","past","into"]', 'along', 'along 沿著走廊走。'),
(14, 'multiple_choice', 'The manager moved her desk _____ the window.', '["onto","to","into","toward"]', 'to', 'moved to 移到某地點。'),
(14, 'transform', 'He entered the meeting room. (Use: walked into)', NULL, 'He walked into the meeting room.', 'walked into 表進入的動作。'),
(14, 'multiple_choice', 'She ran _____ the street to catch a taxi.', '["through","across","into","along"]', 'across', 'across 橫越街道。'),
(14, 'multiple_choice', 'The courier went _____ the building to make the delivery.', '["to","through","past","into"]', 'into', 'into 進入建築物。'),
(14, 'fill_blank', 'We drove _____ the new factory on our way to the airport.', NULL, 'past', 'past 表經過某地點。'),
(14, 'multiple_choice', 'The document was passed _____ the table.', '["along","into","through","across"]', 'across', 'passed across 從桌子一端傳到另一端。'),
(14, 'multiple_choice', 'She took the elevator _____ the parking garage.', '["onto","into","to","through"]', 'to', 'to 表目的地樓層或地點。'),
(14, 'multiple_choice', 'The goods were shipped _____ several distribution centers.', '["through","to","into","across"]', 'through', 'through 表中轉經過幾個中心。'),
(14, 'fill_blank', 'Could you bring the files _____ my office?', NULL, 'to', 'bring to 帶到某地。'),
(14, 'multiple_choice', 'He walked _____ the podium to begin his keynote.', '["across","into","to","onto"]', 'to', 'walked to 走向講台（onto 也可用於上台）。'),
(14, 'multiple_choice', 'The intern hurried _____ the corridor to deliver the report.', '["through","along","across","into"]', 'along', 'along 沿走廊快走。'),
(14, 'multiple_choice', 'The new manager was moved _____ the Tokyo branch.', '["to","through","onto","into"]', 'to', 'moved to 調派到東京分部。'),
(14, 'multiple_choice', 'She glanced _____ the street before crossing.', '["through","along","across","into"]', 'across', 'across 橫過，glanced across 朝對面看。'),
(15, 'multiple_choice', 'She is responsible _____ managing the entire supply chain.', '["of","for","to","with"]', 'for', 'responsible for 負責，固定搭配。'),
(15, 'multiple_choice', 'Are you familiar _____ our company''s return policy?', '["of","with","to","about"]', 'with', 'familiar with 熟悉，固定搭配。'),
(15, 'multiple_choice', 'The team was satisfied _____ the outcome of the negotiation.', '["of","by","about","with"]', 'with', 'satisfied with 對...滿意，固定搭配。'),
(15, 'multiple_choice', 'He is interested _____ exploring new markets in Southeast Asia.', '["for","with","about","in"]', 'in', 'interested in 對...感興趣，固定搭配。'),
(15, 'fill_blank', 'She is very good _____ managing difficult clients.', NULL, 'at', 'good at 擅長，固定搭配。'),
(15, 'multiple_choice', 'We are committed _____ delivering the highest quality service.', '["to","with","for","in"]', 'to', 'committed to 致力於，固定搭配。'),
(15, 'multiple_choice', 'He was disappointed _____ the quarterly results.', '["in","with","about","by"]', 'with', 'disappointed with/in 對...失望，均可用。'),
(15, 'multiple_choice', 'The CFO is worried _____ the rising operational costs.', '["with","of","for","about"]', 'about', 'worried about 擔心，固定搭配。'),
(15, 'transform', 'He has awareness of the risks. (Use: aware of)', NULL, 'He is aware of the risks involved in this project.', 'aware of 知道，固定搭配。'),
(15, 'multiple_choice', 'Our company is capable _____ handling large-scale projects.', '["to","of","for","with"]', 'of', 'capable of 有能力，固定搭配。'),
(15, 'multiple_choice', 'The client was impressed _____ our presentation.', '["about","by","with","of"]', 'by', 'impressed by/with 均可，by 更強調感受來源。'),
(15, 'fill_blank', 'She is enthusiastic _____ the new marketing initiative.', NULL, 'about', 'enthusiastic about 對...充滿熱情，固定搭配。'),
(15, 'multiple_choice', 'We are concerned _____ the delay in delivery.', '["about","of","with","for"]', 'about', 'concerned about 擔憂，固定搭配。'),
(15, 'multiple_choice', 'He is not suitable _____ this position.', '["for","of","with","to"]', 'for', 'suitable for 適合，固定搭配。'),
(15, 'multiple_choice', 'The manager was very strict _____ punctuality.', '["with","of","about","for"]', 'about', 'strict about 嚴格要求，固定搭配。'),
(15, 'fill_blank', 'Our team is very proud _____ this achievement.', NULL, 'of', 'proud of 對...感到驕傲，固定搭配。'),
(15, 'multiple_choice', 'She is very skilled _____ data analysis.', '["for","at","with","in"]', 'at', 'skilled at 擅長，固定搭配（skilled in 也可）。'),
(15, 'multiple_choice', 'The company is based _____ Singapore.', '["in","at","on","for"]', 'in', 'based in 總部設於，固定搭配。'),
(15, 'multiple_choice', 'He is tired _____ attending endless meetings.', '["from","with","about","of"]', 'of', 'tired of 厭倦，固定搭配。'),
(15, 'multiple_choice', 'The team is fully dedicated _____ completing this project.', '["with","for","in","to"]', 'to', 'dedicated to 獻身於，固定搭配。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(16, 'multiple_choice', 'We applied _____ a government grant to fund the project.', '["to","for","in","with"]', 'for', 'apply for 申請，固定搭配。'),
(16, 'multiple_choice', 'She deals _____ customer complaints on a daily basis.', '["with","in","for","about"]', 'with', 'deal with 處理，固定搭配。'),
(16, 'multiple_choice', 'Our success relies _____ the dedication of our team members.', '["in","with","on","for"]', 'on', 'rely on 依賴，固定搭配。'),
(16, 'multiple_choice', 'The company is investing _____ renewable energy infrastructure.', '["into","in","for","on"]', 'in', 'invest in 投資於，固定搭配。'),
(16, 'fill_blank', 'He agreed _____ the proposed changes to the contract.', NULL, 'to', 'agree to (proposal/change) 同意某事，固定搭配。'),
(16, 'multiple_choice', 'We need to comply _____ all local safety regulations.', '["for","by","to","with"]', 'with', 'comply with 遵守，固定搭配。'),
(16, 'multiple_choice', 'She specializes _____ international trade law.', '["in","for","with","on"]', 'in', 'specialize in 專門從事，固定搭配。'),
(16, 'multiple_choice', 'The manager apologized _____ the miscommunication.', '["with","to","for","about"]', 'for', 'apologize for 為...道歉，固定搭配。'),
(16, 'transform', 'He contributes money to the charity fund. (Use: contributes to)', NULL, 'He contributes to the company''s success every day.', 'contribute to 貢獻於，固定搭配。'),
(16, 'multiple_choice', 'We are looking _____ a new distribution partner.', '["at","after","into","for"]', 'for', 'look for 尋找，固定搭配。'),
(16, 'multiple_choice', 'She reported _____ the regional director every week.', '["on","for","to","with"]', 'to', 'report to 向...匯報，固定搭配。'),
(16, 'fill_blank', 'The company prides itself _____ excellent customer service.', NULL, 'on', 'pride oneself on 以...自豪，固定搭配。'),
(16, 'multiple_choice', 'He is responsible _____ a team of 15 engineers.', '["for","with","to","of"]', 'for', 'responsible for 負責，固定搭配。'),
(16, 'multiple_choice', 'We should focus _____ improving client retention rates.', '["with","on","in","for"]', 'on', 'focus on 專注於，固定搭配。'),
(16, 'multiple_choice', 'The team succeeded _____ launching the product on schedule.', '["at","with","in","for"]', 'in', 'succeed in 成功地做到，固定搭配。'),
(16, 'fill_blank', 'Could you elaborate _____ the cost-saving measures?', NULL, 'on', 'elaborate on 詳細說明，固定搭配。'),
(16, 'multiple_choice', 'Our policy prohibits us _____ sharing confidential data.', '["for","from","with","of"]', 'from', 'prohibit from 禁止，固定搭配。'),
(16, 'multiple_choice', 'She tends _____ work long hours before major deadlines.', '["to","with","toward","for"]', 'to', 'tend to 傾向於，固定搭配。'),
(16, 'multiple_choice', 'We are considering _____ expanding to new markets.', '["—","on","about","for"]', '—', 'consider + V-ing 直接接動名詞，不需介系詞。'),
(16, 'multiple_choice', 'He objected _____ the proposed budget cuts.', '["to","about","with","for"]', 'to', 'object to 反對，固定搭配。'),
(17, 'multiple_choice', 'If you _____ the invoice, we will process your order immediately.', '["send","sending","will send","sent"]', 'send', 'if 子句用現在式；send 正確。'),
(17, 'multiple_choice', 'If demand increases, prices generally _____.', '["are rising","rose","will rise","rise"]', 'rise', '零條件句：普遍規律，兩個現在式。'),
(17, 'multiple_choice', 'If she _____ the interview, she will get the job.', '["will pass","passes","passed","passing"]', 'passes', 'if 子句現在式 passes，主句 will get。'),
(17, 'fill_blank', 'If we _____ (not / reduce) costs, the project will go over budget.', NULL, 'do not reduce', 'if 子句現在式，否定 do not reduce。'),
(17, 'multiple_choice', 'If you heat water to 100°C, it _____.', '["will boil","boiled","is boiling","boils"]', 'boils', '零條件句：科學事實，兩個現在式。'),
(17, 'multiple_choice', 'We will lose the client if we _____ to respond quickly.', '["are failing","failed","will fail","fail"]', 'fail', 'if 子句現在式 fail，主句 will lose。'),
(17, 'multiple_choice', 'If the team _____ the target, they will receive a bonus.', '["met","will meet","meets","is meeting"]', 'meets', 'if 子句現在式 meets，主句 will receive。'),
(17, 'transform', 'We might expand if we secure funding. (Use: will expand if we secure)', NULL, 'We will expand into new markets if we secure the necessary funding.', '第一條件句：will + if + 現在式。'),
(17, 'multiple_choice', 'If you press this button, the printer _____.', '["started","will start","is starting","starts"]', 'starts', '零條件句：操作指示，兩個現在式。'),
(17, 'fill_blank', 'If the weather _____ (be) good, the outdoor event will go ahead.', NULL, 'is', 'if 子句現在式 is，天氣預測。'),
(17, 'multiple_choice', 'If the client _____ by Friday, we will cancel the order.', '["will not confirm","has not confirmed","did not confirm","does not confirm"]', 'does not confirm', 'if 子句現在式否定 does not confirm。'),
(17, 'multiple_choice', 'Temperatures _____ if greenhouse gas emissions continue to rise.', '["will increase","increased","increase","are increasing"]', 'will increase', '第一條件句主句用 will increase 預測。'),
(17, 'multiple_choice', 'If you _____ your password, you can reset it online.', '["will forget","forgot","are forgetting","forget"]', 'forget', 'if 子句現在式 forget，零條件句操作說明。'),
(17, 'fill_blank', 'If the proposal _____ (approve) this week, work will begin immediately.', NULL, 'is approved', 'if 子句被動現在式 is approved。'),
(17, 'multiple_choice', 'She _____ the project if she gets the approval.', '["is managing","manages","managed","will manage"]', 'will manage', '主句 will manage，第一條件句。'),
(17, 'multiple_choice', 'If you _____ any questions, please contact our helpdesk.', '["have","will have","had","are having"]', 'have', 'if 子句現在式 have。'),
(17, 'transform', 'Assuming we sign the contract, we start next month. (Use: If we sign)', NULL, 'If we sign the contract this week, we will start next month.', '第一條件句：if + 現在式，will + 原形。'),
(17, 'fill_blank', 'If you _____ (not / leave) now, you will miss the train.', NULL, 'do not leave', 'if 子句否定現在式。'),
(17, 'multiple_choice', 'If the market _____ as expected, returns will be strong.', '["performs","performed","will perform","is performing"]', 'performs', 'if 子句現在式 performs。'),
(17, 'multiple_choice', 'Employees receive overtime pay if they _____ more than 40 hours a week.', '["work","worked","are working","will work"]', 'work', '零條件句：公司政策，兩個現在式。'),
(18, 'multiple_choice', 'If I _____ the manager, I would restructure the team.', '["were","am","was","be"]', 'were', '正式英語 if I were 用 were，第二條件句。'),
(18, 'multiple_choice', 'If we _____ more resources, we could finish ahead of schedule.', '["have","will have","had","would have"]', 'had', 'if 子句過去式 had，第二條件句。'),
(18, 'multiple_choice', 'She would apply for the promotion if she _____ more confident.', '["were","would be","was","is"]', 'were', '正式英語 if she were，第二條件句。'),
(18, 'fill_blank', 'If our pricing _____ (be) more competitive, we would win more clients.', NULL, 'were', '第二條件句 if 子句用 were。'),
(18, 'multiple_choice', 'What would you do if you _____ in charge?', '["were","are","would be","will be"]', 'were', 'if you were in charge 第二條件句 were。'),
(18, 'multiple_choice', 'If they _____ the investment, the company would expand faster.', '["increase","will increase","increased","would increase"]', 'increased', 'if 子句過去式 increased，主句 would expand。'),
(18, 'transform', 'We can''t reduce costs without cutting staff. (Use: If we could)', NULL, 'If we could reduce costs without cutting staff, we would do it immediately.', '第二條件句：假設我們有能力做到。'),
(18, 'multiple_choice', 'If the market _____ differently, we would need a new strategy.', '["behaves","would behave","will behave","behaved"]', 'behaved', 'if 子句過去式 behaved，第二條件句假設。'),
(18, 'fill_blank', 'I would attend the conference if I _____ (not / be) so busy.', NULL, 'were not', '第二條件句 if I were not，正式英語。'),
(18, 'multiple_choice', 'If the client _____ more time, we could deliver a better product.', '["would give","will give","gave","gives"]', 'gave', 'if 子句過去式 gave，第二條件句。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(18, 'multiple_choice', 'She would be able to lead the project if she _____ more experience.', '["had","will have","has","would have"]', 'had', 'if 子句過去式 had，第二條件句。'),
(18, 'multiple_choice', 'If we _____ a bigger budget, we could run a global campaign.', '["have","will have","would have","had"]', 'had', 'if 子句 had，第二條件句假設更多預算。'),
(18, 'transform', 'We don''t have time, so we can''t review everything. (Use: If we had)', NULL, 'If we had more time, we would review every aspect of the proposal.', '第二條件句假設有時間的情況。'),
(18, 'fill_blank', 'What would you recommend if you _____ (be) the consultant?', NULL, 'were', '正式第二條件句，if you were。'),
(18, 'multiple_choice', 'If the headquarters _____ in Asia, travel costs would be lower.', '["would be","is","was","were"]', 'were', 'if 子句 were，正式第二條件句。'),
(18, 'multiple_choice', 'He would accept the offer if the salary _____ higher.', '["is","would be","was","were"]', 'were', 'if the salary were 第二條件句正式用法。'),
(18, 'multiple_choice', 'If I _____ you, I would focus on client retention.', '["would be","am","were","was"]', 'were', 'If I were you 建議句型。'),
(18, 'fill_blank', 'If the partnership _____ (be) confirmed, we would announce it immediately.', NULL, 'were', '第二條件句 if 子句用 were。'),
(18, 'multiple_choice', 'The project would take less time if we _____ more staff.', '["hired","will hire","would hire","hire"]', 'hired', 'if 子句過去式 hired。'),
(18, 'multiple_choice', 'If they _____ the deal, it would be a major milestone.', '["secured","secure","would secure","will secure"]', 'secured', 'if 子句過去式 secured，第二條件句。'),
(19, 'multiple_choice', 'If we _____ earlier, we would have captured the market.', '["invested","have invested","had invested","would invest"]', 'had invested', 'if 子句過去完成式 had invested，第三條件句。'),
(19, 'multiple_choice', 'She would have got the promotion if she _____ the project.', '["has completed","would complete","completed","had completed"]', 'had completed', 'if 子句 had completed，第三條件句。'),
(19, 'fill_blank', 'If the team _____ (communicate) better, the misunderstanding would not have occurred.', NULL, 'had communicated', '第三條件句 if 子句 had communicated。'),
(19, 'multiple_choice', 'We would have met the deadline if there _____ no supply chain issues.', '["had been","was","had have","were"]', 'had been', 'if 子句 had been，第三條件句被動條件。'),
(19, 'multiple_choice', 'If I _____ the email earlier, I would have responded in time.', '["had seen","have seen","would see","saw"]', 'had seen', 'if 子句 had seen，第三條件句。'),
(19, 'multiple_choice', 'The project would have succeeded if we _____ a better team.', '["had assembled","have assembled","would assemble","assembled"]', 'had assembled', 'if 子句 had assembled，第三條件句。'),
(19, 'transform', 'We didn''t launch early enough. That''s why we lost market share. (Use: If we had launched)', NULL, 'If we had launched the product earlier, we would have gained more market share.', '第三條件句反思過去決策。'),
(19, 'fill_blank', 'If the budget _____ (approve) earlier, we would have started sooner.', NULL, 'had been approved', '第三條件句被動 had been approved。'),
(19, 'multiple_choice', 'She wouldn''t have resigned if she _____ a pay rise.', '["received","has received","had received","would receive"]', 'had received', 'if 子句 had received，第三條件句。'),
(19, 'multiple_choice', 'If the negotiations _____ longer, we might have reached a better deal.', '["would last","had lasted","have lasted","lasted"]', 'had lasted', 'if 子句 had lasted，第三條件句。'),
(19, 'multiple_choice', 'We _____ more if we had targeted a different demographic.', '["had sold","would have sold","sold","would sell"]', 'would have sold', '主句 would have sold，第三條件句結果。'),
(19, 'fill_blank', 'If they _____ (accept) our initial proposal, the project would have started in Q1.', NULL, 'had accepted', '第三條件句 if 子句 had accepted。'),
(19, 'multiple_choice', 'He would have attended the summit if he _____ been invited.', '["has","had","was","would have"]', 'had', 'if 子句 had been，第三條件句。'),
(19, 'transform', 'The deal fell through because we lacked preparation. (Use: If we had prepared)', NULL, 'If we had prepared more thoroughly, the deal would not have fallen through.', '第三條件句反思準備不足。'),
(19, 'multiple_choice', 'If the system _____ down, we would have lost all the data.', '["would crash","had crashed","has crashed","crashed"]', 'had crashed', 'if 子句 had crashed，第三條件句。'),
(19, 'multiple_choice', 'She would have become CEO if she _____ at the company longer.', '["would stay","has stayed","stayed","had stayed"]', 'had stayed', 'if 子句 had stayed，第三條件句。'),
(19, 'fill_blank', 'If we _____ (hire) more staff, we would not have missed the deadline.', NULL, 'had hired', '第三條件句 if 子句 had hired。'),
(19, 'multiple_choice', 'The launch would have been more successful if we _____ the market properly.', '["researched","had researched","would research","have researched"]', 'had researched', 'if 子句 had researched，第三條件句。'),
(19, 'multiple_choice', 'If I _____ the job offer, I would have moved to London.', '["accepted","would accept","had accepted","have accepted"]', 'had accepted', 'if 子句 had accepted，第三條件句。'),
(19, 'multiple_choice', 'They wouldn''t have run out of stock if they _____ demand correctly.', '["have forecast","had forecast","would forecast","forecast"]', 'had forecast', 'if 子句 had forecast，第三條件句。'),
(20, 'multiple_choice', 'If I _____ that job offer in 2020, I would be in New York now.', '["took","would take","had taken","take"]', 'had taken', 'if 子句 had taken（過去假設），主句 would be（現在結果）。'),
(20, 'multiple_choice', 'She would already be a director if she _____ the promotion.', '["accepts","accepted","had accepted","would accept"]', 'had accepted', '混合條件：had accepted 過去，would be 現在。'),
(20, 'fill_blank', 'If we _____ (invest) in that startup, we would be much wealthier now.', NULL, 'had invested', '混合條件：had invested 過去，would be 現在。'),
(20, 'multiple_choice', 'If the project _____ failed, the company would be in a much worse position today.', '["didn''t","wouldn''t have","had not","hasn''t"]', 'had not', 'had not failed（過去完成式否定），would be（現在）。'),
(20, 'multiple_choice', 'He wouldn''t be so stressed now if he _____ better at delegating.', '["were","would have been","had been","was"]', 'had been', '混合條件：had been 過去，wouldn''t be 現在。'),
(20, 'multiple_choice', 'If I _____ that business partnership, we might be global leaders today.', '["had not turned down","hadn''t turned down","didn''t turn down","won''t turn down"]', 'had not turned down', 'had not turned down 過去完成式否定。'),
(20, 'transform', 'We made a bad decision last year. That''s why we''re struggling now. (Use mixed conditional)', NULL, 'If we had made a better decision last year, we would not be struggling now.', '混合條件反思過去決策的現在影響。'),
(20, 'fill_blank', 'If she _____ (not / resign) last year, she would still be working here.', NULL, 'had not resigned', '混合條件：had not resigned 過去，would be 現在。'),
(20, 'multiple_choice', 'If the market _____ crashed in 2020, our investment would be thriving now.', '["wouldn''t have","didn''t","had not","hasn''t"]', 'had not', 'had not crashed 過去完成否定，would be thriving 現在結果。'),
(20, 'multiple_choice', 'He would be more fluent in English now if he _____ his studies earlier.', '["would start","has started","started","had started"]', 'had started', '混合條件：had started 過去，would be 現在。'),
(20, 'multiple_choice', 'If we _____ diversified earlier, we would be less vulnerable to market changes now.', '["had","have","did","would have"]', 'had', 'had diversified 過去完成，would be 現在結果。'),
(20, 'fill_blank', 'If they _____ (choose) a different supplier, delivery would not be an issue now.', NULL, 'had chosen', '混合條件：had chosen 過去假設，would not be 現在影響。'),
(20, 'multiple_choice', 'She wouldn''t have so many responsibilities now if she _____ every opportunity.', '["won''t seize","hadn''t seized","didn''t seize","hasn''t seized"]', 'hadn''t seized', '混合條件：hadn''t seized 過去，wouldn''t have 現在。'),
(20, 'multiple_choice', 'If the team _____ the right tools from the start, we would be much further along.', '["would use","had used","was using","used"]', 'had used', '混合條件：had used 過去，would be 現在。'),
(20, 'transform', 'He spent too much on advertising. Now the budget is tight. (Use mixed conditional)', NULL, 'If he had not spent so much on advertising, the budget would not be so tight now.', '混合條件：had not spent 過去，would not be 現在。'),
(20, 'fill_blank', 'If we _____ (build) that factory, our capacity would be double what it is today.', NULL, 'had built', '混合條件：had built 過去假設，would be 現在。'),
(20, 'multiple_choice', 'She might be fluent in Japanese now if she _____ the language course.', '["had completed","has completed","completed","would complete"]', 'had completed', '混合條件：had completed 過去，might be 現在。'),
(20, 'multiple_choice', 'If I _____ the networking event, I would already know the key clients.', '["had attended","have attended","attended","would attend"]', 'had attended', '混合條件：had attended 過去，would know 現在。'),
(20, 'fill_blank', 'The company _____ (be) more profitable now if they had controlled costs earlier.', NULL, 'would be', '混合條件主句：would be 現在結果。'),
(20, 'multiple_choice', 'If she _____ taken that scholarship, she would have a much stronger network now.', '["had","would have","has","was"]', 'had', 'had taken 過去，would have 現在。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(21, 'multiple_choice', '_____ you send me the revised proposal by Thursday?', '["Can","Will","Could","Should"]', 'Could', 'Could you 是更禮貌的請求方式，商業英語常用。'),
(21, 'multiple_choice', 'She _____ speak three languages fluently.', '["could","can","may","should"]', 'can', '描述現在的能力，用 can。'),
(21, 'multiple_choice', 'When I was a junior analyst, I _____ rarely attend senior meetings.', '["may","can","should","could"]', 'could', '過去的情況（when I was），用 could 表過去能力。'),
(21, 'fill_blank', '_____ I borrow your notes from the meeting?', NULL, 'Could', 'Could I 是禮貌請求許可的表達。'),
(21, 'multiple_choice', 'This feature _____ be implemented in the next software update.', '["could","can","should","will"]', 'could', 'could 表假設可能性，語氣較不確定。'),
(21, 'multiple_choice', 'The new system _____ process 1,000 transactions per second.', '["might","could","may","can"]', 'can', '描述系統現在的能力，用 can。'),
(21, 'multiple_choice', '_____ you explain this clause in the contract in more detail?', '["Could","Would","Can","Should"]', 'Could', 'Could you 更禮貌正式，商業英語偏好。'),
(21, 'transform', 'It is possible that we find a cheaper supplier. (Use: could find)', NULL, 'We could find a cheaper supplier if we expand our search.', 'could 表假設可能性。'),
(21, 'multiple_choice', 'The design team _____ create five mockups within two days.', '["can","should","could","may"]', 'can', 'can 表現在能力。'),
(21, 'fill_blank', '_____ she attend the conference in your place?', NULL, 'Could', 'Could she 詢問可能性或請求。'),
(21, 'multiple_choice', 'I _____ not reach the client all morning — the number was busy.', '["could","would","can","should"]', 'could', 'could not 過去無法，描述過去的失敗嘗試。'),
(21, 'multiple_choice', 'The project manager _____ assign tasks more efficiently.', '["can","should","could","must"]', 'could', 'could 表假設改進的可能性，比 should 更婉轉。'),
(21, 'multiple_choice', '_____ you please confirm your attendance by Friday?', '["Must","Could","Will","Can"]', 'Could', 'Could you please 是最禮貌的正式請求。'),
(21, 'fill_blank', 'She _____ not understand the technical jargon in the report.', NULL, 'could', 'could not 過去無法理解。'),
(21, 'multiple_choice', 'If we improve logistics, we _____ reduce delivery time by 20%.', '["could","can","will","should"]', 'could', 'could 表達假設條件下的可能性。'),
(21, 'multiple_choice', 'This opportunity _____ be very profitable for us.', '["must","should","could","can"]', 'could', 'could 表評估中的可能性，語氣謹慎。'),
(21, 'multiple_choice', 'She _____ type 80 words per minute when she was a secretary.', '["might","may","can","could"]', 'could', '過去能力用 could。'),
(21, 'transform', 'I want permission to work from home on Fridays. (Use: Could I)', NULL, 'Could I work from home on Fridays?', 'Could I 是禮貌請求許可的標準句型。'),
(21, 'multiple_choice', 'The team _____ complete the project ahead of schedule if they work overtime.', '["can","should","could","must"]', 'could', 'could 表條件下的可能性。'),
(21, 'multiple_choice', 'We _____ always outsource this task if our team is overloaded.', '["may","can","could","should"]', 'can', 'can 表現在存在的選項和能力。'),
(22, 'multiple_choice', 'All employees _____ complete the annual compliance training.', '["might","must","should","have to"]', 'must', 'must 表公司規定的強烈義務。'),
(22, 'multiple_choice', 'She _____ travel to five countries next month — it''s in her contract.', '["must","ought to","has to","should"]', 'has to', 'has to 表合約中的外在義務。'),
(22, 'multiple_choice', 'You _____ share confidential client data outside the company.', '["should not","must not","cannot","do not have to"]', 'must not', 'must not 表嚴格禁止，比 should not 更強烈。'),
(22, 'multiple_choice', 'Employees _____ work on Sundays unless it''s an emergency.', '["cannot","do not have to","must not","should not"]', 'do not have to', 'do not have to 表不必要，不是禁止。'),
(22, 'fill_blank', 'I _____ (finish) the report tonight — the board needs it tomorrow morning.', NULL, 'must finish', 'must 表強烈主觀義務。'),
(22, 'multiple_choice', 'She _____ be the new director — she was introduced as such.', '["must","has to","should","ought to"]', 'must', 'must 表邏輯推斷（她一定是...）。'),
(22, 'multiple_choice', 'We _____ meet the ISO certification requirements by Q4.', '["must","have to","ought to","should"]', 'have to', 'have to 表外在認證要求。'),
(22, 'multiple_choice', 'You _____ use a VPN when accessing the company server remotely.', '["should","have to","ought to","must"]', 'must', 'must 表 IT 安全規定的強制要求。'),
(22, 'transform', 'It is mandatory to wear a hard hat in the construction zone. (Use: must)', NULL, 'You must wear a hard hat in the construction zone at all times.', 'must 表嚴格規定。'),
(22, 'multiple_choice', 'I _____ make 20 client calls today — that''s my target.', '["need","must","have to","should"]', 'have to', 'have to 表外在業績目標的要求。'),
(22, 'multiple_choice', 'He _____ be exhausted — he worked 18 hours straight.', '["must","ought to","should","has to"]', 'must', 'must 表對現在情況的推斷。'),
(22, 'fill_blank', 'We _____ (disclose) all financial risks in the prospectus — it''s the law.', NULL, 'must disclose', '法律規定用 must 表強制義務。'),
(22, 'multiple_choice', 'You _____ leave the office during core hours without manager approval.', '["must not","should not","cannot","do not have to"]', 'must not', 'must not 表禁止行為。'),
(22, 'multiple_choice', 'They _____ submit monthly reports to the head office.', '["should","must","have to","ought to"]', 'have to', 'have to 表定期外在規定。'),
(22, 'multiple_choice', 'The certificate _____ be renewed every two years.', '["must","has to","should","ought to"]', 'has to', 'has to 表外在規定要求。'),
(22, 'fill_blank', 'You _____ (not/attend) the optional seminar if you are busy.', NULL, 'do not have to attend', 'do not have to 表不強制，非禁止。'),
(22, 'multiple_choice', 'This document _____ be the one signed by both parties.', '["has to","ought to","should","must"]', 'must', 'must 表根據邏輯的推斷。'),
(22, 'multiple_choice', 'She _____ clock in before 9 a.m. — it''s company policy.', '["ought to","must","should","has to"]', 'has to', 'has to 表公司外在政策。'),
(22, 'multiple_choice', 'All contracts _____ be reviewed by legal before signing.', '["ought to","should","have to","must"]', 'must', 'must 強調公司強制規定。'),
(22, 'multiple_choice', 'You _____ book a meeting room if it''s just a quick chat.', '["must not","do not have to","cannot","should not"]', 'do not have to', 'do not have to 表不必要，不是禁止。'),
(23, 'multiple_choice', 'You _____ proofread your emails before sending them to clients.', '["will","can","should","must"]', 'should', 'should 表建議最佳做法。'),
(23, 'multiple_choice', 'We _____ consider the risks before making a final decision.', '["can","ought","should","must"]', 'should', 'should 表建議考慮因素。'),
(23, 'multiple_choice', 'She _____ to request a meeting before the deadline.', '["must","should","can","ought"]', 'ought', 'ought to 和 should 意思相同，ought 後接 to。'),
(23, 'fill_blank', 'The report _____ (include) an executive summary for clarity.', NULL, 'should include', 'should 建議最佳做法。'),
(23, 'multiple_choice', 'Managers _____ give regular feedback to their team members.', '["should","can","might","must"]', 'should', 'should 表期望行為和建議。'),
(23, 'multiple_choice', 'The team _____ have more frequent progress updates.', '["would","should","must","can"]', 'should', 'should 建議改進做法。'),
(23, 'multiple_choice', 'According to the guidelines, all invoices _____ be processed within 30 days.', '["would","should","can","must"]', 'should', 'should 表期望和建議的標準做法。'),
(23, 'transform', 'It is advisable to back up your data regularly. (Use: should)', NULL, 'You should back up your data on a regular basis.', 'should 表建議。'),
(23, 'multiple_choice', 'We _____ have informed the client earlier about the delay.', '["must","would","can","should"]', 'should', 'should have 表對過去的後悔或批評（但本題是現在建議框架）。'),
(23, 'fill_blank', 'She _____ (consult) the legal team before signing any external agreements.', NULL, 'should consult', 'should 建議徵詢法律意見。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(23, 'multiple_choice', 'The presentation _____ be no longer than 30 minutes.', '["must","will","can","should"]', 'should', 'should 表建議長度，比 must 委婉。'),
(23, 'multiple_choice', 'He _____ arrive early to the interview to make a good impression.', '["could","must","should","can"]', 'should', 'should 建議最佳行為。'),
(23, 'multiple_choice', 'Staff _____ not use company resources for personal purposes.', '["might","can","must","should"]', 'should', 'should not 表不建議，比 must not 稍委婉。'),
(23, 'fill_blank', 'We _____ (review) the budget more carefully next time.', NULL, 'should review', 'should 表建議改進。'),
(23, 'multiple_choice', 'If there is a conflict of interest, employees _____ declare it.', '["should","must","would","can"]', 'should', 'should 表期望行為（declare 利益衝突）。'),
(23, 'multiple_choice', 'The contractor _____ have submitted the documents last week.', '["should","would","can","must"]', 'should', 'should have + p.p. 表對過去的批評。'),
(23, 'multiple_choice', 'All team members _____ attend the kickoff meeting.', '["might","should","can","must"]', 'should', 'should 表期望出席，比 must 稍委婉。'),
(23, 'transform', 'It is expected that you dress professionally. (Use: should)', NULL, 'You should dress professionally at all client meetings.', 'should 表期望行為。'),
(23, 'fill_blank', 'The project timeline _____ (update) whenever there are significant changes.', NULL, 'should be updated', 'should be + p.p. 被動建議。'),
(23, 'multiple_choice', 'He _____ to acknowledge the client''s concerns more empathetically.', '["can","ought","must","should"]', 'ought', 'ought to 同 should，表應該的行為。'),
(24, 'multiple_choice', 'The project _____ be delayed due to supply chain issues.', '["should","will","may","must"]', 'may', 'may 表可能性（50%左右）。'),
(24, 'multiple_choice', 'Sales _____ decline if we don''t improve our marketing strategy.', '["must","will","might","should"]', 'might', 'might 表較低確定性的預測。'),
(24, 'multiple_choice', '_____ I ask you to review this document before the meeting?', '["May","Can","Will","Should"]', 'May', 'May I 是非常正式的請求許可方式。'),
(24, 'fill_blank', 'The merger _____ (not / proceed) as planned if regulations change.', NULL, 'may not proceed', 'may not 表可能不會發生。'),
(24, 'multiple_choice', 'She _____ have the authority to sign this contract.', '["will","should","may","must"]', 'may', 'may 表不確定的可能性。'),
(24, 'multiple_choice', 'The conference _____ be moved online — nothing is confirmed yet.', '["will","should","must","might"]', 'might', 'might 強調更高的不確定性。'),
(24, 'multiple_choice', 'You _____ use the conference room if it''s available.', '["should","may","might","will"]', 'may', 'may 表正式許可使用。'),
(24, 'transform', 'It is possible that the price will increase next quarter. (Use: may increase)', NULL, 'The price may increase next quarter due to rising material costs.', 'may increase 表謹慎預測。'),
(24, 'multiple_choice', 'The results _____ not be what we expected.', '["will","should","must","may"]', 'may', 'may not 表可能不達預期。'),
(24, 'fill_blank', 'We _____ (need) to revise our timeline if the client requests changes.', NULL, 'might need', 'might 表較不確定的可能性。'),
(24, 'multiple_choice', 'There _____ be some unexpected costs associated with this project.', '["will","may","must","should"]', 'may', 'may be 表可能性，商業預測中常用。'),
(24, 'multiple_choice', 'The CEO _____ attend the meeting remotely.', '["will","must","may","should"]', 'may', 'may 表尚未確定的可能性。'),
(24, 'multiple_choice', 'This approach _____ not be suitable for all clients.', '["might","should","will","must"]', 'might', 'might not 較謹慎的否定可能性。'),
(24, 'fill_blank', 'The new product _____ (appeal) to a younger demographic.', NULL, 'may appeal', 'may 表商業可能性預測。'),
(24, 'multiple_choice', 'He _____ already be aware of the issue — let me check.', '["might","will","must","may"]', 'might', 'might 表較低確定性的猜測。'),
(24, 'multiple_choice', 'Profits _____ increase significantly if we enter the Asian market.', '["may","should","will","must"]', 'may', 'may 表條件性可能，語氣謹慎。'),
(24, 'multiple_choice', '_____ we proceed to the next agenda item?', '["Might","Can","Will","May"]', 'May', 'May we 是正式許可/請求。'),
(24, 'transform', 'There is a possibility that the deadline will be extended. (Use: might be extended)', NULL, 'The deadline might be extended, depending on progress.', 'might 表較不確定的可能。'),
(24, 'fill_blank', 'She _____ (not / be) available for the Thursday meeting.', NULL, 'may not be', 'may not be 表可能無法出席。'),
(24, 'multiple_choice', 'The new regulation _____ affect our supply chain operations.', '["must","might","may","will"]', 'may', 'may 表政策可能帶來的影響，謹慎語氣。'),
(25, 'multiple_choice', '_____ you be able to join the call this afternoon?', '["Would","Will","Should","Could"]', 'Would', 'Would you be able to 最禮貌的商業邀請/詢問。'),
(25, 'multiple_choice', 'When I was a junior analyst, I _____ prepare reports every Friday.', '["used to","could","will","would"]', 'would', 'would 表過去的規律性習慣。'),
(25, 'multiple_choice', 'I _____ recommend the premium package for your business needs.', '["could","would","should","will"]', 'would', 'I would recommend 委婉建議。'),
(25, 'fill_blank', '_____ you mind sending me the updated version by 5 p.m.?', NULL, 'Would', 'Would you mind 是非常禮貌的請求。'),
(25, 'multiple_choice', 'She said she _____ forward the documents later that day.', '["would","should","could","will"]', 'would', '間接引語中 will → would。'),
(25, 'multiple_choice', 'In the past, the team _____ hold daily briefings every morning.', '["would","will","could","should"]', 'would', 'would 表過去規律習慣。'),
(25, 'multiple_choice', 'He _____ like to schedule a meeting to discuss the proposal.', '["should","would","will","could"]', 'would', 'would like to 是禮貌表達意願的固定搭配。'),
(25, 'transform', 'Please give me your opinion on this. (Use: I would appreciate)', NULL, 'I would appreciate your thoughts on this proposal.', 'would appreciate 禮貌請求意見。'),
(25, 'multiple_choice', '_____ it be possible to extend the deadline by one week?', '["Could","Would","Should","Will"]', 'Would', 'Would it be possible to 是非常正式的商業請求。'),
(25, 'fill_blank', 'I _____ (not / advise) accepting the offer without legal review.', NULL, 'would not advise', 'would not advise 委婉建議不要。'),
(25, 'multiple_choice', 'If given the choice, she _____ prefer a hybrid work model.', '["should","will","would","could"]', 'would', 'would prefer 表假設偏好。'),
(25, 'multiple_choice', 'We _____ be happy to arrange a demonstration of our product.', '["should","would","will","could"]', 'would', 'would be happy to 禮貌答應商業請求。'),
(25, 'multiple_choice', 'He _____ often arrive early to prepare for the day ahead.', '["would","could","should","will"]', 'would', 'would 表過去的習慣行為。'),
(25, 'fill_blank', '_____ you be available for a call next Tuesday at 2 p.m.?', NULL, 'Would', 'Would you be available 商業日程安排的禮貌問法。'),
(25, 'multiple_choice', 'I _____ suggest reviewing the contract terms once more.', '["would","should","will","could"]', 'would', 'I would suggest 委婉建議。'),
(25, 'multiple_choice', 'The board _____ appreciate a more detailed financial analysis.', '["would","will","could","should"]', 'would', 'would appreciate 表假設的讚賞或期望。'),
(25, 'multiple_choice', 'In her previous role, she _____ manage a team of 20 people.', '["could","will","should","would"]', 'would', 'would 表過去職責的規律習慣。'),
(25, 'transform', 'Please accept our apology for the inconvenience. (Use: We would like to)', NULL, 'We would like to apologize for any inconvenience caused.', 'would like to 禮貌的商業道歉。'),
(25, 'fill_blank', 'This product _____ (suit) clients who prioritize efficiency.', NULL, 'would suit', 'would suit 條件性建議搭配。'),
(25, 'multiple_choice', 'I _____ not want to miss this opportunity if I were in your position.', '["will","could","would","should"]', 'would', 'would not want 表假設情況下的意願。');