INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(86, 'multiple_choice', 'Please find the _____ for your recent order attached to this email.', '["invoice","account","receipt","bill"]', 'invoice', 'invoice 發票（向客戶請款的帳單），receipt 收據（已付款證明）。'),
(86, 'multiple_choice', 'The company sent out a _____ to inform employees about the new policy.', '["memo","bulletin","notice","announcement"]', 'memo', 'memo（備忘錄）通常指公司內部通知。'),
(86, 'multiple_choice', 'We need to finalize the _____ before the deal can go through.', '["deal","paper","contract","agreement"]', 'contract', 'finalize the contract 最終確定合約，最準確。'),
(86, 'fill_blank', 'The goods will be _____ within three business days of receiving payment.', NULL, 'dispatched / shipped', 'dispatched/shipped 出貨，商業英語常用。'),
(86, 'multiple_choice', 'She is responsible for _____ new talent for the organization.', '["employing to","staffing up","hiring out","recruiting"]', 'recruiting', 'recruiting new talent 招募新人才，固定搭配。'),
(86, 'multiple_choice', 'The _____ terms state that payment is due within 30 days.', '["financial","billing","payment","invoice"]', 'payment', 'payment terms 付款條件，固定搭配。'),
(86, 'multiple_choice', 'We need to review the _____ before signing to ensure all terms are acceptable.', '["criteria and standards","policies and procedures","rules and regulations","terms and conditions"]', 'terms and conditions', 'terms and conditions 條款細則，合約必備。'),
(86, 'fill_blank', 'Could you provide us with a _____ for the services you will provide?', NULL, 'quotation / quote', 'quotation/quote 報價單，正式商業文件。'),
(86, 'multiple_choice', 'The _____ meeting gave employees a chance to raise concerns about the restructuring.', '["staff","town hall","company","group"]', 'town hall', 'town hall meeting 全員大會，商業英語術語。'),
(86, 'multiple_choice', 'She was given a _____ for her outstanding contribution to the project.', '["reward","raise","bonus","promotion"]', 'bonus', 'bonus 獎金（非加薪 raise，非晉升 promotion）。'),
(86, 'multiple_choice', 'Please submit your _____ form for the expenses incurred during your business trip.', '["invoice","payment","reimbursement","claim"]', 'reimbursement', 'reimbursement form 費用報銷表格，最準確。'),
(86, 'fill_blank', 'The client requested a _____ on the price for placing a large order.', NULL, 'discount / reduction', 'discount 折扣，commercial 英語常見。'),
(86, 'multiple_choice', 'The new marketing _____ increased brand awareness significantly.', '["program","project","initiative","campaign"]', 'campaign', 'marketing campaign 行銷活動，最常見搭配。'),
(86, 'multiple_choice', 'She was asked to prepare a _____ of the meeting for distribution.', '["notes","transcript","minutes","record"]', 'minutes', 'minutes of a meeting 會議記錄，固定搭配。'),
(86, 'multiple_choice', 'We would like to place an _____ for 500 units of your product.', '["application","request","inquiry","order"]', 'order', 'place an order 下訂單，固定搭配。'),
(86, 'fill_blank', 'The company''s annual _____ showed strong revenue growth.', NULL, 'report / financial results', 'annual report 年度報告，常見商業文件。'),
(86, 'multiple_choice', 'The _____ department handles all compensation and benefits issues.', '["Personnel","Staffing","Human Resources","Employee"]', 'Human Resources', 'Human Resources（HR）人力資源部門，最通用。'),
(86, 'multiple_choice', 'We are currently _____ a new software development partner.', '["searching","finding","seeking","looking"]', 'seeking', 'seeking a partner 尋求合作夥伴，正式動詞。'),
(86, 'fill_blank', 'Please _____ the attached document and return it signed.', NULL, 'review / sign', 'review and sign 審閱並簽署。'),
(86, 'multiple_choice', 'The _____ for the new CEO position attracted over 200 applicants.', '["bulletin","announcement","advertisement","job posting"]', 'job posting', 'job posting 職位公告，數位時代最常用。'),
(87, 'multiple_choice', 'The company reported a _____ of $2 million due to unexpected costs.', '["deficit","deficiency","loss","shortage"]', 'deficit', 'deficit 赤字/虧損，財務術語。'),
(87, 'multiple_choice', 'Our top priority this year is _____ — keeping our existing clients happy.', '["customer service","client management","customer retention","account handling"]', 'customer retention', 'customer retention 客戶保留率，商業策略關鍵詞。'),
(87, 'multiple_choice', 'The _____ year runs from April to March in our company.', '["fiscal","annual","financial","accounting"]', 'fiscal', 'fiscal year 財政年度，正式財務術語。'),
(87, 'multiple_choice', 'The two companies announced a _____ that will create the largest firm in the sector.', '["merger","alliance","acquisition","partnership"]', 'merger', 'merger 合併（兩公司合為一）；acquisition 收購（一方買下另一方）。'),
(87, 'fill_blank', 'The company''s _____ grew by 15% compared to the same period last year.', NULL, 'revenue / turnover', 'revenue 收入，financial 核心指標。'),
(87, 'multiple_choice', 'She has a strong _____ record — she has never missed a deadline.', '["job","performance","track","work"]', 'track', 'track record 業績記錄，固定搭配。'),
(87, 'multiple_choice', 'We need to improve our _____ process to attract better candidates.', '["recruitment","staffing","hiring","employment"]', 'recruitment', 'recruitment process 招募流程，正式 HR 術語。'),
(87, 'fill_blank', 'The board approved a major _____ to streamline operations and reduce headcount.', NULL, 'restructuring', 'restructuring 重組，商業策略術語。'),
(87, 'multiple_choice', 'She serves as a _____ between the client and the technical team.', '["go-between","bridge","liaison","contact"]', 'liaison', 'liaison 聯絡員/中間人，正式商業術語。'),
(87, 'multiple_choice', 'The company filed for _____ after failing to repay its debts.', '["bankruptcy","closure","insolvency","liquidation"]', 'bankruptcy', 'bankruptcy 破產，法律商業術語。'),
(87, 'multiple_choice', 'We need to allocate more resources to _____ development.', '["goods","product","item","merchandise"]', 'product', 'product development 產品開發，固定搭配。'),
(87, 'fill_blank', 'The new acquisition will _____ our market position significantly.', NULL, 'strengthen / enhance', 'strengthen/enhance our position 鞏固/提升市場地位。'),
(87, 'multiple_choice', 'She was given _____ to negotiate directly with the supplier.', '["allowance","ability","permission","authorization"]', 'authorization', 'authorization 授權，正式商業術語。'),
(87, 'multiple_choice', 'The _____ of the company''s shares fell sharply following the announcement.', '["rate","worth","price","value"]', 'value', 'value of shares 股票價值，financial 術語。'),
(87, 'multiple_choice', 'We need to reduce our _____ costs to improve profit margins.', '["fixed","running","operational","overhead"]', 'overhead', 'overhead costs 間接成本/管理費用，financial 術語。'),
(87, 'fill_blank', 'The client submitted a formal _____ about the quality of our service.', NULL, 'complaint', 'complaint 正式投訴，商業英語。'),
(87, 'multiple_choice', 'The company set an _____ target of 20% revenue growth next year.', '["optimistic","realistic","ambitious","aggressive"]', 'ambitious', 'ambitious target 雄心勃勃的目標，正面語境。'),
(87, 'multiple_choice', 'She is in charge of _____ with key industry partners.', '["networking","communicating","collaborating","liaising"]', 'liaising', 'liaising with partners 與合作夥伴保持聯繫，正式動詞。'),
(87, 'fill_blank', 'All employees must sign a _____ (non-disclosure agreement) before starting.', NULL, 'non-disclosure agreement / NDA', 'NDA 保密協議，商業英語縮寫。'),
(87, 'multiple_choice', 'The company signed a _____ with a major retailer to distribute its products.', '["retail deal","trade contract","sales contract","distribution agreement"]', 'distribution agreement', 'distribution agreement 分銷協議，正式商業術語。'),
(88, 'multiple_choice', 'The two sides reached a _____ after weeks of difficult talks.', '["agreement","compromise","settlement","deal"]', 'compromise', 'reach a compromise 達成妥協，談判術語。'),
(88, 'multiple_choice', 'He _____ the task to his assistant to free up time for strategic work.', '["transferred","gave","delegated","assigned"]', 'delegated', 'delegate a task 委派任務，管理術語。'),
(88, 'multiple_choice', 'The company''s _____ revenue grew by 30% thanks to its new app.', '["digital","internet","online","tech"]', 'digital', 'digital revenue 數位收入，現代商業術語。'),
(88, 'fill_blank', 'The startup''s _____ model is designed to serve millions of users without extra costs.', NULL, 'scalable / scalability', 'scalable business model 可擴展商業模式。'),
(88, 'multiple_choice', 'Her _____ of industry trends allowed her to anticipate market shifts.', '["awareness","knowledge","grasp","understanding"]', 'knowledge', 'knowledge of 對...的瞭解，knowledge of industry trends 最自然。'),
(88, 'multiple_choice', 'The company is trying to _____ its brand in the competitive market.', '["differentiate","separate","distinguish","isolate"]', 'differentiate', 'differentiate a brand 讓品牌差異化，商業策略術語。'),
(88, 'multiple_choice', 'We need to assess the _____ of opening a new branch in that market.', '["possibility","probability","feasibility","viability"]', 'feasibility', 'feasibility 可行性，assess the feasibility 評估可行性。'),
(88, 'fill_blank', 'The new product was a _____ technology that changed how people communicate.', NULL, 'disruptive', 'disruptive technology 顛覆性科技，現代商業術語。'),
(88, 'multiple_choice', 'She has a strong _____ and is known for meeting her targets consistently.', '["values","morals","standards","work ethic"]', 'work ethic', 'work ethic 工作道德/勤勉，固定搭配。'),
(88, 'multiple_choice', 'The company offered a _____ to the client to make up for the delivery delay.', '["concession","compensation","discount","benefit"]', 'concession', 'concession 讓步/優惠，談判術語。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(88, 'multiple_choice', 'The annual _____ with external auditors is a regulatory requirement.', '["inspection","audit","review","check"]', 'audit', 'audit 審計，formal financial inspection。'),
(88, 'fill_blank', 'She _____ successfully between the two competing factions to reach an agreement.', NULL, 'mediated / negotiated', 'mediate/negotiate between parties 調解/談判。'),
(88, 'multiple_choice', 'He presented a _____ case for investing in the new technology.', '["good","strong","convincing","compelling"]', 'compelling', 'compelling case 有說服力的論點，商業提案術語。'),
(88, 'multiple_choice', 'The company''s _____ structure was simplified to improve decision-making speed.', '["corporate","organizational","management","company"]', 'organizational', 'organizational structure 組織架構，管理術語。'),
(88, 'multiple_choice', 'All parties must _____ to the confidentiality clause in the contract.', '["hold","adhere","stick","follow"]', 'adhere', 'adhere to 遵守，正式法律/商業術語。'),
(88, 'fill_blank', 'The firm announced it would _____ its non-core assets to focus on its main business.', NULL, 'divest / sell off', 'divest 出售非核心資產，商業策略術語。'),
(88, 'multiple_choice', 'She presented a _____ plan with three phases covering the next five years.', '["management","strategic","operational","business"]', 'strategic', 'strategic plan 策略計劃，固定搭配。'),
(88, 'multiple_choice', 'The _____ of the deal fell through at the last minute.', '["ending","closing","completion","finalization"]', 'finalization', 'finalization of a deal 最終確定交易，名詞化形式。'),
(88, 'fill_blank', 'The company''s _____ (market capitalization) exceeded $10 billion last year.', NULL, 'market capitalization / market cap', 'market cap 市值，重要財務術語。'),
(88, 'multiple_choice', 'His _____ approach to management earned him a reputation as a great leader.', '["collaborative","cooperative","joint","team"]', 'collaborative', 'collaborative approach 協作方式，管理術語。'),
(89, 'multiple_choice', 'In a business email, ''Please find attached...'' means:', '["Please look for the attachment.","Please attach a document.","The attachment is included with the email.","The document will be sent later."]', 'The attachment is included with the email.', 'Please find attached 表附件已附上。'),
(89, 'multiple_choice', 'What does ''As per our previous discussion'' indicate in an email?', '["The writer is referring back to an earlier conversation.","The writer is disagreeing.","The writer is starting a new topic.","The writer is apologising."]', 'The writer is referring back to an earlier conversation.', 'as per 表依照，referring to earlier discussion。'),
(89, 'multiple_choice', 'In a job posting, ''competitive salary'' most likely means:', '["A salary that involves competition.","A salary that compares well with industry standards.","A salary that is the highest available.","A salary that is challenging to earn."]', 'A salary that compares well with industry standards.', 'competitive salary 有競爭力的薪資，與業界相當。'),
(89, 'fill_blank', 'In a business letter, ''We regret to inform you...'' is used to deliver _____  news.', NULL, 'negative / bad', 'regret to inform 表遺憾地通知，傳遞壞消息。'),
(89, 'multiple_choice', 'What does ''cc:'' mean in an email header?', '["The email is from the CEO.","The email has been copied to additional recipients.","The email needs confirmation.","The email content is confidential."]', 'The email has been copied to additional recipients.', 'cc = carbon copy，副本收件人。'),
(89, 'multiple_choice', 'In a memo, ''effective immediately'' means:', '["The change has been effective for a while.","The change or instruction starts right away.","The change may be effective in the future.","The change will be effective eventually."]', 'The change or instruction starts right away.', 'effective immediately 立即生效。'),
(89, 'multiple_choice', 'A ''cover letter'' in a job application is:', '["A letter introducing yourself and explaining your interest in the position.","A summary of your work experience.","A reference from a previous employer.","A list of your qualifications."]', 'A letter introducing yourself and explaining your interest in the position.', 'cover letter 求職信，介紹自己與申請原因。'),
(89, 'transform', 'What does ''Subject to change without notice'' mean in a price list? (Explain in English)', NULL, 'It means prices may change at any time and the company does not have to inform customers in advance.', 'subject to change without notice 隨時可能改變，不另行通知。'),
(89, 'multiple_choice', 'In a notice, ''This supersedes all previous versions'' means:', '["This is the most current version and replaces all older ones.","This is the first version.","This has been approved by all departments.","This corrects errors in the last version."]', 'This is the most current version and replaces all older ones.', 'supersede 取代，表此版本為最新官方版本。'),
(89, 'multiple_choice', 'What does ''please RSVP by Friday'' mean?', '["Please arrive no later than Friday.","Please respond to survey questions by Friday.","Please read and review the invitation by Friday.","Please confirm whether you will attend by Friday."]', 'Please confirm whether you will attend by Friday.', 'RSVP = Répondez s''il vous plaît（法文），請回覆確認出席。'),
(89, 'multiple_choice', 'In a business report, ''Q3'' refers to:', '["The third question in a survey.","The third goal of the project.","The third item on the agenda.","The third quarter of the financial year."]', 'The third quarter of the financial year.', 'Q3 = Quarter 3，第三季。'),
(89, 'fill_blank', '''The meeting has been postponed until further notice'' means it has been _____.', NULL, 'cancelled / delayed indefinitely', 'postponed until further notice 暫時延期，無新日期。'),
(89, 'multiple_choice', 'What is an ''agenda'' in the context of a meeting?', '["The minutes of the previous meeting.","A list of attendees.","A summary of decisions made.","A list of topics to be discussed during the meeting."]', 'A list of topics to be discussed during the meeting.', 'agenda 會議議程，討論事項清單。'),
(89, 'multiple_choice', 'In a business context, ''ROI'' stands for:', '["Rate of Inflation","Return on Investment","Revenue over Income","Results of Implementation"]', 'Return on Investment', 'ROI = Return on Investment 投資報酬率。'),
(89, 'multiple_choice', 'If a contract is ''null and void'', it means:', '["The contract is valid and enforceable.","The contract has expired.","The contract has no legal force.","The contract needs revision."]', 'The contract has no legal force.', 'null and void 無效，不具法律效力。'),
(89, 'transform', 'What does ''The figures are subject to revision'' mean in a report?', NULL, 'It means the figures may be updated or changed later, and the current figures are not final.', 'subject to revision 可能修訂，非最終數字。'),
(89, 'fill_blank', 'In a job advertisement, ''competitive benefits package'' refers to salary, _____, and other perks.', NULL, 'healthcare / bonuses / paid leave', 'benefits package 福利套餐，包含薪資外的各種福利。'),
(89, 'multiple_choice', '''FYI'' in an email subject line means:', '["For Your Immediate response","From Your Inbox","For Your Information — no action required.","Follow Up Instructions"]', 'For Your Information — no action required.', 'FYI = For Your Information 供您參考。'),
(89, 'multiple_choice', 'A ''bottom line'' in business refers to:', '["The net profit or loss of a company.","The final sentence of a report.","The last point in a presentation.","The baseline budget."]', 'The net profit or loss of a company.', 'bottom line 最終損益，常引申為最重要的結果。'),
(89, 'multiple_choice', 'In business correspondence, ''enclosed please find'' means:', '["Please prepare the enclosed document.","Please search for the enclosed document.","The document will be sent separately.","The mentioned document is included with the letter."]', 'The mentioned document is included with the letter.', 'enclosed please find = please find enclosed 信中附上文件。'),
(90, 'multiple_choice', 'The number of employees in this branch _____ increased.', '["have","were","are","has"]', 'has', 'the number of 作主語，動詞用單數 has。'),
(90, 'multiple_choice', 'A number of issues _____ been identified.', '["have","is","was","has"]', 'have', 'a number of 作主語，動詞用複數 have。'),
(90, 'multiple_choice', 'Each of the candidates _____ required to submit a portfolio.', '["are","is","have been","were"]', 'is', 'each of + 複數名詞，動詞用單數 is。'),
(90, 'fill_blank', 'Neither the CEO nor the managers _____ available for comment.', NULL, 'were', 'neither...nor 就近原則，managers 複數，were。'),
(90, 'multiple_choice', 'Not only the sales team but also the director _____ attending the summit.', '["have been","were","is","are"]', 'is', 'not only...but also 就近原則，director 單數，is。'),
(90, 'multiple_choice', 'The staff _____ notified about the policy change.', '["were","is","has been","was"]', 'were', 'staff 通常視為複數（集合名詞），were。'),
(90, 'multiple_choice', 'All of the information _____ been verified.', '["has","have","are","were"]', 'has', 'all of + 不可數名詞 information，動詞單數 has。'),
(90, 'multiple_choice', 'Either the manager or the assistants _____ responsible.', '["is","are","have been","were"]', 'are', 'either...or 就近原則，assistants 複數，are。'),
(90, 'fill_blank', 'The board of directors _____ a meeting next Tuesday.', NULL, 'is holding', 'board of directors 集合名詞（正式英語多用單數）is holding。'),
(90, 'multiple_choice', 'There _____ several problems with the proposal.', '["were","is","are","has been"]', 'are', 'there are + 複數名詞 problems。'),
(90, 'multiple_choice', 'The team''s performance _____ improved significantly.', '["were","have","has","are"]', 'has', 'team''s performance 主語單數，has improved。'),
(90, 'multiple_choice', 'None of the applications _____ complete.', '["was","are","has been","is"]', 'are', 'none of + 複數名詞，可接複數（informal: none are）。'),
(90, 'multiple_choice', 'The data _____ clearly showing an upward trend.', '["is","have been","were","are"]', 'is', 'data 作不可數名詞時，is（現代用法）。'),
(90, 'fill_blank', 'A series of workshops _____ scheduled for the new hires.', NULL, 'has been / is', 'a series of 集合名詞，單數動詞。'),
(90, 'multiple_choice', 'Both the quality and the cost _____ need to be considered.', '["of the product","product''s","products''","of product"]', 'of the product', 'both...and 後，動詞複數（need），of the product 修飾兩者。'),
(90, 'multiple_choice', 'Each department _____ submit its report by the end of the month.', '["must their own","must they","must","must their"]', 'must', 'each department 單數，must + 原形動詞。'),
(90, 'multiple_choice', 'More than one application _____ been disqualified.', '["were","are","has","have"]', 'has', 'more than one + 單數名詞，動詞用單數 has。'),
(90, 'fill_blank', 'The committee _____ (decide) on the final candidate last week.', NULL, 'decided', 'committee 集合名詞（正式英語單數），decided。'),
(90, 'multiple_choice', 'Economics _____ the study of how resources are allocated.', '["is","have been","are","were"]', 'is', 'Economics 學科名稱用單數 is。'),
(90, 'multiple_choice', 'Ten years _____ a long time to commit to any project.', '["is","were","are","have been"]', 'is', 'ten years as a concept of duration = single unit，is。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(91, 'multiple_choice', 'She is _____ charge of the entire Asia-Pacific marketing division.', '["in","on","at","for"]', 'in', 'in charge of 負責，固定搭配。'),
(91, 'multiple_choice', 'We need to _____ out a full audit before the end of the quarter.', '["do","take","make","carry"]', 'carry', 'carry out 執行/進行，固定搭配。'),
(91, 'multiple_choice', 'The meeting has been _____ off until next week.', '["put","moved","set","taken"]', 'put', 'put off 推遲，片語動詞。'),
(91, 'fill_blank', 'She is looking _____ to working with the new team.', NULL, 'forward', 'look forward to 期待，固定搭配。'),
(91, 'multiple_choice', 'We had to _____ with several complaints from clients this week.', '["manage","cope","handle","deal"]', 'deal', 'deal with 處理，固定片語動詞。'),
(91, 'multiple_choice', 'The project was _____ off due to budget constraints.', '["set","taken","put","called"]', 'called', 'called off 取消，片語動詞。'),
(91, 'multiple_choice', 'Please _____ back to me by tomorrow with your decision.', '["respond","reply","come","get"]', 'get', 'get back to someone 回覆，片語動詞。'),
(91, 'fill_blank', 'We need to _____ on a decision before the client arrives.', NULL, 'agree', 'agree on a decision 就某事達成一致。'),
(91, 'multiple_choice', 'The new policy will _____ into effect next Monday.', '["make","come","go","take"]', 'come', 'come into effect 生效，固定搭配。'),
(91, 'multiple_choice', 'She was _____ up for a promotion after her outstanding performance.', '["stood","put","set","raised"]', 'put', 'put someone up for 提名，片語動詞。'),
(91, 'multiple_choice', 'He _____ through all the reports in record time.', '["looked","ran","went","read"]', 'went', 'go through 仔細閱讀/審閱，片語動詞。'),
(91, 'fill_blank', 'We need to _____ up with a new marketing strategy for Q3.', NULL, 'come', 'come up with 想出，片語動詞。'),
(91, 'multiple_choice', 'The CEO _____ out the company''s five-year plan at the AGM.', '["set","drew","put","laid"]', 'laid', 'lay out 詳細說明，片語動詞。'),
(91, 'multiple_choice', 'The company _____ in on a deal worth $10 million.', '["cashed","came","broke","moved"]', 'cashed', 'cash in on 從中獲利，片語動詞。'),
(91, 'multiple_choice', 'He was asked to _____ for the director at the meeting.', '["substitute to","fill up","stand in","cover over"]', 'stand in', 'stand in for 代替，片語動詞。'),
(91, 'fill_blank', 'Please _____ on the key points only — we have limited time.', NULL, 'focus', 'focus on 專注於，片語動詞。'),
(91, 'multiple_choice', 'The deal is still _____ — we haven''t confirmed it yet.', '["up the air","up in the air","in the air","on the air"]', 'up in the air', 'up in the air 懸而未決，固定習語。'),
(91, 'multiple_choice', 'She _____ up the courage to ask for a raise.', '["gained","worked","built","found"]', 'worked', 'work up the courage 鼓起勇氣，固定搭配。'),
(91, 'multiple_choice', 'We need to _____ down the cost of each component.', '["divide","cut","break","split"]', 'break', 'break down 分解，片語動詞。'),
(91, 'multiple_choice', 'The client _____ through on their promise and paid on time.', '["came","held","followed","went"]', 'came', 'come through 兌現承諾，片語動詞。'),
(92, 'multiple_choice', 'The company made a major _____ in the new factory.', '["investment","invest","investing","invested"]', 'investment', '空格需名詞，investment（-ment 名詞字尾）。'),
(92, 'multiple_choice', 'She was _____ promoted to regional director after just two years.', '["recent","recentness","recently","recency"]', 'recently', '空格需副詞修飾 promoted，recently（-ly）。'),
(92, 'multiple_choice', 'The _____ of the product launch was widely praised.', '["executing","execution","execute","executive"]', 'execution', '空格需名詞，execution（-tion 名詞字尾）。'),
(92, 'fill_blank', 'The company is committed to _____ (sustain) its growth over the next decade.', NULL, 'sustaining / sustainable growth', 'sustaining 動名詞作受語。'),
(92, 'multiple_choice', 'Her _____ analysis of the market proved invaluable.', '["thoroughness","thoroughly","thoroughly","thorough"]', 'thorough', '空格需形容詞修飾 analysis，thorough。'),
(92, 'multiple_choice', 'The process was completed very _____.', '["efficient","efficiency","efficientness","efficiently"]', 'efficiently', '空格需副詞修飾動詞，efficiently（-ly）。'),
(92, 'multiple_choice', 'There has been significant _____ in our customer satisfaction scores.', '["improvement","improve","improving","improved"]', 'improvement', '空格需名詞，improvement（-ment）。'),
(92, 'fill_blank', 'The team was highly _____ (motivate) by the CEO''s speech.', NULL, 'motivated', 'motivated 過去分詞作形容詞。'),
(92, 'multiple_choice', 'She gave a very _____ presentation.', '["impress","impressive","impressively","impression"]', 'impressive', '空格需形容詞修飾名詞，impressive（-ive）。'),
(92, 'multiple_choice', 'The _____ of all employees must be verified.', '["identity","identify","identifying","identified"]', 'identity', '空格需名詞，identity（-ity 名詞字尾）。'),
(92, 'multiple_choice', 'He spoke _____ about the company''s plans.', '["confidence","confidently","confident","confidently"]', 'confidently', '空格需副詞修飾動詞 spoke，confidently（-ly）。'),
(92, 'fill_blank', 'The _____ (manage) team met to discuss the restructuring plan.', NULL, 'management', 'management team 管理團隊，名詞 management。'),
(92, 'multiple_choice', 'We need to _____ our processes to reduce costs.', '["streamlines","streamlined","streamline","streamlining"]', 'streamline', '空格需動詞（need to + 原形），streamline。'),
(92, 'multiple_choice', 'Her attention to _____ is what sets her apart.', '["details","detail","detailing","detailed"]', 'detail', 'attention to detail 固定搭配，名詞 detail。'),
(92, 'multiple_choice', 'The new system is remarkably _____ to operate.', '["ease","easily","easier","easy"]', 'easy', '空格需形容詞（is + 形容詞），easy。'),
(92, 'transform', 'The project''s success depended on the team''s cooperation. (Find the verb form)', NULL, 'The team cooperated effectively, ensuring the project''s success.', 'cooperated 是動詞形式；cooperation 是名詞。'),
(92, 'fill_blank', 'She has extensive _____ (know) in this field.', NULL, 'knowledge', 'knowledge 是 know 的名詞形式。'),
(92, 'multiple_choice', 'He is _____ for his creative approach to problem-solving.', '["renowned","renown","renownedly","renowning"]', 'renowned', 'renowned 知名的，形容詞。'),
(92, 'multiple_choice', 'The company places great _____ on teamwork.', '["emphasis","emphasizing","emphatic","emphasize"]', 'emphasis', '空格需名詞，place emphasis on 強調。'),
(92, 'multiple_choice', 'The _____ of the new policy was handled smoothly.', '["implementing","implementation","implement","implemented"]', 'implementation', '空格需名詞，implementation（-tion）。'),
(93, 'multiple_choice', 'Which sentence is grammatically correct?', '["She has worked here from 2018.","She has been working here since 2018.","She works here since 2018.","She is working here since 2018."]', 'She has been working here since 2018.', 'since + 完成式，has been working 正確。'),
(93, 'multiple_choice', 'Which sentence is correct?', '["The report will submit by Friday.","The report will be submitted by Friday.","The report will be submit by Friday.","The report be submitted by Friday."]', 'The report will be submitted by Friday.', 'will be submitted 未來被動式正確。'),
(93, 'multiple_choice', 'Which sentence has a grammatical error?', '["He waited for two hours.","He has been waiting since two hours.","He has been waiting for two hours.","He has been waiting since 10 a.m."]', 'He has been waiting since two hours.', 'since + 時間點（since 10 a.m.）；for + 時間段（for two hours）。'),
(93, 'fill_blank', 'Find the error: ''The staffs were informed about the change.'' → Correct: _____.', NULL, 'The staff were informed about the change.', 'staff 不可數/集合名詞，不加 s。'),
(93, 'multiple_choice', 'Which sentence is correct?', '["Neither he nor she were present.","Neither he nor she was present.","Neither he nor her were present.","Neither him nor her was present."]', 'Neither he nor she was present.', 'he/she 主格；neither...nor + 單數動詞 was。'),
(93, 'multiple_choice', 'Which is correct?', '["The project must be complete on time.","The project must completed on time.","The project must be completed on time.","The project must to be completed on time."]', 'The project must be completed on time.', 'must be + p.p. 情態動詞被動，completed 不是 complete。'),
(93, 'multiple_choice', 'Which sentence has a grammatical error?', '["She got used to working late.","She is used to work late.","She is used to working late.","She was used to working late."]', 'She is used to work late.', 'be used to + V-ing 習慣於，不是 to + 原形。'),
(93, 'fill_blank', 'Find the error: ''We are looking forward to hear from you.'' → Correct: _____.', NULL, 'We are looking forward to hearing from you.', 'look forward to + V-ing，不是 to + 原形。'),
(93, 'multiple_choice', 'Which sentence is correct?', '["The client, whom I met yesterday, was very impressed.","The client, who I met yesterday, was very impressed.","The client, that I met yesterday, was very impressed.","The client, which I met yesterday, was very impressed."]', 'The client, who I met yesterday, was very impressed.', 'whom（受格）用於受詞關係代名詞（正式）；who 也可接受，which/that 在非限定子句中不適用。'),
(93, 'multiple_choice', 'Which sentence has a grammatical error?', '["In spite of the rain, the event was a success.","Despite of the rain, the event was a success.","Despite the rain, the event was a success.","Although it rained, the event was a success."]', 'Despite of the rain, the event was a success.', 'despite + 名詞短語，不需要 of；despite of 是錯誤用法。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(93, 'multiple_choice', 'Which is correct?', '["He was very tired that he couldn''t concentrate.","He was such tired that he couldn''t concentrate.","He was so tired that he couldn''t concentrate.","He was too tired that he couldn''t concentrate."]', 'He was so tired that he couldn''t concentrate.', 'so + 形容詞 + that 結果子句正確。'),
(93, 'fill_blank', 'Find the error: ''I look forward to hear from you soon.'' → Correct: _____.', NULL, 'I look forward to hearing from you soon.', 'look forward to + V-ing。'),
(93, 'multiple_choice', 'Which sentence is correct?', '["All employees are required attend the meeting.","All employees are required to attend the meeting.","All employees are require to attend the meeting.","All employees required to attend the meeting."]', 'All employees are required to attend the meeting.', 'are required to + 原形，被動式不定詞。'),
(93, 'multiple_choice', 'Which sentence has an error?', '["We discussed about the budget in detail.","We talked about the budget in detail.","We went over the budget in detail.","We discussed the budget in detail."]', 'We discussed about the budget in detail.', 'discuss 直接接受語（不需 about），discussed about 是錯誤用法。'),
(93, 'multiple_choice', 'Which is correct?', '["The manager together with her team are attending.","The manager, together with her team, are attending the summit.","The manager, together with her team, is attending the summit.","The manager and her team is attending the summit."]', 'The manager, together with her team, is attending the summit.', 'together with 不影響主語（manager），動詞用單數 is。'),
(93, 'transform', 'Find and correct the error: ''She suggested to postpone the meeting.''', NULL, 'She suggested postponing the meeting.', 'suggest + V-ing，不接 to + 原形。'),
(93, 'fill_blank', 'Find the error: ''He is responsible of managing the team.'' → Correct: _____.', NULL, 'He is responsible for managing the team.', 'responsible for，不是 responsible of。'),
(93, 'multiple_choice', 'Which sentence is correct?', '["Please let me know whether you need any further informations.","Please let me know if you need any further information.","Please let I know if you need any further information.","Please let me know if you need any further information."]', 'Please let me know if you need any further information.', 'information 不可數（no plural）；let me know（not let I know）。'),
(93, 'multiple_choice', 'Which sentence has a grammatical error?', '["The new policy has an effect on all employees.","The new policy effects all employees starting next month.","The new policy affects all employees starting next month.","The new policy will affect all employees."]', 'The new policy effects all employees starting next month.', 'effect 是名詞，affect 是動詞；effects（當動詞用）是「使...生效」，不是 affects 的意思。'),
(93, 'multiple_choice', 'Which sentence is correct?', '["She is one of the most talented employee I have ever met.","She is one of the most talented employees I have ever met.","She is one of the most talent employees I have ever met.","She is the one of most talented employees I have ever meet."]', 'She is one of the most talented employees I have ever met.', 'one of the most + 最高級 + 複數名詞 + I have ever met 正確。'),
(94, 'multiple_choice', 'She works in finance, _____ ?', '["does she","isn''t she","isn''t it","doesn''t she"]', 'doesn''t she', '助動詞 does 的否定附加問句 doesn''t she。'),
(94, 'multiple_choice', 'You haven''t met the new director, _____ ?', '["don''t you","didn''t you","haven''t you","have you"]', 'have you', 'haven''t 的正面附加問句 have you。'),
(94, 'multiple_choice', 'The meeting was cancelled, _____ ?', '["isn''t it","wasn''t there","was it","wasn''t it"]', 'wasn''t it', 'was 的否定附加問句 wasn''t it。'),
(94, 'fill_blank', 'They will submit the report on time, _____ ?', NULL, 'won''t they', 'will 的否定附加問句 won''t they。'),
(94, 'multiple_choice', 'He can speak three languages, _____ ?', '["can''t he","cannot he","isn''t he","doesn''t he"]', 'can''t he', 'can 的否定附加問句 can''t he。'),
(94, 'multiple_choice', 'We should review the contract again, _____ ?', '["shouldn''t we","should we","don''t we","aren''t we"]', 'shouldn''t we', 'should 的否定附加問句 shouldn''t we。'),
(94, 'multiple_choice', 'The project hasn''t been approved yet, _____ ?', '["has it","doesn''t it","is it","hasn''t it"]', 'has it', 'hasn''t 的正面附加問句 has it。'),
(94, 'fill_blank', 'You are the new account manager, _____ ?', NULL, 'aren''t you', 'are 的否定附加問句 aren''t you。'),
(94, 'multiple_choice', 'Nobody called while I was in the meeting, _____ ?', '["didn''t nobody","did anybody","did they","didn''t they"]', 'did they', 'nobody 是否定詞，附加問句用正面 did they。'),
(94, 'multiple_choice', 'Let''s take a break, _____ ?', '["will we","shall we","shall they","don''t we"]', 'shall we', 'let''s 的附加問句固定用 shall we。'),
(94, 'multiple_choice', 'She''d already submitted the proposal, _____ ?', '["hasn''t she","hadn''t she","wouldn''t she","didn''t she"]', 'hadn''t she', 'had（= she''d）的否定附加問句 hadn''t she。'),
(94, 'fill_blank', 'This is your first time attending the summit, _____ ?', NULL, 'isn''t it', 'is 的否定附加問句 isn''t it。'),
(94, 'multiple_choice', 'You wouldn''t mind reviewing this draft, _____ ?', '["would you","will you","wouldn''t you","do you"]', 'would you', 'wouldn''t 的正面附加問句 would you。'),
(94, 'multiple_choice', 'Everyone signed the NDA, _____ ?', '["isn''t it","haven''t they","didn''t they","did they"]', 'didn''t they', 'everyone 指全體，附加問句用 didn''t they。'),
(94, 'multiple_choice', 'The data must be verified, _____ ?', '["shouldn''t it","must it","mustn''t it","isn''t it"]', 'mustn''t it', 'must 的否定附加問句 mustn''t it。'),
(94, 'fill_blank', 'You''ve been here before, _____ ?', NULL, 'haven''t you', 'have 的否定附加問句 haven''t you。'),
(94, 'multiple_choice', 'Nothing was mentioned about the timeline, _____ ?', '["was it","were it","wasn''t it","did it"]', 'was it', 'nothing 是否定詞，正面附加問句 was it。'),
(94, 'multiple_choice', 'She''s been promoted, _____ ?', '["hasn''t it","didn''t she","isn''t she","hasn''t she"]', 'hasn''t she', 'has been 的否定附加問句 hasn''t she。'),
(94, 'multiple_choice', 'The deadline is firm, _____ ?', '["isn''t it","doesn''t it","is it","isn''t there"]', 'isn''t it', 'is 的否定附加問句 isn''t it。'),
(94, 'transform', 'He should have informed us earlier. Make a tag question.', NULL, 'He should have informed us earlier, shouldn''t he?', 'should have 的否定附加問句 shouldn''t he。'),
(95, 'multiple_choice', 'We will proceed _____ all parties have agreed.', '["although","unless","as long as","despite"]', 'as long as', 'as long as = if（只要），條件表達。'),
(95, 'multiple_choice', '_____ we receive the payment, we cannot dispatch the goods.', '["Unless","As long as","If","Provided that"]', 'Unless', 'unless = if not，除非我們收到付款才出貨。'),
(95, 'multiple_choice', 'The deal will go through _____ both sides sign by Friday.', '["unless","provided that","despite","although"]', 'provided that', 'provided that = on condition that，前提是。'),
(95, 'fill_blank', 'We will extend the deadline _____ you submit a progress report.', NULL, 'provided that / as long as', 'provided that/as long as 表前提條件。'),
(95, 'multiple_choice', 'She will accept the role _____ she gets a competitive package.', '["although","unless","provided","as long as"]', 'as long as', 'as long as 表只要條件成立就接受。'),
(95, 'multiple_choice', 'We will not proceed _____ we have full board approval.', '["provided","as long as","unless","if"]', 'unless', 'unless = if not，沒有全體批准就不推進。'),
(95, 'multiple_choice', '_____ the weather permits, the outdoor event will go ahead.', '["Despite","Unless","Although","Provided that"]', 'Provided that', 'provided that 表前提條件。'),
(95, 'fill_blank', 'The project will stay on budget _____ we avoid scope creep.', NULL, 'as long as', 'as long as 只要避免範疇蔓延。'),
(95, 'multiple_choice', '_____ you have any objections, please raise them now.', '["Unless","Provided that","If","As long as"]', 'If', 'if 普通條件，現在請提出異議。'),
(95, 'multiple_choice', 'She will stay with the company _____ her salary is reviewed.', '["despite","although","provided that","unless"]', 'provided that', 'provided that 表前提條件。'),
(95, 'transform', 'We will sign the contract if the price is right. (Use: as long as)', NULL, 'We will sign the contract as long as the price is competitive.', 'as long as 替換 if 表條件。'),
(95, 'fill_blank', 'The partnership will continue _____ both parties honour the agreement.', NULL, 'as long as / provided that', 'as long as / provided that 表持續條件。'),
(95, 'multiple_choice', '_____ costs are controlled, the project should be profitable.', '["As long as","Despite","Although","Unless"]', 'As long as', 'as long as 表只要成本受控。'),
(95, 'multiple_choice', 'We cannot release the report _____ it has been approved.', '["provided","if","as long as","unless"]', 'unless', 'unless = if not，沒批准就不能發佈。'),
(95, 'multiple_choice', 'She will mentor the new team _____ she is given adequate time.', '["although","provided that","despite","unless"]', 'provided that', 'provided that 表前提（給她足夠時間）。'),
(95, 'transform', 'I will help if you ask me. (Use: unless)', NULL, 'I will not help unless you ask me directly.', 'unless = if not。'),
(95, 'fill_blank', 'The system will run smoothly _____ it is updated regularly.', NULL, 'as long as / provided that', '只要定期更新，系統就能正常運作。'),
(95, 'multiple_choice', '_____ there are objections, we will proceed with the plan.', '["As long as","If","Provided that","Unless"]', 'Unless', 'unless there are objections = if there are no objections。'),
(95, 'multiple_choice', 'The contract is valid _____ both parties comply with its terms.', '["unless","as long as","despite","although"]', 'as long as', 'as long as 表持續條件。'),
(95, 'multiple_choice', 'We will launch in Q2 _____ the testing phase is completed on time.', '["despite","although","unless","provided that"]', 'provided that', 'provided that 表前提條件。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(96, 'multiple_choice', 'She _____ on this project since January.', '["has worked","is working","works","has been working"]', 'has been working', 'since 搭配現在完成進行式，強調持續動作。'),
(96, 'multiple_choice', 'We _____ for a new supplier for three months.', '["look","are looking","have been looking","looked"]', 'have been looking', 'for three months 持續到現在，現在完成進行式。'),
(96, 'multiple_choice', 'How long _____ you _____ for the company?', '["have / worked","are / working","did / work","have / been working"]', 'have / been working', 'How long + have + been + V-ing 問持續時間。'),
(96, 'fill_blank', 'The team _____ (work) overtime all week to meet the deadline.', NULL, 'has been working', 'all week 現在完成進行式，強調持續。'),
(96, 'multiple_choice', 'He looks tired. He _____ since 6 a.m.', '["worked","has worked","has been working","is working"]', 'has been working', '說明疲憊的原因，has been working 強調持續。'),
(96, 'multiple_choice', 'Sales _____ declining for the past three quarters.', '["are","has been","have been","were"]', 'have been', 'Sales 複數，have been declining。'),
(96, 'fill_blank', 'I _____ (try) to contact you all morning!', NULL, 'have been trying', 'all morning 現在完成進行式，強調反覆嘗試。'),
(96, 'multiple_choice', 'The R&D team _____ the new formula for two years.', '["has developed","developed","develops","has been developing"]', 'has been developing', 'for two years 持續到現在，has been developing。'),
(96, 'multiple_choice', 'She _____ consistently well since joining the team.', '["performs","is performing","has been performing","has performed"]', 'has been performing', 'since joining 持續表現，has been performing。'),
(96, 'transform', 'She started learning Mandarin. She still learns it today. (Use present perfect continuous)', NULL, 'She has been learning Mandarin for the past two years.', 'has been learning + for + 時間段。'),
(96, 'fill_blank', 'The company _____ (expand) its operations across Southeast Asia.', NULL, 'has been expanding', 'has been expanding 強調持續中的擴張。'),
(96, 'multiple_choice', 'It _____ raining since last night, so the event may be cancelled.', '["has been","was","is","had been"]', 'has been', 'since last night 現在完成進行式 has been raining。'),
(96, 'multiple_choice', 'They _____ new markets for the past six months.', '["have explored","explore","have been exploring","explored"]', 'have been exploring', 'for the past six months 現在完成進行式。'),
(96, 'multiple_choice', 'He _____ complaints from clients about the delay.', '["receives","received","has received","has been receiving"]', 'has been receiving', '強調持續收到投訴，has been receiving。'),
(96, 'fill_blank', 'We _____ (wait) for your approval for over a week.', NULL, 'have been waiting', 'have been waiting 強調一直在等待。'),
(96, 'multiple_choice', 'She _____ for this position for a very long time.', '["prepares","prepared","has prepared","has been preparing"]', 'has been preparing', 'has been preparing 強調長期備考。'),
(96, 'multiple_choice', 'The team _____ very hard recently.', '["has been working","works","has worked","worked"]', 'has been working', 'recently 搭配現在完成進行式。'),
(96, 'transform', 'He started negotiating last month and is still negotiating. (Use: has been)', NULL, 'He has been negotiating the contract terms for over a month.', 'has been negotiating 現在完成進行式。'),
(96, 'fill_blank', 'They _____ (discuss) the terms for hours — no agreement yet.', NULL, 'have been discussing', 'have been discussing 強調持續的討論。'),
(96, 'multiple_choice', 'The company _____ a new investor for the past year.', '["sought","seeks","has been seeking","has sought"]', 'has been seeking', 'for the past year 現在完成進行式。'),
(97, 'multiple_choice', 'He said the Earth _____ round.', '["has been","is","was","will be"]', 'is', '普遍科學事實，時態不後移，保持 is。'),
(97, 'multiple_choice', 'She said that water _____ at 100 degrees Celsius.', '["boiled","boils","will boil","would boil"]', 'boils', '普遍科學事實不後移，boils 正確。'),
(97, 'multiple_choice', 'He mentioned that the meeting _____ at 3 p.m. today.', '["is","will be","was","would be"]', 'is', '仍然為真（今天的會議），可不後移，is 正確。'),
(97, 'fill_blank', 'She said the sun _____ in the east. (No backshift needed)', NULL, 'rises', '普遍自然事實不後移，rises。'),
(97, 'multiple_choice', 'He told me that he _____ in marketing for over 20 years.', '["worked","is working","has been working","had been working"]', 'has been working', '仍然為真（他現在仍在），可保持 has been working。'),
(97, 'multiple_choice', 'The manager said that the policy _____ into effect next Monday.', '["comes","will come","would come","came"]', 'comes', '未來仍為真（政策下週生效），can report as is。'),
(97, 'multiple_choice', 'She explained that our product _____ the highest in the industry.', '["would rank","ranked","ranks","has ranked"]', 'ranks', '仍為真的事實，ranks 可不後移。'),
(97, 'fill_blank', 'He pointed out that the company _____ (be) the market leader for five years.', NULL, 'has been / is', '現在仍為真，可不後移。'),
(97, 'multiple_choice', 'She noted that honesty _____ the best policy.', '["would be","is","was","has been"]', 'is', '普遍真理不後移，is 正確。'),
(97, 'multiple_choice', 'He said that oil prices _____ due to geopolitical tensions.', '["were rising","rose","would rise","are rising"]', 'are rising', '仍在發生的趨勢，are rising 不後移。'),
(97, 'transform', 'She told me: ''Our team always meets deadlines.'' (Report without backshift)', NULL, 'She told me that their team always meets deadlines.', 'meets 仍為真，不後移。'),
(97, 'fill_blank', 'He said the agreement _____ (still / be) in force.', NULL, 'is still in force', '仍然有效，is 不後移。'),
(97, 'multiple_choice', 'She reminded us that the office _____ at 9 a.m.', '["opened","would open","opens","will open"]', 'opens', '每日慣例仍為真，opens 不後移。'),
(97, 'multiple_choice', 'He noted that the economy _____ steadily.', '["is growing","would grow","grew","was growing"]', 'is growing', '現在仍在進行的趨勢，is growing 不後移。'),
(97, 'multiple_choice', 'She said that client satisfaction _____ our top priority.', '["remains","would remain","will remain","remained"]', 'remains', '現在仍為真，remains 不後移。'),
(97, 'transform', 'He told us: ''The contract expires in two months.'' (Report - still true)', NULL, 'He told us that the contract expires in two months.', '仍然有效的未來事實，expires 不後移。'),
(97, 'fill_blank', 'She mentioned that the new system _____ (work) well.', NULL, 'works / is working', '現在仍為真，works/is working 不後移。'),
(97, 'multiple_choice', 'He said quality assurance _____ every batch.', '["covered","would cover","covers","will cover"]', 'covers', '仍為真的程序，covers 不後移。'),
(97, 'multiple_choice', 'She noted that the market _____ still very competitive.', '["has been","was","is","would be"]', 'is', 'is 仍然為真，不後移。'),
(97, 'multiple_choice', 'He said that good communication _____ the key to success.', '["was","is","would be","has been"]', 'is', '普遍商業原則，is 不後移。'),
(98, 'multiple_choice', '_____, we need to review the budget; secondly, we need to hire more staff.', '["At first","In first","Firstly","For first"]', 'Firstly', 'Firstly...Secondly 列舉順序，最正式。'),
(98, 'multiple_choice', 'The product is affordable; _____, it is highly durable.', '["however","meanwhile","therefore","furthermore"]', 'furthermore', 'furthermore 補充更多優點。'),
(98, 'multiple_choice', 'She speaks French and Spanish. _____, she is learning Mandarin.', '["In addition","Furthermore","Moreover","As well"]', 'In addition', 'In addition 補充資訊，最常見。'),
(98, 'fill_blank', 'The new system saves time. _____, it reduces errors significantly.', NULL, 'Moreover / Furthermore', 'moreover/furthermore 補充遞進關係。'),
(98, 'multiple_choice', 'We offer competitive pricing _____ excellent after-sales service.', '["and also","furthermore","as well as","in addition to"]', 'as well as', 'as well as 連接兩個名詞短語，最自然。'),
(98, 'multiple_choice', 'He is experienced in finance; _____, he has a strong background in tech.', '["furthermore","however","what is more","therefore"]', 'what is more', 'what is more 強調遞進，書面。'),
(98, 'multiple_choice', '_____, the company expanded; then it diversified; _____, it went global.', '["In first / at last","First / finally","Firstly / last","At first / final"]', 'First / finally', 'first...finally 列舉序列最常見。'),
(98, 'transform', 'There are two reasons: cost and time. We need to cut costs. We also need to save time. (List)', NULL, 'Firstly, we need to reduce costs; secondly, we need to save time.', 'firstly...secondly 正式列舉。'),
(98, 'fill_blank', 'The plan is ambitious. _____, it is achievable with the right resources.', NULL, 'However / Nevertheless / That said', '轉折後的補充讓步。'),
(98, 'multiple_choice', '_____ cutting costs, we are also improving quality.', '["As well","Moreover","In addition to","Furthermore"]', 'In addition to', 'in addition to + V-ing 補充動作。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(98, 'multiple_choice', 'She is talented; _____, she works incredibly hard.', '["however","therefore","meanwhile","moreover"]', 'moreover', 'moreover 補充遞進。'),
(98, 'multiple_choice', 'The new branch, _____, will create 200 jobs.', '["therefore","however","furthermore","in addition"]', 'in addition', 'in addition 補充資訊。'),
(98, 'fill_blank', 'The product is innovative. _____, the pricing is very competitive.', NULL, 'In addition / Furthermore / Moreover', '補充更多優點。'),
(98, 'multiple_choice', 'We completed the project on time; _____, we came in under budget.', '["nevertheless","therefore","however","what is more"]', 'what is more', 'what is more 表示額外的好消息。'),
(98, 'multiple_choice', 'He is responsible, _____ punctual, and highly professional.', '["in addition","moreover","furthermore","as well as"]', 'as well as', 'as well as 連接形容詞。'),
(98, 'transform', 'We have three advantages. Add a listing structure.', NULL, 'Firstly, we offer the lowest price; secondly, the fastest delivery; and finally, the best service.', 'firstly...secondly...finally 列舉。'),
(98, 'fill_blank', 'She has strong analytical skills. _____, she is an excellent communicator.', NULL, 'Furthermore / In addition / Moreover', '補充第二個優點。'),
(98, 'multiple_choice', 'The strategy is cost-effective; _____, it is environmentally friendly.', '["therefore","however","meanwhile","in addition"]', 'in addition', 'in addition 補充環保優點。'),
(98, 'multiple_choice', 'Not only was the presentation well-organized; it was _____ very engaging.', '["also","furthermore","as well","too"]', 'also', 'not only...also 固定搭配。'),
(98, 'multiple_choice', 'The training covers technical skills _____ soft skills.', '["and also","furthermore","as well as","in addition to"]', 'as well as', 'as well as 連接兩種技能。'),
(99, 'multiple_choice', 'Sales increased in Asia; _____, they declined in Europe.', '["moreover","meanwhile","therefore","however"]', 'however', 'however 表轉折對比。'),
(99, 'multiple_choice', 'The project was challenging; _____, the team delivered excellent results.', '["meanwhile","nevertheless","moreover","therefore"]', 'nevertheless', 'nevertheless 表儘管如此。'),
(99, 'multiple_choice', 'Our product is expensive. _____, clients continue to choose it for its quality.', '["Despite","Even so","Although","However"]', 'Even so', 'even so 表即便如此，強調讓步。'),
(99, 'fill_blank', 'We increased our marketing spend. _____, sales have not improved significantly.', NULL, 'However / Nevertheless', '表轉折讓步。'),
(99, 'multiple_choice', 'Our competitors charge less; _____, we offer superior quality and service.', '["moreover","on the other hand","therefore","however"]', 'on the other hand', 'on the other hand 表另一方面的權衡。'),
(99, 'multiple_choice', 'The cost is high; _____, the long-term benefits justify the investment.', '["however","therefore","moreover","meanwhile"]', 'however', 'however 表轉折，引出讓步的論點。'),
(99, 'multiple_choice', '_____, our Asian division is thriving; our European operations are struggling.', '["However","By contrast","On the other hand","Nevertheless"]', 'By contrast', 'by contrast 強調明確對比。'),
(99, 'transform', 'We cut costs. However, quality did not improve. (Use: Nevertheless)', NULL, 'We cut costs; nevertheless, quality did not improve as expected.', 'nevertheless 表儘管如此。'),
(99, 'fill_blank', 'The new approach is promising. _____, it carries significant risks.', NULL, 'However / That said / On the other hand', '表轉折，引出風險。'),
(99, 'multiple_choice', 'Sales figures were disappointing. _____, the team remained motivated.', '["Despite","Even so","Although","However"]', 'Even so', 'even so 表即便如此，士氣仍高。'),
(99, 'multiple_choice', 'Costs increased; _____, we maintained our profit margins.', '["meanwhile","nonetheless","moreover","therefore"]', 'nonetheless', 'nonetheless = nevertheless，儘管如此。'),
(99, 'multiple_choice', 'The first option is faster; _____, the second is more cost-effective.', '["therefore","however","on the other hand","moreover"]', 'on the other hand', 'on the other hand 引出對比選項。'),
(99, 'fill_blank', 'The proposal was well-received. _____, the board requested significant revisions.', NULL, 'However / That said', '然而仍需修改。'),
(99, 'multiple_choice', '_____, we underperformed this year; we have a clear strategy for improvement.', '["That said","By contrast","Even so","On the other hand"]', 'That said', 'that said 承認不足的同時轉入正面。'),
(99, 'multiple_choice', 'Prices have fallen; _____, consumer demand has not increased significantly.', '["but","yet","and","so"]', 'yet', 'yet 表意外的轉折（落price but 需求未增）。'),
(99, 'transform', 'The results were poor. In contrast, our competitors performed well. (Use: whereas)', NULL, 'Whereas our competitors performed well, our results were disappointing.', 'whereas 引導對比子句。'),
(99, 'fill_blank', 'The market is growing rapidly. _____, competition is intensifying.', NULL, 'However / At the same time', '表同時發生的對比情況。'),
(99, 'multiple_choice', 'Our costs are lower than competitors; _____, our margins are not higher.', '["and","yet","but","however"]', 'yet', 'yet 表意外轉折。'),
(99, 'multiple_choice', 'The strategy succeeded in Q1; _____, Q2 results were disappointing.', '["moreover","however","therefore","meanwhile"]', 'however', 'however 轉折，說明結果不一致。'),
(99, 'multiple_choice', 'We have strong regional support; _____, global recognition remains limited.', '["meanwhile","therefore","nonetheless","moreover"]', 'nonetheless', 'nonetheless 表儘管如此，全球知名度仍有限。'),
(100, 'multiple_choice', '_____ did the new policy take effect?', '["What time did","Since when","At when","When"]', 'When', 'When 問時間。'),
(100, 'multiple_choice', '_____ approved the budget increase?', '["Which","Who","Whose","Whom"]', 'Who', 'who 問主語人物，主語問句無倒裝。'),
(100, 'multiple_choice', '_____ is she responsible for?', '["Which","What","Whom","Why"]', 'What', 'what is she responsible for 問職責。'),
(100, 'multiple_choice', 'Could you tell me _____ the meeting is?', '["where","when is","where does","where is"]', 'where', '間接問句陳述語序：where the meeting is。'),
(100, 'fill_blank', '_____ long have you been working in this department?', NULL, 'How', 'How long 問持續時間。'),
(100, 'multiple_choice', '_____ does the company ship its products to?', '["What","Which","Where","Whom"]', 'Where', 'where 問地點目的地。'),
(100, 'multiple_choice', 'Do you know _____ submitted the proposal?', '["whose","whom","who","which"]', 'who', '主語間接問句，who 正確。'),
(100, 'multiple_choice', '_____ did the delay happen?', '["How","What","Where","Why"]', 'Why', 'why 問原因。'),
(100, 'fill_blank', '_____ many employees are in the Hong Kong office?', NULL, 'How', 'How many 問數量。'),
(100, 'multiple_choice', '_____ is in charge of client relations?', '["Which","Who","Whose","Whom"]', 'Who', 'who 問主語人物。'),
(100, 'multiple_choice', 'Could you clarify _____ the new process works?', '["where","what","why","how"]', 'how', 'how 問方式，間接問句陳述語序。'),
(100, 'multiple_choice', '_____ proposed the new strategy?', '["Whom","Which","Whose","Who"]', 'Who', 'who 問主語，主語問句。'),
(100, 'fill_blank', '_____ are the benefits of this approach?', NULL, 'What', 'What are the benefits 問優點。'),
(100, 'multiple_choice', '_____ client complained about the service?', '["Who","Which","What","Whom"]', 'Which', 'which 問哪一位（有限範圍）。'),
(100, 'multiple_choice', 'Do you know _____ the document was filed?', '["when is","how","where is","where"]', 'where', '間接問句陳述語序，where the document was filed。'),
(100, 'multiple_choice', '_____ often does the board meet?', '["When","How much","What","How"]', 'How', 'how often 問頻率。'),
(100, 'transform', 'Ask about the reason for the project delay using a formal indirect question.', NULL, 'Could you explain why the project has been delayed?', 'Could you explain why + 陳述語序。'),
(100, 'fill_blank', '_____ many days did it take to complete the audit?', NULL, 'How', 'How many days 問天數。'),
(100, 'multiple_choice', '_____ won the contract?', '["What","Whom","Which","Who"]', 'Who', 'who 問主語，主語問句。'),
(100, 'multiple_choice', '_____ long will the restructuring take?', '["What","How","When","Where"]', 'How', 'how long 問時間長度。');