INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(26, 'multiple_choice', 'We _____ informed the client about the delay earlier.', '["would have","should have","could have","must have"]', 'should have', 'should have + p.p. 表批評或遺憾：應該通知但沒有。'),
(26, 'multiple_choice', 'She _____ the meeting from the start — she had the expertise.', '["must have led","could have led","should have led","would have led"]', 'could have led', 'could have 表過去本可以做的可能性。'),
(26, 'multiple_choice', 'If we had acted faster, we _____ the contract.', '["might have won","should have won","would have won","could have won"]', 'would have won', '第三條件句結果：would have won。'),
(26, 'fill_blank', 'The error _____ (avoid) if the team had followed the protocol.', NULL, 'could have been avoided', 'could have been + p.p. 表過去本可避免的被動式。'),
(26, 'multiple_choice', 'He _____ the report on time — he had enough information.', '["should have submitted","must have submitted","would have submitted","could have submitted"]', 'could have submitted', 'could have 表過去本有能力做到。'),
(26, 'multiple_choice', 'I _____ accepted the original offer — the counter-offer was worse.', '["would have","should have","must have","could have"]', 'should have', 'should have + p.p. 表後悔沒接受。'),
(26, 'multiple_choice', 'They _____ the market more thoroughly before launching.', '["might have researched","could have researched","should have researched","would have researched"]', 'should have researched', 'should have 表應該做的準備工作。'),
(26, 'transform', 'It was a mistake not to hire more staff. (Use: should have hired)', NULL, 'We should have hired more staff to handle the increased demand.', 'should have hired 表過去應該做的決定。'),
(26, 'multiple_choice', 'She _____ the project independently — she had all the skills.', '["must have managed","would have managed","could have managed","should have managed"]', 'could have managed', 'could have 表過去本有能力獨立完成。'),
(26, 'fill_blank', 'He _____ (not / approve) the expense without authorization.', NULL, 'should not have approved', 'should not have + p.p. 表批評：不應該那樣做。'),
(26, 'multiple_choice', 'If she had asked for help, we _____ her.', '["should have assisted","could have assisted","would have assisted","must have assisted"]', 'would have assisted', '第三條件句：would have + p.p.'),
(26, 'multiple_choice', 'The system _____ down if the backup had been set up properly.', '["must not have crashed","should not have crashed","would not have crashed","could not have crashed"]', 'would not have crashed', '第三條件句否定：would not have + p.p.'),
(26, 'multiple_choice', 'We _____ a different supplier — the current one has been unreliable.', '["could have chosen","might have chosen","would have chosen","should have chosen"]', 'should have chosen', 'should have 對過去選擇的後悔。'),
(26, 'fill_blank', 'If the meeting had started on time, we _____ (finish) early.', NULL, 'would have finished', '第三條件句主句 would have finished。'),
(26, 'multiple_choice', 'The team _____ the risk earlier — there were warning signs.', '["could have identified","must have identified","would have identified","should have identified"]', 'should have identified', 'should have 表應負責任的批評。'),
(26, 'multiple_choice', 'He _____ the presentation better if he''d had more preparation time.', '["would have delivered","should have delivered","must have delivered","could have delivered"]', 'could have delivered', 'could have 表有條件的過去可能性。'),
(26, 'multiple_choice', 'We _____ the deal — the client was clearly interested.', '["would have closed","could have closed","should have closed","must have closed"]', 'should have closed', 'should have 表失去機會的遺憾。'),
(26, 'transform', 'It was possible to reduce costs by 15%. (Use: could have reduced)', NULL, 'We could have reduced costs by 15% if we had optimized the supply chain.', 'could have 表過去本可實現的節約。'),
(26, 'fill_blank', 'She _____ (inform) us earlier — we were completely unprepared.', NULL, 'should have informed', 'should have + p.p. 批評應該提前告知。'),
(26, 'multiple_choice', 'If they had responded sooner, the partnership _____ saved.', '["would have been","must have been","should have been","could have been"]', 'could have been', 'could have been + p.p. 表過去被動可能性。'),
(27, 'multiple_choice', 'The quarterly report _____ by the finance team every month.', '["will prepare","is prepared","prepares","has prepared"]', 'is prepared', '被動現在式 is prepared，report 是接受者。'),
(27, 'multiple_choice', 'The contract _____ by both parties yesterday.', '["was signed","has been signed","signed","is signed"]', 'was signed', 'yesterday 過去時間，被動過去式 was signed。'),
(27, 'multiple_choice', 'New employees _____ a two-week training program.', '["gave","are given","are giving","give"]', 'are given', 'are given 被動現在式，employees 接受培訓。'),
(27, 'fill_blank', 'The budget proposal _____ (approve) by the board last Tuesday.', NULL, 'was approved', 'last Tuesday 過去，被動過去式 was approved。'),
(27, 'multiple_choice', 'These products _____ in several Asian countries.', '["manufacture","were manufacturing","manufactured","are manufactured"]', 'are manufactured', 'are manufactured 被動現在式，描述持續的製造。'),
(27, 'multiple_choice', 'The new policy _____ to all staff via email last week.', '["communicated","was communicated","has been communicated","is communicated"]', 'was communicated', 'last week 過去，被動過去式 was communicated。'),
(27, 'multiple_choice', 'All expenses _____ by the accounting department.', '["reviewing","are reviewed","review","were reviewed"]', 'are reviewed', 'are reviewed 被動現在式表定期流程。'),
(27, 'transform', 'The IT department manages the server maintenance. (Use passive)', NULL, 'The server maintenance is managed by the IT department.', 'is managed by 被動語態。'),
(27, 'fill_blank', 'The new office building _____ (design) by a renowned architect.', NULL, 'was designed', 'was designed 被動過去式。'),
(27, 'multiple_choice', 'Invoices _____ within 30 days of receipt.', '["are processing","are processed","process","were processed"]', 'are processed', 'are processed 被動現在式表公司政策。'),
(27, 'multiple_choice', 'The client _____ about the changes immediately.', '["is notifying","notified","was notified","has notified"]', 'was notified', 'was notified 被動過去式，client 接受通知。'),
(27, 'multiple_choice', 'Performance reviews _____ twice a year.', '["have conducted","are conducted","conduct","were conducting"]', 'are conducted', 'are conducted 被動現在式描述定期程序。'),
(27, 'fill_blank', 'The sales data _____ (analyze) by the marketing team on a monthly basis.', NULL, 'is analyzed', '被動現在式 is analyzed 表定期活動。'),
(27, 'multiple_choice', 'The order was _____ due to a quality control issue.', '["cancel","cancelling","have cancelled","cancelled"]', 'cancelled', 'was cancelled 被動過去式，由 was 引導，接過去分詞。'),
(27, 'multiple_choice', 'The new product line _____ at the trade fair last year.', '["has been launched","was launched","is launched","launched"]', 'was launched', 'last year 過去，was launched 被動過去式。'),
(27, 'multiple_choice', 'All decisions _____ by the senior management team.', '["make","have made","were making","are made"]', 'are made', 'are made 被動現在式表決策流程。'),
(27, 'transform', 'They deliver goods to clients within 48 hours. (Use passive)', NULL, 'Goods are delivered to clients within 48 hours.', 'are delivered 被動現在式，強調流程而非執行者。'),
(27, 'fill_blank', 'Overtime payments _____ (calculate) based on the employee''s basic salary.', NULL, 'are calculated', 'are calculated 被動現在式表計算方式。'),
(27, 'multiple_choice', 'The report _____ once a quarter to the board of directors.', '["is submitted","submits","was submitting","submitting"]', 'is submitted', 'is submitted 被動現在式表定期提交。'),
(27, 'multiple_choice', 'The system _____ down for maintenance every weekend.', '["takes","is taken","has taken","was taking"]', 'is taken', 'is taken down 被動現在式 phrasal verb。'),
(28, 'multiple_choice', 'The contract _____ by both parties as of this morning.', '["is signed","had been signed","has been signed","was signed"]', 'has been signed', 'as of this morning 連結到現在，現在完成被動。'),
(28, 'multiple_choice', 'All the required documents _____ before the deadline.', '["were submitted","had been submitted","have been submitted","were being submitted"]', 'had been submitted', 'before the deadline 建立先後，過去完成被動。'),
(28, 'fill_blank', 'The new accounting software _____ (install) across all departments.', NULL, 'has been installed', 'has been + p.p. 現在完成被動，現在已完成。'),
(28, 'multiple_choice', 'By the time we arrived, the presentation _____ already _____.', '["was / being prepared","has / been prepared","had / been prepared","is / prepared"]', 'had / been prepared', 'had been prepared 過去完成被動 already。'),
(28, 'multiple_choice', 'The budget _____ three times this year.', '["is revised","was revised","has been revised","had been revised"]', 'has been revised', 'this year 到目前，現在完成被動 has been revised。'),
(28, 'multiple_choice', 'Before the announcement, the plan _____ carefully.', '["has been reviewed","had been reviewed","was being reviewed","was reviewed"]', 'had been reviewed', 'before 建立先後，過去完成被動 had been reviewed。'),
(28, 'transform', 'The team finished the analysis. (Use present perfect passive)', NULL, 'The analysis has been completed by the team.', 'has been completed 現在完成被動。'),
(28, 'fill_blank', 'The terms of the agreement _____ (negotiate) over several weeks.', NULL, 'have been negotiated', 'have been + p.p. 現在完成被動。'),
(28, 'multiple_choice', 'It _____ that the new policy would be implemented in Q3.', '["had been announced","was announced","is announced","has been announced"]', 'has been announced', 'has been announced 現在完成被動，強調現在已知。'),
(28, 'multiple_choice', 'By 2020, three offices _____ opened globally.', '["were","have been","had been","are"]', 'had been', 'by 2020 過去時間點，had been opened 過去完成被動。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(28, 'multiple_choice', 'New safety standards _____ to all employees this week.', '["had been communicated","have been communicated","were communicated","are communicated"]', 'have been communicated', 'this week 到目前，現在完成被動。'),
(28, 'fill_blank', 'The results _____ (verify) by an independent auditor before release.', NULL, 'had been verified', 'before release 建立先後，過去完成被動。'),
(28, 'multiple_choice', 'A breakthrough solution _____ by our R&D team.', '["was developed","is developed","has been developed","had been developed"]', 'has been developed', '強調現在成果，現在完成被動 has been developed。'),
(28, 'multiple_choice', 'By the end of Q2, 1,000 units _____ shipped.', '["had been","were","are","have been"]', 'had been', 'by the end of Q2 過去時間點，had been shipped。'),
(28, 'multiple_choice', 'Three candidates _____ for the final interview.', '["were shortlisted","are shortlisted","have been shortlisted","had been shortlisted"]', 'have been shortlisted', '強調目前狀態，現在完成被動。'),
(28, 'transform', 'Someone already reviewed the proposal. (Use present perfect passive)', NULL, 'The proposal has already been reviewed by the committee.', 'has already been reviewed 現在完成被動。'),
(28, 'fill_blank', 'The merger _____ (finalize) by the legal teams of both companies.', NULL, 'has been finalized', 'has been + p.p. 現在完成被動。'),
(28, 'multiple_choice', 'Before launch, the product _____ extensively for safety.', '["is tested","was tested","had been tested","has been tested"]', 'had been tested', 'before launch 先後關係，過去完成被動。'),
(28, 'multiple_choice', 'The client _____ kept informed throughout the project.', '["had been","was","is","has been"]', 'has been', 'has been kept 現在完成被動持續式。'),
(28, 'multiple_choice', 'The new system _____ in use since January.', '["had been","was","has been","is"]', 'has been', 'since January 持續到現在，has been in use。'),
(29, 'multiple_choice', 'The report _____ submitted by 5 p.m. on Friday.', '["should","must be","can","will"]', 'must be', 'must be + p.p. 表強制要求的被動式。'),
(29, 'multiple_choice', 'All proposals _____ reviewed by the compliance team.', '["can","will","must","should be"]', 'should be', 'should be + p.p. 建議性被動規定。'),
(29, 'multiple_choice', 'Your application _____ processed within five working days.', '["should","must","will be","can"]', 'will be', 'will be + p.p. 預告未來被動動作。'),
(29, 'fill_blank', 'The invoice _____ (pay) within 30 days of receipt.', NULL, 'must be paid', 'must be + p.p. 強制性被動規定。'),
(29, 'multiple_choice', 'Client data _____ shared with third parties without consent.', '["must not be","will not","should not","can not"]', 'must not be', 'must not be + p.p. 嚴格禁止的被動式。'),
(29, 'multiple_choice', 'These documents _____ kept confidential at all times.', '["can be","must be","should","will be"]', 'must be', 'must be + p.p. 強制保密要求。'),
(29, 'multiple_choice', 'The application form _____ completed in full.', '["will be","must","should be","can"]', 'should be', 'should be + p.p. 建議做到完整填寫。'),
(29, 'transform', 'We can access the system remotely. (Use passive)', NULL, 'The system can be accessed remotely.', 'can be + p.p. 情態被動，強調系統功能。'),
(29, 'fill_blank', 'The budget _____ (approve) before any expenditure is made.', NULL, 'must be approved', 'must be + p.p. 強制先決條件。'),
(29, 'multiple_choice', 'All visitors _____ registered at the front desk.', '["must be","should","will","can"]', 'must be', 'must be + p.p. 強制安全規定。'),
(29, 'multiple_choice', 'The timeline _____ adjusted if there are unexpected delays.', '["should be","must be","may be","will be"]', 'may be', 'may be + p.p. 表可能需要調整。'),
(29, 'multiple_choice', 'Results _____ announced at the annual shareholders'' meeting.', '["can","should","will be","must be"]', 'will be', 'will be + p.p. 預告未來被動事件。'),
(29, 'fill_blank', 'Personal information _____ (not / share) without written permission.', NULL, 'must not be shared', 'must not be + p.p. 嚴格禁止。'),
(29, 'multiple_choice', 'Overtime _____ authorized in advance by your line manager.', '["must be","should","will be","can"]', 'must be', 'must be + p.p. 強制預先授權。'),
(29, 'multiple_choice', 'These changes _____ implemented by the end of Q3.', '["must","can","will","should be"]', 'should be', 'should be + p.p. 建議性期限。'),
(29, 'multiple_choice', 'A copy of the contract _____ sent to all parties involved.', '["should","will be","can","must be"]', 'will be', 'will be + p.p. 預告文件分發。'),
(29, 'transform', 'Someone should inform the client about this. (Use passive)', NULL, 'The client should be informed about this change immediately.', 'should be + p.p. 情態被動。'),
(29, 'fill_blank', 'The equipment _____ (inspect) regularly to ensure safety.', NULL, 'should be inspected', 'should be + p.p. 定期安全檢查建議。'),
(29, 'multiple_choice', 'The project _____ completed without additional resources.', '["must not be","should not be","cannot be","will not be"]', 'cannot be', 'cannot be + p.p. 表無法完成的被動式。'),
(29, 'multiple_choice', 'Any defects _____ reported to the quality control team.', '["must","can","should be","will be"]', 'should be', 'should be + p.p. 建議性程序。'),
(30, 'multiple_choice', 'We _____ the office _____ last month.', '["made / renovated","got / renovate","had / renovated","let / renovate"]', 'had / renovated', 'have something done 安排裝修，had renovated。'),
(30, 'multiple_choice', 'She needs to _____ her laptop _____ before the conference.', '["have / repair","get / repaired","make / repaired","let / repaired"]', 'get / repaired', 'get something done 安排修理，get repaired。'),
(30, 'multiple_choice', 'The manager _____ the intern _____ the report.', '["let / prepared","made / to prepare","had / prepare","got / prepared"]', 'had / prepare', 'have someone do 命令做某事，had + 人 + 原形。'),
(30, 'fill_blank', 'We need to _____ the contract _____ (check) by our lawyers.', NULL, 'have / checked', 'have something done 委託律師審查。'),
(30, 'multiple_choice', 'Can you _____ the presentation slides _____ by tomorrow?', '["make / prepared","have / prepare","get / ready","let / ready"]', 'get / ready', 'get something ready 使其準備好。'),
(30, 'multiple_choice', 'She _____ her team _____ a full market analysis.', '["had / conduct","got / conducted","made / to conduct","let / conduct"]', 'had / conduct', 'had someone do 命令做分析。'),
(30, 'multiple_choice', 'We should _____ the financial reports _____ by an external auditor.', '["let / audited","get / audit","make / audited","have / audited"]', 'have / audited', 'have something done 外部審計。'),
(30, 'transform', 'An outside company cleaned the office. (Use: had the office)', NULL, 'We had the office cleaned by an outside company.', 'have something done 被動使役。'),
(30, 'fill_blank', 'Could you _____ someone _____ (deliver) the documents to our client?', NULL, 'get / to deliver', 'get someone to do 說服/委派做事。'),
(30, 'multiple_choice', 'He _____ the brochures _____ at a local print shop.', '["got / print","let / printed","made / printed","had / printed"]', 'had / printed', 'had something printed 委託印製。'),
(30, 'multiple_choice', 'They are going to _____ the website _____ next week.', '["let / redesigned","make / redesigned","get / redesign","have / redesigned"]', 'have / redesigned', 'have something done 委外改版。'),
(30, 'multiple_choice', 'She _____ the assistant _____ the meeting room before the clients arrived.', '["got / setting up","let / set up","made / set up","had / set up"]', 'had / set up', 'had someone do 命令安排。'),
(30, 'fill_blank', 'I need to _____ my car _____ (service) before the long drive.', NULL, 'have / serviced', 'have something done 服務的委託。'),
(30, 'multiple_choice', 'We _____ the new branch _____ by an interior design firm.', '["got / furnish","had / furnished","made / furnished","let / furnish"]', 'had / furnished', 'had something done 委外室內設計。'),
(30, 'multiple_choice', 'The CEO _____ the PR team _____ a press release immediately.', '["made / to draft","got / drafted","let / draft","had / draft"]', 'had / draft', 'had someone do 命令起草。'),
(30, 'multiple_choice', 'Can you _____ the report _____ into Chinese?', '["get / translated","have / translate","make / translated","let / translate"]', 'get / translated', 'get something done 委外翻譯。'),
(30, 'transform', 'An expert examined the machinery. (Use: had the machinery)', NULL, 'We had the machinery examined by an expert.', 'had something done 委請專家檢查。'),
(30, 'fill_blank', 'She _____ the IT team _____ (install) the new software on her computer.', NULL, 'had / install', 'had someone do 命令安裝，原形動詞。'),
(30, 'multiple_choice', 'We plan to _____ the annual report _____ before the AGM.', '["get / publish","let / published","make / published","have / published"]', 'have / published', 'have something done 印製報告。'),
(30, 'multiple_choice', 'He _____ his assistant _____ all the travel arrangements.', '["got / to make","let / make","had / make","made / to make"]', 'got / to make', 'got someone to do 說服/委派做安排。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(31, 'multiple_choice', 'He said, ''I will send the report.'' → He said he _____ send the report.', '["shall","will","can","would"]', 'would', 'will → would 時態後移。'),
(31, 'multiple_choice', 'She told me, ''I am working on the proposal.'' → She told me she _____ on the proposal.', '["was working","works","worked","is working"]', 'was working', 'am/is working → was working 時態後移。'),
(31, 'multiple_choice', 'They said, ''We have completed the audit.'' → They said they _____ the audit.', '["were completing","had completed","have completed","completed"]', 'had completed', 'have completed → had completed 時態後移。'),
(31, 'fill_blank', 'She said, ''I can finish this by Friday.'' → She said she _____ finish it by Friday.', NULL, 'could', 'can → could 時態後移。'),
(31, 'multiple_choice', 'The manager said, ''The project is on track.'' → The manager said the project _____ on track.', '["will be","were","was","is"]', 'was', 'is → was 時態後移。'),
(31, 'multiple_choice', 'He told us, ''I signed the contract yesterday.'' → He told us he _____ the contract the day before.', '["had signed","was signing","signed","has signed"]', 'had signed', 'signed → had signed 時態後移。'),
(31, 'transform', 'The CEO said: ''We will expand into Europe next year.'' (Use reported speech)', NULL, 'The CEO said they would expand into Europe the following year.', 'will → would；next year → the following year。'),
(31, 'fill_blank', 'She said, ''I am going to attend the conference.'' → She said she _____ the conference.', NULL, 'was going to attend', 'am going to → was going to 時態後移。'),
(31, 'multiple_choice', 'He said, ''The client may cancel the order.'' → He said the client _____ cancel the order.', '["will","might","can","may"]', 'might', 'may → might 時態後移。'),
(31, 'multiple_choice', 'They announced, ''We are launching a new product.'' → They announced they _____ a new product.', '["launch","are launching","launched","were launching"]', 'were launching', 'are launching → were launching 時態後移。'),
(31, 'fill_blank', 'She said, ''I have never seen such a detailed proposal.'' → She said she _____ such a detailed proposal.', NULL, 'had never seen', 'have never seen → had never seen 時態後移。'),
(31, 'multiple_choice', 'The director said, ''The results exceeded expectations.'' → The director said the results _____ expectations.', '["have exceeded","had exceeded","were exceeding","exceeded"]', 'had exceeded', 'exceeded → had exceeded 時態後移。'),
(31, 'multiple_choice', 'He told us, ''We must cut costs immediately.'' → He told us they _____ cut costs immediately.', '["must","should","would","had to"]', 'had to', 'must → had to 時態後移。'),
(31, 'transform', 'The client said: ''I need more time to review the terms.'' (Use reported speech)', NULL, 'The client said he needed more time to review the terms.', 'need → needed 時態後移。'),
(31, 'fill_blank', 'She told me, ''I will call you tomorrow.'' → She told me she _____ the next day.', NULL, 'would call', 'will → would；tomorrow → the next day。'),
(31, 'multiple_choice', 'He said, ''The meeting starts at 10.'' → He said the meeting _____ at 10.', '["started","start","starts","had started"]', 'started', 'starts → started 時態後移（現在→過去）。'),
(31, 'multiple_choice', 'They said, ''We can deliver within 48 hours.'' → They said they _____ deliver within 48 hours.', '["could","would","will","can"]', 'could', 'can → could 時態後移。'),
(31, 'fill_blank', 'The consultant said, ''This approach is more efficient.'' → The consultant said that approach _____ more efficient.', NULL, 'was', 'is → was 時態後移。'),
(31, 'multiple_choice', 'She said, ''I haven''t finished the analysis.'' → She said she _____ the analysis.', '["haven''t finished","hadn''t finished","wasn''t finishing","didn''t finish"]', 'hadn''t finished', 'haven''t → hadn''t 時態後移。'),
(31, 'multiple_choice', 'He told the team, ''The client is impressed.'' → He told the team the client _____ impressed.', '["was","has been","were","is"]', 'was', 'is → was 時態後移。'),
(32, 'multiple_choice', '''What is the deadline?'' → She asked what the deadline _____.', '["is","was","were","will be"]', 'was', '間接問句陳述語序，is → was。'),
(32, 'multiple_choice', '''Is the report ready?'' → He asked _____ the report was ready.', '["whether","if","that","what"]', 'if', 'yes/no 問句用 if 或 whether 引導間接問句。'),
(32, 'multiple_choice', '''When will the meeting start?'' → They asked when the meeting _____.', '["would start","starts","will start","started"]', 'would start', 'will → would；陳述語序。'),
(32, 'fill_blank', '''Do you need any assistance?'' → She asked _____ I needed any assistance.', NULL, 'if/whether', 'yes/no 問句用 if 或 whether 引導。'),
(32, 'multiple_choice', '''Where is the nearest conference center?'' → He asked where the nearest conference center _____.', '["is","was","were","will be"]', 'was', '間接問句 is → was。'),
(32, 'multiple_choice', '''Have you reviewed the proposal?'' → She asked _____ I had reviewed the proposal.', '["that","if","what","whether"]', 'whether', 'whether 引導 yes/no 間接問句。'),
(32, 'multiple_choice', '''How many units can we order?'' → The client asked how many units they _____ order.', '["will","would","could","can"]', 'could', 'can → could 時態後移。'),
(32, 'transform', '''Are you satisfied with the service?'' → The manager asked ...(Use reported question)', NULL, 'The manager asked whether we were satisfied with the service.', 'whether + 陳述語序 + was。'),
(32, 'fill_blank', '''Why did the project fail?'' → The board asked why the project _____.', NULL, 'had failed', 'why + 過去完成式（failed → had failed）。'),
(32, 'multiple_choice', '''What does the contract include?'' → She asked what the contract _____.', '["included","will include","has included","includes"]', 'included', 'includes → included 時態後移。'),
(32, 'multiple_choice', '''Can I speak to the manager?'' → He asked _____ he could speak to the manager.', '["whether","if","what","that"]', 'if', 'yes/no 問句 if 引導。'),
(32, 'multiple_choice', '''Who is in charge of the project?'' → They asked _____ was in charge of the project.', '["whether","who","which","what"]', 'who', 'who 仍是疑問詞，引導間接問句。'),
(32, 'fill_blank', '''How long will the installation take?'' → She asked how long the installation _____ take.', NULL, 'would', 'will → would 時態後移。'),
(32, 'multiple_choice', '''Did the client confirm the order?'' → He asked _____ the client had confirmed the order.', '["whether","what","that","if"]', 'whether', 'whether 引導 yes/no 間接問句；did confirm → had confirmed。'),
(32, 'multiple_choice', '''Which option do you prefer?'' → She asked which option we _____.', '["will prefer","preferred","have preferred","prefer"]', 'preferred', 'prefer → preferred 時態後移。'),
(32, 'transform', '''Is there a cheaper alternative?'' → The client asked ...(Use reported question)', NULL, 'The client asked if there was a cheaper alternative.', 'if + 陳述語序 + was。'),
(32, 'fill_blank', '''What time does the office open?'' → He asked what time the office _____.', NULL, 'opened', 'does open → opened 時態後移。'),
(32, 'multiple_choice', '''Has the payment been processed?'' → She asked _____ the payment had been processed.', '["what","that","whether","if"]', 'whether', 'whether + 被動過去完成式 had been processed。'),
(32, 'multiple_choice', '''Who approved the budget?'' → They asked who _____ the budget.', '["has approved","had approved","was approving","approved"]', 'had approved', 'approved → had approved 時態後移。'),
(32, 'multiple_choice', '''What are the main objectives?'' → He asked what the main objectives _____.', '["are","will be","were","had been"]', 'were', 'are → were 時態後移。'),
(33, 'multiple_choice', '''Submit the report by Friday.'' → He told us _____ the report by Friday.', '["submitting","that we submit","to submit","submit"]', 'to submit', 'tell + 人 + to do 間接命令。'),
(33, 'multiple_choice', '''Don''t be late.'' → She asked them _____ late.', '["to not be","not to be","not be","that not be"]', 'not to be', '間接否定命令：not to + 原形。'),
(33, 'multiple_choice', '''Please prepare the agenda.'' → The manager asked her _____ the agenda.', '["prepare","that she prepares","to prepare","preparing"]', 'to prepare', 'ask + 人 + to do 間接請求。'),
(33, 'fill_blank', '''Follow the company guidelines.'' → He told the new staff _____ the company guidelines.', NULL, 'to follow', 'tell + 人 + to do。'),
(33, 'multiple_choice', '''Don''t share the confidential data.'' → She told him _____ the confidential data.', '["to not share","not sharing","that he not share","not to share"]', 'not to share', 'tell + 人 + not to do。'),
(33, 'multiple_choice', '''Please review the proposal carefully.'' → He asked the team _____ the proposal carefully.', '["to review","that they review","review","reviewing"]', 'to review', 'ask + 人 + to do。'),
(33, 'multiple_choice', '''Call the client immediately.'' → She instructed me _____ the client immediately.', '["to call","that I call","call","calling"]', 'to call', 'instruct + 人 + to do 間接命令。'),
(33, 'transform', 'The boss said: ''Please don''t miss the deadline.'' (Use reported command)', NULL, 'The boss asked us not to miss the deadline.', 'asked + 人 + not to do。'),
(33, 'fill_blank', '''Update the spreadsheet daily.'' → The supervisor told the intern _____ the spreadsheet daily.', NULL, 'to update', 'tell + 人 + to do。'),
(33, 'multiple_choice', '''Please don''t use the printer during peak hours.'' → She asked staff _____ the printer during peak hours.', '["not using","not to use","to not use","that they not use"]', 'not to use', 'ask + 人 + not to do。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(33, 'multiple_choice', '''Read the contract carefully before signing.'' → He advised her _____ the contract carefully.', '["that she reads","read","to read","reading"]', 'to read', 'advise + 人 + to do。'),
(33, 'multiple_choice', '''Don''t discuss salary with colleagues.'' → The HR manager warned them _____ salary with colleagues.', '["that they not discuss","not discussing","to not discuss","not to discuss"]', 'not to discuss', 'warn + 人 + not to do。'),
(33, 'fill_blank', '''Please confirm the order by email.'' → She asked the client _____ the order by email.', NULL, 'to confirm', 'ask + 人 + to do。'),
(33, 'multiple_choice', '''Attend the orientation session.'' → The company required all new hires _____ the orientation session.', '["that they attend","attending","attend","to attend"]', 'to attend', 'require + 人 + to do。'),
(33, 'multiple_choice', '''Don''t park in the visitor spaces.'' → He told staff _____ in the visitor spaces.', '["not to park","to not park","not parking","that they not park"]', 'not to park', 'tell + 人 + not to do。'),
(33, 'transform', 'The IT team said: ''Please restart your computer after the update.'' (Use reported)', NULL, 'The IT team asked all users to restart their computers after the update.', 'asked + 人 + to do，注意代名詞調整。'),
(33, 'fill_blank', '''Send me the draft by Monday.'' → She instructed him _____ the draft by Monday.', NULL, 'to send', 'instruct + 人 + to do。'),
(33, 'multiple_choice', '''Don''t forget to include the appendix.'' → She reminded him _____ to include the appendix.', '["to not","that he don''t","not","do not"]', 'not', 'remind + 人 + not to forget。'),
(33, 'multiple_choice', '''Please copy me on all emails to the client.'' → He asked her _____ him on all emails to the client.', '["that she copies","copying","to copy","copy"]', 'to copy', 'ask + 人 + to do。'),
(33, 'multiple_choice', '''Report any issues immediately.'' → The manager told staff _____ any issues immediately.', '["that they report","reporting","to report","report"]', 'to report', 'tell + 人 + to do。'),
(34, 'multiple_choice', '''I am writing the contract now.'' → She said she _____ the contract then.', '["wrote","is writing","writes","was writing"]', 'was writing', 'is writing → was writing，now → then。'),
(34, 'multiple_choice', '''We will finalize the deal tomorrow.'' → They said they _____ the deal the following day.', '["had finalized","will finalize","would finalize","finalize"]', 'would finalize', 'will → would；tomorrow → the following day。'),
(34, 'multiple_choice', '''I have already sent the invoice.'' → He said he _____ the invoice.', '["had already sent","has already sent","was already sending","already sent"]', 'had already sent', 'have sent → had sent 時態後移。'),
(34, 'fill_blank', '''The client can meet us today.'' → She said the client _____ meet them that day.', NULL, 'could', 'can → could；today → that day。'),
(34, 'multiple_choice', '''I may attend the conference.'' → She said she _____ attend the conference.', '["might","may","can","would"]', 'might', 'may → might 時態後移。'),
(34, 'multiple_choice', '''We signed the deal last week.'' → He said they _____ the deal the week before.', '["were signing","had signed","have signed","signed"]', 'had signed', 'signed → had signed；last week → the week before。'),
(34, 'transform', 'Direct: ''This is our best offer.'' → Report this statement.', NULL, 'She said that was their best offer.', 'this → that；is → was；our → their。'),
(34, 'fill_blank', '''I have been working here for three years.'' → He said he _____ there for three years.', NULL, 'had been working', 'have been working → had been working；here → there。'),
(34, 'multiple_choice', '''Our profits are increasing this year.'' → She said their profits _____ that year.', '["had increased","were increasing","increase","are increasing"]', 'were increasing', 'are increasing → were increasing；this → that。'),
(34, 'multiple_choice', '''I must submit the report today.'' → He said he _____ submit the report that day.', '["would","had to","should","must"]', 'had to', 'must → had to；today → that day。'),
(34, 'multiple_choice', '''We are expanding into new markets here.'' → She said they _____ into new markets there.', '["are expanding","expand","have expanded","were expanding"]', 'were expanding', 'are expanding → were expanding；here → there。'),
(34, 'fill_blank', '''The meeting will be held tomorrow.'' → She said the meeting _____ the following day.', NULL, 'would be held', 'will be held → would be held；tomorrow → the following day。'),
(34, 'multiple_choice', '''We can reduce costs by 10%.'' → He said they _____ reduce costs by 10%.', '["can","could","might","would"]', 'could', 'can → could 時態後移。'),
(34, 'multiple_choice', '''I''ve never seen such growth.'' → She said she _____ such growth.', '["had never seen","hadn''t been seeing","has never seen","never saw"]', 'had never seen', 'have never seen → had never seen。'),
(34, 'transform', 'Direct: ''These negotiations may take longer than expected.'' → Report this.', NULL, 'He warned that those negotiations might take longer than expected.', 'may → might；these → those。'),
(34, 'fill_blank', '''We finished the project yesterday.'' → They said they _____ the project the day before.', NULL, 'had finished', 'finished → had finished；yesterday → the day before。'),
(34, 'multiple_choice', '''We are going to restructure the company.'' → He said they _____ the company.', '["will restructure","were going to restructure","would restructure","are going to restructure"]', 'were going to restructure', 'are going to → were going to。'),
(34, 'multiple_choice', '''The client is here now.'' → She said the client _____ there then.', '["had been","is","was","were"]', 'was', 'is → was；here → there；now → then。'),
(34, 'fill_blank', '''I can''t attend the meeting today.'' → He said he _____ the meeting that day.', NULL, 'couldn''t attend', 'can''t → couldn''t；today → that day。'),
(34, 'multiple_choice', '''We''ve already solved the problem.'' → She said they _____ the problem.', '["were solving","solved","had already solved","have already solved"]', 'had already solved', 'have solved → had solved。'),
(35, 'multiple_choice', 'The employee _____ submitted the best proposal will be promoted.', '["which","whose","who","that"]', 'who', 'who 指人，限定性關係子句。'),
(35, 'multiple_choice', 'The software _____ we use has been updated.', '["which","who","whose","that"]', 'that', 'that 可指物，限定性關係子句。'),
(35, 'multiple_choice', 'The company _____ products are sold worldwide is headquartered in Germany.', '["whose","who","that","which"]', 'whose', 'whose 所有格，修飾 products。'),
(35, 'fill_blank', 'The report _____ was submitted last week has been approved.', NULL, 'that/which', 'that 或 which 指物，限定性關係子句。'),
(35, 'multiple_choice', 'The manager _____ I reported to was very supportive.', '["whose","who","which","that"]', 'who', 'who 指人，作受語。'),
(35, 'multiple_choice', 'The city _____ the conference will be held is London.', '["which","who","where","that"]', 'where', 'where 指地點的關係副詞。'),
(35, 'multiple_choice', 'The client _____ placed the largest order will receive a discount.', '["whose","who","which","that"]', 'who', 'who 指人（客戶）。'),
(35, 'transform', 'The candidate was hired. He had the most experience. (Use: who)', NULL, 'The candidate who had the most experience was hired.', 'who 引導限定性關係子句。'),
(35, 'multiple_choice', 'The proposal _____ received the most votes was accepted.', '["which","that","who","whose"]', 'that', 'that 指物（proposal），限定性子句。'),
(35, 'fill_blank', 'The department _____ handles international accounts is expanding.', NULL, 'that/which', 'that 或 which 指部門。'),
(35, 'multiple_choice', 'The time _____ we need to submit the report is 5 p.m.', '["which","when","that","who"]', 'when', 'when 指時間的關係副詞。'),
(35, 'multiple_choice', 'The platform _____ we have chosen is highly secure.', '["who","which","that","whose"]', 'that', 'that 指物。'),
(35, 'multiple_choice', 'The partner _____ firm specializes in intellectual property law is ideal.', '["that","who","which","whose"]', 'whose', 'whose 所有格，修飾 firm。'),
(35, 'fill_blank', 'The strategy _____ proved most effective was adopted by the board.', NULL, 'that/which', 'that 或 which 指策略。'),
(35, 'multiple_choice', 'The director _____ presentation impressed the investors was promoted.', '["who","which","whose","that"]', 'whose', 'whose 所有格，修飾 presentation。'),
(35, 'multiple_choice', 'The branch _____ was opened last year is already profitable.', '["who","that","whose","which"]', 'that', 'that 指物（branch）。'),
(35, 'transform', 'She identified the error. The error had caused the delay. (Use: that)', NULL, 'She identified the error that had caused the delay.', 'that 引導限定性關係子句。'),
(35, 'fill_blank', 'The vendor _____ we have partnered with offers competitive pricing.', NULL, 'that/who', 'that 或 who（公司可用 who 或 that）。'),
(35, 'multiple_choice', 'The year _____ we launched the product was 2021.', '["when","that","who","which"]', 'when', 'when 指年份（時間關係副詞）。'),
(35, 'multiple_choice', 'The team _____ developed the app won the innovation award.', '["whose","who","which","that"]', 'that', 'that 指整個團隊（也可 who）。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(36, 'multiple_choice', 'Our CEO, _____ joined in 2015, has transformed the company.', '["whose","which","that","who"]', 'who', '非限定性關係子句，不可用 that，用 who 指人。'),
(36, 'multiple_choice', 'The new office, _____ is located in the city centre, opened last month.', '["whose","which","who","that"]', 'which', '非限定性關係子句，which 指物，不可用 that。'),
(36, 'multiple_choice', 'The merger, _____ was announced last week, surprised the industry.', '["which","that","whose","who"]', 'which', '非限定性關係子句 which 指事件。'),
(36, 'fill_blank', 'Ms. Chen, _____ daughter is also an engineer, leads our R&D team.', NULL, 'whose', 'whose 所有格非限定性關係子句。'),
(36, 'multiple_choice', 'The contract, _____ runs until 2028, includes performance clauses.', '["who","which","whose","that"]', 'which', '非限定性子句 which，注意逗號。'),
(36, 'multiple_choice', 'The annual conference, _____ attracts 500 delegates, is held in April.', '["who","whose","which","that"]', 'which', '非限定性子句 which 指事件。'),
(36, 'transform', 'John Smith leads the team. He has 20 years of experience. (Use non-defining)', NULL, 'John Smith, who has 20 years of experience, leads the team.', '非限定性子句加逗號，who 指人。'),
(36, 'multiple_choice', 'Singapore, _____ we opened our first Asian office, is a key market.', '["that","where","which","who"]', 'where', 'where 指地點的非限定性關係副詞。'),
(36, 'fill_blank', 'The Q4 report, _____ shows record profits, will be presented to the board tomorrow.', NULL, 'which', '非限定性子句 which，注意逗號。'),
(36, 'multiple_choice', 'Our largest client, _____ we have worked with for ten years, renewed the contract.', '["whom","which","that","who"]', 'whom', 'whom 是受格關係代名詞，正式用法（也可用 who）。'),
(36, 'multiple_choice', 'The product launch, _____ attracted significant media attention, was a success.', '["whose","who","which","that"]', 'which', '非限定性子句 which。'),
(36, 'multiple_choice', 'Dr. Lee, _____ research was cited in the report, will present at the conference.', '["that","who","which","whose"]', 'whose', 'whose 所有格非限定性關係子句。'),
(36, 'transform', 'The proposal was rejected. It had been reviewed by all departments. (Use non-defining)', NULL, 'The proposal, which had been reviewed by all departments, was rejected.', 'which 非限定性子句加逗號。'),
(36, 'fill_blank', '2023, _____ we achieved record revenue, was our best year.', NULL, 'when', 'when 指年份的非限定性關係副詞。'),
(36, 'multiple_choice', 'The CFO, _____ resigned last month, was known for his innovative strategies.', '["that","which","whose","who"]', 'who', '非限定性子句 who 指人。'),
(36, 'multiple_choice', 'The new policy, _____ takes effect in January, will affect all employees.', '["whose","who","which","that"]', 'which', '非限定性子句 which 指政策。'),
(36, 'fill_blank', 'Our branch in Tokyo, _____ opened five years ago, is now our most profitable.', NULL, 'which', '非限定性子句 which 補充說明東京分部。'),
(36, 'multiple_choice', 'The training program, _____ lasts three weeks, covers essential business skills.', '["whose","which","that","who"]', 'which', '非限定性子句 which。'),
(36, 'multiple_choice', 'Mr. Wang, _____ I met at the trade fair, is interested in a partnership.', '["who","which","that","whom"]', 'whom', 'whom 受格，正式英語；也可用 who。'),
(36, 'multiple_choice', 'The AGM, _____ all shareholders are invited to attend, is scheduled for May.', '["whose","which","that","who"]', 'which', '非限定性子句 which。'),
(37, 'multiple_choice', 'The person _____ handles our logistics is very efficient.', '["whose","which","who","that"]', 'who', 'who 指人，主格。'),
(37, 'multiple_choice', 'The document _____ I need is on your desk.', '["which","whose","who","that"]', 'that', 'that 指物，可替代 which（限定子句）。'),
(37, 'multiple_choice', 'The company _____ logo is red and blue is our main competitor.', '["that","who","whose","which"]', 'whose', 'whose 所有格，修飾 logo。'),
(37, 'fill_blank', 'The staff member _____ processed your order has been promoted.', NULL, 'who/that', 'who 或 that 均可指人（限定子句）。'),
(37, 'multiple_choice', 'The software _____ we installed last week has improved productivity.', '["who","whose","that","which"]', 'that', 'that 指物。'),
(37, 'multiple_choice', 'The employee _____ performance was exceptional received a bonus.', '["who","that","which","whose"]', 'whose', 'whose 所有格，修飾 performance。'),
(37, 'multiple_choice', 'The branch _____ the CEO visited last month is performing well.', '["that","whose","who","which"]', 'that', 'that 指物，受格用法（受詞可省略）。'),
(37, 'transform', 'The consultant helped us. His firm is based in New York. (Use: whose)', NULL, 'The consultant whose firm is based in New York helped us.', 'whose 所有格限定性關係子句。'),
(37, 'multiple_choice', 'The system _____ was installed last year needs an upgrade.', '["whose","who","that","which"]', 'that', 'that 指物，主格用法。'),
(37, 'fill_blank', 'The client _____ we spoke to yesterday wants a revised proposal.', NULL, 'who/whom/that', 'who 或 that 可指人；whom 正式受格。'),
(37, 'multiple_choice', 'The project _____ budget exceeded one million was reviewed by the board.', '["which","that","who","whose"]', 'whose', 'whose 所有格，修飾 budget。'),
(37, 'multiple_choice', 'The partner _____ brought in the most new clients won the award.', '["whose","which","who","that"]', 'who', 'who 指人（partner），主格。'),
(37, 'multiple_choice', 'The regulations _____ were introduced last year affected many industries.', '["that","whose","who","which"]', 'that', 'that 指物（regulations）。'),
(37, 'transform', 'The manager worked hard. She always meets her targets. (Use: who)', NULL, 'She is the kind of manager who always meets her targets.', 'who 引導描述人的關係子句。'),
(37, 'fill_blank', 'The product _____ we developed has received excellent reviews.', NULL, 'that/which', 'that 或 which 均可指物。'),
(37, 'multiple_choice', 'The consultant _____ advice we followed was right.', '["whose","that","which","who"]', 'whose', 'whose 所有格，修飾 advice。'),
(37, 'multiple_choice', 'This is the platform _____ connects buyers and sellers globally.', '["which","that","whose","who"]', 'that', 'that 指物，限定性子句。'),
(37, 'fill_blank', 'The team _____ won the award was from the marketing department.', NULL, 'that/which', 'that 或 which 均可（限定性子句）。'),
(37, 'multiple_choice', 'The investor _____ funded the startup is well known in the industry.', '["who","that","which","whose"]', 'who', 'who 指人（investor）。'),
(37, 'multiple_choice', 'The policy _____ was introduced in Q1 has improved efficiency.', '["that","who","which","whose"]', 'that', 'that 指物（policy）。'),
(38, 'multiple_choice', 'She decided _____ the new marketing strategy.', '["of implementing","to implement","implementing","implement"]', 'to implement', 'decide + to do 決定做。'),
(38, 'multiple_choice', 'We considered _____ our office in Singapore.', '["relocate","of relocating","to relocate","relocating"]', 'relocating', 'consider + V-ing 考慮做。'),
(38, 'multiple_choice', 'He agreed _____ the proposal by the end of the week.', '["of reviewing","to review","reviewing","review"]', 'to review', 'agree + to do 同意做。'),
(38, 'fill_blank', 'She finished _____ (write) the report and sent it to the client.', NULL, 'writing', 'finish + V-ing 完成做。'),
(38, 'multiple_choice', 'They plan _____ a new branch in Europe next year.', '["opening","of opening","open","to open"]', 'to open', 'plan + to do 計劃做。'),
(38, 'multiple_choice', 'He suggested _____ the product launch to Q1.', '["of postponing","postponing","postpone","to postpone"]', 'postponing', 'suggest + V-ing 建議做。'),
(38, 'multiple_choice', 'I avoid _____ important meetings without proper preparation.', '["attend","of attending","to attend","attending"]', 'attending', 'avoid + V-ing 避免做。'),
(38, 'transform', 'The manager said he would sign the contract. (Use: agreed to sign)', NULL, 'The manager agreed to sign the contract before the deadline.', 'agree + to do。'),
(38, 'multiple_choice', 'She stopped _____ when she heard the news.', '["to talk","talking","talk","of talking"]', 'talking', 'stopped talking 停止說話（動作結束）；stopped to talk 停下來去說話。'),
(38, 'fill_blank', 'We expect _____ (receive) the shipment by Thursday.', NULL, 'to receive', 'expect + to do 期待。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(38, 'multiple_choice', 'The team practiced _____ the presentation before the big day.', '["of giving","giving","give","to give"]', 'giving', 'practice + V-ing 練習做。'),
(38, 'multiple_choice', 'She remembered _____ the invoice — it was done last week.', '["sending","of sending","to send","send"]', 'sending', 'remembered sending 記得曾做（過去已做）。'),
(38, 'multiple_choice', 'He tried _____ the client''s concerns in his email.', '["to address","addressing","of addressing","address"]', 'to address', 'try + to do 嘗試做（努力）。'),
(38, 'fill_blank', 'Would you mind _____ (postpone) the meeting by one hour?', NULL, 'postponing', 'Would you mind + V-ing 請求。'),
(38, 'multiple_choice', 'We recommend _____ the terms before signing.', '["reviewing","review","to review","of reviewing"]', 'reviewing', 'recommend + V-ing 建議做。'),
(38, 'multiple_choice', 'She managed _____ all five projects on time.', '["to complete","complete","of completing","completing"]', 'to complete', 'manage + to do 設法做到。'),
(38, 'multiple_choice', 'He enjoys _____ with international clients.', '["of working","working","work","to work"]', 'working', 'enjoy + V-ing 喜歡做。'),
(38, 'transform', 'It would be a good idea to expand into Asia. (Use: suggest expanding)', NULL, 'She suggested expanding into Asian markets next year.', 'suggest + V-ing。'),
(38, 'fill_blank', 'The company failed _____ (meet) its Q3 targets.', NULL, 'to meet', 'fail + to do 未能做到。'),
(38, 'multiple_choice', 'She offered _____ with the onboarding process.', '["to help","helping","help","of helping"]', 'to help', 'offer + to do 提議做。'),
(39, 'multiple_choice', '_____ effectively with clients is a key skill in sales.', '["To communicate","Communication","Communicating","Communicate"]', 'Communicating', 'Communicating 動名詞作主語。'),
(39, 'multiple_choice', '_____ the budget carefully ensures financial stability.', '["Management","Managed","Managing","To manage"]', 'Managing', 'Managing 動名詞作主語。'),
(39, 'fill_blank', '_____ (meet) deadlines consistently is essential in this role.', NULL, 'Meeting', 'Meeting 動名詞作主語。'),
(39, 'multiple_choice', '_____ a diverse team brings different perspectives to problem-solving.', '["Leading","Lead","Leads","To lead"]', 'Leading', 'Leading 動名詞作主語。'),
(39, 'multiple_choice', '_____ customer satisfaction should be every employee''s priority.', '["To maintain","Maintained","Maintain","Maintaining"]', 'Maintaining', 'Maintaining 動名詞作主語。'),
(39, 'multiple_choice', '_____ the right suppliers is crucial for quality control.', '["Selected","Select","Selecting","To select"]', 'Selecting', 'Selecting 動名詞作主語。'),
(39, 'transform', 'It is important to track your expenses carefully. (Use gerund as subject)', NULL, 'Tracking your expenses carefully is important for financial management.', 'Tracking 動名詞作主語。'),
(39, 'fill_blank', '_____ (negotiate) well can save the company significant costs.', NULL, 'Negotiating', 'Negotiating 動名詞作主語。'),
(39, 'multiple_choice', '_____ new technologies early gives companies a competitive advantage.', '["Adopted","Adopt","Adopting","To adopt"]', 'Adopting', 'Adopting 動名詞作主語。'),
(39, 'multiple_choice', '_____ in professional development benefits both employees and the company.', '["Investing","Invested","Invest","To invest"]', 'Investing', 'Investing 動名詞作主語。'),
(39, 'multiple_choice', '_____ clearly and concisely is vital for business communication.', '["To write","Written","Writing","Write"]', 'Writing', 'Writing 動名詞作主語。'),
(39, 'fill_blank', '_____ (build) a strong network is essential for career growth.', NULL, 'Building', 'Building 動名詞作主語。'),
(39, 'multiple_choice', '_____ a global workforce requires cross-cultural competence.', '["To manage","Managed","Managing","Manage"]', 'Managing', 'Managing 動名詞作主語。'),
(39, 'multiple_choice', '_____ the market before entering reduces business risk.', '["Research","Researching","To research","Researched"]', 'Researching', 'Researching 動名詞作主語。'),
(39, 'transform', 'It takes skill to analyze complex data quickly. (Use gerund subject)', NULL, 'Analyzing complex data quickly takes considerable skill and experience.', 'Analyzing 動名詞作主語。'),
(39, 'fill_blank', '_____ (set) clear goals is the first step to project success.', NULL, 'Setting', 'Setting 動名詞作主語。'),
(39, 'multiple_choice', '_____ regularly with your team prevents miscommunication.', '["Met","To meet","Meeting","Meet"]', 'Meeting', 'Meeting 動名詞作主語。'),
(39, 'multiple_choice', '_____ to clients'' needs builds long-term business relationships.', '["Listening","To listen","Listen","Listened"]', 'Listening', 'Listening 動名詞作主語。'),
(39, 'fill_blank', '_____ (take) initiative is a quality we look for in all our employees.', NULL, 'Taking', 'Taking 動名詞作主語。'),
(39, 'multiple_choice', '_____ the company''s mission and values is expected of all staff.', '["To understand","Understand","Understanding","Understood"]', 'Understanding', 'Understanding 動名詞作主語。'),
(40, 'multiple_choice', 'She flew to Shanghai _____ meet the key supplier.', '["so as","for","to","in order"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'We hired a consultant _____ improve our operational efficiency.', '["for","at","to","in"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'He attended the seminar _____ network with industry leaders.', '["in order","to","for","so as"]', 'to', 'to + 原形動詞表目的。'),
(40, 'fill_blank', 'She called the client _____ (confirm) the order details.', NULL, 'to confirm', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'We use this platform _____ streamline communication across departments.', '["at","in","for","to"]', 'to', 'to + 原形表工具使用目的。'),
(40, 'multiple_choice', 'The company launched a new initiative _____ attract top talent.', '["in order to","for","so as","to"]', 'in order to', 'in order to 更正式的目的表達，也可用 to。'),
(40, 'multiple_choice', 'He took a finance course _____ better understand the balance sheet.', '["in","for","to","at"]', 'to', 'to + 原形動詞表目的。'),
(40, 'transform', 'We created the policy. The purpose was to prevent data breaches. (Use: in order to)', NULL, 'We created this policy in order to prevent data breaches.', 'in order to 更正式的目的不定詞。'),
(40, 'fill_blank', 'The team worked overtime _____ (meet) the project deadline.', NULL, 'to meet', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'She gave the client a discount _____ retain the business relationship.', '["so as","to","in order","for"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'We need _____ expand our market presence.', '["for","so as","in","to"]', 'to', 'need + to + 原形。'),
(40, 'multiple_choice', 'The CEO travelled to New York _____ sign the partnership agreement.', '["in","at","for","to"]', 'to', 'to + 原形動詞表目的。'),
(40, 'fill_blank', 'We streamlined our process _____ (reduce) operational costs.', NULL, 'to reduce', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'She took detailed notes _____ not forget any action items.', '["in order not to","so as not to","to not","not to"]', 'so as not to', 'so as not to 表負面目的（避免）。'),
(40, 'multiple_choice', 'The firm invested in R&D _____ develop innovative solutions.', '["in","for","at","to"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'He reviewed the proposal carefully _____ identify any weaknesses.', '["so as","for","in order to","to"]', 'in order to', 'in order to 更正式的目的不定詞。'),
(40, 'transform', 'We redesigned the website. The goal was to improve user experience. (Use: to)', NULL, 'We redesigned the website to improve the user experience.', 'to + 原形動詞表目的。'),
(40, 'fill_blank', 'She prepared a detailed handover document _____ (help) her successor.', NULL, 'to help', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'The company held focus groups _____ gather consumer feedback.', '["for","in","at","to"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'We implemented the new system _____ reduce manual data entry.', '["for","to","in","at"]', 'to', 'to + 原形動詞表目的。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(41, 'multiple_choice', 'The manager asked the team _____ the report by noon.', '["to submit","submit","submitting","of submitting"]', 'to submit', 'ask + 人 + to do。'),
(41, 'multiple_choice', 'We want our employees _____ with clients professionally.', '["of communicating","communicate","communicating","to communicate"]', 'to communicate', 'want + 人 + to do。'),
(41, 'fill_blank', 'The director advised us _____ (reconsider) the pricing strategy.', NULL, 'to reconsider', 'advise + 人 + to do。'),
(41, 'multiple_choice', 'The company requires all staff _____ annual training.', '["complete","of completing","to complete","completing"]', 'to complete', 'require + 人 + to do。'),
(41, 'multiple_choice', 'She encouraged her team _____ new approaches.', '["to try","of trying","trying","try"]', 'to try', 'encourage + 人 + to do。'),
(41, 'multiple_choice', 'We expect all applicants _____ a portfolio.', '["submit","of submitting","submitting","to submit"]', 'to submit', 'expect + 人 + to do。'),
(41, 'multiple_choice', 'The policy allows employees _____ from home two days a week.', '["work","to work","of working","working"]', 'to work', 'allow + 人 + to do。'),
(41, 'transform', 'The CEO told us: manage the budget carefully. (Use: asked us to)', NULL, 'The CEO asked us to manage the budget more carefully.', 'ask + 人 + to do。'),
(41, 'multiple_choice', 'He hired a consultant _____ the marketing strategy.', '["to revise","of revising","revise","revising"]', 'to revise', 'hired someone to do 委託做某事。'),
(41, 'fill_blank', 'The board authorized the CFO _____ (sign) contracts up to $1 million.', NULL, 'to sign', 'authorize + 人 + to do 授權。'),
(41, 'multiple_choice', 'She invited the client _____ a factory tour.', '["of joining","join","joining","to join"]', 'to join', 'invite + 人 + to do。'),
(41, 'multiple_choice', 'The company trains staff _____ with the new software.', '["of working","to work","work","working"]', 'to work', 'trains someone to do 培訓做某事。'),
(41, 'multiple_choice', 'He persuaded the client _____ the extended warranty.', '["purchase","of purchasing","purchasing","to purchase"]', 'to purchase', 'persuade + 人 + to do。'),
(41, 'fill_blank', 'We need you _____ (confirm) your attendance by Friday.', NULL, 'to confirm', 'need + 人 + to do。'),
(41, 'multiple_choice', 'The supervisor told the intern _____ the filing system.', '["organize","to organize","of organizing","organizing"]', 'to organize', 'tell + 人 + to do。'),
(41, 'multiple_choice', 'They enabled the team _____ remotely during the crisis.', '["work","to work","working","of working"]', 'to work', 'enable + 人 + to do 使...能夠。'),
(41, 'transform', 'The client asked: please send us a detailed quotation. (Use: asked us to)', NULL, 'The client asked us to send them a detailed quotation.', 'ask + 人 + to do，注意代名詞調整。'),
(41, 'fill_blank', 'The manager reminded her _____ (submit) the expense claims.', NULL, 'to submit', 'remind + 人 + to do。'),
(41, 'multiple_choice', 'The firm appointed her _____ the new regional director.', '["of being","being","to be","be"]', 'to be', 'appoint + 人 + to be 任命為。'),
(41, 'multiple_choice', 'He helped the client _____ the right product.', '["to choose","choose","choosing","of choosing"]', 'to choose', 'help + 人 + to do（to 可省略）。'),
(42, 'multiple_choice', 'Our new system is _____ than the previous one.', '["faster","more fast","fast","more faster"]', 'faster', '單音節加 -er：faster。'),
(42, 'multiple_choice', 'This approach is _____ to implement than the original plan.', '["easiest","more easy","easier","most easy"]', 'easier', 'easy → easier，比較級。'),
(42, 'multiple_choice', 'The new model is _____ efficient than its predecessor.', '["very","most","much","more"]', 'more', '多音節用 more + 形容詞。'),
(42, 'fill_blank', 'Their customer service is _____ (good) than ours.', NULL, 'better', 'good → better 不規則比較級。'),
(42, 'multiple_choice', 'The situation is _____ than we initially expected.', '["more bad","more worse","worser","worse"]', 'worse', 'bad → worse 不規則比較級。'),
(42, 'multiple_choice', 'The revised proposal is _____ clear than the first version.', '["more clear","most clear","clearer","clearly"]', 'clearer', 'clear → clearer，單音節加 -er。'),
(42, 'multiple_choice', 'Processing times are _____ with the new software.', '["shortest","most short","more short","shorter"]', 'shorter', 'short → shorter 比較級。'),
(42, 'transform', 'Version 2 is not as effective as version 1. (Use: less effective)', NULL, 'Version 2 is less effective than version 1.', 'less + 形容詞表劣於比較。'),
(42, 'multiple_choice', 'She is a _____ communicator than her predecessor.', '["most good","better","more good","gooder"]', 'better', 'good → better 不規則比較級。'),
(42, 'fill_blank', 'This solution is _____ (cost-effective) than the alternatives.', NULL, 'more cost-effective', '多音節形容詞 more + cost-effective。'),
(42, 'multiple_choice', 'The new office is _____ accessible to public transport.', '["very","much","more","most"]', 'more', 'more accessible 多音節比較級。'),
(42, 'multiple_choice', 'Working conditions are _____ than they were five years ago.', '["much good","more better","much more better","much better"]', 'much better', 'much 可加強比較級，good → better。'),
(42, 'multiple_choice', 'Our Q3 results were _____ than Q2.', '["strongly","more strong","most strong","stronger"]', 'stronger', 'strong → stronger 比較級。'),
(42, 'transform', 'Outsourcing is cheaper. In-house is more reliable. (Use: cheaper than)', NULL, 'Outsourcing is cheaper than in-house, but in-house is more reliable.', 'cheaper than 比較兩種選項。'),
(42, 'fill_blank', 'This model is _____ (efficient) and _____ (affordable) than the old one.', NULL, 'more efficient / more affordable', '多音節形容詞加 more。'),
(42, 'multiple_choice', 'This quarter''s performance is _____ than last year''s.', '["much far good","farther good","far better","more far better"]', 'far better', 'far better 用 far 加強比較級。'),
(42, 'multiple_choice', 'The process became _____ as we automated more tasks.', '["most smooth","smoother","smoothly","more smooth"]', 'smoother', 'smooth → smoother 比較級。'),
(42, 'multiple_choice', 'This is a _____ approach to solving the problem.', '["innovativer","more innovative","much innovative","most innovative"]', 'more innovative', 'innovative 多音節，more innovative。'),
(42, 'fill_blank', 'The new hire is _____ (experienced) than we expected.', NULL, 'more experienced', 'experienced 多音節，more experienced。'),
(42, 'multiple_choice', 'His proposal is _____ than hers in terms of feasibility.', '["more realistic","realisticker","much realistic","most realistic"]', 'more realistic', 'realistic 多音節，more realistic。'),
(43, 'multiple_choice', 'This is _____ proposal we have received.', '["the better","the best","better","the most good"]', 'the best', 'good → the best 最高級。'),
(43, 'multiple_choice', 'Our Q4 was _____ quarter in the company''s history.', '["most profitable","the profitablest","the most profitable","more profitable"]', 'the most profitable', 'profitable 多音節，the most profitable。'),
(43, 'multiple_choice', 'She is _____ candidate for this role.', '["the qualifiedest","most qualified","the most qualified","more qualified"]', 'the most qualified', 'qualified 多音節，the most qualified。'),
(43, 'fill_blank', 'This was _____ (bad) product launch we''ve ever experienced.', NULL, 'the worst', 'bad → the worst 不規則最高級。'),
(43, 'multiple_choice', 'The new software is _____ option available.', '["most cheap","the cheapest","cheaper","cheapest"]', 'the cheapest', 'cheap → the cheapest，最高級前加 the。'),
(43, 'multiple_choice', 'This deal represents _____ opportunity we have seen this year.', '["the most great","more great","the greatest","greatest"]', 'the greatest', 'great → the greatest。'),
(43, 'multiple_choice', 'That was _____ presentation I have ever attended.', '["more inspiring","the most inspiring","the most inspired","the inspiringest"]', 'the most inspiring', 'inspiring 多音節，the most inspiring。'),
(43, 'transform', 'No other quarter performed better than Q3. (Use: best)', NULL, 'Q3 was our best-performing quarter of the year.', 'the best 最高級。'),
(43, 'multiple_choice', 'He is _____ salesperson on our team.', '["the most productive","the productivest","more productive","most productive"]', 'the most productive', 'productive 多音節，the most productive。'),
(43, 'fill_blank', 'This is _____ (far) we have ever expanded geographically.', NULL, 'the furthest/farthest', 'far → the furthest/farthest 最高級。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(43, 'multiple_choice', 'The first approach is _____ of all the options presented.', '["least expensive","less expensive","the most cheapest","the least expensive"]', 'the least expensive', 'the least expensive 最低程度最高級。'),
(43, 'multiple_choice', 'She achieved _____ results in the department.', '["higher","highest","the highest","most high"]', 'the highest', 'high → the highest，最高級前 the。'),
(43, 'multiple_choice', 'This has been _____ challenging project I have managed.', '["more","the better","the most","a most"]', 'the most', 'the most + challenging，多音節最高級。'),
(43, 'transform', 'No solution is simpler than option A. (Use: simplest)', NULL, 'Option A is the simplest solution available.', 'the simplest 最高級。'),
(43, 'fill_blank', 'He is one of _____ (experienced) managers in the industry.', NULL, 'the most experienced', 'one of the most + 形容詞最高級。'),
(43, 'multiple_choice', 'The Tokyo branch is performing _____ of all our offices.', '["better","the most good","the best","much good"]', 'the best', 'best 副詞最高級，表現最好。'),
(43, 'multiple_choice', 'This was _____ decision we could have made.', '["more bad","badder","the most bad","the worst"]', 'the worst', 'bad → the worst 最高級。'),
(43, 'multiple_choice', 'He is _____ analyst on the team in terms of accuracy.', '["the precisest","the most precise","more precise","most precise"]', 'the most precise', 'precise 多音節，the most precise。'),
(43, 'fill_blank', 'This strategy gave us _____ (high) return on investment.', NULL, 'the highest', 'high → the highest，最高級。'),
(43, 'multiple_choice', 'That client has been _____ loyal partner since the beginning.', '["a most","our best","our most","the more"]', 'our most', 'our most loyal 限定詞 + 最高級。'),
(44, 'multiple_choice', 'Our new product is _____ reliable _____ the competitor''s.', '["as / as","more / as","so / as","as / than"]', 'as / as', 'as...as 表兩者相等。'),
(44, 'multiple_choice', 'The delivery was not _____ fast _____ we had expected.', '["as / as","so / as","more / as","as / than"]', 'as / as', 'not as...as 表不如預期。'),
(44, 'multiple_choice', 'This branch is performing just _____ well _____ last year.', '["so / as","as / than","as / as","more / as"]', 'as / as', 'just as...as 強調完全相等。'),
(44, 'fill_blank', 'Our costs are twice _____ high _____ our competitors''.', NULL, 'as / as', 'twice as...as 表兩倍關係。'),
(44, 'multiple_choice', 'She works just _____ hard _____ anyone else on the team.', '["so / as","more / as","as / than","as / as"]', 'as / as', 'just as...as 完全相等。'),
(44, 'multiple_choice', 'Is this model _____ durable _____ the previous one?', '["so / as","more / as","as / as","as / than"]', 'as / as', 'as...as 疑問句比較。'),
(44, 'multiple_choice', 'The results weren''t _____ impressive _____ expected.', '["so / as","as / than","more / as","as / as"]', 'as / as', 'not as...as 表低於預期。'),
(44, 'transform', 'Revenues are equal this year and last year. (Use: as high as)', NULL, 'Revenues this year are as high as last year''s.', 'as...as 表數量相等。'),
(44, 'multiple_choice', 'The new platform is _____ efficient _____ the old one.', '["more / as","as much / than","as / as twice","twice as / as"]', 'twice as / as', 'twice as...as 兩倍效率。'),
(44, 'fill_blank', 'Their pricing is _____ competitive _____ ours.', NULL, 'not as / as', 'not as...as 表劣勢比較。'),
(44, 'multiple_choice', 'This report is _____ detailed _____ the one last quarter.', '["more / as","so / as","as / than","as / as"]', 'as / as', 'as...as 兩份報告同等詳細。'),
(44, 'multiple_choice', 'She speaks _____ clearly _____ any senior manager.', '["more / as","as / than","as / as","so / as"]', 'as / as', '副詞用 as...as。'),
(44, 'multiple_choice', 'The client isn''t _____ demanding _____ we thought.', '["more / as","as / as","so / as","as / than"]', 'as / as', 'not as...as 表不如預期。'),
(44, 'transform', 'Profits in Q1 equal profits in Q2. (Use: as high as)', NULL, 'Q1 profits were as high as Q2 profits.', 'as...as 數量相等。'),
(44, 'fill_blank', 'Our service is _____ reliable _____ our top competitor''s.', NULL, 'as / as', 'as...as 表相等。'),
(44, 'multiple_choice', 'This proposal is _____ comprehensive _____ the other one.', '["not so / than","less / than","so / as","not as / as"]', 'not as / as', 'not as...as 表較不全面。'),
(44, 'multiple_choice', 'The new hire is _____ experienced _____ the rest of the team.', '["as / as","as / than","more / as","so / as"]', 'as / as', 'as...as 相等經驗。'),
(44, 'fill_blank', 'Working remotely can be _____ productive _____ working in the office.', NULL, 'as / as', 'as...as 表相等生產力。'),
(44, 'multiple_choice', 'The interest rate is _____ high _____ it was last year.', '["so / as","as / than","not as / as","less / than"]', 'not as / as', 'not as...as 表較低。'),
(44, 'multiple_choice', 'This software is _____ user-friendly _____ its predecessor.', '["three times as / as","times as / as","as / so","more / as"]', 'three times as / as', 'three times as...as 三倍用法。'),
(45, 'multiple_choice', '_____ we invest in training, _____ our team performs.', '["More / better","The more / the more better","The most / the best","The more / the better"]', 'The more / the better', 'The more...the better 雙重比較。'),
(45, 'multiple_choice', '_____ the deadline, _____ the team works.', '["The most close / the hardest","Closer / harder","More close / more hard","The closer / the harder"]', 'The closer / the harder', 'The closer...the harder 雙重比較。'),
(45, 'fill_blank', '_____ clients we retain, _____ our revenue grows. (Use double comparative)', NULL, 'The more / the more', 'The more...the more 正比關係。'),
(45, 'multiple_choice', '_____ the team communicates, _____ the project runs.', '["Most frequently / most smoothly","More frequently / more smooth","The frequently / the smooth","The more frequently / the more smoothly"]', 'The more frequently / the more smoothly', 'the + 比較副詞的雙重比較。'),
(45, 'multiple_choice', '_____ data we have, _____ informed our decisions.', '["More / most","More / more","The more / the more","The most / the most"]', 'The more / the more', 'The more data...the more informed 雙重比較。'),
(45, 'multiple_choice', '_____ we delay, _____ it will cost.', '["The longest / the most","Longer / more","The more long / the more much","The longer / the more"]', 'The longer / the more', 'The longer...the more 時間與費用的反比。'),
(45, 'transform', 'If we expand faster, we get better economies of scale. (Use double comparative)', NULL, 'The faster we expand, the greater the economies of scale we achieve.', 'The faster...the greater 雙重比較。'),
(45, 'fill_blank', '_____ transparent our reporting, _____ investors trust us. (Use double comparative)', NULL, 'The more / the more', 'The more transparent...the more trust 雙重比較。'),
(45, 'multiple_choice', '_____ the team''s morale, _____ their performance.', '["The higher / the better","Higher / better","High / good","The most high / the best"]', 'The higher / the better', 'The higher...the better 雙重比較。'),
(45, 'multiple_choice', '_____ we automate, _____ time we save.', '["Most / more","The more / the more","The most / most","More / more"]', 'The more / the more', 'The more...the more 自動化與時間節省的正比。'),
(45, 'multiple_choice', '_____ complex the deal, _____ time it takes to close.', '["The more / the more","The most / most","More / more","Most / the most"]', 'The more / the more', 'The more complex...the more time 雙重比較。'),
(45, 'fill_blank', '_____ quickly we resolve the issue, _____ the client will be. (Use double comparative)', NULL, 'The more / the happier', 'The more quickly...the happier 雙重比較。'),
(45, 'multiple_choice', '_____ employees we hire, _____ our training costs.', '["The most / highest","Most / more high","The more / the higher","More / higher"]', 'The more / the higher', 'The more...the higher 雙重比較。'),
(45, 'transform', 'Strong branding leads to higher customer loyalty. (Use double comparative)', NULL, 'The stronger the brand, the higher the customer loyalty.', 'The stronger...the higher 雙重比較。'),
(45, 'multiple_choice', '_____ we focus on quality, _____ our reputation becomes.', '["Most / more strong","More / stronger","The more / the stronger","The most / strongest"]', 'The more / the stronger', 'The more...the stronger 品質與聲譽的關係。'),
(45, 'fill_blank', '_____ diversified the portfolio, _____ the risk. (Use double comparative)', NULL, 'The more / the lower', 'The more diversified...the lower the risk 雙重比較。'),
(45, 'multiple_choice', '_____ innovative the product, _____ it captures the market.', '["More / faster","The more / the faster","Most / more fast","The most / fastest"]', 'The more / the faster', 'The more innovative...the faster market capture。'),
(45, 'multiple_choice', '_____ clear our strategy, _____ aligned the team will be.', '["The most / most","Much / more","The more / the more","More / more"]', 'The more / the more', 'The more clear...the more aligned 雙重比較。'),
(45, 'transform', 'Faster decisions produce better results. (Use double comparative)', NULL, 'The faster we make decisions, the better the results will be.', 'The faster...the better 雙重比較。'),
(45, 'fill_blank', '_____ data-driven our approach, _____ accurate our forecasts. (Use double comparative)', NULL, 'The more / the more', 'The more data-driven...the more accurate 雙重比較。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(46, 'multiple_choice', '_____ the contract is signed, we can begin the project.', '["While","Until","Once","As soon as"]', 'Once', 'Once 表一旦...就，同 as soon as。'),
(46, 'multiple_choice', 'Please notify me _____ the client arrives.', '["before","as soon as","while","until"]', 'as soon as', 'as soon as 表一到達就立即通知。'),
(46, 'multiple_choice', 'She will stay in the office _____ the report is finished.', '["before","while","until","when"]', 'until', 'until 表持續到某事完成為止。'),
(46, 'fill_blank', '_____ (finish) the presentation, we will take questions.', NULL, 'After finishing / When we finish', 'after + V-ing 或 when + clause。'),
(46, 'multiple_choice', 'He checks his emails _____ he commutes to work.', '["once","until","while","before"]', 'while', 'while 表同時進行的動作。'),
(46, 'multiple_choice', 'We need to finalize the budget _____ the board meeting.', '["until","when","before","after"]', 'before', 'before the board meeting 截止時間。'),
(46, 'transform', 'The meeting ends. Then we will announce the results. (Use: after)', NULL, 'After the meeting ends, we will announce the results.', 'after + 時間子句。'),
(46, 'fill_blank', '_____ (submit) your application, please read all the requirements.', NULL, 'Before submitting', 'before + V-ing 提交前注意事項。'),
(46, 'multiple_choice', 'Sales increased significantly _____ the new campaign was launched.', '["before","after","while","until"]', 'after', 'after the campaign was launched 描述因果和時間。'),
(46, 'multiple_choice', 'By the time the CEO arrived, the team _____ already started.', '["had","have","was","has"]', 'had', 'by the time + 現在式，主句過去完成式。'),
(46, 'multiple_choice', '_____ working with international clients, she developed strong language skills.', '["While","Before","Until","Once"]', 'While', 'while + V-ing 表同時進行的情況。'),
(46, 'fill_blank', 'We cannot proceed _____ we receive the signed contract.', NULL, 'until', 'until 表等到...才能進行。'),
(46, 'multiple_choice', 'She always reviews the agenda _____ she enters the meeting room.', '["after","before","while","until"]', 'before', 'before 表進場前先做的事。'),
(46, 'multiple_choice', 'The problem was resolved _____ it escalated further.', '["when","before","until","after"]', 'before', 'before it escalated 提前解決。'),
(46, 'transform', 'The training finishes. We will assign team roles. (Use: when)', NULL, 'When the training finishes, we will assign everyone their team roles.', 'when + 現在式（表未來），will 主句。'),
(46, 'fill_blank', 'We had completed the onboarding _____ the new hire started.', NULL, 'before', 'before the new hire started，時間先後關係。'),
(46, 'multiple_choice', '_____ the audit is complete, the results will be shared with all departments.', '["Once","Before","Until","While"]', 'Once', 'Once the audit is complete 表完成後。'),
(46, 'multiple_choice', 'She takes notes _____ the client is speaking.', '["until","after","before","while"]', 'while', 'while 表同時進行。'),
(46, 'multiple_choice', 'The deal was announced _____ both sides had agreed on all terms.', '["after","before","while","until"]', 'after', 'after both sides agreed 強調先後。'),
(46, 'multiple_choice', 'He will work on this project _____ he transfers to the new position.', '["until","when","before","after"]', 'until', 'until he transfers 持續到調職為止。'),
(47, 'multiple_choice', '_____ the deadline was extended, we have more time to review.', '["Since","Despite","Although","Because of"]', 'Since', 'since/because 引導原因子句。'),
(47, 'multiple_choice', 'We had to cancel the event _____ low attendance.', '["because of","since","now that","as"]', 'because of', 'because of + 名詞短語（非子句）表原因。'),
(47, 'multiple_choice', 'She was promoted _____ she consistently exceeded her targets.', '["however","because","although","despite"]', 'because', 'because 引導原因子句。'),
(47, 'fill_blank', '_____ the market has stabilized, we can proceed with the investment.', NULL, 'Now that', 'now that 表現在情況改變，因此...。'),
(47, 'multiple_choice', '_____ the project was behind schedule, additional resources were allocated.', '["As","Despite","Although","However"]', 'As', 'as 引導原因子句，較正式。'),
(47, 'multiple_choice', 'We need to act quickly _____ our competitors are already ahead.', '["however","because","although","despite"]', 'because', 'because 引導原因子句。'),
(47, 'multiple_choice', 'He was unable to attend the meeting _____ a prior commitment.', '["as","due to","because","since"]', 'due to', 'due to + 名詞短語（非子句）表原因，正式用法。'),
(47, 'transform', 'The project failed. The reason was poor communication. (Use: because)', NULL, 'The project failed because of poor communication among the teams.', 'because of + 名詞短語。'),
(47, 'fill_blank', '_____ the economy is recovering, consumer confidence is rising.', NULL, 'As / Since', 'as 或 since 引導原因子句。'),
(47, 'multiple_choice', '_____ he had the most experience, he was chosen to lead the negotiation.', '["Despite","However","Since","Although"]', 'Since', 'since 引導原因子句，用於說明已知原因。'),
(47, 'multiple_choice', 'The order was delayed _____ a production error.', '["since","owing to","because","as"]', 'owing to', 'owing to + 名詞短語，正式原因表達。'),
(47, 'multiple_choice', '_____ the new policy was implemented, employee satisfaction has improved.', '["Because of","Now that","Although","Since"]', 'Now that', 'now that 表現在的新情況導致的結果。'),
(47, 'fill_blank', 'She was given extra responsibility _____ she had proven herself reliable.', NULL, 'because / since', 'because 或 since 引導原因子句。'),
(47, 'multiple_choice', 'The meeting was rescheduled _____ the CEO was travelling.', '["however","despite","although","as"]', 'as', 'as 引導原因子句，較正式。'),
(47, 'multiple_choice', 'We lost the contract _____ our pricing was not competitive.', '["despite","although","however","because"]', 'because', 'because 引導原因子句。'),
(47, 'transform', 'The branch closed. There was insufficient demand. (Use: due to)', NULL, 'The branch was closed due to insufficient demand in the local market.', 'due to + 名詞短語表原因。'),
(47, 'fill_blank', '_____ (because) bad weather, the outdoor event was moved indoors.', NULL, 'Because of / Due to', 'because of / due to + 名詞短語。'),
(47, 'multiple_choice', 'She left the firm early _____ a family emergency.', '["since","because of","as","now that"]', 'because of', 'because of + 名詞短語。'),
(47, 'multiple_choice', '_____ sales are declining, we must reassess our strategy.', '["However","Despite","Although","As"]', 'As', 'as 引導原因子句。'),
(47, 'multiple_choice', 'The contract was terminated _____ breach of terms.', '["since","as","because","due to"]', 'due to', 'due to 正式書面原因表達。'),
(48, 'multiple_choice', '_____ the budget was limited, the project was completed on time.', '["Although","Since","While","Because"]', 'Although', 'although 引導讓步子句。'),
(48, 'multiple_choice', 'Sales increased _____ we reduced our marketing spend.', '["although","even though","while","because"]', 'even though', 'even though 強調更大的讓步（減少行銷費用仍增加）。'),
(48, 'multiple_choice', 'Our product is more expensive _____ it offers greater value.', '["despite","however","although","but"]', 'but', 'but 連接對比子句（並列）。'),
(48, 'fill_blank', '_____ (although) the proposal was rejected, we learned from the experience.', NULL, 'Although / Even though', 'although/even though 引導讓步子句。'),
(48, 'multiple_choice', '_____ our team is small, we consistently deliver high-quality results.', '["Although","Despite","However","Whereas"]', 'Whereas', 'whereas 也可引導對比（此處也可用 Although）。'),
(48, 'multiple_choice', 'The market is recovering _____ some sectors are still struggling.', '["while","since","although","because"]', 'while', 'while 表兩種情況的對比。'),
(48, 'multiple_choice', 'She accepted the offer _____ the salary was lower than expected.', '["because","even though","since","while"]', 'even though', 'even though 強調讓步。'),
(48, 'transform', 'We increased output. At the same time, we reduced defects. (Use: while)', NULL, 'While we increased output, we also managed to reduce defects.', 'while 表同時對比或並列情況。'),
(48, 'fill_blank', '_____ having limited resources, the team delivered excellent results.', NULL, 'Despite', 'despite + V-ing 讓步表達。'),
(48, 'multiple_choice', 'The demand for our product is high _____ the price increase.', '["even though","despite","while","although"]', 'despite', 'despite + 名詞短語（非子句）。');