INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(66, 'multiple_choice', 'The presentation was _____ — everyone was falling asleep.', '["bored","boring","boringly","bore"]', 'boring', 'boring 形容報告本身令人無聊。'),
(66, 'multiple_choice', 'She was _____ by the innovative features of the new software.', '["impressing","impressed","impress","impressingly"]', 'impressed', 'impressed 形容她的感受，-ed 形容詞。'),
(66, 'multiple_choice', 'The training session was _____ and highly effective.', '["engaging","engaged","engagement","engagingly"]', 'engaging', 'engaging 形容訓練課程令人投入，-ing 形容詞。'),
(66, 'fill_blank', 'He was _____ (confuse) by the conflicting reports from different departments.', NULL, 'confused', 'confused 形容他的感受（被搞糊塗了）。'),
(66, 'multiple_choice', 'The client seemed _____ with the proposed timeline.', '["satisfied","satisfying","satisfy","satisfiedly"]', 'satisfied', 'satisfied 形容客戶的感受，-ed 形容詞。'),
(66, 'multiple_choice', 'The merger news was _____ for the entire industry.', '["surprised","surprising","surprisingly","surprise"]', 'surprising', 'surprising 形容消息本身令人驚訝，-ing。'),
(66, 'multiple_choice', 'He was _____ about the prospect of leading the project.', '["exciting","excited","excitedly","excite"]', 'excited', 'excited 形容他的感受，-ed。'),
(66, 'transform', 'The quarterly data shocked the investors. (Use -ing or -ed adjective)', NULL, 'The quarterly data was shocking. The investors were shocked.', 'shocking 形容資料，shocked 形容投資者的感受。'),
(66, 'multiple_choice', 'The client was _____ by the delay and demanded an explanation.', '["frustratedly","frustrating","frustrate","frustrated"]', 'frustrated', 'frustrated 形容客戶的感受，-ed。'),
(66, 'fill_blank', 'The new system is very _____ (interest) to use.', NULL, 'interesting', 'interesting 形容系統本身，-ing。'),
(66, 'multiple_choice', 'She gave a very _____ speech at the award ceremony.', '["inspiring","inspired","inspire","inspiredly"]', 'inspiring', 'inspiring 形容演講令人振奮，-ing。'),
(66, 'multiple_choice', 'He is _____ with his current workload.', '["overwhelming","overwhelmedly","overwhelm","overwhelmed"]', 'overwhelmed', 'overwhelmed 形容他的感受，-ed。'),
(66, 'multiple_choice', 'The results were _____ — far better than expected.', '["encouraging","encouragedly","encourage","encouraged"]', 'encouraging', 'encouraging 形容結果令人鼓舞，-ing。'),
(66, 'fill_blank', 'They were _____ (embarrass) by the mistake in the public report.', NULL, 'embarrassed', 'embarrassed 形容他們的感受，-ed。'),
(66, 'multiple_choice', 'The proposal is quite _____ and needs revision.', '["confuse","confusingly","confusing","confused"]', 'confusing', 'confusing 形容提案令人困惑，-ing。'),
(66, 'multiple_choice', 'She was _____ to hear that she had been selected.', '["delightedly","delighting","delight","delighted"]', 'delighted', 'delighted 形容她的感受（非常高興），-ed。'),
(66, 'multiple_choice', 'The project status update was rather _____.', '["alarm","alarming","alarmingly","alarmed"]', 'alarming', 'alarming 形容更新內容令人擔憂，-ing。'),
(66, 'transform', 'The technical report was hard to follow. Many people felt confused. (Use adjectives)', NULL, 'The technical report was confusing, and many readers were confused.', 'confusing（報告）vs confused（讀者感受）。'),
(66, 'fill_blank', 'The team felt _____ (motivate) by the CEO''s speech.', NULL, 'motivated', 'motivated 形容團隊的感受，-ed。'),
(66, 'multiple_choice', 'His presentation was extremely _____ and well-structured.', '["information","informative","informed","informingly"]', 'informative', 'informative 形容報告本身資訊豐富，-ive 形容詞。'),
(67, 'multiple_choice', 'She _____ sends a follow-up email after every client meeting.', '["seldom","never","always","is always"]', 'always', 'always 頻率最高，置主要動詞前。'),
(67, 'multiple_choice', 'We _____ hold team-building events twice a year.', '["rarely","always","usually","never"]', 'usually', 'usually 表一般情況下（通常），置主要動詞前。'),
(67, 'multiple_choice', 'He is _____ late — it''s a known problem.', '["always","usually","rarely","often"]', 'often', 'often 置 be 動詞後。'),
(67, 'fill_blank', 'Our team _____ (occasional) works overtime to meet deadlines.', NULL, 'occasionally', 'occasionally 頻率副詞置主要動詞前。'),
(67, 'multiple_choice', 'She _____ forgets important deadlines.', '["always","often","usually","rarely"]', 'rarely', 'rarely 幾乎不，置主要動詞前。'),
(67, 'multiple_choice', 'The CEO _____ attends daily briefings — her schedule is too busy.', '["rarely","always","often","usually"]', 'rarely', 'rarely attends 幾乎不出席。'),
(67, 'multiple_choice', 'We _____ receive complaints about our premium service.', '["always","usually","often","seldom"]', 'seldom', 'seldom 幾乎不（書面），置主要動詞前。'),
(67, 'transform', 'She doesn''t often work on weekends. (Use: rarely)', NULL, 'She rarely works on weekends, even during busy periods.', 'rarely 頻率低，置動詞前。'),
(67, 'multiple_choice', 'The quarterly report is _____ submitted on time.', '["always","never","seldom","rarely"]', 'always', 'always 表每次都準時，置 be 後。'),
(67, 'fill_blank', 'He _____ (frequent) checks the project dashboard.', NULL, 'frequently', 'frequently 頻率副詞。'),
(67, 'multiple_choice', 'We _____ find errors in automatically generated reports.', '["seldom","never","sometimes","always"]', 'sometimes', 'sometimes 有時（中等頻率）。'),
(67, 'multiple_choice', 'The manager _____ praises good work publicly.', '["regularly","never","rarely","seldom"]', 'regularly', 'regularly 定期，置主要動詞前。'),
(67, 'multiple_choice', 'Clients _____ request revisions to the proposal.', '["never","rarely","seldom","often"]', 'often', 'often 表常常請求修改。'),
(67, 'transform', 'It''s not common for her to miss meetings. (Use: rarely)', NULL, 'She rarely misses meetings without giving prior notice.', 'rarely 幾乎不，置主要動詞前。'),
(67, 'fill_blank', 'He _____ (never) submits his reports without proofreading them.', NULL, 'never', 'never 絕對不，置主要動詞前。'),
(67, 'multiple_choice', 'She is _____ the first person to arrive in the office.', '["never","always","seldom","usually"]', 'usually', 'usually the first 通常最早。'),
(67, 'multiple_choice', 'We _____ miss a delivery deadline.', '["always","never","often","usually"]', 'never', 'never miss 絕不錯過。'),
(67, 'multiple_choice', 'The board _____ meets once a month.', '["rarely","seldom","typically","never"]', 'typically', 'typically 通常（典型地），頻率副詞。'),
(67, 'fill_blank', 'She _____ (always) double-checks her calculations before presenting.', NULL, 'always', 'always 置主要動詞前。'),
(67, 'multiple_choice', 'Performance reviews are _____ conducted annually.', '["never","normally","seldom","rarely"]', 'normally', 'normally conducted 通常每年進行。'),
(68, 'multiple_choice', 'The new policy is _____ important for all employees to understand.', '["extremer","most extremely","extreme","extremely"]', 'extremely', 'extremely + 形容詞，程度副詞。'),
(68, 'multiple_choice', 'The presentation was _____ persuasive, but not entirely convincing.', '["very much","much","quite","mostly"]', 'quite', 'quite 表相當（有些限制性）。'),
(68, 'multiple_choice', 'She was _____ aware of the risks before signing the contract.', '["fully","with fully","full","fulling"]', 'fully', 'fully aware 完全知曉，程度副詞 fully。'),
(68, 'fill_blank', 'The results are _____ (slight) better than last quarter.', NULL, 'slightly', 'slightly + 比較級，稍微好一點。'),
(68, 'multiple_choice', 'He is _____ experienced in international negotiations.', '["a lot","high","highly","very much"]', 'highly', 'highly experienced 非常有經驗（highly 修飾形容詞）。'),
(68, 'multiple_choice', 'The project is _____ complete — only the final report is missing.', '["mostly","almost","nearly complete","quite"]', 'almost', 'almost complete 幾乎完成。'),
(68, 'multiple_choice', 'The client was _____ satisfied with the revised proposal.', '["entirely","entire","entiredly","with entirely"]', 'entirely', 'entirely satisfied 完全滿意。'),
(68, 'transform', 'She is not very confident about the outcome. (Use: somewhat)', NULL, 'She is somewhat uncertain about the final outcome.', 'somewhat 表有些程度的不確定。'),
(68, 'multiple_choice', 'The budget is _____ tight this quarter.', '["pretty much","quite much","fairly so","rather"]', 'rather', 'rather tight 相當緊（商業正式用語）。'),
(68, 'fill_blank', 'This task is _____ (complete) straightforward and shouldn''t take long.', NULL, 'completely / quite', 'completely 或 quite straightforward。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(68, 'multiple_choice', 'He is _____ qualified for this position — exceeds all requirements.', '["more than","much","quite","enough"]', 'more than', 'more than qualified 超過所需資格。'),
(68, 'multiple_choice', 'The market has _____ changed in the past decade.', '["significantly","much significantly","a significant","significant"]', 'significantly', 'significantly 副詞修飾動詞 changed。'),
(68, 'multiple_choice', 'The proposal is _____ ready — just needs final approval.', '["mostly","quite","almost","nearly much"]', 'almost', 'almost ready 快要好了。'),
(68, 'transform', 'The improvement was not large, just moderate. (Use: slightly)', NULL, 'The improvement was slightly larger than in the previous period.', 'slightly + 比較級表輕微差距。'),
(68, 'fill_blank', 'She is _____ (absolute) committed to meeting this deadline.', NULL, 'absolutely', 'absolutely committed 完全投入。'),
(68, 'multiple_choice', 'The team was _____ overwhelmed by the scope of the project.', '["at initial","initialy","initially","initial"]', 'initially', 'initially overwhelmed 最初感到不堪負荷。'),
(68, 'multiple_choice', 'Results are _____ dependent on market conditions.', '["largely","large","larging","much largely"]', 'largely', 'largely dependent 很大程度上取決於。'),
(68, 'multiple_choice', 'This approach is _____ different from what we tried before.', '["a fundamental","fundamental","fundamentally","with fundamental"]', 'fundamentally', 'fundamentally different 根本上不同。'),
(68, 'fill_blank', 'The contract terms are _____ (fair) reasonable and we recommend signing.', NULL, 'fairly', 'fairly reasonable 相當合理。'),
(68, 'multiple_choice', 'She is _____ capable of handling this independently.', '["much perfectly","perfecting","perfect","perfectly"]', 'perfectly', 'perfectly capable 完全有能力。'),
(69, 'multiple_choice', 'The project was delayed; _____, we met the overall goal.', '["meanwhile","moreover","therefore","however"]', 'however', 'however 表轉折讓步。'),
(69, 'multiple_choice', 'Sales increased last quarter; _____, we need to maintain the momentum.', '["meanwhile","moreover","however","therefore"]', 'therefore', 'therefore 表因此，結果。'),
(69, 'multiple_choice', 'The new system is faster; _____, it is much easier to use.', '["however","moreover","meanwhile","therefore"]', 'moreover', 'moreover 表此外、而且（遞進）。'),
(69, 'fill_blank', 'We have reduced costs; _____, we have improved quality.', NULL, 'furthermore / moreover', 'furthermore 表進一步，遞進。'),
(69, 'multiple_choice', 'The budget was cut; _____, the team delivered excellent results.', '["meanwhile","moreover","therefore","nevertheless"]', 'nevertheless', 'nevertheless 表儘管如此（讓步）。'),
(69, 'multiple_choice', 'Sales dropped in Q1; _____, the company remained profitable.', '["therefore","moreover","however","meanwhile"]', 'however', 'however 表轉折。'),
(69, 'multiple_choice', 'The report was incomplete; _____, the meeting was postponed.', '["moreover","however","consequently","meanwhile"]', 'consequently', 'consequently 表因此，結果。'),
(69, 'transform', 'We finished the analysis. At the same time, the client submitted new data. (Use: meanwhile)', NULL, 'We finished the analysis; meanwhile, the client submitted additional data.', 'meanwhile 表同時發生。'),
(69, 'multiple_choice', 'The strategy was risky; _____, it paid off in the long run.', '["meanwhile","moreover","therefore","nevertheless"]', 'nevertheless', 'nevertheless 表儘管如此，結果還是成功。'),
(69, 'fill_blank', 'We exceeded our targets; _____, the board has approved additional funding.', NULL, 'consequently / therefore', 'consequently/therefore 表因此獲批預算。'),
(69, 'multiple_choice', 'The market is volatile; _____, we are reviewing our investment strategy.', '["meanwhile","moreover","however","therefore"]', 'therefore', 'therefore 表因此要重新評估。'),
(69, 'multiple_choice', 'She is skilled in data analysis; _____, she is an excellent communicator.', '["however","therefore","meanwhile","moreover"]', 'moreover', 'moreover 遞進，不只有分析能力還有溝通能力。'),
(69, 'multiple_choice', 'The results were disappointing; _____, we are committed to improvement.', '["therefore","moreover","however","meanwhile"]', 'however', 'however 轉折，表仍致力於改進。'),
(69, 'transform', 'The price increased. As a result, demand fell. (Use: consequently)', NULL, 'The price increased; consequently, demand fell significantly.', 'consequently 表結果。'),
(69, 'fill_blank', 'The negotiations failed; _____, the company sought alternative partners.', NULL, 'consequently / therefore', '因此尋求替代夥伴。'),
(69, 'multiple_choice', 'The first proposal was rejected; _____, we submitted a revised version.', '["meanwhile","consequently","moreover","however"]', 'consequently', 'consequently 表因此採取後續行動。'),
(69, 'multiple_choice', 'The new policy saves time; _____, it reduces errors.', '["furthermore","therefore","meanwhile","however"]', 'furthermore', 'furthermore 表此外（遞進優點）。'),
(69, 'multiple_choice', 'We cut costs; _____, we maintained service quality.', '["meanwhile","nevertheless","moreover","therefore"]', 'nevertheless', 'nevertheless 表儘管削減成本，服務品質仍維持。'),
(69, 'fill_blank', 'The report was submitted on time; _____, the content was incomplete.', NULL, 'however', 'however 表轉折（準時但內容不完整）。'),
(69, 'multiple_choice', 'She worked long hours; _____, she took regular breaks.', '["moreover","meanwhile","nevertheless","therefore"]', 'nevertheless', 'nevertheless 表儘管如此仍有休息。'),
(70, 'multiple_choice', '_____ is the communication breakdown that caused the project delay.', '["That","What","It","This"]', 'It', 'It is...that 分裂句固定結構。'),
(70, 'multiple_choice', 'It was _____ who first proposed the new strategy.', '["which marketing director","the marketing director","marketing director that","what marketing director"]', 'the marketing director', 'It was + 強調成分 + who（指人）。'),
(70, 'multiple_choice', 'It is _____ that we need to focus on first.', '["the retention customer","which customer retention","customer retention","what customer retention"]', 'customer retention', 'It is...that 強調受語。'),
(70, 'fill_blank', '_____ (It) is the timeline, not the budget, _____ (that) concerns the board most.', NULL, 'It / that', 'It is...that 強調主語中的特定成分。'),
(70, 'multiple_choice', 'It was _____ that the company experienced its biggest growth.', '["on 2022","at 2022","in 2022","2022"]', 'in 2022', 'It was + 時間 + that 強調時間。'),
(70, 'multiple_choice', 'It is _____ that sets us apart from our competitors.', '["what our quality","the quality our","our commitment to quality","which quality"]', 'our commitment to quality', 'It is...that 強調核心競爭優勢。'),
(70, 'multiple_choice', 'It was the sales team _____ secured the deal.', '["that","which","whom","who"]', 'that', 'It was + 人 + that/who。'),
(70, 'transform', 'The quality of our service concerns clients most. (Use cleft sentence)', NULL, 'It is the quality of our service that clients appreciate most.', 'It is...that 分裂句強調主語。'),
(70, 'multiple_choice', 'It was _____ that the system crashed.', '["in during audit","while the audit","at audit","during the audit"]', 'during the audit', 'It was + 時間狀語 + that 強調時間。'),
(70, 'fill_blank', 'It _____ (be) the CEO''s vision _____ (drive) the company''s transformation.', NULL, 'was / that', 'It was...that 強調 CEO 的願景。'),
(70, 'multiple_choice', 'It is _____ that we must improve immediately.', '["what response time","the responding time","which response","our response time"]', 'our response time', 'It is...that 強調需改進的方面。'),
(70, 'multiple_choice', 'It was _____ that led to the breakthrough.', '["which team","the team''s collaboration","what collaboration","the collaborate team"]', 'the team''s collaboration', 'It was...that 強調成功原因。'),
(70, 'multiple_choice', 'It is not the price but the _____ that matters to clients.', '["qualify","quality","qualified","qualities"]', 'quality', 'It is...that 強調客戶真正在意的是品質。'),
(70, 'transform', 'The new technology changed how we work. (Use cleft sentence)', NULL, 'It is the new technology that has completely changed how we work.', 'It is...that 強調主語。'),
(70, 'fill_blank', 'It was _____ the product launch _____ attracted international media attention.', NULL, 'the success of / that', 'It was...that 強調事件。'),
(70, 'multiple_choice', 'It was _____ that she finally received the recognition she deserved.', '["on award ceremony","at the annual awards ceremony","in annual ceremony","at ceremony annual"]', 'at the annual awards ceremony', 'It was + 地點狀語 + that 強調地點。'),
(70, 'multiple_choice', '_____ is his attention to detail that makes him invaluable.', '["This","That","What","It"]', 'It', 'It is...that 分裂句。'),
(70, 'transform', 'The new regulation affected the whole industry. (Use cleft sentence)', NULL, 'It was the new regulation that affected the entire industry.', 'It was...that 強調主語。'),
(70, 'fill_blank', 'It _____ (be) the client''s feedback _____ (guide) the product revision.', NULL, 'was / that', 'It was...that 強調客戶意見的重要性。'),
(70, 'multiple_choice', 'It is _____ that has made this project so challenging.', '["the lacking resources","the lack of resources","what lack of resources","which resource lack"]', 'the lack of resources', 'It is...that 強調挑戰原因。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(71, 'multiple_choice', 'We _____ appreciate your patience during this process.', '["are","do","have","really"]', 'do', 'do appreciate 強調確實感謝，反駁不耐煩的印象。'),
(71, 'multiple_choice', 'She _____ submit the report — I saw her send it myself.', '["does","did","was","has"]', 'did', 'did submit 強調她確實提交了（過去式強調）。'),
(71, 'multiple_choice', 'He _____ try his best, even if the results weren''t perfect.', '["is","has","would","does"]', 'does', 'does try 強調他確實努力了（三單現在式）。'),
(71, 'fill_blank', 'I _____ (emphatic) believe this is the right decision for the company.', NULL, 'do', 'do believe 強調肯定信念。'),
(71, 'multiple_choice', 'We _____ value our relationship with your company.', '["do","would","have","are"]', 'do', 'do value 強調確實重視關係。'),
(71, 'multiple_choice', 'They _____ complete their projects on time, contrary to what you might think.', '["have","were","do","are"]', 'do', 'do complete 反駁認為他們不能按時完成的看法。'),
(71, 'multiple_choice', 'She _____ work extremely hard — she just doesn''t show it.', '["is","has","does","would"]', 'does', 'does work 強調她確實努力（三單）。'),
(71, 'transform', 'We really care about quality. (Use emphatic do)', NULL, 'We do care about maintaining the highest quality standards.', 'do care 強調確實在乎。'),
(71, 'fill_blank', 'The team _____ (emphatic) meet their deadlines, despite the challenges.', NULL, 'does', 'does meet 強調三單事實。'),
(71, 'multiple_choice', 'He _____ send the invoice, but it may have gone to your spam folder.', '["did","was","had","has"]', 'did', 'did send 強調他確實寄了（過去式）。'),
(71, 'multiple_choice', 'We _____ understand the urgency of this matter.', '["are","do","have","would"]', 'do', 'do understand 強調理解的語氣。'),
(71, 'multiple_choice', 'I _____ apologize for any inconvenience this may have caused.', '["do","have","am","would"]', 'do', 'do apologize 強調真誠道歉。'),
(71, 'transform', 'She took all the necessary precautions. (Use emphatic did)', NULL, 'She did take all the necessary precautions before the launch.', 'did take 強調過去確實採取措施。'),
(71, 'fill_blank', 'They _____ (emphatic) try to resolve the issue before escalating.', NULL, 'did', 'did try 強調過去確實嘗試解決。'),
(71, 'multiple_choice', 'The results _____ show improvement compared to last quarter.', '["have","are","would","do"]', 'do', 'do show 強調結果確實顯示改善。'),
(71, 'multiple_choice', 'We _____ meet our obligations under the contract.', '["are","have","do","would"]', 'do', 'do meet 強調確實履行合約義務。'),
(71, 'multiple_choice', 'She _____ receive the email, but she was too busy to respond.', '["has","did","was","had"]', 'did', 'did receive 強調她確實收到了（過去式）。'),
(71, 'transform', 'The new policy has had a positive impact. (Use emphatic does)', NULL, 'The new policy does have a positive impact on employee morale.', 'does have 強調政策確實有效。'),
(71, 'fill_blank', 'I _____ (emphatic) think we should reconsider our approach.', NULL, 'do', 'do think 強調肯定意見。'),
(71, 'multiple_choice', 'He _____ handle pressure very well — that''s why he leads the team.', '["would","is","does","has"]', 'does', 'does handle 強調能力（三單）。'),
(72, 'multiple_choice', 'We recommend that the board _____ the proposal immediately.', '["approves","approved","approve","approving"]', 'approve', 'recommend that + 原形動詞（虛擬語氣）。'),
(72, 'multiple_choice', 'The committee insists that all documents _____ in English.', '["were submitted","be submitted","should submitted","are submitted"]', 'be submitted', 'insist that + 原形被動（be + p.p.）。'),
(72, 'multiple_choice', 'It is essential that every employee _____ the training.', '["attends","is attending","attend","attended"]', 'attend', 'It is essential that + 原形動詞。'),
(72, 'fill_blank', 'The director suggested that the team _____ (reconsider) its approach.', NULL, 'reconsider', 'suggest that + 原形動詞，虛擬語氣。'),
(72, 'multiple_choice', 'The policy requires that all contractors _____ background checks.', '["are undergoing","undergo","underwent","undergoes"]', 'undergo', 'require that + 原形動詞。'),
(72, 'multiple_choice', 'It is important that the report _____ before Friday.', '["should completed","was completed","is completed","be completed"]', 'be completed', 'It is important that + 原形（被動）。'),
(72, 'multiple_choice', 'She demands that the error _____ immediately.', '["is corrected","was corrected","be corrected","should corrected"]', 'be corrected', 'demand that + 原形（被動）。'),
(72, 'transform', 'The management says all staff must attend. (Use: requires that)', NULL, 'Management requires that all staff attend the mandatory briefing.', 'require that + 原形動詞。'),
(72, 'fill_blank', 'The legal team recommended that the contract _____ (revise) before signing.', NULL, 'be revised', 'recommend that + 原形被動，虛擬語氣。'),
(72, 'multiple_choice', 'It is vital that the team _____ aware of the new regulations.', '["was","should be","be","is"]', 'be', 'It is vital that + be（原形）。'),
(72, 'multiple_choice', 'The auditor suggested that the company _____ its accounting practices.', '["reviewed","review","reviews","should review"]', 'review', 'suggest that + 原形動詞。'),
(72, 'multiple_choice', 'We insist that the supplier _____ a replacement within 48 hours.', '["is providing","provide","provides","should provide"]', 'provide', 'insist that + 原形動詞。'),
(72, 'transform', 'It is necessary for all managers to complete the form. (Use subjunctive)', NULL, 'It is necessary that all managers complete the certification form.', 'It is necessary that + 原形動詞。'),
(72, 'fill_blank', 'The board proposed that a new committee _____ (form) to investigate the issue.', NULL, 'be formed', 'propose that + 原形（被動），虛擬語氣。'),
(72, 'multiple_choice', 'It is crucial that the strategy _____ before the board meeting.', '["was finalized","is finalized","be finalized","should finalize"]', 'be finalized', 'It is crucial that + 原形（被動）。'),
(72, 'multiple_choice', 'The manager recommended that she _____ leadership training.', '["undergo","undergoes","underwent","is undergoing"]', 'undergo', 'recommend that + 原形，虛擬語氣。'),
(72, 'multiple_choice', 'The protocol demands that all visitors _____ security badges.', '["should wear","wear","wears","wore"]', 'wear', 'demand that + 原形動詞。'),
(72, 'transform', 'We advise that all stakeholders attend. (Use: suggest that)', NULL, 'We suggest that all stakeholders attend the annual general meeting.', 'suggest that + 原形動詞。'),
(72, 'fill_blank', 'It is imperative that the deadline _____ (meet).', NULL, 'be met', 'be met 原形被動，虛擬語氣。'),
(72, 'multiple_choice', 'She proposed that the salary review _____ every year.', '["be conducted","should conducted","is conducted","was conducted"]', 'be conducted', 'propose that + 原形被動。'),
(73, 'multiple_choice', 'I wish I _____ more time to review the proposal.', '["had","have","will have","would have"]', 'had', 'wish + 過去式表對現在的願望。'),
(73, 'multiple_choice', 'She wishes she _____ taken that promotion years ago.', '["had","will have","have","would have"]', 'had', 'wish + 過去完成式表對過去的遺憾。'),
(73, 'multiple_choice', 'If only we _____ better market research before the launch.', '["do","would do","did","had done"]', 'had done', 'if only + 過去完成式表過去的遺憾，語氣更強。'),
(73, 'fill_blank', 'He wishes the client _____ (respond) faster to our emails.', NULL, 'would respond', 'wish + would + 原形表對他人行為的期望。'),
(73, 'multiple_choice', 'We wish we _____ the contract before the price increase.', '["had signed","signed","have signed","would sign"]', 'had signed', 'wish + 過去完成式表後悔沒有及早簽約。'),
(73, 'multiple_choice', 'If only she _____ more confident during the presentation.', '["had been","were","was","would be"]', 'were', 'if only + were（正式英語）表對現在的願望。'),
(73, 'multiple_choice', 'I wish our team _____ more efficiently.', '["has worked","worked","would work","works"]', 'worked', 'wish + 過去式表對現在的願望。'),
(73, 'transform', 'I regret that we did not hire more staff. (Use: If only)', NULL, 'If only we had hired more staff, we could have met the demand.', 'if only + 過去完成式表過去遺憾。'),
(73, 'fill_blank', 'He wishes the new system _____ (work) as well as the old one.', NULL, 'worked', 'wish + 過去式表對現在的願望。'),
(73, 'multiple_choice', 'If only I _____ about the deal before it fell through.', '["would know","have known","had known","knew"]', 'had known', 'if only + 過去完成式表遺憾。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(73, 'multiple_choice', 'She wishes she _____ have a better work-life balance.', '["can","would","should","could"]', 'could', 'wish + could 表希望能夠（可能性的願望）。'),
(73, 'multiple_choice', 'We wish the client _____ give us more detailed feedback.', '["should","would","could","will"]', 'would', 'wish + would 表期望他人行為改變。'),
(73, 'transform', 'We regret that we lost that account. (Use: We wish we hadn''t)', NULL, 'We wish we hadn''t lost that valuable account.', 'wish + 過去完成否定表遺憾。'),
(73, 'fill_blank', 'If only the budget _____ (be) larger, we could have achieved more.', NULL, 'had been', 'if only + 過去完成式表過去遺憾。'),
(73, 'multiple_choice', 'He wishes he _____ asked for more details before signing.', '["have","had","would have","will have"]', 'had', 'wish + 過去完成式表遺憾。'),
(73, 'multiple_choice', 'If only we _____ the opportunity sooner.', '["recognized","have recognized","would recognize","had recognized"]', 'had recognized', 'if only + 過去完成式。'),
(73, 'multiple_choice', 'She wishes her presentation _____ gone better.', '["had","have","would have","will have"]', 'had', 'wish + 過去完成式表遺憾。'),
(73, 'transform', 'I regret that I didn''t network more at the conference. (Use: I wish I had)', NULL, 'I wish I had networked more at the conference.', 'wish + 過去完成式表遺憾。'),
(73, 'fill_blank', 'If only the team _____ (follow) the original plan, we would be on track.', NULL, 'had followed', 'if only + 過去完成式表後悔。'),
(73, 'multiple_choice', 'We wish the supplier _____ more transparent about delivery times.', '["is","were","was","would be"]', 'were', 'wish + were（過去式）表對現在狀況的願望。'),
(74, 'multiple_choice', '_____ the contract carefully, she noticed a significant error.', '["Read","Having read","Reading","To read"]', 'Reading', 'Reading 現在分詞子句表示同時進行的動作。'),
(74, 'multiple_choice', '_____ in the industry for ten years, she has built an impressive network.', '["To work","Having worked","Worked","Working"]', 'Having worked', 'Having worked = 完成分詞子句，表在主句動作前已完成。'),
(74, 'multiple_choice', '_____ a cost-effective solution, the team adopted the new software.', '["Sought","Having sought","To seek","Seeking"]', 'Seeking', 'Seeking a solution 分詞子句表目的或同時進行。'),
(74, 'fill_blank', '_____ (walk) into the meeting room, he noticed the client looked concerned.', NULL, 'Walking', 'Walking into 現在分詞子句。'),
(74, 'multiple_choice', '_____ that the client was unsatisfied, the manager personally called.', '["Known","Knowing","Having known","To know"]', 'Knowing', 'Knowing that 現在分詞子句表示因為知道。'),
(74, 'multiple_choice', 'She sat at her desk, _____ through the annual report.', '["having flipped","flipped","to flip","flipping"]', 'flipping', 'flipping through 伴隨動作的現在分詞子句。'),
(74, 'multiple_choice', '_____ all stakeholders, the manager made a balanced decision.', '["Consulted","To consult","Consulting","Having consulted"]', 'Consulting', 'Consulting all stakeholders 分詞子句（因此/同時）。'),
(74, 'transform', 'Because she had reviewed all the data, she was confident in her recommendation. (Use -ing clause)', NULL, 'Having reviewed all the data, she was confident in her recommendation.', 'Having reviewed 完成分詞子句。'),
(74, 'fill_blank', '_____ (understand) the risks, the board approved the merger cautiously.', NULL, 'Understanding', 'Understanding the risks 現在分詞子句表因為了解風險。'),
(74, 'multiple_choice', 'He answered all the client''s questions, _____ his expertise.', '["to demonstrate","demonstrated","demonstrating","having demonstrated"]', 'demonstrating', 'demonstrating 伴隨動作的分詞子句。'),
(74, 'multiple_choice', '_____ a thorough analysis, the consultants recommended restructuring.', '["Having conducted","To conduct","Conducting","Conducted"]', 'Having conducted', 'Having conducted 表在主句動作前已完成分析。'),
(74, 'multiple_choice', 'The CEO gave the speech, _____ to the achievements of the entire team.', '["referring","having referred","referred","to refer"]', 'referring', 'referring to 分詞子句，伴隨動作。'),
(74, 'transform', 'Because she worked efficiently, she finished ahead of schedule. (Use -ing clause)', NULL, 'Working efficiently, she finished the project well ahead of schedule.', 'Working efficiently 現在分詞子句表原因。'),
(74, 'fill_blank', '_____ (not / realize) the severity, he underestimated the challenge.', NULL, 'Not realizing', 'Not realizing 否定分詞子句。'),
(74, 'multiple_choice', '_____ the proposal three times, she finally submitted it.', '["Revising","Having revised","Revised","To revise"]', 'Having revised', 'Having revised 表完成後提交。'),
(74, 'multiple_choice', 'She reported the issue, _____ full documentation to support her claims.', '["to provide","having provided","provided","providing"]', 'providing', 'providing 伴隨動作。'),
(74, 'multiple_choice', '_____ late, he missed the beginning of the presentation.', '["To arrive","Having arrived","Arriving","Arrived"]', 'Arriving', 'Arriving late 現在分詞子句（因為晚到）。'),
(74, 'transform', 'After she read the brief, she prepared detailed questions. (Use -ing clause)', NULL, 'Having read the brief, she prepared detailed and insightful questions.', 'Having read 完成分詞子句。'),
(74, 'fill_blank', '_____ (consider) all options, the team chose the most cost-effective approach.', NULL, 'Having considered', 'Having considered 完成分詞子句。'),
(74, 'multiple_choice', 'The director walked out, _____ nothing further to add.', '["saying","said","to say","having said"]', 'saying', 'saying 伴隨動作的分詞子句。'),
(75, 'multiple_choice', '_____ by the legal team, the contract was ready to sign.', '["Reviewing","Having reviewed","To review","Reviewed"]', 'Reviewed', 'Reviewed by 被動過去分詞子句，表完成審查後。'),
(75, 'multiple_choice', '_____ clearly, the instructions were easy to follow.', '["Having written","Written","To write","Writing"]', 'Written', 'Written clearly 被動過去分詞子句。'),
(75, 'multiple_choice', 'The report, _____ overnight, impressed everyone the next morning.', '["completing","having completed","completed","to complete"]', 'completed', 'completed overnight 被動分詞子句。'),
(75, 'fill_blank', '_____ (train) by industry experts, the staff are highly competent.', NULL, 'Trained', 'Trained by 被動過去分詞子句。'),
(75, 'multiple_choice', '_____ thoroughly, the proposal was approved without objection.', '["Having prepared","To prepare","Prepared","Preparing"]', 'Prepared', 'Prepared thoroughly 被動過去分詞子句。'),
(75, 'multiple_choice', 'The data, _____ three times, was finally accepted as accurate.', '["verifying","to verify","verified","having verified"]', 'verified', 'verified three times 被動分詞子句（非限定）。'),
(75, 'multiple_choice', '_____ in Seoul, the new branch quickly became profitable.', '["Establishing","Established","To establish","Having established"]', 'Established', 'Established in Seoul 被動過去分詞子句。'),
(75, 'transform', 'Because the design was approved, production could begin. (Use past participle clause)', NULL, 'Approved by the design committee, the product went into production.', 'Approved 被動過去分詞子句。'),
(75, 'fill_blank', '_____ (submit) on time, the report received positive feedback from the board.', NULL, 'Submitted', 'Submitted on time 被動分詞子句。'),
(75, 'multiple_choice', 'The proposal, _____ by senior leadership, was distributed to all managers.', '["to endorse","endorsed","endorsing","having endorsed"]', 'endorsed', 'endorsed by senior leadership 被動分詞修飾 proposal。'),
(75, 'multiple_choice', '_____ on the market for ten years, the brand is widely trusted.', '["To establish","Having established","Establishing","Established"]', 'Established', 'Established on the market 被動過去分詞子句。'),
(75, 'multiple_choice', 'Once _____, the product will be available in all major retail stores.', '["to launch","launched","having launched","launching"]', 'launched', 'Once launched 被動過去分詞子句。'),
(75, 'transform', 'After the issue was identified, the team worked on a solution. (Use past participle clause)', NULL, 'Identified early, the issue was resolved before it escalated.', 'Identified 被動過去分詞子句。'),
(75, 'fill_blank', '_____ (analyse) carefully, the results showed a clear trend.', NULL, 'Analysed', 'Analysed carefully 被動過去分詞子句。'),
(75, 'multiple_choice', 'If _____ correctly, this strategy should yield significant returns.', '["having implemented","implementing","implemented","to implement"]', 'implemented', 'If implemented correctly 條件被動分詞子句。'),
(75, 'multiple_choice', 'The system, _____ in 2020, is due for an upgrade.', '["having installed","installing","installed","to install"]', 'installed', 'installed in 2020 被動分詞修飾 system。'),
(75, 'multiple_choice', '_____ in three languages, the annual report reaches a global audience.', '["To publish","Published","Publishing","Having published"]', 'Published', 'Published in three languages 被動過去分詞子句。'),
(75, 'transform', 'Once we finalize the agreement, we will make an announcement. (Use past participle clause)', NULL, 'Once finalized, the agreement will be publicly announced.', 'Once finalized 被動過去分詞子句。'),
(75, 'fill_blank', '_____ (overwhelm) with requests, the support team needed more staff.', NULL, 'Overwhelmed', 'Overwhelmed 被動過去分詞子句，表被淹沒在請求中。'),
(75, 'multiple_choice', '_____ by the client, the revised proposal was immediately accepted.', '["Having requested","Requesting","Requested","To request"]', 'Requested', 'Requested by the client 被動過去分詞子句。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(76, 'multiple_choice', 'The employee _____ the project is very experienced.', '["managed","managing","who managing","to manage"]', 'managing', 'managing 現在分詞縮減關係子句（= who manages）。'),
(76, 'multiple_choice', 'The report _____ last week has been approved.', '["submitted","that submitted","to submit","submitting"]', 'submitted', 'submitted 過去分詞縮減被動關係子句（= that was submitted）。'),
(76, 'multiple_choice', 'The candidates _____ for the position all have relevant experience.', '["to apply","applied","who applying","applying"]', 'applying', 'applying 現在分詞縮減主動關係子句。'),
(76, 'fill_blank', 'The system _____ (install) last year needs an upgrade.', NULL, 'installed', 'installed 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'The clients _____ at the trade fair placed large orders.', '["contacting","contacted","who contacting","to contact"]', 'contacted', 'contacted 過去分詞縮減被動關係子句（= who were contacted）。'),
(76, 'multiple_choice', 'The team _____ the analysis made several key recommendations.', '["conducted","who conducting","to conduct","conducting"]', 'conducting', 'conducting 現在分詞縮減主動關係子句（= that is conducting）。'),
(76, 'multiple_choice', 'The software _____ by our IT team is highly efficient.', '["that developing","developed","developing","to develop"]', 'developed', 'developed 過去分詞縮減被動關係子句。'),
(76, 'transform', 'The employee who was selected for the promotion has ten years of experience. (Reduce)', NULL, 'The employee selected for the promotion has ten years of experience.', 'selected 過去分詞縮減被動關係子句。'),
(76, 'fill_blank', 'The proposal _____ (consider) by the board will be announced next week.', NULL, 'being considered', 'being considered 表正在進行中的被動分詞子句。'),
(76, 'multiple_choice', 'Any employee _____ in misconduct will face disciplinary action.', '["to engage","engaged","who engaging","engaging"]', 'engaging', 'engaging in 現在分詞縮減主動關係子句。'),
(76, 'multiple_choice', 'The documents _____ to all parties must be signed.', '["to send","sent","sending","that sending"]', 'sent', 'sent to all parties 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'The companies _____ to participate in the pilot program will be contacted.', '["to select","selected","selecting","that selecting"]', 'selected', 'selected 過去分詞縮減被動關係子句。'),
(76, 'transform', 'The manager who is leading the restructuring is highly experienced. (Reduce)', NULL, 'The manager leading the restructuring is highly experienced.', 'leading 現在分詞縮減主動關係子句。'),
(76, 'fill_blank', 'The data _____ (collect) over three years will be analysed this quarter.', NULL, 'collected', 'collected 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'All orders _____ before Friday will be processed by next week.', '["that placing","to place","placing","placed"]', 'placed', 'placed before Friday 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'The team _____ on the new platform faces some technical challenges.', '["worked","that working","working","to work"]', 'working', 'working on 現在分詞縮減主動關係子句。'),
(76, 'multiple_choice', 'The contract _____ by both parties takes effect immediately.', '["signing","signed","that signing","to sign"]', 'signed', 'signed by both parties 過去分詞縮減被動關係子句。'),
(76, 'transform', 'The client who complained about the delay was given a discount. (Reduce)', NULL, 'The client complaining about the delay was given a discount.', 'complaining 現在分詞縮減主動關係子句。'),
(76, 'fill_blank', 'The staff _____ (recruit) through the agency will start next month.', NULL, 'recruited', 'recruited 過去分詞縮減被動關係子句。'),
(76, 'multiple_choice', 'The strategy _____ last year has proven very effective.', '["adopting","that adopting","adopted","to adopt"]', 'adopted', 'adopted last year 過去分詞縮減被動關係子句。'),
(77, 'multiple_choice', 'Which is more formal?', '["Hey, want to know about your services?","I''m writing to ask about your services.","I am writing to enquire about your services.","Got questions about your services."]', 'I am writing to enquire about your services.', '完整形式、正式詞彙 enquire，更書面正式。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''buy''?', '["get","pick up","grab","purchase"]', 'purchase', 'purchase 比 buy 更正式。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''use''?', '["make use","use out","utilise","use up"]', 'utilise', 'utilise 是 use 的正式書面表達。'),
(77, 'fill_blank', 'Please _____ (tell) us if you require further assistance. (formal)', NULL, 'inform', 'inform 比 tell 更正式。'),
(77, 'multiple_choice', 'Which is more appropriate for a formal business letter?', '["Sorry, but you didn''t get the job.","We regret to inform you that your application has been unsuccessful.","We''re sad to say you failed.","Your application didn''t make it."]', 'We regret to inform you that your application has been unsuccessful.', '正式：regret to inform，完整形式，禮貌措辭。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''help''?', '["chip in","assist","lend a hand","pitch in"]', 'assist', 'assist 比 help 更正式。'),
(77, 'multiple_choice', 'Which is more formal?', '["Just give us a call anytime.","Feel free to contact us.","Please do not hesitate to contact us.","Ring us whenever."]', 'Please do not hesitate to contact us.', 'Please do not hesitate to 是正式商業英語的標準用語。'),
(77, 'transform', 'The meeting is going to start at 2 p.m. (Make more formal)', NULL, 'The meeting is scheduled to commence at 2:00 p.m.', 'is scheduled to commence 更正式；2:00 p.m. 更正式。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''end''?', '["finish up","stop","terminate","quit"]', 'terminate', 'terminate 比 end 更正式（尤指合約）。'),
(77, 'fill_blank', 'We would like to _____ (send) you a copy of our latest brochure. (formal)', NULL, 'forward', 'forward 比 send 更正式。'),
(77, 'multiple_choice', 'Which is NOT appropriate in a formal business email?', '["That sounds great! I''ll get back to you ASAP.","Please find attached the requested document.","We look forward to your response.","We would be delighted to proceed."]', 'That sounds great! I''ll get back to you ASAP.', '口語縮寫 ASAP 和感嘆號不適合正式商業郵件。'),
(77, 'multiple_choice', 'Which sentence uses formal register?', '["Just confirming I got your message.","We wish to confirm receipt of your correspondence.","Thanks for writing to us.","We got your email."]', 'We wish to confirm receipt of your correspondence.', '正式：confirm receipt of your correspondence，無縮寫，正式詞彙。'),
(77, 'transform', 'We want to know if you''re interested. (Make more formal)', NULL, 'We would like to know whether you would be interested in this proposal.', 'would like to + whether 更正式。'),
(77, 'fill_blank', 'I _____ (write) to follow up on our discussion last week. (formal)', NULL, 'am writing to', 'am writing to 正式信件開頭。'),
(77, 'multiple_choice', 'Which is the formal equivalent of ''start''?', '["get going","kick off","commence","start up"]', 'commence', 'commence 比 start 更正式。'),
(77, 'multiple_choice', 'Which sentence is most appropriate for a formal email closing?', '["Hope to hear from you.","We look forward to hearing from you at your earliest convenience.","Talk soon!","Get back to me when you can."]', 'We look forward to hearing from you at your earliest convenience.', '正式結尾語，完整表達，無縮寫。'),
(77, 'multiple_choice', 'Which is the formal way to say ''find out''?', '["look into","figure out","ascertain","dig up"]', 'ascertain', 'ascertain 是 find out 的正式書面表達。'),
(77, 'transform', 'Thanks for your help. (Make more formal)', NULL, 'We would like to express our sincere gratitude for your assistance.', 'express gratitude 正式感謝用語。'),
(77, 'fill_blank', 'We are _____ (look/for) suitable candidates for this position. (formal)', NULL, 'seeking', 'seeking 比 looking for 更正式。'),
(77, 'multiple_choice', 'Which is the formal way to say ''talk about''?', '["talk through","discuss","go over","chat about"]', 'discuss', 'discuss 比 talk about 更正式書面。'),
(78, 'multiple_choice', 'This _____ indicate that sales are beginning to recover.', '["certainly","may","always","definitely"]', 'may', 'may 表謹慎的可能性，是典型的模糊限制語。'),
(78, 'multiple_choice', 'It _____ that there has been a misunderstanding.', '["seems","proves","clearly is","is"]', 'seems', 'it seems that 表猜測/外交委婉。'),
(78, 'multiple_choice', 'The results _____ suggest that the strategy is working.', '["always","definitely","would appear to","certainly"]', 'would appear to', 'would appear to 是高度模糊限制語。'),
(78, 'fill_blank', 'Sales have _____ (possible) declined due to seasonal factors.', NULL, 'possibly', 'possibly 表猜測性副詞，模糊限制語。'),
(78, 'multiple_choice', 'This is _____ due to increased competition.', '["definitely","certainly","arguably","clearly"]', 'arguably', 'arguably 表可以爭論，軟化斷言。'),
(78, 'multiple_choice', 'There _____ be some resistance to the new policy.', '["must","might","shall","will"]', 'might', 'might 表猜測可能性，模糊限制語。'),
(78, 'multiple_choice', 'It _____ that costs will continue to rise.', '["is clear","is likely","is certain","is definite"]', 'is likely', 'is likely 表可能但不確定。'),
(78, 'transform', 'The data shows that profits will fall. (Soften with hedging)', NULL, 'The data suggests that profits may fall slightly next quarter.', 'suggests 和 may 模糊限制語。'),
(78, 'multiple_choice', 'The decline _____ be attributed to external factors.', '["can probably","always","definitely","certainly can"]', 'can probably', 'can probably 是模糊限制語組合。'),
(78, 'fill_blank', 'This _____ (tend) to indicate that there is room for improvement.', NULL, 'tends to', 'tends to indicate 是模糊限制語搭配。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(78, 'multiple_choice', 'It _____ fair to say that progress has been made.', '["would be","is definitely","is certainly","is clearly"]', 'would be', 'it would be fair to say 是典型模糊限制語。'),
(78, 'multiple_choice', 'The evidence _____ suggest a causal relationship.', '["does not","does not necessarily","never","cannot"]', 'does not necessarily', 'does not necessarily 是模糊限制的否定表達。'),
(78, 'multiple_choice', 'There is _____ a connection between the two events.', '["certainly","clearly","possibly","definitely"]', 'possibly', 'possibly 表謹慎猜測。'),
(78, 'transform', 'We are sure that the market will improve. (Add hedging)', NULL, 'We believe that the market may improve over the coming months.', 'believe that...may 模糊限制語。'),
(78, 'fill_blank', 'The report _____ (indicate) that further research is needed.', NULL, 'indicates / suggests', 'indicates 比 proves 更謹慎；suggests 更是模糊限制語。'),
(78, 'multiple_choice', 'This _____ be seen as a positive development.', '["could","shall","will","must"]', 'could', 'could be seen as 模糊限制語。'),
(78, 'multiple_choice', 'It _____ that some stakeholders may have concerns.', '["is certain","is conceivable","is definite","is obvious"]', 'is conceivable', 'it is conceivable that 是正式模糊限制語。'),
(78, 'transform', 'The new regulation will affect all businesses. (Soften with hedging)', NULL, 'The new regulation is likely to affect most businesses to some extent.', 'is likely to 和 to some extent 模糊限制語。'),
(78, 'fill_blank', 'This _____ (appear) to be a viable long-term solution.', NULL, 'appears', 'appears to be 是模糊限制語。'),
(78, 'multiple_choice', 'The figures _____ point to a slight improvement.', '["certainly","definitely","clearly","seem to"]', 'seem to', 'seem to 表謹慎推斷，模糊限制語。'),
(79, 'multiple_choice', 'Which sentence uses nominalization?', '["We''re putting off the launch.","We decided to postpone the launch.","We postponed it.","A decision was made to postpone the launch."]', 'A decision was made to postpone the launch.', 'A decision was made 將動詞 decide 名詞化。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''improve''?', '["improvement","improved","improving","to improve"]', 'improvement', 'improvement 是 improve 的名詞化形式。'),
(79, 'multiple_choice', 'Which sentence uses nominalization?', '["More people want it.","Demand has increased.","People are buying more.","An increase in demand has been observed."]', 'An increase in demand has been observed.', 'An increase in demand 名詞化 demand increased。'),
(79, 'fill_blank', 'Which noun is the nominalization of ''reduce''? → _____.', NULL, 'reduction', 'reduction 是 reduce 的名詞化。'),
(79, 'multiple_choice', 'We need to _____ our strategy. (Make it more formal using nominalization)', '["check","review","look at","conduct a review of"]', 'conduct a review of', 'conduct a review of 是 review 的名詞化形式，更正式。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''analyse''?', '["to analyse","analysing","analysis","analysed"]', 'analysis', 'analysis 是 analyse 的名詞化。'),
(79, 'multiple_choice', 'Which sentence uses nominalization?', '["We finished setting up the system.","We implemented the new system on schedule.","The new system was set up on time.","The implementation of the new system was completed on schedule."]', 'The implementation of the new system was completed on schedule.', 'The implementation 名詞化 implement。'),
(79, 'transform', 'We agreed to proceed with the merger. (Nominalize)', NULL, 'Agreement was reached to proceed with the merger.', 'agreement 是 agree 的名詞化。'),
(79, 'fill_blank', 'The _____ (discuss) of the proposal took two hours.', NULL, 'discussion', 'discussion 是 discuss 的名詞化。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''fail''?', '["to fail","failure","failed","failing"]', 'failure', 'failure 是 fail 的名詞化。'),
(79, 'multiple_choice', 'Which sentence is more formal through nominalization?', '["We''ve grown a lot.","Significant growth has been achieved.","Growth happened significantly.","We grew significantly."]', 'Significant growth has been achieved.', 'significant growth has been achieved 名詞化 grew。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''solve''?', '["solved","solving","to solve","solution"]', 'solution', 'solution 是 solve 的名詞化。'),
(79, 'fill_blank', 'The _____ (acquire) of the company was completed last year.', NULL, 'acquisition', 'acquisition 是 acquire 的名詞化。'),
(79, 'multiple_choice', 'Which sentence uses nominalization correctly?', '["We were negotiating for three weeks.","Negotiating took three weeks.","The negotiation of terms took three weeks.","We negotiated terms for three weeks."]', 'The negotiation of terms took three weeks.', 'The negotiation of terms 名詞化 negotiated。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''decide''?', '["to decide","decision","deciding","decided"]', 'decision', 'decision 是 decide 的名詞化。'),
(79, 'transform', 'We evaluated the risks carefully. (Nominalize)', NULL, 'A thorough evaluation of the risks was conducted.', 'evaluation 是 evaluate 的名詞化。'),
(79, 'fill_blank', 'We conducted a _____ (investigate) into the issue.', NULL, 'investigation', 'investigation 是 investigate 的名詞化。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''recommend''?', '["recommended","recommending","to recommend","recommendation"]', 'recommendation', 'recommendation 是 recommend 的名詞化。'),
(79, 'multiple_choice', 'Which sentence demonstrates nominalization?', '["We expanded successfully into Asia.","We went into Asia successfully.","The expansion of our operations into Asia has been successful.","Expanding into Asia worked out."]', 'The expansion of our operations into Asia has been successful.', 'The expansion of our operations 名詞化 expanded。'),
(79, 'multiple_choice', 'Which is the nominalized form of ''approve''?', '["approving","approval","to approve","approved"]', 'approval', 'approval 是 approve 的名詞化。'),
(80, 'multiple_choice', 'Which is the more formal, impersonal version?', '["I''ve decided to postpone it.","We decided to postpone the launch.","It has been decided to postpone the launch.","Let''s postpone the launch."]', 'It has been decided to postpone the launch.', 'It has been decided 非人稱被動式，最正式。'),
(80, 'multiple_choice', 'Which sentence uses impersonal structure?', '["Note that the results are preliminary.","It is important to note that the results are preliminary.","You should note the preliminary results.","I want you to note the preliminary results."]', 'It is important to note that the results are preliminary.', 'It is important to note that 非人稱結構。'),
(80, 'multiple_choice', 'Which is the most formal way to start a recommendation?', '["You should implement these measures.","Implement these measures.","It is recommended that the following measures be implemented.","We recommend implementing these measures."]', 'It is recommended that the following measures be implemented.', 'It is recommended that + 虛擬語氣，非人稱被動，最正式。'),
(80, 'fill_blank', 'It _____ (note) that the data has certain limitations.', NULL, 'should be noted', 'it should be noted that 非人稱被動式。'),
(80, 'multiple_choice', 'Which uses passive voice appropriately?', '["We rejected the proposal.","They rejected the proposal because of budget.","The proposal was rejected due to budget constraints.","Budget constraints made us reject it."]', 'The proposal was rejected due to budget constraints.', 'The proposal was rejected 被動語態，不強調行為者。'),
(80, 'multiple_choice', 'Which is the most formal impersonal structure?', '["It would appear that further investigation is required.","Apparently, we need to investigate more.","It seems we need to look into this more.","We think further investigation is needed."]', 'It would appear that further investigation is required.', 'It would appear that 最高度正式非人稱結構。'),
(80, 'multiple_choice', 'Which sentence demonstrates formal passive writing?', '["We got the board to review the findings.","The findings have been reviewed and approved by the board.","The board reviewed and approved the findings.","The board has reviewed and approved everything."]', 'The findings have been reviewed and approved by the board.', 'The findings have been reviewed...被動語態，無人稱強調。'),
(80, 'transform', 'We will announce the results at the AGM. (Make impersonal/passive)', NULL, 'It has been decided that the results will be announced at the AGM.', '被動+非人稱結構。'),
(80, 'fill_blank', 'It _____ (establish) that the new policy will take effect in Q2.', NULL, 'has been established', 'it has been established that 非人稱被動式。'),
(80, 'multiple_choice', 'Which is the most appropriate sentence for a formal report conclusion?', '["Obviously the strategy worked.","The strategy was effective, we think.","It can therefore be concluded that the strategy has been effective.","So we can say the strategy worked."]', 'It can therefore be concluded that the strategy has been effective.', 'It can be concluded that 正式非人稱被動推論。'),
(80, 'multiple_choice', 'Which impersonal structure is correct?', '["It is believed that the market will recover by year end.","People believe the market will recover.","We believe the market will recover.","I believe the market will recover."]', 'It is believed that the market will recover by year end.', 'It is believed that 非人稱被動，報告中常用。'),
(80, 'multiple_choice', 'Which is the most formal?', '["We are taking steps to address the issue.","We''re working on fixing the issue.","Steps are being taken to address the issue.","We''re on it."]', 'Steps are being taken to address the issue.', 'Steps are being taken 被動進行式，非人稱。'),
(80, 'transform', 'We need to ensure all employees understand the policy. (Make formal/impersonal)', NULL, 'It is essential that all employees are made aware of the new policy.', 'It is essential that + 被動，非人稱。'),
(80, 'fill_blank', 'It _____ (report) that the merger negotiations are ongoing.', NULL, 'has been reported', 'it has been reported that 非人稱被動式。'),
(80, 'multiple_choice', 'Which is the most appropriate for a formal notice?', '["All staff must attend the briefing.","You all have to attend.","All staff are required to attend the mandatory briefing.","Everyone needs to come to the briefing."]', 'All staff are required to attend the mandatory briefing.', 'All staff are required to 被動非人稱，最正式。'),
(80, 'multiple_choice', 'Which is a correct impersonal structure?', '["Note that sales improved.","We should note that sales improved.","Don''t forget sales improved.","It is worth noting that sales have improved significantly."]', 'It is worth noting that sales have improved significantly.', 'It is worth noting that 非人稱結構。'),
(80, 'multiple_choice', 'Which sentence best exemplifies formal passive in reports?', '["We spent six months collecting data.","Data collection took six months.","The data was collected over a period of six months.","We collected data for six months."]', 'The data was collected over a period of six months.', 'The data was collected 標準學術/報告被動式。'),
(80, 'transform', 'We have identified several key issues. (Make formal/impersonal)', NULL, 'Several key issues have been identified in the course of this review.', 'Several key issues have been identified 非人稱被動式。'),
(80, 'fill_blank', 'It is _____ (expect) that the new system will reduce errors by 30%.', NULL, 'expected', 'it is expected that 非人稱被動預測。'),
(80, 'multiple_choice', 'Which is the most formal way to express an obligation?', '["It is mandatory that all contractors comply with safety regulations.","Make sure all contractors follow safety rules.","All contractors must comply with safety regulations.","Every contractor needs to follow safety rules."]', 'It is mandatory that all contractors comply with safety regulations.', 'It is mandatory that + 虛擬語氣，非人稱被動，最正式。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(81, 'multiple_choice', 'Which sentence correctly uses a colon?', '["The proposal covers three areas, budget: timeline and resources.","The proposal covers three areas: budget, timeline, and resources.","The proposal covers three areas; budget, timeline, and resources.","The proposal covers: three areas budget timeline resources."]', 'The proposal covers three areas: budget, timeline, and resources.', '冒號引出列表正確用法。'),
(81, 'multiple_choice', 'Which sentence correctly uses a semicolon?', '["The project is behind schedule: we need more resources.","The project is behind schedule; we need to allocate more resources.","The project is behind schedule, we need more resources.","The project is behind schedule but we need more resources."]', 'The project is behind schedule; we need to allocate more resources.', '分號連接兩個獨立但相關的子句。'),
(81, 'fill_blank', 'The meeting covered the following topics_____ budget allocation, staffing, and the Q4 strategy.', NULL, '：（colon）', '冒號引出列表。'),
(81, 'multiple_choice', 'Which correctly uses a colon?', '["Please bring the following, documents: your passport CV and references.","Please bring the following documents; your passport, CV, and references.","Please bring: the following documents your passport CV and references.","Please bring the following documents: your passport, CV, and references."]', 'Please bring the following documents: your passport, CV, and references.', '冒號引出列表。'),
(81, 'multiple_choice', 'Which correctly uses a semicolon?', '["Sales increased in Asia, however they declined in Europe.","Sales increased in Asia: however, they declined in Europe.","Sales increased in Asia; however, they declined in Europe.","Sales increased in Asia - however they declined in Europe."]', 'Sales increased in Asia; however, they declined in Europe.', '分號 + 連接副詞 however 正確用法。'),
(81, 'multiple_choice', 'Where should a colon go in this sentence? ''We offer three payment options _____ monthly, quarterly, or annually.''', '["，",":","；","—"]', ':', '冒號引出選項列表。'),
(81, 'fill_blank', 'She has one goal_____ to become the regional director within five years.', NULL, '：（colon）', '冒號強調唯一目標。'),
(81, 'multiple_choice', 'Which is correct?', '["The budget was approved consequently the project began.","The budget was approved: consequently the project began.","The budget was approved; consequently, the project began.","The budget was approved, consequently the project began."]', 'The budget was approved; consequently, the project began.', '分號 + 連接副詞 consequently 正確。'),
(81, 'multiple_choice', 'Which sentence uses a semicolon correctly?', '["The report is comprehensive, it covers all KPIs.","The report is comprehensive; it covers all key performance indicators.","The report is comprehensive: it covers all KPIs.","The report is comprehensive. It covers all KPIs."]', 'The report is comprehensive; it covers all key performance indicators.', '分號連接兩個緊密相關的獨立子句。'),
(81, 'transform', 'The company has three priorities. These are: growth, innovation, and sustainability. (Combine using colon)', NULL, 'The company has three priorities: growth, innovation, and sustainability.', '冒號合併為一個句子列舉。'),
(81, 'multiple_choice', 'Which correctly uses a colon?', '["The conclusion: is clear we must cut costs immediately.","The conclusion is clear, we must cut costs immediately.","The conclusion is clear; we must cut costs immediately.","The conclusion is clear: we must cut costs immediately."]', 'The conclusion is clear: we must cut costs immediately.', '冒號強調後面的重要陳述。'),
(81, 'fill_blank', 'We have identified two issues_____ the timeline is too tight, and the budget is insufficient.', NULL, '：（colon）', '冒號引出後面的說明。'),
(81, 'multiple_choice', 'Which sentence uses punctuation correctly?', '["She is qualified; she has an MBA and ten years of experience.","She is qualified - she has an MBA and ten years of experience.","She is qualified, she has an MBA and ten years of experience.","She is qualified: she has an MBA and ten years of experience."]', 'She is qualified; she has an MBA and ten years of experience.', '分號連接兩個獨立子句正確（冒號也可，但分號表更對等關係）。'),
(81, 'multiple_choice', 'Choose the correctly punctuated sentence:', '["There are four steps, research plan execute and review.","There are four steps; research, plan, execute, and review.","There are four, steps: research plan execute and review.","There are four steps: research, plan, execute, and review."]', 'There are four steps: research, plan, execute, and review.', '冒號引出四個步驟的列表。'),
(81, 'transform', 'Sales are falling. Furthermore, costs are rising. (Join with semicolon)', NULL, 'Sales are falling; furthermore, costs are rising.', '分號 + 連接副詞 furthermore。'),
(81, 'fill_blank', 'The agenda includes the following items_____ Q3 review, budget proposal, and staffing update.', NULL, '：（colon）', '冒號引出會議議程列表。'),
(81, 'multiple_choice', 'Which is correct?', '["The deadline is Friday. Please ensure all reports are submitted.","The deadline is Friday: please ensure all reports are submitted.","The deadline is Friday; please ensure all reports are submitted.","The deadline is Friday, please ensure all reports are submitted."]', 'The deadline is Friday; please ensure all reports are submitted.', '分號連接兩個緊密相關子句，命令強調。'),
(81, 'multiple_choice', 'Choose the correct sentence:', '["The audit revealed one major concern, insufficient documentation.","The audit revealed: one major concern insufficient documentation.","The audit revealed one major concern; insufficient documentation.","The audit revealed one major concern: insufficient documentation."]', 'The audit revealed one major concern: insufficient documentation.', '冒號強調唯一的重大問題。'),
(81, 'fill_blank', 'We have three options_____ negotiate, compromise, or walk away.', NULL, '：（colon）', '冒號引出選項。'),
(81, 'multiple_choice', 'Which correctly uses a semicolon?', '["He is an expert in finance, she specializes in operations.","He is an expert in finance: she specializes in operations.","He is an expert in finance; she specializes in operations.","He is an expert in finance. she specializes in operations."]', 'He is an expert in finance; she specializes in operations.', '分號連接對比的兩個獨立子句。'),
(82, 'multiple_choice', 'Which is correct?', '["The companies'' annual report was released today.","The companies annual report was released today.","The company''s annual report was released today.","The companys'' annual report was released today."]', 'The company''s annual report was released today.', 'company''s 單數所有格。'),
(82, 'multiple_choice', 'Which is correct?', '["It is''s important to review the contract carefully.","Its important to review the contract carefully.","It''s important to review the contract carefully.","Its'' important to review the contract carefully."]', 'It''s important to review the contract carefully.', 'It''s = it is，縮寫用撇號。'),
(82, 'multiple_choice', 'Which is correct?', '["The managers report''s are due on Friday.","The manager''s reports are due on Friday.","The managers'' reports are due on Friday.","The managers reports are due on Friday."]', 'The managers'' reports are due on Friday.', 'managers'' 複數所有格（多個管理者的報告）。'),
(82, 'fill_blank', 'The product has its _____ (own) unique features. (its or it''s?)', NULL, 'its', '其 own = its，所有格，不加撇號。'),
(82, 'multiple_choice', 'Which is correct?', '["The teams'' performance exceeded all expectations.","The teams performance exceeded all expectations.","The team''s performance exceeded all expectations.","The team''s performance exceeded all expectations."]', 'The team''s performance exceeded all expectations.', 'team''s 單數所有格正確。'),
(82, 'multiple_choice', 'Which sentence uses the apostrophe correctly?', '["Were pleased to announce the launch of our new product.","We are''s pleased to announce our new product.","We''re pleased to announce the launch of our new product.","Were'' pleased to announce the launch."]', 'We''re pleased to announce the launch of our new product.', 'We''re = we are，縮寫正確。'),
(82, 'multiple_choice', 'Which is correct?', '["The CEOs'' decision was final.","The CEOs decision was final.","The CEO''s decision was final.","The CEO''s decision was final."]', 'The CEO''s decision was final.', 'CEO''s 單數所有格正確。'),
(82, 'fill_blank', 'The company revised _____ pricing strategy. (its or it''s?)', NULL, 'its', 'its 所有格，不加撇號。'),
(82, 'multiple_choice', 'Which is correct for multiple employees?', '["The employees contract''s were all renewed.","The employees contracts were all renewed.","The employees'' contracts were all renewed.","The employee''s contracts were all renewed."]', 'The employees'' contracts were all renewed.', 'employees'' 複數所有格。'),
(82, 'multiple_choice', 'Which is correct?', '["They''s already submitted their proposals.","Their''ve already submitted their proposals.","They''ve already submitted their proposals.","They have''s already submitted their proposals."]', 'They''ve already submitted their proposals.', 'They''ve = they have，縮寫正確。'),
(82, 'multiple_choice', 'Which sentence is correct?', '["The shareholder''s meeting is scheduled for next Tuesday.","The shareholders'' meeting is scheduled for next Tuesday.","The shareholder''s'' meeting is scheduled for next Tuesday.","The shareholders meeting is scheduled for next Tuesday."]', 'The shareholders'' meeting is scheduled for next Tuesday.', 'shareholders'' 複數所有格（多個股東的會議）。'),
(82, 'fill_blank', '_____ (It is) been three months since the merger was announced.', NULL, 'It''s', 'It''s = it has，縮寫用撇號。'),
(82, 'multiple_choice', 'Which is correct?', '["The two companies''s merger was announced yesterday.","The two company''s merger was announced yesterday.","The two companies'' merger was announced yesterday.","The two companies merger was announced yesterday."]', 'The two companies'' merger was announced yesterday.', 'companies'' 複數所有格。'),
(82, 'multiple_choice', 'Which is correct?', '["He responsible for client relations.","His responsible for client relations.","He''s responsible for client relations.","He is''s responsible for client relations."]', 'He''s responsible for client relations.', 'He''s = he is，縮寫正確。'),
(82, 'multiple_choice', 'Which apostrophe usage is correct?', '["The department''s budget was increased.","The departments budget was increased.","The department''s budget was increased.","The departments'' budget was increased."]', 'The department''s budget was increased.', 'department''s 單數所有格。'),
(82, 'transform', 'The office of the director is on the 10th floor. (Use possessive apostrophe)', NULL, 'The director''s office is on the 10th floor.', 'director''s 單數所有格代替 of 結構。'),
(82, 'fill_blank', 'The company _____ known for its innovative products. (it''s or its)', NULL, 'It''s', 'It''s = it is，作謂語動詞。'),
(82, 'multiple_choice', 'Which is correct?', '["Don''t share the clients'' personal data.","Do not share the clients personal data.","Don''t share the client''s personal data.","Dont share the client''s personal data."]', 'Don''t share the client''s personal data.', 'Don''t 縮寫；client''s 單數所有格正確。'),
(82, 'multiple_choice', 'Which is correct for a company owned by multiple owners?', '["The directors decision was unanimous.","The director''s decision was unanimous.","The directors'' decision was unanimous.","The directors''s decision was unanimous."]', 'The directors'' decision was unanimous.', 'directors'' 複數所有格正確。'),
(82, 'multiple_choice', 'Which sentence has NO apostrophe error?', '["We''ve received confirmation from all our supplier''s.","Weve received confirmation from all our suppliers.","We have''s received confirmation from all our suppliers.","We''ve received confirmation from all our suppliers."]', 'We''ve received confirmation from all our suppliers.', 'We''ve 縮寫正確；suppliers 複數名詞，不需要撇號。'),
(83, 'multiple_choice', 'The new software will greatly _____ our workflow efficiency.', '["extend","enhance","enlarge","expand"]', 'enhance', 'enhance 提升（品質/效率），最適合 workflow efficiency 的搭配。'),
(83, 'multiple_choice', 'All employees are required to _____ with the new data protection regulations.', '["follow","obey","agree","comply"]', 'comply', 'comply with regulations 固定搭配，表遵守法規。'),
(83, 'multiple_choice', 'The company plans to _____ its operations to Southeast Asia next year.', '["increase","develop","expand","enhance"]', 'expand', 'expand operations 擴大業務規模，固定搭配。'),
(83, 'fill_blank', 'The director will _____ the team through the restructuring process.', NULL, 'guide / lead', 'guide/lead someone through a process 指引通過。'),
(83, 'multiple_choice', 'The quarterly results _____ a significant improvement in profit margins.', '["reveal out","demonstrate","indicate to","show up"]', 'demonstrate', 'demonstrate 正式表達，展示結果；demonstrate a improvement 正確搭配。'),
(83, 'multiple_choice', 'We need to _____ additional funding to complete the project.', '["get","earn","find","secure"]', 'secure', 'secure funding 取得資金，商業英語固定搭配。'),
(83, 'multiple_choice', 'The board has _____ the new marketing strategy.', '["accepted","confirmed","endorsed","agreed"]', 'endorsed', 'endorse 正式核可/背書，比 agree 更強烈。'),
(83, 'fill_blank', 'The company _____ a significant market share within its first year.', NULL, 'captured / gained', 'capture/gain market share 取得市場份額。'),
(83, 'multiple_choice', 'Please _____ receipt of this document by signing the enclosed form.', '["verify","acknowledge","confirm","accept"]', 'acknowledge', 'acknowledge receipt of 確認收到，正式書面搭配。'),
(83, 'multiple_choice', 'The new policy will _____ in effect from the first of next month.', '["make","come","go","take"]', 'come', 'come into effect 生效，固定搭配。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(83, 'multiple_choice', 'She was _____ as the most innovative employee of the year.', '["appreciated","rewarded","recognized","known"]', 'recognized', 'recognized as 被認可為，正式表彰搭配。'),
(83, 'fill_blank', 'The merger was _____ by the relevant regulatory authorities.', NULL, 'approved / sanctioned', 'approve/sanction the merger 批准合併。'),
(83, 'multiple_choice', 'The team needs to _____ a solution before the client meeting tomorrow.', '["devise","develop up","find out","think"]', 'devise', 'devise a solution 設計/制定解決方案，正式搭配。'),
(83, 'multiple_choice', 'Our products are _____ to customers in over 50 countries.', '["available","obtainable","possible","accessible"]', 'available', 'available to customers 對客戶可取得，常用搭配。'),
(83, 'multiple_choice', 'The company has _____ significant progress in reducing its carbon footprint.', '["achieved","done","accomplished","made"]', 'made', 'make progress 固定搭配。'),
(83, 'fill_blank', 'She _____ an important role in the company''s expansion into Asia.', NULL, 'played', 'play a role 扮演角色，固定搭配。'),
(83, 'multiple_choice', 'The new branch will be _____ in the financial district.', '["situated","placed","positioned","located"]', 'located', 'located in 位於，商業英語常見。'),
(83, 'multiple_choice', 'The proposal was _____ on several grounds, including cost and timing.', '["refused","denied","rejected","declined"]', 'rejected', 'rejected on grounds 以...為由被拒絕。'),
(83, 'fill_blank', 'The CEO _____ a speech about the company''s vision at the annual meeting.', NULL, 'delivered / gave', 'deliver/give a speech 發表演講。'),
(83, 'multiple_choice', 'All team members are expected to _____ their best effort in this project.', '["offer","provide","give","contribute"]', 'contribute', 'contribute one''s best effort 貢獻最大努力，正式商業表達。'),
(84, 'multiple_choice', 'The committee _____ a final decision until all the data has been reviewed.', '["has not made","does not make","will not make","did not make"]', 'will not make', 'will not make...until 表未來的條件：直到資料審查完才做決定。'),
(84, 'multiple_choice', 'Please ensure the report is submitted _____ Friday at the latest.', '["until","before","on","by"]', 'by', 'by Friday 截止日期用 by（at the latest 確認是截止）。'),
(84, 'multiple_choice', 'All staff who _____ the meeting will receive the minutes by email.', '["will not attend","are not attending","have not attended","do not attend"]', 'do not attend', 'do not attend 泛指所有不出席者（零條件句式）。'),
(84, 'fill_blank', 'The software _____ (install) on all company computers by the end of the week.', NULL, 'will have been installed', '未來完成被動式。'),
(84, 'multiple_choice', 'Neither the CEO nor the directors _____ available for comment.', '["has been","is","was","were"]', 'were', 'neither...nor 就近原則，directors 複數，were。'),
(84, 'multiple_choice', 'The proposal, _____ was submitted last week, has been approved.', '["what","who","which","that"]', 'which', '非限定性關係子句（逗號隔開），用 which。'),
(84, 'multiple_choice', 'She has been working for the company _____ she graduated.', '["as","from","for","since"]', 'since', 'since + 時間點，現在完成進行式。'),
(84, 'fill_blank', 'The meeting _____ (reschedule) to 3 p.m. due to a scheduling conflict.', NULL, 'has been rescheduled', '現在完成被動式，說明已完成的重新安排。'),
(84, 'multiple_choice', 'He was promoted _____ his outstanding performance.', '["because of","even though","although","despite"]', 'because of', 'because of + 名詞短語表原因。'),
(84, 'multiple_choice', 'The report must _____ before the board meeting begins.', '["be to review","review","be reviewed","be reviewing"]', 'be reviewed', 'must be reviewed 情態動詞被動式。'),
(84, 'multiple_choice', 'Applicants _____ relevant experience are encouraged to apply.', '["having","with","of","who have"]', 'with', 'with relevant experience 介系詞短語修飾 applicants（也可用 having 或 who have）。'),
(84, 'fill_blank', 'By the time the new branch opens, we _____ (expand) into five new markets.', NULL, 'will have expanded', 'by the time 未來完成式。'),
(84, 'multiple_choice', 'The results were _____ better than anticipated.', '["considerably","considering","considerable","considerate"]', 'considerably', 'considerably 副詞修飾 better（比較級）。'),
(84, 'multiple_choice', '_____ the price increase, demand remains strong.', '["Because of","Even though","Despite","Although"]', 'Despite', 'Despite + 名詞短語（price increase），讓步。'),
(84, 'multiple_choice', 'She is the _____ experienced candidate for this position.', '["most","very","much","more"]', 'most', 'the most + 形容詞最高級。'),
(84, 'transform', 'Active: The HR team reviewed all applications. (Passive)', NULL, 'All applications were reviewed by the HR team.', 'were reviewed by 被動語態。'),
(84, 'fill_blank', 'The client _____ (not / respond) to our emails for two weeks.', NULL, 'has not responded', '現在完成式否定，for two weeks 持續。'),
(84, 'multiple_choice', 'We recommend that all participants _____ the pre-reading materials.', '["are reviewing","reviewed","review","reviews"]', 'review', 'recommend that + 原形動詞（虛擬語氣）。'),
(84, 'multiple_choice', 'The survey results indicate _____ customer satisfaction has improved.', '["that","how","which","what"]', 'that', 'indicate + that 名詞子句受語。'),
(84, 'multiple_choice', 'All shipments _____ before they are dispatched.', '["must be inspected","are must inspected","must have inspected","must inspect"]', 'must be inspected', 'must be inspected 情態動詞被動。'),
(85, 'multiple_choice', 'Thank you for your email of March 15th. We are _____ to inform you that...', '["happy","delighted","glad","pleased"]', 'pleased', 'pleased 最常見的正式商業郵件開頭表達（delighted 也正式但 pleased 更標準）。'),
(85, 'multiple_choice', 'We _____ your order and it will be dispatched within two working days.', '["will receive","have received","received","are receiving"]', 'have received', 'have received 現在完成式，說明已收到訂單。'),
(85, 'multiple_choice', 'Should you have any questions, please do not _____ to contact us.', '["hesitate","try","want","wait"]', 'hesitate', 'do not hesitate to contact us 正式商業套語。'),
(85, 'fill_blank', 'We are writing to _____ you that your application has been successful.', NULL, 'inform', 'inform someone that 正式商業通知。'),
(85, 'multiple_choice', 'Further to our conversation _____ Friday, I am sending you the revised proposal.', '["in","by","on","at"]', 'on', 'on Friday 特定日期用 on。'),
(85, 'multiple_choice', 'Please find _____ the document you requested.', '["attached","inside","below","enclosed"]', 'attached', 'Please find attached 電子郵件附件的標準用語。'),
(85, 'multiple_choice', 'We would like to take this _____ to thank you for your continued support.', '["chance","opportunity","time","occasion"]', 'opportunity', 'take this opportunity to 正式感謝套語。'),
(85, 'transform', 'Write the standard phrase to open an email politely enquiring about an order status.', NULL, 'I am writing to enquire about the current status of our order placed on March 10th.', 'enquire about 正式詢問。'),
(85, 'fill_blank', 'I am _____ to confirm that the meeting has been rescheduled to 10 a.m.', NULL, 'writing', 'I am writing to confirm 正式郵件開頭。'),
(85, 'multiple_choice', 'We _____ any inconvenience this may have caused.', '["apologise for","apologise of","are sorry to","apologise about"]', 'apologise for', 'apologise for 正式道歉，固定搭配。'),
(85, 'multiple_choice', 'Please _____ receipt of this email by clicking the confirmation link below.', '["acknowledge","confirm","accept","verify"]', 'acknowledge', 'acknowledge receipt 確認收到，正式書面用語。'),
(85, 'multiple_choice', 'We are _____ to announce the appointment of Ms. Chen as our new CFO.', '["happy","pleased","glad","delighted"]', 'delighted', 'delighted to announce 正式公告用語，最正式。'),
(85, 'fill_blank', 'If you _____ any further queries, please do not hesitate to get in touch.', NULL, 'have / should have', 'If you have / should you have 正式條件句。'),
(85, 'multiple_choice', 'This is to _____ you that your account has been successfully created.', '["notify","inform","say","tell"]', 'notify', 'notify someone that 正式通知。'),
(85, 'multiple_choice', 'We _____ to your email within one business day.', '["responded","will respond","respond","are responding"]', 'will respond', 'will respond 承諾未來動作。'),
(85, 'multiple_choice', 'As per our _____ agreement, payment is due within 30 days of the invoice date.', '["mutual","common","collective","shared"]', 'mutual', 'mutual agreement 雙方協議，固定搭配。'),
(85, 'fill_blank', 'We wish to _____ your attention to the changes outlined in this document.', NULL, 'draw / bring', 'draw/bring someone''s attention to 引起注意。'),
(85, 'multiple_choice', 'We look _____ to receiving your response.', '["ahead","onward","towards","forward"]', 'forward', 'look forward to + V-ing 固定期待用語。'),
(85, 'multiple_choice', 'Please _____ that any expenses must be pre-approved by your line manager.', '["understand","remember","note","know"]', 'note', 'Please note that 正式提醒用語。'),
(85, 'multiple_choice', 'In _____ to your query, please find the requested information below.', '["response","reaction","answer","reply"]', 'response', 'in response to 正式回覆套語。');