INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(21, 'multiple_choice', '_____ you send me the revised proposal by Thursday?', '["Can","Will","Could","Should"]', 'Could', 'Could you 是更禮貌的請求方式，商業英語常用。'),
(21, 'multiple_choice', 'She _____ speak three languages fluently.', '["could","can","may","should"]', 'can', '描述現在的能力，用 can。'),
(21, 'multiple_choice', 'When I was a junior analyst, I _____ rarely attend senior meetings.', '["may","can","should","could"]', 'could', '過去的情況（when I was），用 could 表過去能力。'),
(21, 'fill_blank', '_____ I borrow your notes from the meeting?', NULL, 'Could', 'Could I 是禮貌請求許可的表達。'),
(21, 'multiple_choice', 'This feature _____ be implemented in the next software update.', '["could","can","should","will"]', 'could', 'could 表假設可能性，語氣較不確定。'),
(21, 'multiple_choice', 'The new system _____ process 1,000 transactions per second.', '["might","could","may","can"]', 'can', '描述系統現在的能力，用 can。'),
(21, 'multiple_choice', '_____ you explain this clause in the contract in more detail?', '["Could","Would","Can","Should"]', 'Could', 'Could you 更禮貌正式，商業英語偏好。'),
(21, 'transform', 'It is possible that we find a cheaper supplier. (Use: could find)', NULL, 'We could find a cheaper supplier if we expand our search.', 'could 表假設可能性。'),
(21, 'multiple_choice', 'The design team _____ create five mockups within two days.', '["can","should","could","may"]', 'can', 'can 表現在能力。'),
(21, 'fill_blank', '_____ she attend the conference in your place?', NULL, 'Could', 'Could she 詢問可能性或請求。'),
(21, 'multiple_choice', 'I _____ not reach the client all morning — the number was busy.', '["could","would","can","should"]', 'could', 'could not 過去無法，描述過去的失敗嘗試。'),
(21, 'multiple_choice', 'The project manager _____ assign tasks more efficiently.', '["can","should","could","must"]', 'could', 'could 表假設改進的可能性，比 should 更婉轉。'),
(21, 'multiple_choice', '_____ you please confirm your attendance by Friday?', '["Must","Could","Will","Can"]', 'Could', 'Could you please 是最禮貌的正式請求。'),
(21, 'fill_blank', 'She _____ not understand the technical jargon in the report.', NULL, 'could', 'could not 過去無法理解。'),
(21, 'multiple_choice', 'If we improve logistics, we _____ reduce delivery time by 20%.', '["could","can","will","should"]', 'could', 'could 表達假設條件下的可能性。'),
(21, 'multiple_choice', 'This opportunity _____ be very profitable for us.', '["must","should","could","can"]', 'could', 'could 表評估中的可能性，語氣謹慎。'),
(21, 'multiple_choice', 'She _____ type 80 words per minute when she was a secretary.', '["might","may","can","could"]', 'could', '過去能力用 could。'),
(21, 'transform', 'I want permission to work from home on Fridays. (Use: Could I)', NULL, 'Could I work from home on Fridays?', 'Could I 是禮貌請求許可的標準句型。'),
(21, 'multiple_choice', 'The team _____ complete the project ahead of schedule if they work overtime.', '["can","should","could","must"]', 'could', 'could 表條件下的可能性。'),
(21, 'multiple_choice', 'We _____ always outsource this task if our team is overloaded.', '["may","can","could","should"]', 'can', 'can 表現在存在的選項和能力。'),
(22, 'multiple_choice', 'All employees _____ complete the annual compliance training.', '["might","must","should","have to"]', 'must', 'must 表公司規定的強烈義務。'),
(22, 'multiple_choice', 'She _____ travel to five countries next month — it''s in her contract.', '["must","ought to","has to","should"]', 'has to', 'has to 表合約中的外在義務。'),
(22, 'multiple_choice', 'You _____ share confidential client data outside the company.', '["should not","must not","cannot","do not have to"]', 'must not', 'must not 表嚴格禁止，比 should not 更強烈。'),
(22, 'multiple_choice', 'Employees _____ work on Sundays unless it''s an emergency.', '["cannot","do not have to","must not","should not"]', 'do not have to', 'do not have to 表不必要，不是禁止。'),
(22, 'fill_blank', 'I _____ (finish) the report tonight — the board needs it tomorrow morning.', NULL, 'must finish', 'must 表強烈主觀義務。'),
(22, 'multiple_choice', 'She _____ be the new director — she was introduced as such.', '["must","has to","should","ought to"]', 'must', 'must 表邏輯推斷（她一定是...）。'),
(22, 'multiple_choice', 'We _____ meet the ISO certification requirements by Q4.', '["must","have to","ought to","should"]', 'have to', 'have to 表外在認證要求。'),
(22, 'multiple_choice', 'You _____ use a VPN when accessing the company server remotely.', '["should","have to","ought to","must"]', 'must', 'must 表 IT 安全規定的強制要求。'),
(22, 'transform', 'It is mandatory to wear a hard hat in the construction zone. (Use: must)', NULL, 'You must wear a hard hat in the construction zone at all times.', 'must 表嚴格規定。'),
(22, 'multiple_choice', 'I _____ make 20 client calls today — that''s my target.', '["need","must","have to","should"]', 'have to', 'have to 表外在業績目標的要求。'),
(22, 'multiple_choice', 'He _____ be exhausted — he worked 18 hours straight.', '["must","ought to","should","has to"]', 'must', 'must 表對現在情況的推斷。'),
(22, 'fill_blank', 'We _____ (disclose) all financial risks in the prospectus — it''s the law.', NULL, 'must disclose', '法律規定用 must 表強制義務。'),
(22, 'multiple_choice', 'You _____ leave the office during core hours without manager approval.', '["must not","should not","cannot","do not have to"]', 'must not', 'must not 表禁止行為。'),
(22, 'multiple_choice', 'They _____ submit monthly reports to the head office.', '["should","must","have to","ought to"]', 'have to', 'have to 表定期外在規定。'),
(22, 'multiple_choice', 'The certificate _____ be renewed every two years.', '["must","has to","should","ought to"]', 'has to', 'has to 表外在規定要求。'),
(22, 'fill_blank', 'You _____ (not/attend) the optional seminar if you are busy.', NULL, 'do not have to attend', 'do not have to 表不強制，非禁止。'),
(22, 'multiple_choice', 'This document _____ be the one signed by both parties.', '["has to","ought to","should","must"]', 'must', 'must 表根據邏輯的推斷。'),
(22, 'multiple_choice', 'She _____ clock in before 9 a.m. — it''s company policy.', '["ought to","must","should","has to"]', 'has to', 'has to 表公司外在政策。'),
(22, 'multiple_choice', 'All contracts _____ be reviewed by legal before signing.', '["ought to","should","have to","must"]', 'must', 'must 強調公司強制規定。'),
(22, 'multiple_choice', 'You _____ book a meeting room if it''s just a quick chat.', '["must not","do not have to","cannot","should not"]', 'do not have to', 'do not have to 表不必要，不是禁止。'),
(23, 'multiple_choice', 'You _____ proofread your emails before sending them to clients.', '["will","can","should","must"]', 'should', 'should 表建議最佳做法。'),
(23, 'multiple_choice', 'We _____ consider the risks before making a final decision.', '["can","ought","should","must"]', 'should', 'should 表建議考慮因素。'),
(23, 'multiple_choice', 'She _____ to request a meeting before the deadline.', '["must","should","can","ought"]', 'ought', 'ought to 和 should 意思相同，ought 後接 to。'),
(23, 'fill_blank', 'The report _____ (include) an executive summary for clarity.', NULL, 'should include', 'should 建議最佳做法。'),
(23, 'multiple_choice', 'Managers _____ give regular feedback to their team members.', '["should","can","might","must"]', 'should', 'should 表期望行為和建議。'),
(23, 'multiple_choice', 'The team _____ have more frequent progress updates.', '["would","should","must","can"]', 'should', 'should 建議改進做法。'),
(23, 'multiple_choice', 'According to the guidelines, all invoices _____ be processed within 30 days.', '["would","should","can","must"]', 'should', 'should 表期望和建議的標準做法。'),
(23, 'transform', 'It is advisable to back up your data regularly. (Use: should)', NULL, 'You should back up your data on a regular basis.', 'should 表建議。'),
(23, 'multiple_choice', 'We _____ have informed the client earlier about the delay.', '["must","would","can","should"]', 'should', 'should have 表對過去的後悔或批評（但本題是現在建議框架）。'),
(23, 'fill_blank', 'She _____ (consult) the legal team before signing any external agreements.', NULL, 'should consult', 'should 建議徵詢法律意見。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(23, 'multiple_choice', 'The presentation _____ be no longer than 30 minutes.', '["must","will","can","should"]', 'should', 'should 表建議長度，比 must 委婉。'),
(23, 'multiple_choice', 'He _____ arrive early to the interview to make a good impression.', '["could","must","should","can"]', 'should', 'should 建議最佳行為。'),
(23, 'multiple_choice', 'Staff _____ not use company resources for personal purposes.', '["might","can","must","should"]', 'should', 'should not 表不建議，比 must not 稍委婉。'),
(23, 'fill_blank', 'We _____ (review) the budget more carefully next time.', NULL, 'should review', 'should 表建議改進。'),
(23, 'multiple_choice', 'If there is a conflict of interest, employees _____ declare it.', '["should","must","would","can"]', 'should', 'should 表期望行為（declare 利益衝突）。'),
(23, 'multiple_choice', 'The contractor _____ have submitted the documents last week.', '["should","would","can","must"]', 'should', 'should have + p.p. 表對過去的批評。'),
(23, 'multiple_choice', 'All team members _____ attend the kickoff meeting.', '["might","should","can","must"]', 'should', 'should 表期望出席，比 must 稍委婉。'),
(23, 'transform', 'It is expected that you dress professionally. (Use: should)', NULL, 'You should dress professionally at all client meetings.', 'should 表期望行為。'),
(23, 'fill_blank', 'The project timeline _____ (update) whenever there are significant changes.', NULL, 'should be updated', 'should be + p.p. 被動建議。'),
(23, 'multiple_choice', 'He _____ to acknowledge the client''s concerns more empathetically.', '["can","ought","must","should"]', 'ought', 'ought to 同 should，表應該的行為。'),
(24, 'multiple_choice', 'The project _____ be delayed due to supply chain issues.', '["should","will","may","must"]', 'may', 'may 表可能性（50%左右）。'),
(24, 'multiple_choice', 'Sales _____ decline if we don''t improve our marketing strategy.', '["must","will","might","should"]', 'might', 'might 表較低確定性的預測。'),
(24, 'multiple_choice', '_____ I ask you to review this document before the meeting?', '["May","Can","Will","Should"]', 'May', 'May I 是非常正式的請求許可方式。'),
(24, 'fill_blank', 'The merger _____ (not / proceed) as planned if regulations change.', NULL, 'may not proceed', 'may not 表可能不會發生。'),
(24, 'multiple_choice', 'She _____ have the authority to sign this contract.', '["will","should","may","must"]', 'may', 'may 表不確定的可能性。'),
(24, 'multiple_choice', 'The conference _____ be moved online — nothing is confirmed yet.', '["will","should","must","might"]', 'might', 'might 強調更高的不確定性。'),
(24, 'multiple_choice', 'You _____ use the conference room if it''s available.', '["should","may","might","will"]', 'may', 'may 表正式許可使用。'),
(24, 'transform', 'It is possible that the price will increase next quarter. (Use: may increase)', NULL, 'The price may increase next quarter due to rising material costs.', 'may increase 表謹慎預測。'),
(24, 'multiple_choice', 'The results _____ not be what we expected.', '["will","should","must","may"]', 'may', 'may not 表可能不達預期。'),
(24, 'fill_blank', 'We _____ (need) to revise our timeline if the client requests changes.', NULL, 'might need', 'might 表較不確定的可能性。'),
(24, 'multiple_choice', 'There _____ be some unexpected costs associated with this project.', '["will","may","must","should"]', 'may', 'may be 表可能性，商業預測中常用。'),
(24, 'multiple_choice', 'The CEO _____ attend the meeting remotely.', '["will","must","may","should"]', 'may', 'may 表尚未確定的可能性。'),
(24, 'multiple_choice', 'This approach _____ not be suitable for all clients.', '["might","should","will","must"]', 'might', 'might not 較謹慎的否定可能性。'),
(24, 'fill_blank', 'The new product _____ (appeal) to a younger demographic.', NULL, 'may appeal', 'may 表商業可能性預測。'),
(24, 'multiple_choice', 'He _____ already be aware of the issue — let me check.', '["might","will","must","may"]', 'might', 'might 表較低確定性的猜測。'),
(24, 'multiple_choice', 'Profits _____ increase significantly if we enter the Asian market.', '["may","should","will","must"]', 'may', 'may 表條件性可能，語氣謹慎。'),
(24, 'multiple_choice', '_____ we proceed to the next agenda item?', '["Might","Can","Will","May"]', 'May', 'May we 是正式許可/請求。'),
(24, 'transform', 'There is a possibility that the deadline will be extended. (Use: might be extended)', NULL, 'The deadline might be extended, depending on progress.', 'might 表較不確定的可能。'),
(24, 'fill_blank', 'She _____ (not / be) available for the Thursday meeting.', NULL, 'may not be', 'may not be 表可能無法出席。'),
(24, 'multiple_choice', 'The new regulation _____ affect our supply chain operations.', '["must","might","may","will"]', 'may', 'may 表政策可能帶來的影響，謹慎語氣。'),
(25, 'multiple_choice', '_____ you be able to join the call this afternoon?', '["Would","Will","Should","Could"]', 'Would', 'Would you be able to 最禮貌的商業邀請/詢問。'),
(25, 'multiple_choice', 'When I was a junior analyst, I _____ prepare reports every Friday.', '["used to","could","will","would"]', 'would', 'would 表過去的規律性習慣。'),
(25, 'multiple_choice', 'I _____ recommend the premium package for your business needs.', '["could","would","should","will"]', 'would', 'I would recommend 委婉建議。'),
(25, 'fill_blank', '_____ you mind sending me the updated version by 5 p.m.?', NULL, 'Would', 'Would you mind 是非常禮貌的請求。'),
(25, 'multiple_choice', 'She said she _____ forward the documents later that day.', '["would","should","could","will"]', 'would', '間接引語中 will → would。'),
(25, 'multiple_choice', 'In the past, the team _____ hold daily briefings every morning.', '["would","will","could","should"]', 'would', 'would 表過去規律習慣。'),
(25, 'multiple_choice', 'He _____ like to schedule a meeting to discuss the proposal.', '["should","would","will","could"]', 'would', 'would like to 是禮貌表達意願的固定搭配。'),
(25, 'transform', 'Please give me your opinion on this. (Use: I would appreciate)', NULL, 'I would appreciate your thoughts on this proposal.', 'would appreciate 禮貌請求意見。'),
(25, 'multiple_choice', '_____ it be possible to extend the deadline by one week?', '["Could","Would","Should","Will"]', 'Would', 'Would it be possible to 是非常正式的商業請求。'),
(25, 'fill_blank', 'I _____ (not / advise) accepting the offer without legal review.', NULL, 'would not advise', 'would not advise 委婉建議不要。'),
(25, 'multiple_choice', 'If given the choice, she _____ prefer a hybrid work model.', '["should","will","would","could"]', 'would', 'would prefer 表假設偏好。'),
(25, 'multiple_choice', 'We _____ be happy to arrange a demonstration of our product.', '["should","would","will","could"]', 'would', 'would be happy to 禮貌答應商業請求。'),
(25, 'multiple_choice', 'He _____ often arrive early to prepare for the day ahead.', '["would","could","should","will"]', 'would', 'would 表過去的習慣行為。'),
(25, 'fill_blank', '_____ you be available for a call next Tuesday at 2 p.m.?', NULL, 'Would', 'Would you be available 商業日程安排的禮貌問法。'),
(25, 'multiple_choice', 'I _____ suggest reviewing the contract terms once more.', '["would","should","will","could"]', 'would', 'I would suggest 委婉建議。'),
(25, 'multiple_choice', 'The board _____ appreciate a more detailed financial analysis.', '["would","will","could","should"]', 'would', 'would appreciate 表假設的讚賞或期望。'),
(25, 'multiple_choice', 'In her previous role, she _____ manage a team of 20 people.', '["could","will","should","would"]', 'would', 'would 表過去職責的規律習慣。'),
(25, 'transform', 'Please accept our apology for the inconvenience. (Use: We would like to)', NULL, 'We would like to apologize for any inconvenience caused.', 'would like to 禮貌的商業道歉。'),
(25, 'fill_blank', 'This product _____ (suit) clients who prioritize efficiency.', NULL, 'would suit', 'would suit 條件性建議搭配。'),
(25, 'multiple_choice', 'I _____ not want to miss this opportunity if I were in your position.', '["will","could","would","should"]', 'would', 'would not want 表假設情況下的意願。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(26, 'multiple_choice', 'We _____ informed the client about the delay earlier.', '["would have","should have","could have","must have"]', 'should have', 'should have + p.p. 表批評或遺憾：應該通知但沒有。'),
(26, 'multiple_choice', 'She _____ the meeting from the start — she had the expertise.', '["must have led","could have led","should have led","would have led"]', 'could have led', 'could have 表過去本可以做的可能性。'),
(26, 'multiple_choice', 'If we had acted faster, we _____ the contract.', '["might have won","should have won","would have won","could have won"]', 'would have won', '第三條件句結果：would have won。'),
(26, 'fill_blank', 'The error _____ (avoid) if the team had followed the protocol.', NULL, 'could have been avoided', 'could have been + p.p. 表過去本可避免的被動式。'),
(26, 'multiple_choice', 'He _____ the report on time — he had enough information.', '["should have submitted","must have submitted","would have submitted","could have submitted"]', 'could have submitted', 'could have 表過去本有能力做到。'),
(26, 'multiple_choice', 'I _____ accepted the original offer — the counter-offer was worse.', '["would have","should have","must have","could have"]', 'should have', 'should have + p.p. 表後悔沒接受。'),
(26, 'multiple_choice', 'They _____ the market more thoroughly before launching.', '["might have researched","could have researched","should have researched","would have researched"]', 'should have researched', 'should have 表應該做的準備工作。'),
(26, 'transform', 'It was a mistake not to hire more staff. (Use: should have hired)', NULL, 'We should have hired more staff to handle the increased demand.', 'should have hired 表過去應該做的決定。'),
(26, 'multiple_choice', 'She _____ the project independently — she had all the skills.', '["must have managed","would have managed","could have managed","should have managed"]', 'could have managed', 'could have 表過去本有能力獨立完成。'),
(26, 'fill_blank', 'He _____ (not / approve) the expense without authorization.', NULL, 'should not have approved', 'should not have + p.p. 表批評：不應該那樣做。'),
(26, 'multiple_choice', 'If she had asked for help, we _____ her.', '["should have assisted","could have assisted","would have assisted","must have assisted"]', 'would have assisted', '第三條件句：would have + p.p.'),
(26, 'multiple_choice', 'The system _____ down if the backup had been set up properly.', '["must not have crashed","should not have crashed","would not have crashed","could not have crashed"]', 'would not have crashed', '第三條件句否定：would not have + p.p.'),
(26, 'multiple_choice', 'We _____ a different supplier — the current one has been unreliable.', '["could have chosen","might have chosen","would have chosen","should have chosen"]', 'should have chosen', 'should have 對過去選擇的後悔。'),
(26, 'fill_blank', 'If the meeting had started on time, we _____ (finish) early.', NULL, 'would have finished', '第三條件句主句 would have finished。'),
(26, 'multiple_choice', 'The team _____ the risk earlier — there were warning signs.', '["could have identified","must have identified","would have identified","should have identified"]', 'should have identified', 'should have 表應負責任的批評。'),
(26, 'multiple_choice', 'He _____ the presentation better if he''d had more preparation time.', '["would have delivered","should have delivered","must have delivered","could have delivered"]', 'could have delivered', 'could have 表有條件的過去可能性。'),
(26, 'multiple_choice', 'We _____ the deal — the client was clearly interested.', '["would have closed","could have closed","should have closed","must have closed"]', 'should have closed', 'should have 表失去機會的遺憾。'),
(26, 'transform', 'It was possible to reduce costs by 15%. (Use: could have reduced)', NULL, 'We could have reduced costs by 15% if we had optimized the supply chain.', 'could have 表過去本可實現的節約。'),
(26, 'fill_blank', 'She _____ (inform) us earlier — we were completely unprepared.', NULL, 'should have informed', 'should have + p.p. 批評應該提前告知。'),
(26, 'multiple_choice', 'If they had responded sooner, the partnership _____ saved.', '["would have been","must have been","should have been","could have been"]', 'could have been', 'could have been + p.p. 表過去被動可能性。'),
(27, 'multiple_choice', 'The quarterly report _____ by the finance team every month.', '["will prepare","is prepared","prepares","has prepared"]', 'is prepared', '被動現在式 is prepared，report 是接受者。'),
(27, 'multiple_choice', 'The contract _____ by both parties yesterday.', '["was signed","has been signed","signed","is signed"]', 'was signed', 'yesterday 過去時間，被動過去式 was signed。'),
(27, 'multiple_choice', 'New employees _____ a two-week training program.', '["gave","are given","are giving","give"]', 'are given', 'are given 被動現在式，employees 接受培訓。'),
(27, 'fill_blank', 'The budget proposal _____ (approve) by the board last Tuesday.', NULL, 'was approved', 'last Tuesday 過去，被動過去式 was approved。'),
(27, 'multiple_choice', 'These products _____ in several Asian countries.', '["manufacture","were manufacturing","manufactured","are manufactured"]', 'are manufactured', 'are manufactured 被動現在式，描述持續的製造。'),
(27, 'multiple_choice', 'The new policy _____ to all staff via email last week.', '["communicated","was communicated","has been communicated","is communicated"]', 'was communicated', 'last week 過去，被動過去式 was communicated。'),
(27, 'multiple_choice', 'All expenses _____ by the accounting department.', '["reviewing","are reviewed","review","were reviewed"]', 'are reviewed', 'are reviewed 被動現在式表定期流程。'),
(27, 'transform', 'The IT department manages the server maintenance. (Use passive)', NULL, 'The server maintenance is managed by the IT department.', 'is managed by 被動語態。'),
(27, 'fill_blank', 'The new office building _____ (design) by a renowned architect.', NULL, 'was designed', 'was designed 被動過去式。'),
(27, 'multiple_choice', 'Invoices _____ within 30 days of receipt.', '["are processing","are processed","process","were processed"]', 'are processed', 'are processed 被動現在式表公司政策。'),
(27, 'multiple_choice', 'The client _____ about the changes immediately.', '["is notifying","notified","was notified","has notified"]', 'was notified', 'was notified 被動過去式，client 接受通知。'),
(27, 'multiple_choice', 'Performance reviews _____ twice a year.', '["have conducted","are conducted","conduct","were conducting"]', 'are conducted', 'are conducted 被動現在式描述定期程序。'),
(27, 'fill_blank', 'The sales data _____ (analyze) by the marketing team on a monthly basis.', NULL, 'is analyzed', '被動現在式 is analyzed 表定期活動。'),
(27, 'multiple_choice', 'The order was _____ due to a quality control issue.', '["cancel","cancelling","have cancelled","cancelled"]', 'cancelled', 'was cancelled 被動過去式，由 was 引導，接過去分詞。'),
(27, 'multiple_choice', 'The new product line _____ at the trade fair last year.', '["has been launched","was launched","is launched","launched"]', 'was launched', 'last year 過去，was launched 被動過去式。'),
(27, 'multiple_choice', 'All decisions _____ by the senior management team.', '["make","have made","were making","are made"]', 'are made', 'are made 被動現在式表決策流程。'),
(27, 'transform', 'They deliver goods to clients within 48 hours. (Use passive)', NULL, 'Goods are delivered to clients within 48 hours.', 'are delivered 被動現在式，強調流程而非執行者。'),
(27, 'fill_blank', 'Overtime payments _____ (calculate) based on the employee''s basic salary.', NULL, 'are calculated', 'are calculated 被動現在式表計算方式。'),
(27, 'multiple_choice', 'The report _____ once a quarter to the board of directors.', '["is submitted","submits","was submitting","submitting"]', 'is submitted', 'is submitted 被動現在式表定期提交。'),
(27, 'multiple_choice', 'The system _____ down for maintenance every weekend.', '["takes","is taken","has taken","was taking"]', 'is taken', 'is taken down 被動現在式 phrasal verb。'),
(28, 'multiple_choice', 'The contract _____ by both parties as of this morning.', '["is signed","had been signed","has been signed","was signed"]', 'has been signed', 'as of this morning 連結到現在，現在完成被動。'),
(28, 'multiple_choice', 'All the required documents _____ before the deadline.', '["were submitted","had been submitted","have been submitted","were being submitted"]', 'had been submitted', 'before the deadline 建立先後，過去完成被動。'),
(28, 'fill_blank', 'The new accounting software _____ (install) across all departments.', NULL, 'has been installed', 'has been + p.p. 現在完成被動，現在已完成。'),
(28, 'multiple_choice', 'By the time we arrived, the presentation _____ already _____.', '["was / being prepared","has / been prepared","had / been prepared","is / prepared"]', 'had / been prepared', 'had been prepared 過去完成被動 already。'),
(28, 'multiple_choice', 'The budget _____ three times this year.', '["is revised","was revised","has been revised","had been revised"]', 'has been revised', 'this year 到目前，現在完成被動 has been revised。'),
(28, 'multiple_choice', 'Before the announcement, the plan _____ carefully.', '["has been reviewed","had been reviewed","was being reviewed","was reviewed"]', 'had been reviewed', 'before 建立先後，過去完成被動 had been reviewed。'),
(28, 'transform', 'The team finished the analysis. (Use present perfect passive)', NULL, 'The analysis has been completed by the team.', 'has been completed 現在完成被動。'),
(28, 'fill_blank', 'The terms of the agreement _____ (negotiate) over several weeks.', NULL, 'have been negotiated', 'have been + p.p. 現在完成被動。'),
(28, 'multiple_choice', 'It _____ that the new policy would be implemented in Q3.', '["had been announced","was announced","is announced","has been announced"]', 'has been announced', 'has been announced 現在完成被動，強調現在已知。'),
(28, 'multiple_choice', 'By 2020, three offices _____ opened globally.', '["were","have been","had been","are"]', 'had been', 'by 2020 過去時間點，had been opened 過去完成被動。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(28, 'multiple_choice', 'New safety standards _____ to all employees this week.', '["had been communicated","have been communicated","were communicated","are communicated"]', 'have been communicated', 'this week 到目前，現在完成被動。'),
(28, 'fill_blank', 'The results _____ (verify) by an independent auditor before release.', NULL, 'had been verified', 'before release 建立先後，過去完成被動。'),
(28, 'multiple_choice', 'A breakthrough solution _____ by our R&D team.', '["was developed","is developed","has been developed","had been developed"]', 'has been developed', '強調現在成果，現在完成被動 has been developed。'),
(28, 'multiple_choice', 'By the end of Q2, 1,000 units _____ shipped.', '["had been","were","are","have been"]', 'had been', 'by the end of Q2 過去時間點，had been shipped。'),
(28, 'multiple_choice', 'Three candidates _____ for the final interview.', '["were shortlisted","are shortlisted","have been shortlisted","had been shortlisted"]', 'have been shortlisted', '強調目前狀態，現在完成被動。'),
(28, 'transform', 'Someone already reviewed the proposal. (Use present perfect passive)', NULL, 'The proposal has already been reviewed by the committee.', 'has already been reviewed 現在完成被動。'),
(28, 'fill_blank', 'The merger _____ (finalize) by the legal teams of both companies.', NULL, 'has been finalized', 'has been + p.p. 現在完成被動。'),
(28, 'multiple_choice', 'Before launch, the product _____ extensively for safety.', '["is tested","was tested","had been tested","has been tested"]', 'had been tested', 'before launch 先後關係，過去完成被動。'),
(28, 'multiple_choice', 'The client _____ kept informed throughout the project.', '["had been","was","is","has been"]', 'has been', 'has been kept 現在完成被動持續式。'),
(28, 'multiple_choice', 'The new system _____ in use since January.', '["had been","was","has been","is"]', 'has been', 'since January 持續到現在，has been in use。'),
(29, 'multiple_choice', 'The report _____ submitted by 5 p.m. on Friday.', '["should","must be","can","will"]', 'must be', 'must be + p.p. 表強制要求的被動式。'),
(29, 'multiple_choice', 'All proposals _____ reviewed by the compliance team.', '["can","will","must","should be"]', 'should be', 'should be + p.p. 建議性被動規定。'),
(29, 'multiple_choice', 'Your application _____ processed within five working days.', '["should","must","will be","can"]', 'will be', 'will be + p.p. 預告未來被動動作。'),
(29, 'fill_blank', 'The invoice _____ (pay) within 30 days of receipt.', NULL, 'must be paid', 'must be + p.p. 強制性被動規定。'),
(29, 'multiple_choice', 'Client data _____ shared with third parties without consent.', '["must not be","will not","should not","can not"]', 'must not be', 'must not be + p.p. 嚴格禁止的被動式。'),
(29, 'multiple_choice', 'These documents _____ kept confidential at all times.', '["can be","must be","should","will be"]', 'must be', 'must be + p.p. 強制保密要求。'),
(29, 'multiple_choice', 'The application form _____ completed in full.', '["will be","must","should be","can"]', 'should be', 'should be + p.p. 建議做到完整填寫。'),
(29, 'transform', 'We can access the system remotely. (Use passive)', NULL, 'The system can be accessed remotely.', 'can be + p.p. 情態被動，強調系統功能。'),
(29, 'fill_blank', 'The budget _____ (approve) before any expenditure is made.', NULL, 'must be approved', 'must be + p.p. 強制先決條件。'),
(29, 'multiple_choice', 'All visitors _____ registered at the front desk.', '["must be","should","will","can"]', 'must be', 'must be + p.p. 強制安全規定。'),
(29, 'multiple_choice', 'The timeline _____ adjusted if there are unexpected delays.', '["should be","must be","may be","will be"]', 'may be', 'may be + p.p. 表可能需要調整。'),
(29, 'multiple_choice', 'Results _____ announced at the annual shareholders'' meeting.', '["can","should","will be","must be"]', 'will be', 'will be + p.p. 預告未來被動事件。'),
(29, 'fill_blank', 'Personal information _____ (not / share) without written permission.', NULL, 'must not be shared', 'must not be + p.p. 嚴格禁止。'),
(29, 'multiple_choice', 'Overtime _____ authorized in advance by your line manager.', '["must be","should","will be","can"]', 'must be', 'must be + p.p. 強制預先授權。'),
(29, 'multiple_choice', 'These changes _____ implemented by the end of Q3.', '["must","can","will","should be"]', 'should be', 'should be + p.p. 建議性期限。'),
(29, 'multiple_choice', 'A copy of the contract _____ sent to all parties involved.', '["should","will be","can","must be"]', 'will be', 'will be + p.p. 預告文件分發。'),
(29, 'transform', 'Someone should inform the client about this. (Use passive)', NULL, 'The client should be informed about this change immediately.', 'should be + p.p. 情態被動。'),
(29, 'fill_blank', 'The equipment _____ (inspect) regularly to ensure safety.', NULL, 'should be inspected', 'should be + p.p. 定期安全檢查建議。'),
(29, 'multiple_choice', 'The project _____ completed without additional resources.', '["must not be","should not be","cannot be","will not be"]', 'cannot be', 'cannot be + p.p. 表無法完成的被動式。'),
(29, 'multiple_choice', 'Any defects _____ reported to the quality control team.', '["must","can","should be","will be"]', 'should be', 'should be + p.p. 建議性程序。'),
(30, 'multiple_choice', 'We _____ the office _____ last month.', '["made / renovated","got / renovate","had / renovated","let / renovate"]', 'had / renovated', 'have something done 安排裝修，had renovated。'),
(30, 'multiple_choice', 'She needs to _____ her laptop _____ before the conference.', '["have / repair","get / repaired","make / repaired","let / repaired"]', 'get / repaired', 'get something done 安排修理，get repaired。'),
(30, 'multiple_choice', 'The manager _____ the intern _____ the report.', '["let / prepared","made / to prepare","had / prepare","got / prepared"]', 'had / prepare', 'have someone do 命令做某事，had + 人 + 原形。'),
(30, 'fill_blank', 'We need to _____ the contract _____ (check) by our lawyers.', NULL, 'have / checked', 'have something done 委託律師審查。'),
(30, 'multiple_choice', 'Can you _____ the presentation slides _____ by tomorrow?', '["make / prepared","have / prepare","get / ready","let / ready"]', 'get / ready', 'get something ready 使其準備好。'),
(30, 'multiple_choice', 'She _____ her team _____ a full market analysis.', '["had / conduct","got / conducted","made / to conduct","let / conduct"]', 'had / conduct', 'had someone do 命令做分析。'),
(30, 'multiple_choice', 'We should _____ the financial reports _____ by an external auditor.', '["let / audited","get / audit","make / audited","have / audited"]', 'have / audited', 'have something done 外部審計。'),
(30, 'transform', 'An outside company cleaned the office. (Use: had the office)', NULL, 'We had the office cleaned by an outside company.', 'have something done 被動使役。'),
(30, 'fill_blank', 'Could you _____ someone _____ (deliver) the documents to our client?', NULL, 'get / to deliver', 'get someone to do 說服/委派做事。'),
(30, 'multiple_choice', 'He _____ the brochures _____ at a local print shop.', '["got / print","let / printed","made / printed","had / printed"]', 'had / printed', 'had something printed 委託印製。'),
(30, 'multiple_choice', 'They are going to _____ the website _____ next week.', '["let / redesigned","make / redesigned","get / redesign","have / redesigned"]', 'have / redesigned', 'have something done 委外改版。'),
(30, 'multiple_choice', 'She _____ the assistant _____ the meeting room before the clients arrived.', '["got / setting up","let / set up","made / set up","had / set up"]', 'had / set up', 'had someone do 命令安排。'),
(30, 'fill_blank', 'I need to _____ my car _____ (service) before the long drive.', NULL, 'have / serviced', 'have something done 服務的委託。'),
(30, 'multiple_choice', 'We _____ the new branch _____ by an interior design firm.', '["got / furnish","had / furnished","made / furnished","let / furnish"]', 'had / furnished', 'had something done 委外室內設計。'),
(30, 'multiple_choice', 'The CEO _____ the PR team _____ a press release immediately.', '["made / to draft","got / drafted","let / draft","had / draft"]', 'had / draft', 'had someone do 命令起草。'),
(30, 'multiple_choice', 'Can you _____ the report _____ into Chinese?', '["get / translated","have / translate","make / translated","let / translate"]', 'get / translated', 'get something done 委外翻譯。'),
(30, 'transform', 'An expert examined the machinery. (Use: had the machinery)', NULL, 'We had the machinery examined by an expert.', 'had something done 委請專家檢查。'),
(30, 'fill_blank', 'She _____ the IT team _____ (install) the new software on her computer.', NULL, 'had / install', 'had someone do 命令安裝，原形動詞。'),
(30, 'multiple_choice', 'We plan to _____ the annual report _____ before the AGM.', '["get / publish","let / published","make / published","have / published"]', 'have / published', 'have something done 印製報告。'),
(30, 'multiple_choice', 'He _____ his assistant _____ all the travel arrangements.', '["got / to make","let / make","had / make","made / to make"]', 'got / to make', 'got someone to do 說服/委派做安排。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(31, 'multiple_choice', 'He said, ''I will send the report.'' → He said he _____ send the report.', '["shall","will","can","would"]', 'would', 'will → would 時態後移。'),
(31, 'multiple_choice', 'She told me, ''I am working on the proposal.'' → She told me she _____ on the proposal.', '["was working","works","worked","is working"]', 'was working', 'am/is working → was working 時態後移。'),
(31, 'multiple_choice', 'They said, ''We have completed the audit.'' → They said they _____ the audit.', '["were completing","had completed","have completed","completed"]', 'had completed', 'have completed → had completed 時態後移。'),
(31, 'fill_blank', 'She said, ''I can finish this by Friday.'' → She said she _____ finish it by Friday.', NULL, 'could', 'can → could 時態後移。'),
(31, 'multiple_choice', 'The manager said, ''The project is on track.'' → The manager said the project _____ on track.', '["will be","were","was","is"]', 'was', 'is → was 時態後移。'),
(31, 'multiple_choice', 'He told us, ''I signed the contract yesterday.'' → He told us he _____ the contract the day before.', '["had signed","was signing","signed","has signed"]', 'had signed', 'signed → had signed 時態後移。'),
(31, 'transform', 'The CEO said: ''We will expand into Europe next year.'' (Use reported speech)', NULL, 'The CEO said they would expand into Europe the following year.', 'will → would；next year → the following year。'),
(31, 'fill_blank', 'She said, ''I am going to attend the conference.'' → She said she _____ the conference.', NULL, 'was going to attend', 'am going to → was going to 時態後移。'),
(31, 'multiple_choice', 'He said, ''The client may cancel the order.'' → He said the client _____ cancel the order.', '["will","might","can","may"]', 'might', 'may → might 時態後移。'),
(31, 'multiple_choice', 'They announced, ''We are launching a new product.'' → They announced they _____ a new product.', '["launch","are launching","launched","were launching"]', 'were launching', 'are launching → were launching 時態後移。'),
(31, 'fill_blank', 'She said, ''I have never seen such a detailed proposal.'' → She said she _____ such a detailed proposal.', NULL, 'had never seen', 'have never seen → had never seen 時態後移。'),
(31, 'multiple_choice', 'The director said, ''The results exceeded expectations.'' → The director said the results _____ expectations.', '["have exceeded","had exceeded","were exceeding","exceeded"]', 'had exceeded', 'exceeded → had exceeded 時態後移。'),
(31, 'multiple_choice', 'He told us, ''We must cut costs immediately.'' → He told us they _____ cut costs immediately.', '["must","should","would","had to"]', 'had to', 'must → had to 時態後移。'),
(31, 'transform', 'The client said: ''I need more time to review the terms.'' (Use reported speech)', NULL, 'The client said he needed more time to review the terms.', 'need → needed 時態後移。'),
(31, 'fill_blank', 'She told me, ''I will call you tomorrow.'' → She told me she _____ the next day.', NULL, 'would call', 'will → would；tomorrow → the next day。'),
(31, 'multiple_choice', 'He said, ''The meeting starts at 10.'' → He said the meeting _____ at 10.', '["started","start","starts","had started"]', 'started', 'starts → started 時態後移（現在→過去）。'),
(31, 'multiple_choice', 'They said, ''We can deliver within 48 hours.'' → They said they _____ deliver within 48 hours.', '["could","would","will","can"]', 'could', 'can → could 時態後移。'),
(31, 'fill_blank', 'The consultant said, ''This approach is more efficient.'' → The consultant said that approach _____ more efficient.', NULL, 'was', 'is → was 時態後移。'),
(31, 'multiple_choice', 'She said, ''I haven''t finished the analysis.'' → She said she _____ the analysis.', '["haven''t finished","hadn''t finished","wasn''t finishing","didn''t finish"]', 'hadn''t finished', 'haven''t → hadn''t 時態後移。'),
(31, 'multiple_choice', 'He told the team, ''The client is impressed.'' → He told the team the client _____ impressed.', '["was","has been","were","is"]', 'was', 'is → was 時態後移。'),
(32, 'multiple_choice', '''What is the deadline?'' → She asked what the deadline _____.', '["is","was","were","will be"]', 'was', '間接問句陳述語序，is → was。'),
(32, 'multiple_choice', '''Is the report ready?'' → He asked _____ the report was ready.', '["whether","if","that","what"]', 'if', 'yes/no 問句用 if 或 whether 引導間接問句。'),
(32, 'multiple_choice', '''When will the meeting start?'' → They asked when the meeting _____.', '["would start","starts","will start","started"]', 'would start', 'will → would；陳述語序。'),
(32, 'fill_blank', '''Do you need any assistance?'' → She asked _____ I needed any assistance.', NULL, 'if/whether', 'yes/no 問句用 if 或 whether 引導。'),
(32, 'multiple_choice', '''Where is the nearest conference center?'' → He asked where the nearest conference center _____.', '["is","was","were","will be"]', 'was', '間接問句 is → was。'),
(32, 'multiple_choice', '''Have you reviewed the proposal?'' → She asked _____ I had reviewed the proposal.', '["that","if","what","whether"]', 'whether', 'whether 引導 yes/no 間接問句。'),
(32, 'multiple_choice', '''How many units can we order?'' → The client asked how many units they _____ order.', '["will","would","could","can"]', 'could', 'can → could 時態後移。'),
(32, 'transform', '''Are you satisfied with the service?'' → The manager asked ...(Use reported question)', NULL, 'The manager asked whether we were satisfied with the service.', 'whether + 陳述語序 + was。'),
(32, 'fill_blank', '''Why did the project fail?'' → The board asked why the project _____.', NULL, 'had failed', 'why + 過去完成式（failed → had failed）。'),
(32, 'multiple_choice', '''What does the contract include?'' → She asked what the contract _____.', '["included","will include","has included","includes"]', 'included', 'includes → included 時態後移。'),
(32, 'multiple_choice', '''Can I speak to the manager?'' → He asked _____ he could speak to the manager.', '["whether","if","what","that"]', 'if', 'yes/no 問句 if 引導。'),
(32, 'multiple_choice', '''Who is in charge of the project?'' → They asked _____ was in charge of the project.', '["whether","who","which","what"]', 'who', 'who 仍是疑問詞，引導間接問句。'),
(32, 'fill_blank', '''How long will the installation take?'' → She asked how long the installation _____ take.', NULL, 'would', 'will → would 時態後移。'),
(32, 'multiple_choice', '''Did the client confirm the order?'' → He asked _____ the client had confirmed the order.', '["whether","what","that","if"]', 'whether', 'whether 引導 yes/no 間接問句；did confirm → had confirmed。'),
(32, 'multiple_choice', '''Which option do you prefer?'' → She asked which option we _____.', '["will prefer","preferred","have preferred","prefer"]', 'preferred', 'prefer → preferred 時態後移。'),
(32, 'transform', '''Is there a cheaper alternative?'' → The client asked ...(Use reported question)', NULL, 'The client asked if there was a cheaper alternative.', 'if + 陳述語序 + was。'),
(32, 'fill_blank', '''What time does the office open?'' → He asked what time the office _____.', NULL, 'opened', 'does open → opened 時態後移。'),
(32, 'multiple_choice', '''Has the payment been processed?'' → She asked _____ the payment had been processed.', '["what","that","whether","if"]', 'whether', 'whether + 被動過去完成式 had been processed。'),
(32, 'multiple_choice', '''Who approved the budget?'' → They asked who _____ the budget.', '["has approved","had approved","was approving","approved"]', 'had approved', 'approved → had approved 時態後移。'),
(32, 'multiple_choice', '''What are the main objectives?'' → He asked what the main objectives _____.', '["are","will be","were","had been"]', 'were', 'are → were 時態後移。'),
(33, 'multiple_choice', '''Submit the report by Friday.'' → He told us _____ the report by Friday.', '["submitting","that we submit","to submit","submit"]', 'to submit', 'tell + 人 + to do 間接命令。'),
(33, 'multiple_choice', '''Don''t be late.'' → She asked them _____ late.', '["to not be","not to be","not be","that not be"]', 'not to be', '間接否定命令：not to + 原形。'),
(33, 'multiple_choice', '''Please prepare the agenda.'' → The manager asked her _____ the agenda.', '["prepare","that she prepares","to prepare","preparing"]', 'to prepare', 'ask + 人 + to do 間接請求。'),
(33, 'fill_blank', '''Follow the company guidelines.'' → He told the new staff _____ the company guidelines.', NULL, 'to follow', 'tell + 人 + to do。'),
(33, 'multiple_choice', '''Don''t share the confidential data.'' → She told him _____ the confidential data.', '["to not share","not sharing","that he not share","not to share"]', 'not to share', 'tell + 人 + not to do。'),
(33, 'multiple_choice', '''Please review the proposal carefully.'' → He asked the team _____ the proposal carefully.', '["to review","that they review","review","reviewing"]', 'to review', 'ask + 人 + to do。'),
(33, 'multiple_choice', '''Call the client immediately.'' → She instructed me _____ the client immediately.', '["to call","that I call","call","calling"]', 'to call', 'instruct + 人 + to do 間接命令。'),
(33, 'transform', 'The boss said: ''Please don''t miss the deadline.'' (Use reported command)', NULL, 'The boss asked us not to miss the deadline.', 'asked + 人 + not to do。'),
(33, 'fill_blank', '''Update the spreadsheet daily.'' → The supervisor told the intern _____ the spreadsheet daily.', NULL, 'to update', 'tell + 人 + to do。'),
(33, 'multiple_choice', '''Please don''t use the printer during peak hours.'' → She asked staff _____ the printer during peak hours.', '["not using","not to use","to not use","that they not use"]', 'not to use', 'ask + 人 + not to do。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(33, 'multiple_choice', '''Read the contract carefully before signing.'' → He advised her _____ the contract carefully.', '["that she reads","read","to read","reading"]', 'to read', 'advise + 人 + to do。'),
(33, 'multiple_choice', '''Don''t discuss salary with colleagues.'' → The HR manager warned them _____ salary with colleagues.', '["that they not discuss","not discussing","to not discuss","not to discuss"]', 'not to discuss', 'warn + 人 + not to do。'),
(33, 'fill_blank', '''Please confirm the order by email.'' → She asked the client _____ the order by email.', NULL, 'to confirm', 'ask + 人 + to do。'),
(33, 'multiple_choice', '''Attend the orientation session.'' → The company required all new hires _____ the orientation session.', '["that they attend","attending","attend","to attend"]', 'to attend', 'require + 人 + to do。'),
(33, 'multiple_choice', '''Don''t park in the visitor spaces.'' → He told staff _____ in the visitor spaces.', '["not to park","to not park","not parking","that they not park"]', 'not to park', 'tell + 人 + not to do。'),
(33, 'transform', 'The IT team said: ''Please restart your computer after the update.'' (Use reported)', NULL, 'The IT team asked all users to restart their computers after the update.', 'asked + 人 + to do，注意代名詞調整。'),
(33, 'fill_blank', '''Send me the draft by Monday.'' → She instructed him _____ the draft by Monday.', NULL, 'to send', 'instruct + 人 + to do。'),
(33, 'multiple_choice', '''Don''t forget to include the appendix.'' → She reminded him _____ to include the appendix.', '["to not","that he don''t","not","do not"]', 'not', 'remind + 人 + not to forget。'),
(33, 'multiple_choice', '''Please copy me on all emails to the client.'' → He asked her _____ him on all emails to the client.', '["that she copies","copying","to copy","copy"]', 'to copy', 'ask + 人 + to do。'),
(33, 'multiple_choice', '''Report any issues immediately.'' → The manager told staff _____ any issues immediately.', '["that they report","reporting","to report","report"]', 'to report', 'tell + 人 + to do。'),
(34, 'multiple_choice', '''I am writing the contract now.'' → She said she _____ the contract then.', '["wrote","is writing","writes","was writing"]', 'was writing', 'is writing → was writing，now → then。'),
(34, 'multiple_choice', '''We will finalize the deal tomorrow.'' → They said they _____ the deal the following day.', '["had finalized","will finalize","would finalize","finalize"]', 'would finalize', 'will → would；tomorrow → the following day。'),
(34, 'multiple_choice', '''I have already sent the invoice.'' → He said he _____ the invoice.', '["had already sent","has already sent","was already sending","already sent"]', 'had already sent', 'have sent → had sent 時態後移。'),
(34, 'fill_blank', '''The client can meet us today.'' → She said the client _____ meet them that day.', NULL, 'could', 'can → could；today → that day。'),
(34, 'multiple_choice', '''I may attend the conference.'' → She said she _____ attend the conference.', '["might","may","can","would"]', 'might', 'may → might 時態後移。'),
(34, 'multiple_choice', '''We signed the deal last week.'' → He said they _____ the deal the week before.', '["were signing","had signed","have signed","signed"]', 'had signed', 'signed → had signed；last week → the week before。'),
(34, 'transform', 'Direct: ''This is our best offer.'' → Report this statement.', NULL, 'She said that was their best offer.', 'this → that；is → was；our → their。'),
(34, 'fill_blank', '''I have been working here for three years.'' → He said he _____ there for three years.', NULL, 'had been working', 'have been working → had been working；here → there。'),
(34, 'multiple_choice', '''Our profits are increasing this year.'' → She said their profits _____ that year.', '["had increased","were increasing","increase","are increasing"]', 'were increasing', 'are increasing → were increasing；this → that。'),
(34, 'multiple_choice', '''I must submit the report today.'' → He said he _____ submit the report that day.', '["would","had to","should","must"]', 'had to', 'must → had to；today → that day。'),
(34, 'multiple_choice', '''We are expanding into new markets here.'' → She said they _____ into new markets there.', '["are expanding","expand","have expanded","were expanding"]', 'were expanding', 'are expanding → were expanding；here → there。'),
(34, 'fill_blank', '''The meeting will be held tomorrow.'' → She said the meeting _____ the following day.', NULL, 'would be held', 'will be held → would be held；tomorrow → the following day。'),
(34, 'multiple_choice', '''We can reduce costs by 10%.'' → He said they _____ reduce costs by 10%.', '["can","could","might","would"]', 'could', 'can → could 時態後移。'),
(34, 'multiple_choice', '''I''ve never seen such growth.'' → She said she _____ such growth.', '["had never seen","hadn''t been seeing","has never seen","never saw"]', 'had never seen', 'have never seen → had never seen。'),
(34, 'transform', 'Direct: ''These negotiations may take longer than expected.'' → Report this.', NULL, 'He warned that those negotiations might take longer than expected.', 'may → might；these → those。'),
(34, 'fill_blank', '''We finished the project yesterday.'' → They said they _____ the project the day before.', NULL, 'had finished', 'finished → had finished；yesterday → the day before。'),
(34, 'multiple_choice', '''We are going to restructure the company.'' → He said they _____ the company.', '["will restructure","were going to restructure","would restructure","are going to restructure"]', 'were going to restructure', 'are going to → were going to。'),
(34, 'multiple_choice', '''The client is here now.'' → She said the client _____ there then.', '["had been","is","was","were"]', 'was', 'is → was；here → there；now → then。'),
(34, 'fill_blank', '''I can''t attend the meeting today.'' → He said he _____ the meeting that day.', NULL, 'couldn''t attend', 'can''t → couldn''t；today → that day。'),
(34, 'multiple_choice', '''We''ve already solved the problem.'' → She said they _____ the problem.', '["were solving","solved","had already solved","have already solved"]', 'had already solved', 'have solved → had solved。'),
(35, 'multiple_choice', 'The employee _____ submitted the best proposal will be promoted.', '["which","whose","who","that"]', 'who', 'who 指人，限定性關係子句。'),
(35, 'multiple_choice', 'The software _____ we use has been updated.', '["which","who","whose","that"]', 'that', 'that 可指物，限定性關係子句。'),
(35, 'multiple_choice', 'The company _____ products are sold worldwide is headquartered in Germany.', '["whose","who","that","which"]', 'whose', 'whose 所有格，修飾 products。'),
(35, 'fill_blank', 'The report _____ was submitted last week has been approved.', NULL, 'that/which', 'that 或 which 指物，限定性關係子句。'),
(35, 'multiple_choice', 'The manager _____ I reported to was very supportive.', '["whose","who","which","that"]', 'who', 'who 指人，作受語。'),
(35, 'multiple_choice', 'The city _____ the conference will be held is London.', '["which","who","where","that"]', 'where', 'where 指地點的關係副詞。'),
(35, 'multiple_choice', 'The client _____ placed the largest order will receive a discount.', '["whose","who","which","that"]', 'who', 'who 指人（客戶）。'),
(35, 'transform', 'The candidate was hired. He had the most experience. (Use: who)', NULL, 'The candidate who had the most experience was hired.', 'who 引導限定性關係子句。'),
(35, 'multiple_choice', 'The proposal _____ received the most votes was accepted.', '["which","that","who","whose"]', 'that', 'that 指物（proposal），限定性子句。'),
(35, 'fill_blank', 'The department _____ handles international accounts is expanding.', NULL, 'that/which', 'that 或 which 指部門。'),
(35, 'multiple_choice', 'The time _____ we need to submit the report is 5 p.m.', '["which","when","that","who"]', 'when', 'when 指時間的關係副詞。'),
(35, 'multiple_choice', 'The platform _____ we have chosen is highly secure.', '["who","which","that","whose"]', 'that', 'that 指物。'),
(35, 'multiple_choice', 'The partner _____ firm specializes in intellectual property law is ideal.', '["that","who","which","whose"]', 'whose', 'whose 所有格，修飾 firm。'),
(35, 'fill_blank', 'The strategy _____ proved most effective was adopted by the board.', NULL, 'that/which', 'that 或 which 指策略。'),
(35, 'multiple_choice', 'The director _____ presentation impressed the investors was promoted.', '["who","which","whose","that"]', 'whose', 'whose 所有格，修飾 presentation。'),
(35, 'multiple_choice', 'The branch _____ was opened last year is already profitable.', '["who","that","whose","which"]', 'that', 'that 指物（branch）。'),
(35, 'transform', 'She identified the error. The error had caused the delay. (Use: that)', NULL, 'She identified the error that had caused the delay.', 'that 引導限定性關係子句。'),
(35, 'fill_blank', 'The vendor _____ we have partnered with offers competitive pricing.', NULL, 'that/who', 'that 或 who（公司可用 who 或 that）。'),
(35, 'multiple_choice', 'The year _____ we launched the product was 2021.', '["when","that","who","which"]', 'when', 'when 指年份（時間關係副詞）。'),
(35, 'multiple_choice', 'The team _____ developed the app won the innovation award.', '["whose","who","which","that"]', 'that', 'that 指整個團隊（也可 who）。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(36, 'multiple_choice', 'Our CEO, _____ joined in 2015, has transformed the company.', '["whose","which","that","who"]', 'who', '非限定性關係子句，不可用 that，用 who 指人。'),
(36, 'multiple_choice', 'The new office, _____ is located in the city centre, opened last month.', '["whose","which","who","that"]', 'which', '非限定性關係子句，which 指物，不可用 that。'),
(36, 'multiple_choice', 'The merger, _____ was announced last week, surprised the industry.', '["which","that","whose","who"]', 'which', '非限定性關係子句 which 指事件。'),
(36, 'fill_blank', 'Ms. Chen, _____ daughter is also an engineer, leads our R&D team.', NULL, 'whose', 'whose 所有格非限定性關係子句。'),
(36, 'multiple_choice', 'The contract, _____ runs until 2028, includes performance clauses.', '["who","which","whose","that"]', 'which', '非限定性子句 which，注意逗號。'),
(36, 'multiple_choice', 'The annual conference, _____ attracts 500 delegates, is held in April.', '["who","whose","which","that"]', 'which', '非限定性子句 which 指事件。'),
(36, 'transform', 'John Smith leads the team. He has 20 years of experience. (Use non-defining)', NULL, 'John Smith, who has 20 years of experience, leads the team.', '非限定性子句加逗號，who 指人。'),
(36, 'multiple_choice', 'Singapore, _____ we opened our first Asian office, is a key market.', '["that","where","which","who"]', 'where', 'where 指地點的非限定性關係副詞。'),
(36, 'fill_blank', 'The Q4 report, _____ shows record profits, will be presented to the board tomorrow.', NULL, 'which', '非限定性子句 which，注意逗號。'),
(36, 'multiple_choice', 'Our largest client, _____ we have worked with for ten years, renewed the contract.', '["whom","which","that","who"]', 'whom', 'whom 是受格關係代名詞，正式用法（也可用 who）。'),
(36, 'multiple_choice', 'The product launch, _____ attracted significant media attention, was a success.', '["whose","who","which","that"]', 'which', '非限定性子句 which。'),
(36, 'multiple_choice', 'Dr. Lee, _____ research was cited in the report, will present at the conference.', '["that","who","which","whose"]', 'whose', 'whose 所有格非限定性關係子句。'),
(36, 'transform', 'The proposal was rejected. It had been reviewed by all departments. (Use non-defining)', NULL, 'The proposal, which had been reviewed by all departments, was rejected.', 'which 非限定性子句加逗號。'),
(36, 'fill_blank', '2023, _____ we achieved record revenue, was our best year.', NULL, 'when', 'when 指年份的非限定性關係副詞。'),
(36, 'multiple_choice', 'The CFO, _____ resigned last month, was known for his innovative strategies.', '["that","which","whose","who"]', 'who', '非限定性子句 who 指人。'),
(36, 'multiple_choice', 'The new policy, _____ takes effect in January, will affect all employees.', '["whose","who","which","that"]', 'which', '非限定性子句 which 指政策。'),
(36, 'fill_blank', 'Our branch in Tokyo, _____ opened five years ago, is now our most profitable.', NULL, 'which', '非限定性子句 which 補充說明東京分部。'),
(36, 'multiple_choice', 'The training program, _____ lasts three weeks, covers essential business skills.', '["whose","which","that","who"]', 'which', '非限定性子句 which。'),
(36, 'multiple_choice', 'Mr. Wang, _____ I met at the trade fair, is interested in a partnership.', '["who","which","that","whom"]', 'whom', 'whom 受格，正式英語；也可用 who。'),
(36, 'multiple_choice', 'The AGM, _____ all shareholders are invited to attend, is scheduled for May.', '["whose","which","that","who"]', 'which', '非限定性子句 which。'),
(37, 'multiple_choice', 'The person _____ handles our logistics is very efficient.', '["whose","which","who","that"]', 'who', 'who 指人，主格。'),
(37, 'multiple_choice', 'The document _____ I need is on your desk.', '["which","whose","who","that"]', 'that', 'that 指物，可替代 which（限定子句）。'),
(37, 'multiple_choice', 'The company _____ logo is red and blue is our main competitor.', '["that","who","whose","which"]', 'whose', 'whose 所有格，修飾 logo。'),
(37, 'fill_blank', 'The staff member _____ processed your order has been promoted.', NULL, 'who/that', 'who 或 that 均可指人（限定子句）。'),
(37, 'multiple_choice', 'The software _____ we installed last week has improved productivity.', '["who","whose","that","which"]', 'that', 'that 指物。'),
(37, 'multiple_choice', 'The employee _____ performance was exceptional received a bonus.', '["who","that","which","whose"]', 'whose', 'whose 所有格，修飾 performance。'),
(37, 'multiple_choice', 'The branch _____ the CEO visited last month is performing well.', '["that","whose","who","which"]', 'that', 'that 指物，受格用法（受詞可省略）。'),
(37, 'transform', 'The consultant helped us. His firm is based in New York. (Use: whose)', NULL, 'The consultant whose firm is based in New York helped us.', 'whose 所有格限定性關係子句。'),
(37, 'multiple_choice', 'The system _____ was installed last year needs an upgrade.', '["whose","who","that","which"]', 'that', 'that 指物，主格用法。'),
(37, 'fill_blank', 'The client _____ we spoke to yesterday wants a revised proposal.', NULL, 'who/whom/that', 'who 或 that 可指人；whom 正式受格。'),
(37, 'multiple_choice', 'The project _____ budget exceeded one million was reviewed by the board.', '["which","that","who","whose"]', 'whose', 'whose 所有格，修飾 budget。'),
(37, 'multiple_choice', 'The partner _____ brought in the most new clients won the award.', '["whose","which","who","that"]', 'who', 'who 指人（partner），主格。'),
(37, 'multiple_choice', 'The regulations _____ were introduced last year affected many industries.', '["that","whose","who","which"]', 'that', 'that 指物（regulations）。'),
(37, 'transform', 'The manager worked hard. She always meets her targets. (Use: who)', NULL, 'She is the kind of manager who always meets her targets.', 'who 引導描述人的關係子句。'),
(37, 'fill_blank', 'The product _____ we developed has received excellent reviews.', NULL, 'that/which', 'that 或 which 均可指物。'),
(37, 'multiple_choice', 'The consultant _____ advice we followed was right.', '["whose","that","which","who"]', 'whose', 'whose 所有格，修飾 advice。'),
(37, 'multiple_choice', 'This is the platform _____ connects buyers and sellers globally.', '["which","that","whose","who"]', 'that', 'that 指物，限定性子句。'),
(37, 'fill_blank', 'The team _____ won the award was from the marketing department.', NULL, 'that/which', 'that 或 which 均可（限定性子句）。'),
(37, 'multiple_choice', 'The investor _____ funded the startup is well known in the industry.', '["who","that","which","whose"]', 'who', 'who 指人（investor）。'),
(37, 'multiple_choice', 'The policy _____ was introduced in Q1 has improved efficiency.', '["that","who","which","whose"]', 'that', 'that 指物（policy）。'),
(38, 'multiple_choice', 'She decided _____ the new marketing strategy.', '["of implementing","to implement","implementing","implement"]', 'to implement', 'decide + to do 決定做。'),
(38, 'multiple_choice', 'We considered _____ our office in Singapore.', '["relocate","of relocating","to relocate","relocating"]', 'relocating', 'consider + V-ing 考慮做。'),
(38, 'multiple_choice', 'He agreed _____ the proposal by the end of the week.', '["of reviewing","to review","reviewing","review"]', 'to review', 'agree + to do 同意做。'),
(38, 'fill_blank', 'She finished _____ (write) the report and sent it to the client.', NULL, 'writing', 'finish + V-ing 完成做。'),
(38, 'multiple_choice', 'They plan _____ a new branch in Europe next year.', '["opening","of opening","open","to open"]', 'to open', 'plan + to do 計劃做。'),
(38, 'multiple_choice', 'He suggested _____ the product launch to Q1.', '["of postponing","postponing","postpone","to postpone"]', 'postponing', 'suggest + V-ing 建議做。'),
(38, 'multiple_choice', 'I avoid _____ important meetings without proper preparation.', '["attend","of attending","to attend","attending"]', 'attending', 'avoid + V-ing 避免做。'),
(38, 'transform', 'The manager said he would sign the contract. (Use: agreed to sign)', NULL, 'The manager agreed to sign the contract before the deadline.', 'agree + to do。'),
(38, 'multiple_choice', 'She stopped _____ when she heard the news.', '["to talk","talking","talk","of talking"]', 'talking', 'stopped talking 停止說話（動作結束）；stopped to talk 停下來去說話。'),
(38, 'fill_blank', 'We expect _____ (receive) the shipment by Thursday.', NULL, 'to receive', 'expect + to do 期待。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(38, 'multiple_choice', 'The team practiced _____ the presentation before the big day.', '["of giving","giving","give","to give"]', 'giving', 'practice + V-ing 練習做。'),
(38, 'multiple_choice', 'She remembered _____ the invoice — it was done last week.', '["sending","of sending","to send","send"]', 'sending', 'remembered sending 記得曾做（過去已做）。'),
(38, 'multiple_choice', 'He tried _____ the client''s concerns in his email.', '["to address","addressing","of addressing","address"]', 'to address', 'try + to do 嘗試做（努力）。'),
(38, 'fill_blank', 'Would you mind _____ (postpone) the meeting by one hour?', NULL, 'postponing', 'Would you mind + V-ing 請求。'),
(38, 'multiple_choice', 'We recommend _____ the terms before signing.', '["reviewing","review","to review","of reviewing"]', 'reviewing', 'recommend + V-ing 建議做。'),
(38, 'multiple_choice', 'She managed _____ all five projects on time.', '["to complete","complete","of completing","completing"]', 'to complete', 'manage + to do 設法做到。'),
(38, 'multiple_choice', 'He enjoys _____ with international clients.', '["of working","working","work","to work"]', 'working', 'enjoy + V-ing 喜歡做。'),
(38, 'transform', 'It would be a good idea to expand into Asia. (Use: suggest expanding)', NULL, 'She suggested expanding into Asian markets next year.', 'suggest + V-ing。'),
(38, 'fill_blank', 'The company failed _____ (meet) its Q3 targets.', NULL, 'to meet', 'fail + to do 未能做到。'),
(38, 'multiple_choice', 'She offered _____ with the onboarding process.', '["to help","helping","help","of helping"]', 'to help', 'offer + to do 提議做。'),
(39, 'multiple_choice', '_____ effectively with clients is a key skill in sales.', '["To communicate","Communication","Communicating","Communicate"]', 'Communicating', 'Communicating 動名詞作主語。'),
(39, 'multiple_choice', '_____ the budget carefully ensures financial stability.', '["Management","Managed","Managing","To manage"]', 'Managing', 'Managing 動名詞作主語。'),
(39, 'fill_blank', '_____ (meet) deadlines consistently is essential in this role.', NULL, 'Meeting', 'Meeting 動名詞作主語。'),
(39, 'multiple_choice', '_____ a diverse team brings different perspectives to problem-solving.', '["Leading","Lead","Leads","To lead"]', 'Leading', 'Leading 動名詞作主語。'),
(39, 'multiple_choice', '_____ customer satisfaction should be every employee''s priority.', '["To maintain","Maintained","Maintain","Maintaining"]', 'Maintaining', 'Maintaining 動名詞作主語。'),
(39, 'multiple_choice', '_____ the right suppliers is crucial for quality control.', '["Selected","Select","Selecting","To select"]', 'Selecting', 'Selecting 動名詞作主語。'),
(39, 'transform', 'It is important to track your expenses carefully. (Use gerund as subject)', NULL, 'Tracking your expenses carefully is important for financial management.', 'Tracking 動名詞作主語。'),
(39, 'fill_blank', '_____ (negotiate) well can save the company significant costs.', NULL, 'Negotiating', 'Negotiating 動名詞作主語。'),
(39, 'multiple_choice', '_____ new technologies early gives companies a competitive advantage.', '["Adopted","Adopt","Adopting","To adopt"]', 'Adopting', 'Adopting 動名詞作主語。'),
(39, 'multiple_choice', '_____ in professional development benefits both employees and the company.', '["Investing","Invested","Invest","To invest"]', 'Investing', 'Investing 動名詞作主語。'),
(39, 'multiple_choice', '_____ clearly and concisely is vital for business communication.', '["To write","Written","Writing","Write"]', 'Writing', 'Writing 動名詞作主語。'),
(39, 'fill_blank', '_____ (build) a strong network is essential for career growth.', NULL, 'Building', 'Building 動名詞作主語。'),
(39, 'multiple_choice', '_____ a global workforce requires cross-cultural competence.', '["To manage","Managed","Managing","Manage"]', 'Managing', 'Managing 動名詞作主語。'),
(39, 'multiple_choice', '_____ the market before entering reduces business risk.', '["Research","Researching","To research","Researched"]', 'Researching', 'Researching 動名詞作主語。'),
(39, 'transform', 'It takes skill to analyze complex data quickly. (Use gerund subject)', NULL, 'Analyzing complex data quickly takes considerable skill and experience.', 'Analyzing 動名詞作主語。'),
(39, 'fill_blank', '_____ (set) clear goals is the first step to project success.', NULL, 'Setting', 'Setting 動名詞作主語。'),
(39, 'multiple_choice', '_____ regularly with your team prevents miscommunication.', '["Met","To meet","Meeting","Meet"]', 'Meeting', 'Meeting 動名詞作主語。'),
(39, 'multiple_choice', '_____ to clients'' needs builds long-term business relationships.', '["Listening","To listen","Listen","Listened"]', 'Listening', 'Listening 動名詞作主語。'),
(39, 'fill_blank', '_____ (take) initiative is a quality we look for in all our employees.', NULL, 'Taking', 'Taking 動名詞作主語。'),
(39, 'multiple_choice', '_____ the company''s mission and values is expected of all staff.', '["To understand","Understand","Understanding","Understood"]', 'Understanding', 'Understanding 動名詞作主語。'),
(40, 'multiple_choice', 'She flew to Shanghai _____ meet the key supplier.', '["so as","for","to","in order"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'We hired a consultant _____ improve our operational efficiency.', '["for","at","to","in"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'He attended the seminar _____ network with industry leaders.', '["in order","to","for","so as"]', 'to', 'to + 原形動詞表目的。'),
(40, 'fill_blank', 'She called the client _____ (confirm) the order details.', NULL, 'to confirm', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'We use this platform _____ streamline communication across departments.', '["at","in","for","to"]', 'to', 'to + 原形表工具使用目的。'),
(40, 'multiple_choice', 'The company launched a new initiative _____ attract top talent.', '["in order to","for","so as","to"]', 'in order to', 'in order to 更正式的目的表達，也可用 to。'),
(40, 'multiple_choice', 'He took a finance course _____ better understand the balance sheet.', '["in","for","to","at"]', 'to', 'to + 原形動詞表目的。'),
(40, 'transform', 'We created the policy. The purpose was to prevent data breaches. (Use: in order to)', NULL, 'We created this policy in order to prevent data breaches.', 'in order to 更正式的目的不定詞。'),
(40, 'fill_blank', 'The team worked overtime _____ (meet) the project deadline.', NULL, 'to meet', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'She gave the client a discount _____ retain the business relationship.', '["so as","to","in order","for"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'We need _____ expand our market presence.', '["for","so as","in","to"]', 'to', 'need + to + 原形。'),
(40, 'multiple_choice', 'The CEO travelled to New York _____ sign the partnership agreement.', '["in","at","for","to"]', 'to', 'to + 原形動詞表目的。'),
(40, 'fill_blank', 'We streamlined our process _____ (reduce) operational costs.', NULL, 'to reduce', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'She took detailed notes _____ not forget any action items.', '["in order not to","so as not to","to not","not to"]', 'so as not to', 'so as not to 表負面目的（避免）。'),
(40, 'multiple_choice', 'The firm invested in R&D _____ develop innovative solutions.', '["in","for","at","to"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'He reviewed the proposal carefully _____ identify any weaknesses.', '["so as","for","in order to","to"]', 'in order to', 'in order to 更正式的目的不定詞。'),
(40, 'transform', 'We redesigned the website. The goal was to improve user experience. (Use: to)', NULL, 'We redesigned the website to improve the user experience.', 'to + 原形動詞表目的。'),
(40, 'fill_blank', 'She prepared a detailed handover document _____ (help) her successor.', NULL, 'to help', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'The company held focus groups _____ gather consumer feedback.', '["for","in","at","to"]', 'to', 'to + 原形動詞表目的。'),
(40, 'multiple_choice', 'We implemented the new system _____ reduce manual data entry.', '["for","to","in","at"]', 'to', 'to + 原形動詞表目的。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(41, 'multiple_choice', 'The manager asked the team _____ the report by noon.', '["to submit","submit","submitting","of submitting"]', 'to submit', 'ask + 人 + to do。'),
(41, 'multiple_choice', 'We want our employees _____ with clients professionally.', '["of communicating","communicate","communicating","to communicate"]', 'to communicate', 'want + 人 + to do。'),
(41, 'fill_blank', 'The director advised us _____ (reconsider) the pricing strategy.', NULL, 'to reconsider', 'advise + 人 + to do。'),
(41, 'multiple_choice', 'The company requires all staff _____ annual training.', '["complete","of completing","to complete","completing"]', 'to complete', 'require + 人 + to do。'),
(41, 'multiple_choice', 'She encouraged her team _____ new approaches.', '["to try","of trying","trying","try"]', 'to try', 'encourage + 人 + to do。'),
(41, 'multiple_choice', 'We expect all applicants _____ a portfolio.', '["submit","of submitting","submitting","to submit"]', 'to submit', 'expect + 人 + to do。'),
(41, 'multiple_choice', 'The policy allows employees _____ from home two days a week.', '["work","to work","of working","working"]', 'to work', 'allow + 人 + to do。'),
(41, 'transform', 'The CEO told us: manage the budget carefully. (Use: asked us to)', NULL, 'The CEO asked us to manage the budget more carefully.', 'ask + 人 + to do。'),
(41, 'multiple_choice', 'He hired a consultant _____ the marketing strategy.', '["to revise","of revising","revise","revising"]', 'to revise', 'hired someone to do 委託做某事。'),
(41, 'fill_blank', 'The board authorized the CFO _____ (sign) contracts up to $1 million.', NULL, 'to sign', 'authorize + 人 + to do 授權。'),
(41, 'multiple_choice', 'She invited the client _____ a factory tour.', '["of joining","join","joining","to join"]', 'to join', 'invite + 人 + to do。'),
(41, 'multiple_choice', 'The company trains staff _____ with the new software.', '["of working","to work","work","working"]', 'to work', 'trains someone to do 培訓做某事。'),
(41, 'multiple_choice', 'He persuaded the client _____ the extended warranty.', '["purchase","of purchasing","purchasing","to purchase"]', 'to purchase', 'persuade + 人 + to do。'),
(41, 'fill_blank', 'We need you _____ (confirm) your attendance by Friday.', NULL, 'to confirm', 'need + 人 + to do。'),
(41, 'multiple_choice', 'The supervisor told the intern _____ the filing system.', '["organize","to organize","of organizing","organizing"]', 'to organize', 'tell + 人 + to do。'),
(41, 'multiple_choice', 'They enabled the team _____ remotely during the crisis.', '["work","to work","working","of working"]', 'to work', 'enable + 人 + to do 使...能夠。'),
(41, 'transform', 'The client asked: please send us a detailed quotation. (Use: asked us to)', NULL, 'The client asked us to send them a detailed quotation.', 'ask + 人 + to do，注意代名詞調整。'),
(41, 'fill_blank', 'The manager reminded her _____ (submit) the expense claims.', NULL, 'to submit', 'remind + 人 + to do。'),
(41, 'multiple_choice', 'The firm appointed her _____ the new regional director.', '["of being","being","to be","be"]', 'to be', 'appoint + 人 + to be 任命為。'),
(41, 'multiple_choice', 'He helped the client _____ the right product.', '["to choose","choose","choosing","of choosing"]', 'to choose', 'help + 人 + to do（to 可省略）。'),
(42, 'multiple_choice', 'Our new system is _____ than the previous one.', '["faster","more fast","fast","more faster"]', 'faster', '單音節加 -er：faster。'),
(42, 'multiple_choice', 'This approach is _____ to implement than the original plan.', '["easiest","more easy","easier","most easy"]', 'easier', 'easy → easier，比較級。'),
(42, 'multiple_choice', 'The new model is _____ efficient than its predecessor.', '["very","most","much","more"]', 'more', '多音節用 more + 形容詞。'),
(42, 'fill_blank', 'Their customer service is _____ (good) than ours.', NULL, 'better', 'good → better 不規則比較級。'),
(42, 'multiple_choice', 'The situation is _____ than we initially expected.', '["more bad","more worse","worser","worse"]', 'worse', 'bad → worse 不規則比較級。'),
(42, 'multiple_choice', 'The revised proposal is _____ clear than the first version.', '["more clear","most clear","clearer","clearly"]', 'clearer', 'clear → clearer，單音節加 -er。'),
(42, 'multiple_choice', 'Processing times are _____ with the new software.', '["shortest","most short","more short","shorter"]', 'shorter', 'short → shorter 比較級。'),
(42, 'transform', 'Version 2 is not as effective as version 1. (Use: less effective)', NULL, 'Version 2 is less effective than version 1.', 'less + 形容詞表劣於比較。'),
(42, 'multiple_choice', 'She is a _____ communicator than her predecessor.', '["most good","better","more good","gooder"]', 'better', 'good → better 不規則比較級。'),
(42, 'fill_blank', 'This solution is _____ (cost-effective) than the alternatives.', NULL, 'more cost-effective', '多音節形容詞 more + cost-effective。'),
(42, 'multiple_choice', 'The new office is _____ accessible to public transport.', '["very","much","more","most"]', 'more', 'more accessible 多音節比較級。'),
(42, 'multiple_choice', 'Working conditions are _____ than they were five years ago.', '["much good","more better","much more better","much better"]', 'much better', 'much 可加強比較級，good → better。'),
(42, 'multiple_choice', 'Our Q3 results were _____ than Q2.', '["strongly","more strong","most strong","stronger"]', 'stronger', 'strong → stronger 比較級。'),
(42, 'transform', 'Outsourcing is cheaper. In-house is more reliable. (Use: cheaper than)', NULL, 'Outsourcing is cheaper than in-house, but in-house is more reliable.', 'cheaper than 比較兩種選項。'),
(42, 'fill_blank', 'This model is _____ (efficient) and _____ (affordable) than the old one.', NULL, 'more efficient / more affordable', '多音節形容詞加 more。'),
(42, 'multiple_choice', 'This quarter''s performance is _____ than last year''s.', '["much far good","farther good","far better","more far better"]', 'far better', 'far better 用 far 加強比較級。'),
(42, 'multiple_choice', 'The process became _____ as we automated more tasks.', '["most smooth","smoother","smoothly","more smooth"]', 'smoother', 'smooth → smoother 比較級。'),
(42, 'multiple_choice', 'This is a _____ approach to solving the problem.', '["innovativer","more innovative","much innovative","most innovative"]', 'more innovative', 'innovative 多音節，more innovative。'),
(42, 'fill_blank', 'The new hire is _____ (experienced) than we expected.', NULL, 'more experienced', 'experienced 多音節，more experienced。'),
(42, 'multiple_choice', 'His proposal is _____ than hers in terms of feasibility.', '["more realistic","realisticker","much realistic","most realistic"]', 'more realistic', 'realistic 多音節，more realistic。'),
(43, 'multiple_choice', 'This is _____ proposal we have received.', '["the better","the best","better","the most good"]', 'the best', 'good → the best 最高級。'),
(43, 'multiple_choice', 'Our Q4 was _____ quarter in the company''s history.', '["most profitable","the profitablest","the most profitable","more profitable"]', 'the most profitable', 'profitable 多音節，the most profitable。'),
(43, 'multiple_choice', 'She is _____ candidate for this role.', '["the qualifiedest","most qualified","the most qualified","more qualified"]', 'the most qualified', 'qualified 多音節，the most qualified。'),
(43, 'fill_blank', 'This was _____ (bad) product launch we''ve ever experienced.', NULL, 'the worst', 'bad → the worst 不規則最高級。'),
(43, 'multiple_choice', 'The new software is _____ option available.', '["most cheap","the cheapest","cheaper","cheapest"]', 'the cheapest', 'cheap → the cheapest，最高級前加 the。'),
(43, 'multiple_choice', 'This deal represents _____ opportunity we have seen this year.', '["the most great","more great","the greatest","greatest"]', 'the greatest', 'great → the greatest。'),
(43, 'multiple_choice', 'That was _____ presentation I have ever attended.', '["more inspiring","the most inspiring","the most inspired","the inspiringest"]', 'the most inspiring', 'inspiring 多音節，the most inspiring。'),
(43, 'transform', 'No other quarter performed better than Q3. (Use: best)', NULL, 'Q3 was our best-performing quarter of the year.', 'the best 最高級。'),
(43, 'multiple_choice', 'He is _____ salesperson on our team.', '["the most productive","the productivest","more productive","most productive"]', 'the most productive', 'productive 多音節，the most productive。'),
(43, 'fill_blank', 'This is _____ (far) we have ever expanded geographically.', NULL, 'the furthest/farthest', 'far → the furthest/farthest 最高級。');