INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(43, 'multiple_choice', 'The first approach is _____ of all the options presented.', '["least expensive","less expensive","the most cheapest","the least expensive"]', 'the least expensive', 'the least expensive 最低程度最高級。'),
(43, 'multiple_choice', 'She achieved _____ results in the department.', '["higher","highest","the highest","most high"]', 'the highest', 'high → the highest，最高級前 the。'),
(43, 'multiple_choice', 'This has been _____ challenging project I have managed.', '["more","the better","the most","a most"]', 'the most', 'the most + challenging，多音節最高級。'),
(43, 'transform', 'No solution is simpler than option A. (Use: simplest)', NULL, 'Option A is the simplest solution available.', 'the simplest 最高級。'),
(43, 'fill_blank', 'He is one of _____ (experienced) managers in the industry.', NULL, 'the most experienced', 'one of the most + 形容詞最高級。'),
(43, 'multiple_choice', 'The Tokyo branch is performing _____ of all our offices.', '["better","the most good","the best","much good"]', 'the best', 'best 副詞最高級，表現最好。'),
(43, 'multiple_choice', 'This was _____ decision we could have made.', '["more bad","badder","the most bad","the worst"]', 'the worst', 'bad → the worst 最高級。'),
(43, 'multiple_choice', 'He is _____ analyst on the team in terms of accuracy.', '["the precisest","the most precise","more precise","most precise"]', 'the most precise', 'precise 多音節，the most precise。'),
(43, 'fill_blank', 'This strategy gave us _____ (high) return on investment.', NULL, 'the highest', 'high → the highest，最高級。'),
(43, 'multiple_choice', 'That client has been _____ loyal partner since the beginning.', '["a most","our best","our most","the more"]', 'our most', 'our most loyal 限定詞 + 最高級。'),
(44, 'multiple_choice', 'Our new product is _____ reliable _____ the competitor''s.', '["as / as","more / as","so / as","as / than"]', 'as / as', 'as...as 表兩者相等。'),
(44, 'multiple_choice', 'The delivery was not _____ fast _____ we had expected.', '["as / as","so / as","more / as","as / than"]', 'as / as', 'not as...as 表不如預期。'),
(44, 'multiple_choice', 'This branch is performing just _____ well _____ last year.', '["so / as","as / than","as / as","more / as"]', 'as / as', 'just as...as 強調完全相等。'),
(44, 'fill_blank', 'Our costs are twice _____ high _____ our competitors''.', NULL, 'as / as', 'twice as...as 表兩倍關係。'),
(44, 'multiple_choice', 'She works just _____ hard _____ anyone else on the team.', '["so / as","more / as","as / than","as / as"]', 'as / as', 'just as...as 完全相等。'),
(44, 'multiple_choice', 'Is this model _____ durable _____ the previous one?', '["so / as","more / as","as / as","as / than"]', 'as / as', 'as...as 疑問句比較。'),
(44, 'multiple_choice', 'The results weren''t _____ impressive _____ expected.', '["so / as","as / than","more / as","as / as"]', 'as / as', 'not as...as 表低於預期。'),
(44, 'transform', 'Revenues are equal this year and last year. (Use: as high as)', NULL, 'Revenues this year are as high as last year''s.', 'as...as 表數量相等。'),
(44, 'multiple_choice', 'The new platform is _____ efficient _____ the old one.', '["more / as","as much / than","as / as twice","twice as / as"]', 'twice as / as', 'twice as...as 兩倍效率。'),
(44, 'fill_blank', 'Their pricing is _____ competitive _____ ours.', NULL, 'not as / as', 'not as...as 表劣勢比較。'),
(44, 'multiple_choice', 'This report is _____ detailed _____ the one last quarter.', '["more / as","so / as","as / than","as / as"]', 'as / as', 'as...as 兩份報告同等詳細。'),
(44, 'multiple_choice', 'She speaks _____ clearly _____ any senior manager.', '["more / as","as / than","as / as","so / as"]', 'as / as', '副詞用 as...as。'),
(44, 'multiple_choice', 'The client isn''t _____ demanding _____ we thought.', '["more / as","as / as","so / as","as / than"]', 'as / as', 'not as...as 表不如預期。'),
(44, 'transform', 'Profits in Q1 equal profits in Q2. (Use: as high as)', NULL, 'Q1 profits were as high as Q2 profits.', 'as...as 數量相等。'),
(44, 'fill_blank', 'Our service is _____ reliable _____ our top competitor''s.', NULL, 'as / as', 'as...as 表相等。'),
(44, 'multiple_choice', 'This proposal is _____ comprehensive _____ the other one.', '["not so / than","less / than","so / as","not as / as"]', 'not as / as', 'not as...as 表較不全面。'),
(44, 'multiple_choice', 'The new hire is _____ experienced _____ the rest of the team.', '["as / as","as / than","more / as","so / as"]', 'as / as', 'as...as 相等經驗。'),
(44, 'fill_blank', 'Working remotely can be _____ productive _____ working in the office.', NULL, 'as / as', 'as...as 表相等生產力。'),
(44, 'multiple_choice', 'The interest rate is _____ high _____ it was last year.', '["so / as","as / than","not as / as","less / than"]', 'not as / as', 'not as...as 表較低。'),
(44, 'multiple_choice', 'This software is _____ user-friendly _____ its predecessor.', '["three times as / as","times as / as","as / so","more / as"]', 'three times as / as', 'three times as...as 三倍用法。'),
(45, 'multiple_choice', '_____ we invest in training, _____ our team performs.', '["More / better","The more / the more better","The most / the best","The more / the better"]', 'The more / the better', 'The more...the better 雙重比較。'),
(45, 'multiple_choice', '_____ the deadline, _____ the team works.', '["The most close / the hardest","Closer / harder","More close / more hard","The closer / the harder"]', 'The closer / the harder', 'The closer...the harder 雙重比較。'),
(45, 'fill_blank', '_____ clients we retain, _____ our revenue grows. (Use double comparative)', NULL, 'The more / the more', 'The more...the more 正比關係。'),
(45, 'multiple_choice', '_____ the team communicates, _____ the project runs.', '["Most frequently / most smoothly","More frequently / more smooth","The frequently / the smooth","The more frequently / the more smoothly"]', 'The more frequently / the more smoothly', 'the + 比較副詞的雙重比較。'),
(45, 'multiple_choice', '_____ data we have, _____ informed our decisions.', '["More / most","More / more","The more / the more","The most / the most"]', 'The more / the more', 'The more data...the more informed 雙重比較。'),
(45, 'multiple_choice', '_____ we delay, _____ it will cost.', '["The longest / the most","Longer / more","The more long / the more much","The longer / the more"]', 'The longer / the more', 'The longer...the more 時間與費用的反比。'),
(45, 'transform', 'If we expand faster, we get better economies of scale. (Use double comparative)', NULL, 'The faster we expand, the greater the economies of scale we achieve.', 'The faster...the greater 雙重比較。'),
(45, 'fill_blank', '_____ transparent our reporting, _____ investors trust us. (Use double comparative)', NULL, 'The more / the more', 'The more transparent...the more trust 雙重比較。'),
(45, 'multiple_choice', '_____ the team''s morale, _____ their performance.', '["The higher / the better","Higher / better","High / good","The most high / the best"]', 'The higher / the better', 'The higher...the better 雙重比較。'),
(45, 'multiple_choice', '_____ we automate, _____ time we save.', '["Most / more","The more / the more","The most / most","More / more"]', 'The more / the more', 'The more...the more 自動化與時間節省的正比。'),
(45, 'multiple_choice', '_____ complex the deal, _____ time it takes to close.', '["The more / the more","The most / most","More / more","Most / the most"]', 'The more / the more', 'The more complex...the more time 雙重比較。'),
(45, 'fill_blank', '_____ quickly we resolve the issue, _____ the client will be. (Use double comparative)', NULL, 'The more / the happier', 'The more quickly...the happier 雙重比較。'),
(45, 'multiple_choice', '_____ employees we hire, _____ our training costs.', '["The most / highest","Most / more high","The more / the higher","More / higher"]', 'The more / the higher', 'The more...the higher 雙重比較。'),
(45, 'transform', 'Strong branding leads to higher customer loyalty. (Use double comparative)', NULL, 'The stronger the brand, the higher the customer loyalty.', 'The stronger...the higher 雙重比較。'),
(45, 'multiple_choice', '_____ we focus on quality, _____ our reputation becomes.', '["Most / more strong","More / stronger","The more / the stronger","The most / strongest"]', 'The more / the stronger', 'The more...the stronger 品質與聲譽的關係。'),
(45, 'fill_blank', '_____ diversified the portfolio, _____ the risk. (Use double comparative)', NULL, 'The more / the lower', 'The more diversified...the lower the risk 雙重比較。'),
(45, 'multiple_choice', '_____ innovative the product, _____ it captures the market.', '["More / faster","The more / the faster","Most / more fast","The most / fastest"]', 'The more / the faster', 'The more innovative...the faster market capture。'),
(45, 'multiple_choice', '_____ clear our strategy, _____ aligned the team will be.', '["The most / most","Much / more","The more / the more","More / more"]', 'The more / the more', 'The more clear...the more aligned 雙重比較。'),
(45, 'transform', 'Faster decisions produce better results. (Use double comparative)', NULL, 'The faster we make decisions, the better the results will be.', 'The faster...the better 雙重比較。'),
(45, 'fill_blank', '_____ data-driven our approach, _____ accurate our forecasts. (Use double comparative)', NULL, 'The more / the more', 'The more data-driven...the more accurate 雙重比較。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(46, 'multiple_choice', '_____ the contract is signed, we can begin the project.', '["While","Until","Once","As soon as"]', 'Once', 'Once 表一旦...就，同 as soon as。'),
(46, 'multiple_choice', 'Please notify me _____ the client arrives.', '["before","as soon as","while","until"]', 'as soon as', 'as soon as 表一到達就立即通知。'),
(46, 'multiple_choice', 'She will stay in the office _____ the report is finished.', '["before","while","until","when"]', 'until', 'until 表持續到某事完成為止。'),
(46, 'fill_blank', '_____ (finish) the presentation, we will take questions.', NULL, 'After finishing / When we finish', 'after + V-ing 或 when + clause。'),
(46, 'multiple_choice', 'He checks his emails _____ he commutes to work.', '["once","until","while","before"]', 'while', 'while 表同時進行的動作。'),
(46, 'multiple_choice', 'We need to finalize the budget _____ the board meeting.', '["until","when","before","after"]', 'before', 'before the board meeting 截止時間。'),
(46, 'transform', 'The meeting ends. Then we will announce the results. (Use: after)', NULL, 'After the meeting ends, we will announce the results.', 'after + 時間子句。'),
(46, 'fill_blank', '_____ (submit) your application, please read all the requirements.', NULL, 'Before submitting', 'before + V-ing 提交前注意事項。'),
(46, 'multiple_choice', 'Sales increased significantly _____ the new campaign was launched.', '["before","after","while","until"]', 'after', 'after the campaign was launched 描述因果和時間。'),
(46, 'multiple_choice', 'By the time the CEO arrived, the team _____ already started.', '["had","have","was","has"]', 'had', 'by the time + 現在式，主句過去完成式。'),
(46, 'multiple_choice', '_____ working with international clients, she developed strong language skills.', '["While","Before","Until","Once"]', 'While', 'while + V-ing 表同時進行的情況。'),
(46, 'fill_blank', 'We cannot proceed _____ we receive the signed contract.', NULL, 'until', 'until 表等到...才能進行。'),
(46, 'multiple_choice', 'She always reviews the agenda _____ she enters the meeting room.', '["after","before","while","until"]', 'before', 'before 表進場前先做的事。'),
(46, 'multiple_choice', 'The problem was resolved _____ it escalated further.', '["when","before","until","after"]', 'before', 'before it escalated 提前解決。'),
(46, 'transform', 'The training finishes. We will assign team roles. (Use: when)', NULL, 'When the training finishes, we will assign everyone their team roles.', 'when + 現在式（表未來），will 主句。'),
(46, 'fill_blank', 'We had completed the onboarding _____ the new hire started.', NULL, 'before', 'before the new hire started，時間先後關係。'),
(46, 'multiple_choice', '_____ the audit is complete, the results will be shared with all departments.', '["Once","Before","Until","While"]', 'Once', 'Once the audit is complete 表完成後。'),
(46, 'multiple_choice', 'She takes notes _____ the client is speaking.', '["until","after","before","while"]', 'while', 'while 表同時進行。'),
(46, 'multiple_choice', 'The deal was announced _____ both sides had agreed on all terms.', '["after","before","while","until"]', 'after', 'after both sides agreed 強調先後。'),
(46, 'multiple_choice', 'He will work on this project _____ he transfers to the new position.', '["until","when","before","after"]', 'until', 'until he transfers 持續到調職為止。'),
(47, 'multiple_choice', '_____ the deadline was extended, we have more time to review.', '["Since","Despite","Although","Because of"]', 'Since', 'since/because 引導原因子句。'),
(47, 'multiple_choice', 'We had to cancel the event _____ low attendance.', '["because of","since","now that","as"]', 'because of', 'because of + 名詞短語（非子句）表原因。'),
(47, 'multiple_choice', 'She was promoted _____ she consistently exceeded her targets.', '["however","because","although","despite"]', 'because', 'because 引導原因子句。'),
(47, 'fill_blank', '_____ the market has stabilized, we can proceed with the investment.', NULL, 'Now that', 'now that 表現在情況改變，因此...。'),
(47, 'multiple_choice', '_____ the project was behind schedule, additional resources were allocated.', '["As","Despite","Although","However"]', 'As', 'as 引導原因子句，較正式。'),
(47, 'multiple_choice', 'We need to act quickly _____ our competitors are already ahead.', '["however","because","although","despite"]', 'because', 'because 引導原因子句。'),
(47, 'multiple_choice', 'He was unable to attend the meeting _____ a prior commitment.', '["as","due to","because","since"]', 'due to', 'due to + 名詞短語（非子句）表原因，正式用法。'),
(47, 'transform', 'The project failed. The reason was poor communication. (Use: because)', NULL, 'The project failed because of poor communication among the teams.', 'because of + 名詞短語。'),
(47, 'fill_blank', '_____ the economy is recovering, consumer confidence is rising.', NULL, 'As / Since', 'as 或 since 引導原因子句。'),
(47, 'multiple_choice', '_____ he had the most experience, he was chosen to lead the negotiation.', '["Despite","However","Since","Although"]', 'Since', 'since 引導原因子句，用於說明已知原因。'),
(47, 'multiple_choice', 'The order was delayed _____ a production error.', '["since","owing to","because","as"]', 'owing to', 'owing to + 名詞短語，正式原因表達。'),
(47, 'multiple_choice', '_____ the new policy was implemented, employee satisfaction has improved.', '["Because of","Now that","Although","Since"]', 'Now that', 'now that 表現在的新情況導致的結果。'),
(47, 'fill_blank', 'She was given extra responsibility _____ she had proven herself reliable.', NULL, 'because / since', 'because 或 since 引導原因子句。'),
(47, 'multiple_choice', 'The meeting was rescheduled _____ the CEO was travelling.', '["however","despite","although","as"]', 'as', 'as 引導原因子句，較正式。'),
(47, 'multiple_choice', 'We lost the contract _____ our pricing was not competitive.', '["despite","although","however","because"]', 'because', 'because 引導原因子句。'),
(47, 'transform', 'The branch closed. There was insufficient demand. (Use: due to)', NULL, 'The branch was closed due to insufficient demand in the local market.', 'due to + 名詞短語表原因。'),
(47, 'fill_blank', '_____ (because) bad weather, the outdoor event was moved indoors.', NULL, 'Because of / Due to', 'because of / due to + 名詞短語。'),
(47, 'multiple_choice', 'She left the firm early _____ a family emergency.', '["since","because of","as","now that"]', 'because of', 'because of + 名詞短語。'),
(47, 'multiple_choice', '_____ sales are declining, we must reassess our strategy.', '["However","Despite","Although","As"]', 'As', 'as 引導原因子句。'),
(47, 'multiple_choice', 'The contract was terminated _____ breach of terms.', '["since","as","because","due to"]', 'due to', 'due to 正式書面原因表達。'),
(48, 'multiple_choice', '_____ the budget was limited, the project was completed on time.', '["Although","Since","While","Because"]', 'Although', 'although 引導讓步子句。'),
(48, 'multiple_choice', 'Sales increased _____ we reduced our marketing spend.', '["although","even though","while","because"]', 'even though', 'even though 強調更大的讓步（減少行銷費用仍增加）。'),
(48, 'multiple_choice', 'Our product is more expensive _____ it offers greater value.', '["despite","however","although","but"]', 'but', 'but 連接對比子句（並列）。'),
(48, 'fill_blank', '_____ (although) the proposal was rejected, we learned from the experience.', NULL, 'Although / Even though', 'although/even though 引導讓步子句。'),
(48, 'multiple_choice', '_____ our team is small, we consistently deliver high-quality results.', '["Although","Despite","However","Whereas"]', 'Whereas', 'whereas 也可引導對比（此處也可用 Although）。'),
(48, 'multiple_choice', 'The market is recovering _____ some sectors are still struggling.', '["while","since","although","because"]', 'while', 'while 表兩種情況的對比。'),
(48, 'multiple_choice', 'She accepted the offer _____ the salary was lower than expected.', '["because","even though","since","while"]', 'even though', 'even though 強調讓步。'),
(48, 'transform', 'We increased output. At the same time, we reduced defects. (Use: while)', NULL, 'While we increased output, we also managed to reduce defects.', 'while 表同時對比或並列情況。'),
(48, 'fill_blank', '_____ having limited resources, the team delivered excellent results.', NULL, 'Despite', 'despite + V-ing 讓步表達。'),
(48, 'multiple_choice', 'The demand for our product is high _____ the price increase.', '["even though","despite","while","although"]', 'despite', 'despite + 名詞短語（非子句）。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(48, 'multiple_choice', '_____ the economic downturn, our company remained profitable.', '["Despite","Even though","While","Although"]', 'Despite', 'despite + 名詞短語。'),
(48, 'multiple_choice', 'The new system is faster _____ it requires more training.', '["since","while","because","although"]', 'although', 'although 引導對比子句。'),
(48, 'fill_blank', '_____ (although) the conditions were challenging, the team exceeded targets.', NULL, 'Although / Even though', '讓步子句。'),
(48, 'multiple_choice', 'Customer satisfaction improved _____ there were some complaints.', '["since","even though","because","while"]', 'even though', 'even though 強調讓步。'),
(48, 'multiple_choice', 'Their prices are higher _____ ours.', '["although","than","while","however"]', 'than', 'than 比較，注意此處不是對比子句。'),
(48, 'transform', 'We faced many challenges. However, we achieved our goals. (Use: although)', NULL, 'Although we faced many challenges, we still achieved our goals.', 'although 讓步子句。'),
(48, 'multiple_choice', '_____ the merger was risky, the board approved it unanimously.', '["While","Although","Because","Since"]', 'Although', 'although 引導讓步子句。'),
(48, 'fill_blank', 'Sales rose in Asia _____ they fell in Europe.', NULL, 'while / whereas', 'while/whereas 表兩個對比事實。'),
(48, 'multiple_choice', 'He is very skilled _____ sometimes lacks attention to detail.', '["while","since","although","because"]', 'although', 'although 引導讓步子句。'),
(48, 'multiple_choice', '_____ the challenges we faced, the project was a success.', '["Even though","While","Despite","Although"]', 'Despite', 'despite + 名詞短語。'),
(49, 'multiple_choice', 'The data was _____ complex _____ the team needed extra time to analyse it.', '["so / which","such / that","so / that","such / which"]', 'so / that', 'so + 形容詞 + that 結果子句。'),
(49, 'multiple_choice', 'It was _____ a successful campaign _____ we repeated it the following year.', '["so a / that","such / that","so / that","such a / which"]', 'such / that', 'such a + 名詞 + that 結果子句。'),
(49, 'multiple_choice', 'The proposal was _____ well written _____ it was immediately approved.', '["such / that","such / which","so / that","so / which"]', 'so / that', 'so + 副詞 + that。'),
(49, 'fill_blank', 'The traffic was _____ bad _____ she missed the beginning of the meeting.', NULL, 'so / that', 'so + 形容詞 + that 結果子句。'),
(49, 'multiple_choice', 'They made _____ many mistakes _____ the contract had to be rewritten.', '["so / which","so / that","such / that","such / which"]', 'so / that', 'so many + 名詞 + that 結果子句。'),
(49, 'multiple_choice', 'There was _____ a high demand _____ production could not keep up.', '["so a / that","such / that","such / which","so / that"]', 'such / that', 'such + 冠詞 + 名詞 + that。'),
(49, 'multiple_choice', 'The client was _____ impressed _____ she recommended us to three other companies.', '["such / which","so / that","such / that","so / which"]', 'so / that', 'so + 形容詞 + that 結果子句。'),
(49, 'transform', 'The presentation was very long. Nobody could stay focused. (Use: so long that)', NULL, 'The presentation was so long that nobody could stay focused.', 'so + 形容詞 + that 結果子句。'),
(49, 'fill_blank', 'It was _____ an innovative idea _____ the board immediately approved the funding.', NULL, 'such / that', 'such a/an + 名詞 + that 結果子句。'),
(49, 'multiple_choice', 'He spoke _____ clearly _____ everyone understood the strategy perfectly.', '["such / that","so / that","such / which","so / which"]', 'so / that', 'so + 副詞 + that 結果子句。'),
(49, 'multiple_choice', 'There was _____ little time left _____ we had to postpone the launch.', '["so much / that","so / that","such / that","such much / that"]', 'so / that', 'so little + 不可數名詞 + that。'),
(49, 'multiple_choice', 'The results were _____ positive _____ we decided to scale up immediately.', '["such / which","so / that","so / which","such / that"]', 'so / that', 'so + 形容詞 + that。'),
(49, 'fill_blank', 'She worked _____ hard _____ she was promoted within six months.', NULL, 'so / that', 'so + 副詞 + that。'),
(49, 'multiple_choice', 'It was _____ a tight deadline _____ the team worked through the weekend.', '["such / that","such / which","so / that","so a / that"]', 'such / that', 'such a + 名詞 + that。'),
(49, 'multiple_choice', 'The savings were _____ significant _____ the project paid for itself in one year.', '["so / that","so / which","such / that","such / which"]', 'so / that', 'so + 形容詞 + that。'),
(49, 'transform', 'The report had many errors. It had to be completely rewritten. (Use: so many)', NULL, 'The report had so many errors that it had to be completely rewritten.', 'so many + 名詞 + that。'),
(49, 'fill_blank', 'She was _____ knowledgeable _____ everyone came to her for advice.', NULL, 'so / that', 'so + 形容詞 + that。'),
(49, 'multiple_choice', 'There were _____ few applicants _____ the position remained unfilled.', '["such / which","such few / that","so / that","such / that"]', 'so / that', 'so few + 名詞 + that。'),
(49, 'multiple_choice', 'The product launch was _____ a success _____ supply ran out within days.', '["such / that","so / that","so a / that","such / which"]', 'such / that', 'such a + 名詞 + that。'),
(49, 'multiple_choice', 'He presented the plan _____ persuasively _____ the investors agreed immediately.', '["so / which","such / that","such / which","so / that"]', 'so / that', 'so + 副詞 + that。'),
(50, 'multiple_choice', 'The client mentioned _____ the delivery timeline was too long.', '["how","which","that","what"]', 'that', 'that 引導受語名詞子句。'),
(50, 'multiple_choice', 'We need to understand _____ the customer really wants.', '["how","which","that","what"]', 'what', 'what 引導名詞子句，表「什麼」。'),
(50, 'multiple_choice', '_____ the merger will succeed depends on many factors.', '["What","Whether","If","That"]', 'Whether', 'whether 引導主語名詞子句，表是否。'),
(50, 'fill_blank', 'The report shows _____ revenue has increased by 15%.', NULL, 'that', 'that 引導受語名詞子句。'),
(50, 'multiple_choice', 'She asked _____ we could reduce the price.', '["which","what","whether","that"]', 'whether', 'whether 引導間接是否問句（名詞子句）。'),
(50, 'multiple_choice', 'The key issue is _____ we can maintain quality while reducing costs.', '["how","what","whether","that"]', 'whether', 'whether 作補語名詞子句。'),
(50, 'multiple_choice', 'Do you know _____ the meeting is scheduled for today?', '["if","that","what","whether"]', 'whether', 'whether 引導名詞子句，較 if 正式。'),
(50, 'transform', 'The team discussed the timeline. They wanted to know if it was realistic. (Use: whether)', NULL, 'The team discussed whether the timeline was realistic.', 'whether 名詞子句作受語。'),
(50, 'multiple_choice', 'I understand _____ you are concerned about the budget.', '["how","which","that","what"]', 'that', 'that 引導受語名詞子句，表達理解。'),
(50, 'fill_blank', 'The CEO announced _____ the company would expand into three new markets.', NULL, 'that', 'that 引導受語名詞子句（宣布）。'),
(50, 'multiple_choice', '_____ he managed to close the deal was impressive.', '["That","What","Which","How"]', 'How', 'how 引導主語名詞子句，表示方式。'),
(50, 'multiple_choice', 'They are still debating _____ to outsource the work.', '["whether","that","what","how"]', 'whether', 'whether to do 引導名詞子句。'),
(50, 'multiple_choice', 'The manager explained _____ the new process works.', '["that","which","how","what"]', 'how', 'how 引導名詞子句表方式。'),
(50, 'transform', 'He wanted to know the reason for the delay. (Use: why the project was delayed)', NULL, 'He wanted to know why the project had been delayed.', 'why 引導名詞子句作受語。'),
(50, 'fill_blank', 'It is important _____ all team members attend the briefing.', NULL, 'that', 'It is important that + 名詞子句。'),
(50, 'multiple_choice', '_____ the project will be completed by Q3 is not yet confirmed.', '["What","Whether","That","If"]', 'Whether', 'whether 引導主語名詞子句。'),
(50, 'multiple_choice', 'We need to determine _____ the project is still viable.', '["whether","that","how","what"]', 'whether', 'whether 引導受語名詞子句（判斷是否）。'),
(50, 'multiple_choice', 'The fact _____ sales are declining concerns the board.', '["how","that","which","what"]', 'that', 'the fact that 固定搭配引導名詞子句。'),
(50, 'fill_blank', 'I believe _____ we can still meet the deadline with extra resources.', NULL, 'that', 'believe + that 名詞子句。'),
(50, 'multiple_choice', 'Please confirm _____ you will be attending the annual summit.', '["that","what","whether","if"]', 'whether', 'confirm whether 確認是否，正式用法。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(51, 'multiple_choice', 'We increased our budget, _____ the results exceeded expectations.', '["but","and","for","so"]', 'and', 'and 增加並列資訊。'),
(51, 'multiple_choice', 'The proposal was thorough, _____ the client rejected it.', '["and","but","for","so"]', 'but', 'but 表對比轉折。'),
(51, 'multiple_choice', 'Sales were strong, _____ we decided to expand.', '["for","but","so","and"]', 'so', 'so 表結果。'),
(51, 'multiple_choice', 'We can meet on Monday _____ Wednesday.', '["but","or","and","nor"]', 'or', 'or 表選擇。'),
(51, 'fill_blank', 'The product was innovative, _____ it failed to meet safety standards.', NULL, 'yet', 'yet 表意外的轉折，同 but（但更書面）。'),
(51, 'multiple_choice', 'She is experienced in marketing, _____ is she in sales.', '["but","nor","and","or"]', 'nor', 'neither... nor，nor 引導倒裝句。'),
(51, 'multiple_choice', 'We hired more staff, _____ we still can''t meet demand.', '["but","and","yet","so"]', 'yet', 'yet 表出乎意料的轉折。'),
(51, 'multiple_choice', 'He presented the data, _____ the board approved the plan.', '["and","so","but","for"]', 'and', 'and 表順序敘述。'),
(51, 'transform', 'We reduced costs. Therefore we increased profits. (Use: so)', NULL, 'We reduced costs, so we were able to increase profits.', 'so 連接兩個對等子句表結果。'),
(51, 'fill_blank', 'You can email me _____ call me — whichever is more convenient.', NULL, 'or', 'or 表兩個選擇。'),
(51, 'multiple_choice', 'The office is small, _____ the team is very productive.', '["but","and","so","yet"]', 'yet', 'yet 表意外對比（雖然...但）。'),
(51, 'multiple_choice', 'She is the team lead, _____ she has final say on all decisions.', '["so","for","but","and"]', 'so', 'so 表結果或因此。'),
(51, 'multiple_choice', 'We need to cut costs _____ maintain quality.', '["but","and","so","or"]', 'but', 'but 表兩者並列的張力（既要...又要）。'),
(51, 'transform', 'The deadline passed. However, the work was not finished. (Use: but)', NULL, 'The deadline passed, but the work was still not finished.', 'but 表轉折對比。'),
(51, 'fill_blank', 'We can outsource the project _____ handle it in-house.', NULL, 'or', 'or 表選擇。'),
(51, 'multiple_choice', 'She worked hard, _____ she earned the promotion.', '["but","so","and","for"]', 'so', 'so 表結果。'),
(51, 'multiple_choice', 'The team completed the audit _____ submitted the report on the same day.', '["so","but","or","and"]', 'and', 'and 連接兩個動作。'),
(51, 'multiple_choice', 'He is detail-oriented, _____ his team relies on him for accuracy.', '["for","so","but","and"]', 'so', 'so 表結果或原因（較口語）。'),
(51, 'fill_blank', 'We don''t have enough staff, _____ we need to outsource.', NULL, 'so', 'so 連接對等子句表結果。'),
(51, 'multiple_choice', 'The project was risky, _____ the potential returns were worth it.', '["for","but","and","so"]', 'but', 'but 表轉折讓步。'),
(52, 'multiple_choice', 'We will proceed _____ we receive written approval.', '["once","despite","because","although"]', 'once', 'once 表一旦...就，條件性時間。'),
(52, 'multiple_choice', '_____ the budget was approved, the project began immediately.', '["As soon as","Unless","Because of","Although"]', 'As soon as', 'as soon as 表一旦批准就開始。'),
(52, 'multiple_choice', 'She won the contract _____ her proposal was the most detailed.', '["although","because","unless","while"]', 'because', 'because 引導原因子句。'),
(52, 'fill_blank', '_____ the terms are acceptable, we will sign the contract next week.', NULL, 'If / Once / Provided that', '條件從屬連接詞。'),
(52, 'multiple_choice', 'We will miss the deadline _____ we hire more staff immediately.', '["although","if","because","unless"]', 'unless', 'unless = if not，表除非。'),
(52, 'multiple_choice', '_____ the price increases, customer demand may decrease.', '["If","Although","While","Because"]', 'If', 'if 引導條件子句。'),
(52, 'multiple_choice', 'The deal was secured _____ it took longer than expected.', '["because","since","while","although"]', 'although', 'although 引導讓步子句。'),
(52, 'transform', 'Provided the team works overtime, we can deliver on time. (Use: if)', NULL, 'If the team works overtime, we can deliver the project on time.', 'if 條件子句。'),
(52, 'fill_blank', 'She will accept the position _____ the relocation package is included.', NULL, 'provided that / if', 'provided that = if，條件。'),
(52, 'multiple_choice', '_____ he was new to the role, he handled the project remarkably well.', '["Although","While","Because","Since"]', 'Although', 'although 引導讓步子句。'),
(52, 'multiple_choice', 'The system crashed _____ the software was not properly updated.', '["although","because","while","unless"]', 'because', 'because 引導原因子句。'),
(52, 'multiple_choice', 'We cannot proceed _____ all stakeholders have signed off.', '["because","although","unless","until"]', 'until', 'until 表持續等到...才能進行。'),
(52, 'fill_blank', '_____ we invest in technology, we will fall behind competitors.', NULL, 'Unless', 'unless 表除非投資，否則就落後。'),
(52, 'multiple_choice', 'The report was delayed _____ technical difficulties.', '["unless","due to","although","despite"]', 'due to', 'due to + 名詞短語。'),
(52, 'multiple_choice', 'Sales improved _____ the team adopted a new approach.', '["unless","after","although","because"]', 'after', 'after 引導時間子句。'),
(52, 'transform', 'He didn''t attend training. As a result, he wasn''t promoted. (Use: because)', NULL, 'He wasn''t promoted because he hadn''t attended the required training.', 'because 引導原因子句。'),
(52, 'fill_blank', '_____ all conditions are met, the contract will be finalized.', NULL, 'Once / When / Provided that', '條件性從屬連接詞。'),
(52, 'multiple_choice', '_____ the market improves, we will reassess our expansion plans.', '["When","Although","Despite","Unless"]', 'When', 'when 引導時間/條件子句。'),
(52, 'multiple_choice', 'She will lead the project _____ she receives the necessary approvals.', '["unless","because","once","although"]', 'once', 'once 表一旦獲批就...。'),
(52, 'multiple_choice', '_____ the initial cost is high, the long-term benefits are clear.', '["While","Because","Since","Although"]', 'Although', 'although 引導讓步子句。'),
(53, 'multiple_choice', '_____ the manager _____ the assistant will attend the meeting — one of them will.', '["Neither / nor","Not only / but also","Either / or","Both / and"]', 'Either / or', 'either...or 表兩者之一。'),
(53, 'multiple_choice', '_____ the quality _____ the price met our expectations.', '["Neither / nor","Both / and","Either / or","Not only / but also"]', 'Neither / nor', 'neither...nor 表兩者都不符合。'),
(53, 'multiple_choice', '_____ the marketing team _____ the sales team contributed to the success.', '["Not only / but also","Either / or","Neither / nor","Both / and"]', 'Both / and', 'both...and 表兩者都。'),
(53, 'fill_blank', 'We can _____ negotiate the price _____ extend the deadline, but not both.', NULL, 'either / or', 'either...or 表兩個選項之一。'),
(53, 'multiple_choice', '_____ did she miss the deadline, _____ she failed to communicate the delay.', '["Not only / but also","Either / or","Neither / nor","Both / and"]', 'Not only / but also', 'not only...but also 表遞進強調。'),
(53, 'multiple_choice', '_____ the product quality _____ the customer service was satisfactory.', '["Either / or","Neither / nor","Both / and","Not only / but also"]', 'Neither / nor', 'neither...nor 表兩者皆不滿意。'),
(53, 'multiple_choice', 'Either the finance team _____ the legal team _____ the authority to approve this.', '["or / have","or / has","nor / have","and / has"]', 'or / has', 'either...or 就近原則，legal team 單數 has。'),
(53, 'transform', 'We need to improve quality. We also need to reduce costs. (Use: not only...but also)', NULL, 'We need to not only improve quality but also reduce our operating costs.', 'not only...but also 並列。'),
(53, 'fill_blank', 'Neither the CEO _____ the board members _____ present at the signing.', NULL, 'nor / were', 'neither...nor，board members 複數 were。'),
(53, 'multiple_choice', '_____ completing the project on time _____ under budget would be ideal.', '["Either / or","Not only / but also","Neither / nor","Both / and"]', 'Both / and', 'both...and 表兩個目標都達成。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(53, 'multiple_choice', 'Either you meet the requirements, _____ we cannot proceed.', '["and","nor","or","but"]', 'or', 'either...or 構成結果。'),
(53, 'multiple_choice', 'Neither the proposal _____ the contract _____ been signed yet.', '["nor / have","or / has","or / have","nor / has"]', 'nor / has', 'neither...nor，contract 單數，has。'),
(53, 'transform', 'She is efficient. She is also creative. (Use: not only...but also)', NULL, 'She is not only efficient but also highly creative in her approach.', 'not only...but also 強調雙重優點。'),
(53, 'fill_blank', 'We _____ lack the resources _____ the expertise to complete this in-house.', NULL, 'neither / nor', 'neither...nor 表兩者都缺乏。'),
(53, 'multiple_choice', 'Not only _____ she increase sales, _____ she reduced costs.', '["would / but also","is / but also","did / but also","has / and also"]', 'did / but also', 'not only...but also 倒裝結構。'),
(53, 'multiple_choice', 'Either the project manager _____ the deputy will lead the team.', '["or","and","but","nor"]', 'or', 'either...or 選擇。'),
(53, 'fill_blank', '_____ the budget increase _____ the deadline extension was approved.', NULL, 'Neither / nor', 'neither...nor 表兩個請求都被拒絕。'),
(53, 'multiple_choice', 'Both quality _____ efficiency _____ key priorities for our team.', '["nor / are","or / is","and / are","and / is"]', 'and / are', 'both...and 複數，are 正確。'),
(53, 'multiple_choice', 'Not only _____ we exceed revenue targets, _____ we also cut expenses.', '["did / but","have / and","are / but also","were / but also"]', 'did / but', 'not only did（倒裝） + but also。'),
(53, 'multiple_choice', 'Either we find a solution _____ we will lose the client.', '["but","or","nor","and"]', 'or', 'either...or 表兩者取一。'),
(54, 'multiple_choice', 'The manager / approved / the proposal. Which is the correct SVO order?', '["Approved the manager the proposal.","The manager approved the proposal.","The proposal approved the manager.","The proposal the manager approved."]', 'The manager approved the proposal.', '標準 SVO 語序。'),
(54, 'multiple_choice', 'Which sentence has correct SVO order?', '["She submitted the report on Friday.","She the report submitted Friday.","On Friday she submitted the report to.","Submitted she the report Friday."]', 'She submitted the report on Friday.', 'She（S）submitted（V）the report（O）on Friday（時間）。'),
(54, 'fill_blank', 'Reorder: yesterday / the client / called / us → _____.', NULL, 'The client called us yesterday.', 'SVO + 時間副詞置句尾。'),
(54, 'multiple_choice', 'Which is the correct sentence structure?', '["The CEO announced the new strategy at the annual meeting.","Announced at the annual meeting the strategy the CEO.","The CEO at the annual meeting the strategy announced.","At the annual meeting announced the CEO the strategy."]', 'The CEO announced the new strategy at the annual meeting.', 'SVO 語序，時間/地點副詞後置。'),
(54, 'multiple_choice', 'Which sentence follows correct English word order?', '["Emailed she the client the invoice.","She emailed the invoice to the client also correct","She emailed the client the invoice.","The invoice she emailed the client."]', 'She emailed the client the invoice.', 'SVOO（雙受語）語序，人在前物在後，或 She emailed the invoice to the client。'),
(54, 'multiple_choice', 'Where does the adverb ''often'' go in ''She checks her emails''?', '["She often checks her emails.","Often she checks her emails.","She checks her emails often.","She checks often her emails."]', 'She often checks her emails.', '頻率副詞 often 置主要動詞前（助動詞後）。'),
(54, 'transform', 'daily / attends / the manager / morning briefings (Arrange correctly)', NULL, 'The manager attends daily morning briefings.', 'SVO 語序，daily 形容詞修飾 briefings。'),
(54, 'fill_blank', 'Arrange: report / submitted / the team / on time → _____.', NULL, 'The team submitted the report on time.', 'The team（S）submitted（V）the report（O）on time（時間）。'),
(54, 'multiple_choice', 'Which sentence is grammatically correct?', '["Highly rate customers the service.","Customers rate the service highly.","Customers the service rate highly.","Rate customers highly the service."]', 'Customers rate the service highly.', 'SVO + 副詞 highly 置句尾。'),
(54, 'multiple_choice', 'In English, adjectives go _____the noun they modify.', '["before","around","after","following"]', 'before', '形容詞通常置名詞之前（前置修飾）。'),
(54, 'multiple_choice', 'Which is correct?', '["The budget discussed we during the meeting.","We discussed during the meeting the budget.","We discussed the budget during the meeting.","During the meeting we the budget discussed."]', 'We discussed the budget during the meeting.', 'SVO 語序，介系詞短語置句尾。'),
(54, 'fill_blank', 'Arrange: efficiently / the new system / processes / data → _____.', NULL, 'The new system processes data efficiently.', 'SVO + 副詞 efficiently 置句尾。'),
(54, 'multiple_choice', 'Which sentence is correct?', '["He presented to the board the quarterly results.","He presented the quarterly results to the board.","He to the board the quarterly results presented.","To the board he presented the quarterly results."]', 'He presented the quarterly results to the board.', 'SVO + 介系詞短語。'),
(54, 'multiple_choice', 'Where does ''yesterday'' go: ''She attended the conference''?', '["She attended the conference yesterday.","Yesterday she attended the conference yesterday.","She attended yesterday the conference.","She yesterday attended the conference."]', 'She attended the conference yesterday.', '時間副詞通常置句尾（或句首）。'),
(54, 'transform', 'in the city centre / is located / our new office (Arrange correctly)', NULL, 'Our new office is located in the city centre.', 'SV + 地點介系詞短語置句尾。'),
(54, 'fill_blank', 'Arrange: the proposal / carefully / reviewed / she → _____.', NULL, 'She reviewed the proposal carefully.', 'SVO + 副詞 carefully。'),
(54, 'multiple_choice', 'Which is correct word order with indirect and direct objects?', '["Me please send the updated report.","Please send the updated report me.","Please send updated the report me.","Please send me the updated report."]', 'Please send me the updated report.', '雙受語語序：人（me）在直接受語（the report）之前。'),
(54, 'multiple_choice', 'Which sentence is correct?', '["The finance team on time submitted the monthly report.","The finance team submitted the monthly report on time.","On time the finance team submitted the monthly report.","Submitted the monthly report the finance team on time."]', 'The finance team submitted the monthly report on time.', 'SVO + on time 時間副詞置句尾。'),
(54, 'fill_blank', 'Arrange: the clients / impressed / the presentation / deeply → _____.', NULL, 'The presentation deeply impressed the clients.', '深刻印象，副詞 deeply 放動詞前更常見在此語境。'),
(54, 'multiple_choice', 'Which is grammatically correct?', '["She gave the client a detailed overview of the project.","She gave a detailed overview to client the project.","A detailed overview she gave the client of the project.","The client she gave a detailed overview the project."]', 'She gave the client a detailed overview of the project.', 'She（S）gave（V）the client（IO）a detailed overview（DO）。'),
(55, 'multiple_choice', 'She _____ meets her deadlines.', '["all time meets","always","meets always","always met"]', 'always', 'always 頻率副詞置主要動詞前。'),
(55, 'multiple_choice', 'He _____ is late for meetings.', '["all times is","is all times","never is","is never"]', 'is never', 'is never：never 置 be 動詞後。'),
(55, 'multiple_choice', 'The manager reviewed the report _____ before the presentation.', '["quickly","quickest","quickened","quick"]', 'quickly', 'quickly 方式副詞置句尾。'),
(55, 'fill_blank', 'She speaks _____ (clear) and _____ (confident) in client meetings.', NULL, 'clearly / confidently', '副詞 -ly 修飾動詞。'),
(55, 'multiple_choice', 'It is _____ important to proofread before submitting.', '["extremer","most extreme","extreme","extremely"]', 'extremely', 'extremely 程度副詞置形容詞前。'),
(55, 'multiple_choice', 'He has _____ submitted the expense report.', '["already","just before","submitted already","before submitted"]', 'already', 'already 現在完成式置助動詞後。'),
(55, 'multiple_choice', 'They _____ complete this type of project in two weeks.', '["usually","complete usually","usually completed","usual complete"]', 'usually', 'usually 頻率副詞置主要動詞前。'),
(55, 'transform', 'She is efficient. She is very dedicated. (Rewrite with adverbs)', NULL, 'She works efficiently and is extremely dedicated.', '副詞形式修飾動詞/形容詞。'),
(55, 'multiple_choice', 'The proposal was _____ detailed.', '["surprising","surprisingly","with surprise","surprise"]', 'surprisingly', 'surprisingly 程度副詞修飾形容詞 detailed。'),
(55, 'fill_blank', 'The team worked _____ (hard) to meet the deadline.', NULL, 'hard', 'hard 既是形容詞也是副詞，不加 -ly。'),
(55, 'multiple_choice', 'He _____ checks his emails before noon.', '["rarely","rarely checked","check rarely","rare checks"]', 'rarely', 'rarely 頻率副詞置主要動詞前。'),
(55, 'multiple_choice', 'The CEO spoke _____ about the company''s future.', '["enthusiasm","enthusiastically","with enthusiastic","enthusiastic"]', 'enthusiastically', '-ly 副詞修飾動詞 spoke。'),
(55, 'multiple_choice', 'The report is _____ complete — just the conclusion is missing.', '["close","near","almost","most"]', 'almost', 'almost 程度副詞置形容詞前。'),
(55, 'transform', 'She is a careful worker. She is also precise. (Use adverbs)', NULL, 'She works carefully and precisely.', '副詞修飾動詞。'),
(55, 'fill_blank', 'I _____ (occasional) work from home on Fridays.', NULL, 'occasionally', 'occasionally 頻率副詞。'),
(55, 'multiple_choice', 'We have _____ resolved all the outstanding issues.', '["at final","finally","final","at last finally"]', 'finally', 'finally 置助動詞後，have finally resolved。'),
(55, 'multiple_choice', 'The client was _____ satisfied with the outcome.', '["with fully","fulling","full","fully"]', 'fully', 'fully 程度副詞修飾形容詞 satisfied。'),
(55, 'multiple_choice', 'She _____ arrives early to prepare for the day.', '["arrives usual","usual arrives","usually arrived","usually"]', 'usually', 'usually 頻率副詞置主要動詞前。'),
(55, 'fill_blank', 'The new policy is _____ (entire) designed to improve safety.', NULL, 'entirely', 'entirely 程度副詞修飾 designed。'),
(55, 'multiple_choice', 'He speaks English _____ in formal settings.', '["fluenter","fluently","with fluency","fluent"]', 'fluently', 'fluently 副詞修飾 speaks。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(56, 'multiple_choice', '_____ have we seen such a rapid growth in revenue.', '["Hardly","No","Never","Not"]', 'Never', '"Never have we seen" 否定副詞倒裝。'),
(56, 'multiple_choice', 'Not only _____ we exceed our targets, but we also reduced costs.', '["were","did","do","have"]', 'did', 'not only + did 倒裝（過去式）。'),
(56, 'multiple_choice', 'Rarely _____ the board make a unanimous decision so quickly.', '["does","is","has","do"]', 'does', 'rarely + does 倒裝（現在式三單）。'),
(56, 'fill_blank', 'Under no circumstances _____ (should) employees share login credentials.', NULL, 'should', 'under no circumstances 後倒裝，should 提前。'),
(56, 'multiple_choice', 'Hardly _____ the meeting started when a problem arose.', '["does","was","did","had"]', 'had', 'hardly had...when 倒裝句型。'),
(56, 'multiple_choice', 'Not only _____ the product innovative, but it is also affordable.', '["has","are","does","is"]', 'is', 'not only is...（現在式），是倒裝。'),
(56, 'multiple_choice', 'On no account _____ employees use company devices for personal use.', '["must","should","shall","ought"]', 'should', 'on no account + should 倒裝表禁止。'),
(56, 'transform', 'We have never encountered such a challenging project before. (Use inversion)', NULL, 'Never have we encountered such a challenging project before.', 'Never have we 否定副詞倒裝。'),
(56, 'multiple_choice', 'Seldom _____ we receive such positive feedback from clients.', '["have","are","do","does"]', 'do', 'seldom + do 倒裝（複數主詞）。'),
(56, 'fill_blank', 'No sooner _____ she submitted the report _____ the client called.', NULL, 'had / than', 'No sooner had...than 倒裝句型。'),
(56, 'multiple_choice', 'Not until the contract _____ signed _____ the project begin.', '["was / will","had / would","was / could","is / will"]', 'was / could', 'not until + 過去式，主句倒裝 could。'),
(56, 'multiple_choice', 'Little _____ the team know that the client would reject the proposal.', '["does","was","do","did"]', 'did', 'little did...know 否定副詞倒裝。'),
(56, 'multiple_choice', 'Under no circumstances _____ the price be negotiated further.', '["may","could","shall","can"]', 'can', 'under no circumstances + 情態動詞倒裝。'),
(56, 'transform', 'We had never invested so heavily in a single project. (Use inversion)', NULL, 'Never had we invested so heavily in a single project.', 'Never had we 否定副詞倒裝。'),
(56, 'fill_blank', 'Barely _____ (have) the new CEO taken office when the crisis began.', NULL, 'had', 'barely had...when 倒裝句型。'),
(56, 'multiple_choice', 'Not until this year _____ we fully recovered from the downturn.', '["did","had","have","were"]', 'have', 'not until + 現在完成式倒裝 have we。'),
(56, 'multiple_choice', 'Rarely _____ seen such commitment from a team.', '["I have","have we","have I","did I"]', 'have I', 'rarely have I 否定副詞倒裝。'),
(56, 'transform', 'The company had barely announced the merger when investors reacted. (Use inversion)', NULL, 'Barely had the company announced the merger when investors reacted.', 'Barely had...when 倒裝。'),
(56, 'fill_blank', 'Only when the audit _____ (complete) did the board realize the extent of the losses.', NULL, 'was completed', 'only when + 過去被動式；主句倒裝。'),
(56, 'multiple_choice', 'So _____ was the demand that the factory had to run 24 hours.', '["greatly","much great","great","greaten"]', 'great', 'so great...that 引起的倒裝感嘆結構。'),
(57, 'multiple_choice', 'We have _____ updates to share with the team.', '["every","any","no","some"]', 'some', 'some 在肯定句中表有一些。'),
(57, 'multiple_choice', 'Is there _____ feedback from the client?', '["every","any","some","no"]', 'any', 'any 在一般疑問句中。'),
(57, 'multiple_choice', 'We don''t have _____ available budget this quarter.', '["any","some","no","every"]', 'any', 'don''t have any 否定句中用 any。'),
(57, 'fill_blank', 'There are _____ issues with the contract that need to be resolved.', NULL, 'some', '肯定句中 some 表有一些問題。'),
(57, 'multiple_choice', 'Could you give me _____ advice on this proposal?', '["any","every","some","no"]', 'some', 'Could you give me some 期望肯定回應的疑問句。'),
(57, 'multiple_choice', 'We have _____ objections to the proposal.', '["every","no","some","any"]', 'no', 'no objections = not any objections，語氣更強。'),
(57, 'multiple_choice', 'Do you have _____ questions before we begin?', '["no","every","some","any"]', 'any', 'any 在一般疑問句中。'),
(57, 'fill_blank', 'She sent _____ files that contained sensitive information.', NULL, 'some', '肯定句 some files。'),
(57, 'multiple_choice', 'There is _____ guarantee that the deal will succeed.', '["no","every","some","any"]', 'no', 'no guarantee 強調沒有保證。'),
(57, 'multiple_choice', 'We still have _____ work to do before the deadline.', '["every","any","no","some"]', 'some', 'some work 肯定句有些工作要做。'),
(57, 'multiple_choice', 'He didn''t make _____ errors in the report.', '["every","any","no","some"]', 'any', 'didn''t make any errors 否定句用 any。'),
(57, 'fill_blank', 'Could you send me _____ samples of your product?', NULL, 'some', 'Could you send some 期望肯定的疑問句。'),
(57, 'multiple_choice', 'There is _____ room for negotiation on the price.', '["any","no","every","some"]', 'some', 'some room 表有協商空間。'),
(57, 'multiple_choice', 'We have _____ time to waste — the deadline is tomorrow.', '["some","any","every","no"]', 'no', 'no time to waste 強調完全沒有時間。'),
(57, 'multiple_choice', 'Have you received _____ response from the client?', '["any","every","no","some"]', 'any', 'any 在疑問句中。'),
(57, 'fill_blank', 'She made _____ useful suggestions during the meeting.', NULL, 'some', 'some suggestions 肯定句有幾個有用建議。'),
(57, 'multiple_choice', 'There is _____ doubt that this was the right decision.', '["no","every","any","some"]', 'no', 'no doubt 強調毫無疑問。'),
(57, 'transform', 'Do we have budget left? I''d like to know. (Use: any)', NULL, 'Do we have any budget left for this initiative?', 'any 疑問句中用於詢問是否有。'),
(57, 'fill_blank', 'Is there _____ chance we can reschedule the meeting?', NULL, 'any', 'any chance 疑問句詢問可能性。'),
(57, 'multiple_choice', 'We encountered _____ difficulties with the software installation.', '["no","every","some","any"]', 'some', 'some difficulties 肯定句有些困難。'),
(58, 'multiple_choice', 'We don''t have _____ time to complete this analysis.', '["much","few","many","a lot"]', 'much', 'much + 不可數名詞 time。'),
(58, 'multiple_choice', 'There are _____ opportunities in the Asian market.', '["many","much","few","a lot"]', 'many', 'many + 可數複數名詞 opportunities。'),
(58, 'multiple_choice', 'She has _____ experience in project management.', '["much of","few","many","a lot of"]', 'a lot of', 'experience 不可數，a lot of experience，也可用 much（正式）。'),
(58, 'fill_blank', 'We received _____ (many) applications for the position.', NULL, 'many / a lot of', 'many + 可數名詞；a lot of 也可。'),
(58, 'multiple_choice', 'There is _____ competition in the software market.', '["a lot of","many","much of","few"]', 'a lot of', 'competition 不可數，a lot of competition。'),
(58, 'multiple_choice', 'How _____ staff do we need for this project?', '["few","many","a lot of","much"]', 'many', 'how many + 可數名詞 staff。'),
(58, 'multiple_choice', 'We''ve made _____ progress on the merger negotiations.', '["much of","many","a lot of","few"]', 'a lot of', 'progress 不可數，a lot of progress（口語），much progress（正式）。'),
(58, 'fill_blank', 'She doesn''t have _____ information about the client''s requirements.', NULL, 'much', 'much + 不可數名詞 information，否定句。'),
(58, 'multiple_choice', 'How _____ budget has been allocated for marketing?', '["many","few","much","a lot of"]', 'much', 'how much + 不可數名詞 budget。'),
(58, 'multiple_choice', 'There are _____ factors to consider before making a decision.', '["much","a lot","many","few"]', 'many', 'many + 可數複數名詞 factors。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(58, 'multiple_choice', 'We don''t have _____ meetings scheduled for next week.', '["many","much","few","a lot"]', 'many', 'many + 可數名詞 meetings，否定句。'),
(58, 'fill_blank', 'She put _____ effort into preparing for the presentation.', NULL, 'a lot of / much', 'effort 不可數，a lot of 或 much（正式）。'),
(58, 'multiple_choice', '_____ of our clients have requested extended payment terms.', '["Many","Few","A lot","Much"]', 'Many', 'Many + 可數複數名詞 clients。'),
(58, 'multiple_choice', 'There isn''t _____ room in the budget for unexpected expenses.', '["few","a lot","much","many"]', 'much', 'much + 不可數名詞 room（空間）。'),
(58, 'multiple_choice', 'We have _____ data to support our recommendation.', '["few","many","a lot of","much of"]', 'a lot of', 'data 不可數，a lot of data。'),
(58, 'transform', 'The number of complaints was high last quarter. (Use: many)', NULL, 'We received many complaints from clients last quarter.', 'many + 可數複數名詞。'),
(58, 'fill_blank', 'How _____ research have you done on the topic?', NULL, 'much', 'much + 不可數名詞 research。'),
(58, 'multiple_choice', '_____ of the new initiatives are already showing results.', '["A lot","Much","Many","Few"]', 'Many', 'Many + 可數複數 initiatives。'),
(58, 'multiple_choice', 'She has _____ knowledge of international trade law.', '["many","few","extensive","a lot"]', 'extensive', 'extensive knowledge（形容詞）；much knowledge（正式）也可。'),
(58, 'multiple_choice', 'There are _____ advantages to adopting this technology.', '["few","a lot","much","many"]', 'many', 'many + 可數複數名詞 advantages。'),
(59, 'multiple_choice', 'We have _____ options — the situation is very limited.', '["few","little","a few","a little"]', 'few', 'few 幾乎沒有，語氣消極。'),
(59, 'multiple_choice', 'There is _____ time left to revise the proposal — about 30 minutes.', '["little","a little","a few","few"]', 'a little', 'a little 表還有一些時間，積極。'),
(59, 'multiple_choice', 'Only _____ candidates met the minimum qualifications.', '["a little","little","few","a few"]', 'a few', 'a few 表有幾位符合，積極。'),
(59, 'fill_blank', 'There is _____ hope of securing the contract at this late stage.', NULL, 'little', 'little 幾乎沒有希望，消極。'),
(59, 'multiple_choice', 'We still have _____ unresolved issues with the vendor.', '["a little","little","few","a few"]', 'a few', 'a few issues 幾個問題（還有一些需處理）。'),
(59, 'multiple_choice', '_____ effort is required to operate this new system.', '["Few","Little","A little","A few"]', 'Little', 'little effort 幾乎不需要努力。'),
(59, 'multiple_choice', 'She has _____ experience in this field — just six months.', '["a little","a few","few","little"]', 'a little', 'a little experience 有一些（雖然不多但有）。'),
(59, 'transform', 'We have some remaining budget. We can use it for training. (Use: a little)', NULL, 'We have a little budget remaining, which we can use for training.', 'a little + 不可數名詞，積極。'),
(59, 'multiple_choice', '_____ companies offer such a comprehensive package.', '["Little","A little","Few","A few"]', 'Few', 'few companies 幾乎沒有公司（罕見）。'),
(59, 'fill_blank', 'There was _____ confusion after the announcement, so clarification was needed.', NULL, 'a little / some', 'a little confusion 有些困惑（不可數）。'),
(59, 'multiple_choice', 'She has _____ relevant experience, so she may need extra support.', '["little","a few","a little","few"]', 'little', 'little experience 幾乎沒有，語氣消極。'),
(59, 'multiple_choice', 'We received _____ complaints this month, which is encouraging.', '["a few","a little","little","few"]', 'a few', 'a few complaints 有幾個（語氣積極，表示只是少數）。'),
(59, 'multiple_choice', 'There is _____ evidence to support this claim.', '["a little","few","a few","little"]', 'little', 'little evidence 幾乎沒有證據，消極。'),
(59, 'transform', 'We have some time before the call. Let''s prepare. (Use: a little)', NULL, 'We have a little time before the call, so let''s prepare.', 'a little time 有一點時間（積極）。'),
(59, 'fill_blank', '_____ members of the team understood the technical requirements.', NULL, 'Few', 'few members 幾乎沒有人理解，消極。'),
(59, 'multiple_choice', 'She made _____ mistakes in the report — just two minor ones.', '["a few","few","a little","little"]', 'a few', 'a few mistakes 有幾個（有限的）錯誤。'),
(59, 'multiple_choice', 'We have _____ information about the client''s decision-making process.', '["a little","few","little","a few"]', 'little', 'little information 幾乎沒有資訊，消極。'),
(59, 'fill_blank', 'I have _____ concerns about the plan, but overall it looks good.', NULL, 'a few', 'a few concerns 有幾個顧慮（但整體正面）。'),
(59, 'multiple_choice', 'There is _____ demand for this product in the local market.', '["a little","little","a few","few"]', 'little', 'little demand 需求很低，消極。'),
(59, 'multiple_choice', 'She has _____ suggestions to improve the workflow.', '["a little","little","a few","few"]', 'a few', 'a few suggestions 有幾個建議，積極。'),
(60, 'multiple_choice', '_____ employee is required to complete the annual review form.', '["Both","Each","All","Every"]', 'Each', 'each + 單數名詞，強調個別；every 也可用。'),
(60, 'multiple_choice', '_____ department will be assessed during the annual audit.', '["All","Both","Every","Each"]', 'Every', 'every + 單數名詞，強調全部的每一個。'),
(60, 'multiple_choice', '_____ staff members are invited to attend the town hall meeting.', '["Every","Both","All","Each"]', 'All', 'all + 複數名詞，全體。'),
(60, 'fill_blank', '_____ time she presents to the board, she receives excellent feedback.', NULL, 'Every', 'every time 固定搭配，表每次。'),
(60, 'multiple_choice', '_____ of the proposals was reviewed individually.', '["Both","Each","Every","All"]', 'Each', 'each of the + 複數名詞 + 單數動詞。'),
(60, 'multiple_choice', 'We need _____ team member to confirm their attendance.', '["all","both","every","each"]', 'every', 'every + 單數名詞，強調全部。'),
(60, 'multiple_choice', '_____ the information you need is in the report.', '["Both","All","Each","Every"]', 'All', 'all the information 全部資訊，不可數名詞。'),
(60, 'transform', 'We need to inform every person on the team. (Use: each member)', NULL, 'Each member of the team needs to be informed of the changes.', 'each + 單數名詞，強調個別通知。'),
(60, 'fill_blank', 'She takes notes at _____ team meeting.', NULL, 'every / each', 'every/each team meeting，表每次例會。'),
(60, 'multiple_choice', '_____ the applications were reviewed before the shortlist was made.', '["All","Each","Every","Both"]', 'All', 'all the applications 所有申請，複數。'),
(60, 'multiple_choice', '_____ country in the region will be affected by the new trade agreement.', '["Every","Each","Both","All"]', 'Every', 'every country，強調全部每一個國家。'),
(60, 'multiple_choice', 'She spoke to _____ member of the team individually.', '["all","both","each","every"]', 'each', 'each 強調一個一個地個別交談。'),
(60, 'fill_blank', '_____ document in the submission must be signed.', NULL, 'Each / Every', 'each/every + 單數名詞，強調每份文件。'),
(60, 'multiple_choice', 'Not _____ employee was aware of the policy change.', '["both","all","each","every"]', 'every', 'not every 表示不是所有人都知道。'),
(60, 'multiple_choice', '_____ of our offices follow the same security protocols.', '["Each","Both","All","Every"]', 'All', 'all of our offices 複數主語 + 複數動詞。'),
(60, 'transform', 'Both team A and team B submitted their reports. (Use: all)', NULL, 'All teams submitted their reports by the deadline.', 'all teams 表全部的隊伍。'),
(60, 'fill_blank', '_____ item on the agenda was discussed in detail.', NULL, 'Each / Every', 'each/every item 單數，強調每個項目。'),
(60, 'multiple_choice', 'We need to renew _____ subscription before the year ends.', '["all","each","every","both"]', 'every', 'every subscription 每個訂閱（強調整體）。'),
(60, 'multiple_choice', 'She met _____ client personally to understand their needs.', '["both","all","each","every"]', 'every', 'every client 強調沒有一個例外；each 也可用。'),
(60, 'multiple_choice', '_____ of the managers attended the leadership training.', '["All","Every","Each","Both"]', 'All', 'all of the managers 全部的管理者。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(61, 'multiple_choice', 'He prepared the entire presentation _____ without any help.', '["himself","by him","his own","himself only"]', 'himself', 'himself 表強調（他親自）。'),
(61, 'multiple_choice', 'Please help _____ to the refreshments after the meeting.', '["you","yours","yourself","yourselves"]', 'yourself', 'help yourself 請自取，禮貌用語。'),
(61, 'multiple_choice', 'The CEO _____ attended the small team briefing.', '["she","herself","her","hers"]', 'herself', 'herself 強調 CEO 親自出席。'),
(61, 'fill_blank', 'The system updated _____ overnight without any manual input.', NULL, 'itself', 'itself 反身代名詞，系統自動更新。'),
(61, 'multiple_choice', 'We _____ identified the problem before the client noticed.', '["ourself","us","ours","ourselves"]', 'ourselves', 'ourselves 主語 we 的反身代名詞。'),
(61, 'multiple_choice', 'You should introduce _____ to the new team members.', '["yourself","yourselves","yours","you"]', 'yourself', 'yourself 反身，主語 you 單數。'),
(61, 'multiple_choice', 'She hurt _____ trying to carry all the boxes alone.', '["she","herself","her","hers"]', 'herself', 'herself 反身動作。'),
(61, 'multiple_choice', 'They _____ admitted that the project had failed.', '["themselves","theirs","theirselves","them"]', 'themselves', 'themselves 強調他們主動承認。'),
(61, 'transform', 'The team did the work without any outside help. (Use: by themselves)', NULL, 'The team completed the project entirely by themselves.', 'by themselves 表靠自己完成。'),
(61, 'multiple_choice', 'The new software installs _____ automatically.', '["itself","it","its","alone"]', 'itself', 'itself 反身代名詞，系統安裝自身。'),
(61, 'fill_blank', 'He signed the contract _____ to show his commitment.', NULL, 'himself', 'himself 強調本人親自簽署。'),
(61, 'multiple_choice', 'We need to ask _____ whether this strategy is sustainable.', '["ourself","ourselves","ours","us"]', 'ourselves', 'ourselves 反身，主語 we。'),
(61, 'multiple_choice', 'She blamed _____ for the miscommunication.', '["herself","hers","she","her"]', 'herself', 'herself 反身動作（責怪自己）。'),
(61, 'multiple_choice', 'The team should be proud of _____ for achieving this milestone.', '["them","themselves","theirselves","theirs"]', 'themselves', 'themselves 反身，主語 they。'),
(61, 'multiple_choice', 'Please make _____ at home during your visit to our office.', '["yours","you","yourselves","yourself"]', 'yourself', 'make yourself at home 固定用語。'),
(61, 'transform', 'The manager completed the audit without assistance. (Use: himself)', NULL, 'The manager completed the audit himself.', 'himself 強調親自完成。'),
(61, 'fill_blank', 'I taught _____ to use the new CRM system.', NULL, 'myself', 'myself 反身，主語 I，自學。'),
(61, 'multiple_choice', 'They _____ did all the coding without hiring external developers.', '["theirs","themselves","theirselves","them"]', 'themselves', 'themselves 強調自己完成。'),
(61, 'multiple_choice', 'The company prides _____ on its customer service.', '["its","alone","itself","it"]', 'itself', 'pride itself on 固定搭配，反身代名詞 itself。'),
(61, 'multiple_choice', 'Please address any concerns _____ rather than escalating immediately.', '["yourself","yours","you","yourselves"]', 'yourself', 'yourself 反身，請自行處理。'),
(62, 'multiple_choice', '_____ needs to take responsibility for this error.', '["Anyone","No one","Everybody","Someone"]', 'Someone', 'someone 在肯定句中表某人。'),
(62, 'multiple_choice', 'Has _____ reviewed the final draft yet?', '["someone","no one","anyone","everybody"]', 'anyone', 'anyone 在疑問句中。'),
(62, 'multiple_choice', '_____ informed the client about the delay — that was a big mistake.', '["Someone","Anyone","Everybody","No one"]', 'No one', 'no one 表沒有人，語氣強調失誤。'),
(62, 'fill_blank', 'Is there _____ who can help me with this spreadsheet?', NULL, 'anyone', '疑問句中用 anyone。'),
(62, 'multiple_choice', 'There''s _____ at the door asking for the manager.', '["nobody","no one","anyone","someone"]', 'someone', 'someone 在肯定句中。'),
(62, 'multiple_choice', '_____ in the team knows the answer — we need expert help.', '["Everyone","Nobody","Somebody","Anybody"]', 'Nobody', 'nobody 否定，無人知曉。'),
(62, 'multiple_choice', 'Did _____ attend the meeting on my behalf?', '["no one","someone","anyone","nobody"]', 'anyone', '疑問句中 anyone。'),
(62, 'fill_blank', 'We didn''t hear _____ from the client after we sent the proposal.', NULL, 'anything', 'anything 否定句中表沒有任何消息。'),
(62, 'multiple_choice', '_____ told me that the meeting was cancelled — I went there for nothing.', '["Anybody","Nobody","Everyone","Somebody"]', 'Nobody', 'nobody told me 沒有人告訴我。'),
(62, 'multiple_choice', 'Can _____ explain why the report is missing data?', '["someone","anyone","nobody","no one"]', 'anyone', '疑問句中 anyone。'),
(62, 'multiple_choice', '_____ from the finance team confirmed the budget allocation.', '["Nobody","Someone","Anyone","No one"]', 'Someone', 'someone 在肯定句，表有某人確認了。'),
(62, 'fill_blank', 'Is there _____ wrong with the system? It keeps crashing.', NULL, 'anything', 'anything wrong 疑問句詢問是否有問題。'),
(62, 'multiple_choice', 'We need _____ who is fluent in Mandarin for this client.', '["nobody","someone","no one","anyone"]', 'someone', 'someone 特定需求，肯定句。'),
(62, 'multiple_choice', '_____ objected to the new policy at the meeting.', '["Someone","No one","Anyone","Everybody"]', 'No one', 'no one objected 沒有人反對。'),
(62, 'transform', 'I can''t find the document anywhere. (Use: nowhere)', NULL, 'The document is nowhere to be found.', 'nowhere 表哪裡都找不到。'),
(62, 'fill_blank', 'Has _____ sent the meeting invitation to the client?', NULL, 'anyone', '疑問句中 anyone。'),
(62, 'multiple_choice', 'There''s _____ important I need to discuss with you.', '["something","nothing","everything","anything"]', 'something', 'something 肯定句中表有某件重要的事。'),
(62, 'multiple_choice', 'She didn''t tell _____ about the confidential deal.', '["anyone","nobody","someone","no one"]', 'anyone', 'didn''t tell anyone 否定句中 anyone。'),
(62, 'fill_blank', '_____ knows why the project was cancelled so abruptly.', NULL, 'Nobody / No one', 'nobody/no one 表沒有人知道原因。'),
(62, 'multiple_choice', 'He looked _____ for the missing file but couldn''t find it.', '["everywhere","anywhere","somewhere","nowhere"]', 'everywhere', 'everywhere 表到處都找了。'),
(63, 'multiple_choice', 'Can you give me some _____ on this matter?', '["an advice","advise","advices","advice"]', 'advice', 'advice 不可數，不加複數；some advice。'),
(63, 'multiple_choice', 'We need more _____ before making a decision.', '["information","an information","informing","informations"]', 'information', 'information 不可數，no plural；some information。'),
(63, 'multiple_choice', 'All the _____ in the office will be replaced next month.', '["furnitures","furnishings","a furniture","furniture"]', 'furniture', 'furniture 不可數；所有傢俱 all the furniture。'),
(63, 'fill_blank', 'She gave us some useful _____ (feedback) on our presentation.', NULL, 'feedback', 'feedback 不可數，not feedbacks。'),
(63, 'multiple_choice', 'We received _____ from the committee.', '["no newses","no news","any newses","a news"]', 'no news', 'news 不可數，no news（沒有消息）。'),
(63, 'multiple_choice', 'The _____ she provided saved us hours of research.', '["datum","a data","data","datas"]', 'data', 'data 通常作複數（the data are/is），不說 datas。'),
(63, 'multiple_choice', 'We made significant _____ on the project this week.', '["progressing","a progress","progress","progresses"]', 'progress', 'progress 不可數，significant progress。'),
(63, 'fill_blank', 'The company invested heavily in _____ (research).', NULL, 'research', 'research 不可數，not researches。'),
(63, 'multiple_choice', 'Could you share _____ about the client''s background?', '["some knowledges","a knowledge","some knowledge","any knowledges"]', 'some knowledge', 'knowledge 不可數，some knowledge。'),
(63, 'multiple_choice', 'We need _____ manager to oversee this project.', '["an","some","a","any"]', 'a', 'manager 可數，a manager。');

INSERT INTO grammar_questions (topic_id, question_type, question, options_json, correct_answer, explanation) VALUES
(63, 'multiple_choice', 'She has _____ experience in supply chain management.', '["a great deal of","several","many","a few"]', 'a great deal of', 'experience（經驗）不可數，a great deal of experience。'),
(63, 'fill_blank', 'We received _____ important _____ (news) from our Tokyo office today.', NULL, 'some / news', 'news 不可數，some important news。'),
(63, 'multiple_choice', 'The _____ is very complex in this legal document.', '["languaging","language","a language","languages"]', 'language', 'language（此處指語言表達）不可數泛稱。'),
(63, 'multiple_choice', 'They need _____ new _____ to complete the system.', '["any / equipments","a / equipment","some / equipments","some / equipment"]', 'some / equipment', 'equipment 不可數，some equipment。'),
(63, 'multiple_choice', 'We don''t have _____ time to review each document individually.', '["a few","several","many","enough"]', 'enough', 'enough + 不可數名詞 time；many/a few 只用於可數名詞。'),
(63, 'transform', 'She gave me several pieces of advice. (Correct the error if any)', NULL, 'She gave me some valuable advice on the project.', 'advice 不可數，不說 pieces of advice（雖然技術上可以，but several advice 是錯的）。'),
(63, 'fill_blank', 'We need to collect more _____ (information) before deciding.', NULL, 'information', 'information 不可數，not informations。'),
(63, 'multiple_choice', 'All the _____ has been carefully reviewed by the legal team.', '["document","a documentation","documentations","documentation"]', 'documentation', 'documentation 不可數，all the documentation。'),
(63, 'multiple_choice', 'We have received _____ applications for the position.', '["many","much","a lot","several of"]', 'many', 'applications 可數複數，many applications。'),
(63, 'multiple_choice', 'She has _____ knowledge of the local market.', '["several","extensive","a few","many"]', 'extensive', 'extensive knowledge，knowledge 不可數，不用 many。'),
(64, 'multiple_choice', 'We need to conduct a thorough _____ before launching.', '["market research","markets research","researching market","researches of market"]', 'market research', 'market research 複合名詞，market 作前置修飾語。'),
(64, 'multiple_choice', 'Please send this to the _____ department.', '["customer''s service","customers service","service customer","customer service"]', 'customer service', 'customer service 複合名詞。'),
(64, 'multiple_choice', 'We have a _____ on Thursday to discuss the new strategy.', '["boards meeting","meeting of board","board meeting","boardly meeting"]', 'board meeting', 'board meeting 複合名詞。'),
(64, 'fill_blank', 'The _____ (cost/cutting) measures have been very effective.', NULL, 'cost-cutting', 'cost-cutting 連字號複合形容詞。'),
(64, 'multiple_choice', 'She is the _____ of the company.', '["decision maker","decision-maker","decisions-maker","maker of decision"]', 'decision-maker', 'decision-maker 連字號複合名詞。'),
(64, 'multiple_choice', 'Please review the _____ before signing.', '["terms contract","terms of contract","contract terms","contractual of terms"]', 'contract terms', 'contract terms 複合名詞。'),
(64, 'multiple_choice', 'The _____ was delayed due to supply issues.', '["launching of product","launch of product","product launch","products launch"]', 'product launch', 'product launch 複合名詞。'),
(64, 'fill_blank', 'She is in charge of _____ (staff/training).', NULL, 'staff training', 'staff training 複合名詞。'),
(64, 'multiple_choice', 'We need a _____ for the conference room.', '["whiteboard","white board","boarding white","board of white"]', 'whiteboard', 'whiteboard 合一詞的複合名詞。'),
(64, 'multiple_choice', 'The _____ will be distributed to all employees.', '["staff handbook","handbook of staff","staffs handbook","handbooking staff"]', 'staff handbook', 'staff handbook 複合名詞。'),
(64, 'multiple_choice', 'He''s responsible for _____ at our company.', '["controlling of quality","qualities control","control of qualities","quality control"]', 'quality control', 'quality control 複合名詞。'),
(64, 'fill_blank', 'The _____ (data/base) needs to be updated regularly.', NULL, 'database', 'database 合一詞的複合名詞。'),
(64, 'multiple_choice', 'Our _____ team is expanding to meet growing demand.', '["selling force","sales force","sales'' force","force of sales"]', 'sales force', 'sales force 複合名詞。'),
(64, 'multiple_choice', 'They attended a _____ on digital marketing.', '["shop of work","working shop","work shop","workshop"]', 'workshop', 'workshop 合一詞複合名詞。'),
(64, 'multiple_choice', 'Please prepare a _____ for tomorrow''s meeting.', '["presentation of PowerPoint","PowerPointing presentation","presented PowerPoint","PowerPoint presentation"]', 'PowerPoint presentation', 'PowerPoint presentation 複合名詞。'),
(64, 'transform', 'The deadline for the project is next Friday. (Use: project deadline)', NULL, 'The project deadline has been set for next Friday.', 'project deadline 複合名詞。'),
(64, 'fill_blank', 'We need to strengthen our _____ (supply/chain) management.', NULL, 'supply chain', 'supply chain 複合名詞，兩個詞分開。'),
(64, 'multiple_choice', 'She works in _____ management.', '["human resources","humans resource","resource of humans","human''s resources"]', 'human resources', 'human resources management 複合名詞。'),
(64, 'multiple_choice', 'The company issues a monthly _____ to all stakeholders.', '["news letter","letter of news","newsletter","news-letter"]', 'newsletter', 'newsletter 合一詞複合名詞。'),
(64, 'multiple_choice', 'We scheduled a _____ to review the annual figures.', '["reviewing of budget","budget review","review of budgeting","budgets review"]', 'budget review', 'budget review 複合名詞。'),
(65, 'multiple_choice', 'She works in a _____ conference room.', '["modern, small","small, modern","small modern''s","modern small''s"]', 'small, modern', '尺寸（small）在意見/描述（modern）前。'),
(65, 'multiple_choice', 'They bought _____ office chairs.', '["ten comfortable new","comfortable new ten","new comfortable ten","ten new comfortable"]', 'ten comfortable new', '數量（ten）→意見（comfortable）→年齡（new）。'),
(65, 'multiple_choice', 'He is a _____ manager.', '["young talent","talent, young","young, talented","talented, young"]', 'young, talented', '年齡（young）→意見（talented）通常意見前，但 young talented 在此更自然。'),
(65, 'fill_blank', 'We need a _____ (large/Chinese/round) conference table.', NULL, 'large round Chinese', '尺寸→形狀→來源。'),
(65, 'multiple_choice', 'She received _____ promotion.', '["an well-deserved","a well-deserved","a deserved-well","a well-deserving"]', 'a well-deserved', 'a well-deserved 意見性形容詞。'),
(65, 'multiple_choice', 'They installed _____ doors in the new office.', '["beautiful sliding glass","sliding beautiful glass","glass beautiful sliding","beautiful glass sliding"]', 'beautiful glass sliding', '意見（beautiful）→材質（glass）→用途（sliding）。'),
(65, 'multiple_choice', 'It was _____ decision.', '["a difficult business","a business''s difficult","difficult''s business","a business difficult"]', 'a difficult business', '意見（difficult）→目的（business）。'),
(65, 'fill_blank', 'He drives a _____ (small/new/red/Japanese) car.', NULL, 'small new red Japanese', '尺寸→年齡→顏色→來源。'),
(65, 'multiple_choice', 'She is a _____ professional.', '["experienced highly","high experienced","highly experienced","experiencedly high"]', 'highly experienced', '副詞（highly）修飾形容詞（experienced）。'),
(65, 'multiple_choice', 'We ordered _____ sofas for the reception area.', '["two leather large","large two leather","leather two large","two large leather"]', 'two large leather', '數量（two）→尺寸（large）→材質（leather）。'),
(65, 'multiple_choice', 'He is an _____ businessman.', '["ambitious young","ambitious youngly","ambition young","young ambitious"]', 'ambitious young', '意見（ambitious）→年齡（young）。'),
(65, 'fill_blank', 'We use a _____ (modern/digital/small) filing system.', NULL, 'small modern digital', '尺寸→意見→目的（數位）。'),
(65, 'multiple_choice', 'She presented a _____ plan.', '["three-year detailed","detail three-year","three detailed-year","detailed three-year"]', 'detailed three-year', '意見（detailed）→描述（three-year）。'),
(65, 'multiple_choice', 'They work in a _____ building.', '["grey, large, modern","large, grey, modern","modern, grey, large","modern, large, grey"]', 'large, grey, modern', '尺寸（large）→顏色（grey）→年齡/描述（modern）。'),
(65, 'multiple_choice', 'It''s a _____ issue.', '["seriously financial","serious financial","financial serious","finance serious"]', 'serious financial', '意見（serious）→目的（financial）。'),
(65, 'transform', 'The office has a new, small, Italian espresso machine. (Write in correct order)', NULL, 'The office has a new small Italian espresso machine.', '年齡（new）→尺寸（small）→來源（Italian）。'),
(65, 'fill_blank', 'We need a _____ (reliable/new/German) engineering partner.', NULL, 'reliable new German', '意見（reliable）→年齡（new）→來源（German）。'),
(65, 'multiple_choice', 'She wore a _____ jacket.', '["smart black business","smart business black","business smart black","black smart business"]', 'smart black business', '意見（smart）→顏色（black）→目的（business）。'),
(65, 'multiple_choice', 'He has _____ experience.', '["international considerable","considerable international","considerable internation","considerately international"]', 'considerable international', '意見（considerable）→來源/範疇（international）。'),
(65, 'multiple_choice', 'We installed _____ screens in the boardroom.', '["several flat large","several large flat","large several flat","flat large several"]', 'several large flat', '數量（several）→尺寸（large）→形狀（flat）。');